{
  "hash": "853582dc1ab077d95d0a243072e7b33f",
  "result": {
    "engine": "knitr",
    "markdown": "# Simple Linear Regression {#week9}\n\n::: {.callout-tip}\n## What This Session Covers\n\nThis session introduces the workhorse of statistical modeling: linear regression with a single predictor.\n\n1. **The basic principle** - fitting a line that minimizes squared residuals\n2. **Assumptions** - linearity, normality of residuals, homoscedasticity, independence\n3. **Example 1** - preposition use across real time (numeric predictor)\n4. **Model diagnostics** - `performance::check_model()` and formal checks\n5. **Example 2** - teaching styles (categorical predictor)\n6. **Interpreting and reporting** - coefficients, R², model comparison, and summary tables\n:::\n\nThis tutorial introduces regression analysis (also called regression modeling). Regression models are among the most widely used quantitative methods in the language sciences to assess if and how predictors (variables or interactions between variables) correlate with a certain response. \n\nRegression models are so popular because they can\n\n* incorporate many predictors in a single model (multivariate: allows to test the impact of one predictor while the impact of (all) other predictors is controlled for)\n\n* extremely flexible and and can be fitted to different types of predictors and dependent variables\n\n* provide output that can be easily interpreted\n\n* conceptually relative simple and not overly complex from a  mathematical perspective\n\n\nThe major difference between these types of models is that they take different types of dependent variables: linear regressions take numeric, logistic regressions take nominal variables, ordinal regressions take ordinal variables, and Poisson regressions take dependent variables that reflect counts of (rare) events. \n\n## The Basic Principle\n\n::: {.callout-note}\n## Key concept: Residuals\n\nA *residual* is the difference between an observed value and the value the model predicts for that observation - the vertical distance between a data point and the regression line. Residuals are the raw material of regression: the line is chosen to minimize the sum of *squared* residuals, the model assumptions are checked *on the residuals* (normality, constant variance), and the size of the residuals determines how well the model fits (R² measures the proportion of variance that is *not* left in the residuals).\n:::\n\n\nThe idea behind regression analysis is expressed formally in the equation below where $f_{(x)}$ is the $y$-value we want to predict, $\\alpha$ is the intercept (the point where the regression line crosses the $y$-axis), $\\beta$ is the coefficient (the slope of the regression line). \n\n\\begin{equation}\nf_{(x)} = \\alpha + \\beta_{i}x + \\epsilon\n\\end{equation}\n\nTo understand what this means, let us imagine that we have collected information about the how tall people are and what they weigh. Now we want to predict the weight of people of a certain height - let's say 180cm.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-95cd9d6a{table-layout:auto;width:75%;}.cl-95c32ea2{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-95c32ec0{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-95c75644{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-95c77660{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7766a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77674{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7767e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7767f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77680{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77688{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77689{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-95cd9d6a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-95c77660\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ea2\">Height</span></p></th><th class=\"cl-95c7766a\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ea2\">Weight</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77674\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">173</span></p></td><td class=\"cl-95c7767e\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">80</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c7767f\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">169</span></p></td><td class=\"cl-95c77680\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">68</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77674\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">176</span></p></td><td class=\"cl-95c7767e\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">72</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c7767f\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">166</span></p></td><td class=\"cl-95c77680\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">75</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77674\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">161</span></p></td><td class=\"cl-95c7767e\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">70</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c7767f\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">164</span></p></td><td class=\"cl-95c77680\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">65</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77674\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">160</span></p></td><td class=\"cl-95c7767e\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">62</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c7767f\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">158</span></p></td><td class=\"cl-95c77680\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">60</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77674\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">180</span></p></td><td class=\"cl-95c7767e\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">85</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-95c77688\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">187</span></p></td><td class=\"cl-95c77689\"><p class=\"cl-95c75644\"><span class=\"cl-95c32ec0\">92</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe can run a simple linear regression on the data and we get the following output:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# model for upper panels\nm <- lm(Weight ~ Height, data = df)\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Weight ~ Height, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.3939 -2.3610  0.0096  3.1142  5.4453 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -93.7759    27.0379  -3.468 0.008464 ** \nHeight        0.9839     0.1594   6.173 0.000267 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.532 on 8 degrees of freedom\nMultiple R-squared:  0.8265,\tAdjusted R-squared:  0.8048 \nF-statistic: 38.11 on 1 and 8 DF,  p-value: 0.0002671\n```\n\n\n:::\n:::\n\n\n\n\nTo estimate how much some weights who is 180cm tall, we would multiply the coefficient (slope of the line) with 180 ($x$) and add the value of the intercept (point where line crosses the $y$-axis). If we plug in the numbers from the regression model below, we get\n\n\\begin{equation}\n-93.77 + 0.98 ∗ 180 = 83.33 (kg)\n\\end{equation}\n\nA person who is 180cm tall is predicted to weigh 83.33kg. Thus, the predictions of the weights are visualized as the red line in the figure below. Such lines are called *regression lines*. Regression lines are those lines where the sum of the red lines should be minimal. The slope of the regression line is called *coefficient* and the point where the regression line crosses the y-axis at x = 0 is called the *intercept*. Other important concepts in regression analysis are *variance* and *residuals*. *Residuals* are the distance between the line and the points (the red lines) and it is also called *variance*.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-week9_files/figure-html/intro01-1.png){width=672}\n:::\n:::\n\n\n\n\nSome words about the plots in the figure above: the upper left panel shows the raw observed data (black dots). The upper right panel shows the mean weight (blue line) and the residuals (in red). residuals are the distances from the expected or predicted values to the observed values (in this case the mean is the most most basic model which we use to predict values while the observed values simply represent the actual data points). The lower left panel shows observed values and the regression line, i.e, that line which, when drawn through the data points, will have the lowest sum of residuals. The lower right panel shows the regression line and the residuals, i.e. the distances between the expected or predicted values to the actual observed values (in red). Note that the sum of residuals in the lower right panel is much smaller than the sum of residuals in the upper right panel. This suggest that considering Height is a good idea as it explains a substantive amount of residual error and reduces the sum of residuals (or variance).\n\n## Assumptions\n\n::: {.callout-note}\n## Key concept: R² (R-squared)\n\nR² is the proportion of the variance in the outcome that the model accounts for, ranging from 0 (the model explains nothing beyond the mean) to 1 (perfect fit). An R² of .30 means the predictor accounts for 30% of the variability in the outcome. In multiple regression, report the *adjusted* R², which corrects for the number of predictors - plain R² can only ever increase when predictors are added, even useless ones.\n:::\n\n\nLinear regression makes several assumptions about the data. If these assumptions are not met, then this can mean that results of the model can be misleading, inaccurate, or plainly wrong. All these assumptions and potential problems can be checked by producing some diagnostic plots visualizing the residual errors (we will do this below). The assumptions of regression models are:\n\n* **Linearity**: The relationship between the predictor (x) and the outcome (y) is assumed to be linear.  \n* **Normality of residuals**: The residual errors are assumed to be normally distributed.  \n* **Homogeneity**: The residuals are assumed to have a constant variance (homoscedasticity)  \n* **Independence of residuals**: The residuals are assumed not to be correlated.\n\nYou should check whether or not these assumptions hold true. Potential problems include:\n\n* **Non-linearity**: The predictor affects the dependent variable differently for different values.  \n* **Heteroscedasticity**: Non-constant variance of error terms (this means that at least one other important predictor is not included in the model).\n* **Presence of influential observations**:\n  * **Outliers**: extreme values in the dependent variable  \n  * **High-leverage points**: extreme values in the predictors  \n\nNow that we are familiar with the basic principle of regression modeling - i.e. finding the line through data that has the smallest sum of residuals, we will apply this to a linguistic example.\n\n\n## Example 1: Preposition Use across Real-Time\n\nWe will now turn to our first example. In this example, we will investigate whether the frequency of prepositions has changed from Middle English to Late Modern English. The reasoning behind this example is that Old English was highly synthetic compared with Present-Day English which comparatively analytic. In other words, while Old English speakers used case to indicate syntactic relations, speakers of Present-Day English use word order and prepositions to indicate syntactic relationships. This means that the loss of case had to be compensated by different strategies and maybe these strategies continued to develop and increase in frequency even after the change from synthetic to analytic had been mostly accomplished. And this prolonged change in compensatory strategies is what this example will focus on. \n\nThe analysis is based on data extracted from the *Penn Corpora of Historical English* (see http://www.ling.upenn.edu/hist-corpora/), that consists of 603 texts written between 1125 and 1900. In preparation of this example, all elements that were part-of-speech tagged as prepositions were extracted from the PennCorpora. \n\nThen, the relative frequencies (per 1,000 words) of prepositions per text were calculated. This frequency of prepositions per 1,000 words represents our dependent variable. In a next step, the date when each letter had been written was extracted. The resulting two vectors were combined into a table which thus contained for each text, when it was written (independent variable) and its relative frequency of prepositions (dependent or outcome variable).\n\nA regression analysis will follow the steps described below: \n\n1. Extraction and processing of the data\n\n2. Data visualization\n\n3. Applying the regression analysis to the data\n\n4. Diagnosing the regression model and checking whether or not basic model assumptions have been violated.\n\nIn a first step, we load and inspect the data to get a first impression of its properties.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nslrdata  <- base::readRDS(url(\"https://slcladal.github.io/data/sld.rda\", \"rb\"))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-97f0edcc{table-layout:auto;width:75%;}.cl-97e437f8{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97e4380c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97e90f44{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-97e90f58{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-97e94bbc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bc6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bd0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bd1{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bda{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bdb{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94be4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94be5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bee{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bf8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c02{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c03{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c16{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-97f0edcc'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-97e94bbc\"><p class=\"cl-97e90f44\"><span class=\"cl-97e437f8\">Date</span></p></th><th class=\"cl-97e94bc6\"><p class=\"cl-97e90f58\"><span class=\"cl-97e437f8\">Genre</span></p></th><th class=\"cl-97e94bc6\"><p class=\"cl-97e90f58\"><span class=\"cl-97e437f8\">Text</span></p></th><th class=\"cl-97e94bd0\"><p class=\"cl-97e90f44\"><span class=\"cl-97e437f8\">Prepositions</span></p></th><th class=\"cl-97e94bd1\"><p class=\"cl-97e90f58\"><span class=\"cl-97e437f8\">Region</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,736</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Science</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">albin</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">166.01</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,711</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Education</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">anon</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">139.86</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,808</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">PrivateLetter</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">austen</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">130.78</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,878</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Education</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">bain</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">151.29</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,743</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Education</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">barclay</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">145.72</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,908</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Education</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">benson</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">120.77</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,906</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Diary</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">benson</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">119.17</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,897</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Philosophy</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">boethja</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">132.96</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,785</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Philosophy</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">boethri</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">130.49</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,776</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Diary</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">boswell</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">135.94</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,905</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Travel</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">bradley</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">154.20</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,711</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Education</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">brightland</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">149.14</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bda\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,762</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Sermon</span></p></td><td class=\"cl-97e94bdb\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">burton</span></p></td><td class=\"cl-97e94be4\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">159.71</span></p></td><td class=\"cl-97e94be5\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94bee\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,726</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">Sermon</span></p></td><td class=\"cl-97e94bf8\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">butler</span></p></td><td class=\"cl-97e94c02\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">157.49</span></p></td><td class=\"cl-97e94c03\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97e94c0c\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">1,835</span></p></td><td class=\"cl-97e94c0d\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">PrivateLetter</span></p></td><td class=\"cl-97e94c0d\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">carlyle</span></p></td><td class=\"cl-97e94c0e\"><p class=\"cl-97e90f44\"><span class=\"cl-97e4380c\">124.16</span></p></td><td class=\"cl-97e94c16\"><p class=\"cl-97e90f58\"><span class=\"cl-97e4380c\">North</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\nInspecting the data is very important because it can happen that a data set may not load completely or that variables which should be numeric have been converted to character variables. If unchecked, then such issues could go unnoticed and cause trouble.\n\nWe will now plot the data to get a better understanding of what the data looks like.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(slrdata, aes(Date, Prepositions)) +\n  geom_point() +\n  theme_bw() +\n  labs(x = \"Year\", y = \"Prepositions per 1,000 words\") +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr6-1.png){width=672}\n:::\n:::\n\n\n\n\nBefore beginning with the regression analysis, we will center the year. We center the values of year by subtracting each value from the mean of year. This can be useful when dealing with numeric variables because if we did not center year, we would get estimated values for year 0 (a year when English did not even exist yet). If a variable is centered, the regression provides estimates of the model refer to the mean of that numeric variable. In other words, centering can be very helpful, especially with respect to the interpretation of the results that regression models report.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# center date\nslrdata$Date <- slrdata$Date - mean(slrdata$Date) \n```\n:::\n\n\n\n\nWe will now begin the regression analysis by generating a first regression model and inspect its results. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create initial model\nm1.lm <- lm(Prepositions ~ Date, data = slrdata)\n# inspect results\nsummary(m1.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Prepositions ~ Date, data = slrdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-69.101 -13.855   0.578  13.321  62.858 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.322e+02  8.386e-01 157.625   <2e-16 ***\nDate        1.732e-02  7.267e-03   2.383   0.0175 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.43 on 535 degrees of freedom\nMultiple R-squared:  0.01051,\tAdjusted R-squared:  0.008657 \nF-statistic: 5.681 on 1 and 535 DF,  p-value: 0.0175\n```\n\n\n:::\n:::\n\n\n\n\nThe summary output starts by repeating the regression equation. Then, the model provides the distribution of the residuals. The residuals should be distributed normally with the absolute values of the Min and Max as well as the 1Q (first quartile) and 3Q (third quartile) being similar or ideally identical. In our case, the values are very similar which suggests that the residuals are distributed evenly and follow a normal distribution. The next part of the report is the coefficients table. The estimate for the intercept is the value of y at x = 0. The estimate for Date represents the slope of the regression line and tells us that with each year, the predicted frequency of prepositions increase by .01732 prepositions. The t-value is the Estimate divided by the standard error (Std. Error). Based on the t-value, the p-value can be calculated manually as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use pt function (which uses t-values and the degrees of freedom)\n2*pt(-2.383, nrow(slrdata)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01751964\n```\n\n\n:::\n:::\n\n\n\n\nThe R^2^-values tell us how much variance is explained by our model. The baseline value represents a model that uses merely the mean. 0.0105 means that our model explains only 1.05 percent of the variance (0.010 x 100) - which is a tiny amount. The problem of the multiple R^2^ is that it will increase even if we add variables that explain almost no variance. Hence, multiple R^2^ encourages the inclusion of *junk* variables.\n\n\\begin{equation}\nR^2 = R^2_{multiple} = 1 - \\frac{\\sum (y_i - \\hat{y_i})^2}{\\sum (y_i - \\bar y)^2}\n\\end{equation}\n\nThe adjusted R^2^-value takes the number of predictors into account and, thus, the adjusted R^2^ will always be lower than the multiple R^2^. This is so because the adjusted R^2^ penalizes models for having predictors. The equation for the adjusted R^2^ below shows that the amount of variance that is explained by all the variables in the model (the top part of the fraction) must outweigh the inclusion of the number of variables (k) (lower part of the fraction). Thus, the  adjusted R^2^ will decrease when variables are added that explain little or even no variance while it will increase if variables are added that explain a lot of variance.\n\n\\begin{equation}\nR^2_{adjusted} = 1 - (\\frac{(1 - R^2)(n - 1)}{n - k - 1})\n\\end{equation}\n\nIf there is a big difference between the two R^2^-values, then the model contains (many) predictors that do not explain much variance which is not good. The F-statistic and the associated p-value tell us that the model, despite explaining almost no variance, is still significantly better than an intercept-only base-line model (or using the overall mean to predict the frequency of prepositions per text).\n\nWe can test this and also see where the F-values comes from by comparing the \n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create intercept-only base-line model\nm0.lm <- lm(Prepositions ~ 1, data = slrdata)\n# compare the base-line and the more saturated model\nanova(m1.lm, m0.lm, test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Prepositions ~ Date\nModel 2: Prepositions ~ 1\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)  \n1    535 202058                             \n2    536 204204 -1   -2145.6 5.6809 0.0175 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe F- and p-values are exactly those reported by the summary which shows where the F-values comes from and what it means; namely it denote the difference between the base-line and the more saturated model.\n\n\nThe degrees of freedom associated with the residual standard error are the number of cases in the model minus the number of predictors (including the intercept). The residual standard error is square root of the sum of the squared residuals of the model divided by the degrees of freedom. Have a look at he following to clear this up:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# DF = N - number of predictors (including intercept)\nDegreesOfFreedom <- nrow(slrdata)-length(coef(m1.lm))\n# sum of the squared residuals\nSumSquaredResiduals <- sum(resid(m1.lm)^2)\n# Residual Standard Error\nsqrt(SumSquaredResiduals/DegreesOfFreedom); DegreesOfFreedom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.43396\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 535\n```\n\n\n:::\n:::\n\n\n\n\nWe will now check the model assumptions using diagnostic plots. To do this, we use the `check_model` function from the `performance` package [@performance] which generates a panel of diagnostic plots and - very conveniently - tells us in the subtitle of each panel what we should be looking for.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate diagnostic plots\nperformance::check_model(m1.lm)\n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr13-1.png){width=672}\n:::\n:::\n\n\n\n\nWe will go through the panels one by one:\n\n**Posterior Predictive Check**\n\nThis plot compares the distribution of the observed data (green line) with distributions of data simulated from the fitted model (blue lines). If the model captures the data well, the simulated distributions should closely resemble the observed distribution. Strong discrepancies indicate that the model fails to reproduce important characteristics of the data (e.g., skewness or multimodality).\n\n**Linearity**\n\nThis plot is used to check the linearity assumption: the reference line should be flat and horizontal. If a trend becomes visible in the line (e.g., a curve or a zigzag pattern), the relationship between predictor(s) and outcome is not adequately captured by a straight line and the model is problematic (in such cases, transforming variables or adding non-linear terms can help).\n\n**Homogeneity of Variance**\n\nThis plot is used to check the homogeneity of variance of the residuals (homoscedasticity): a flat, horizontal reference line with equally spread points indicates homoscedasticity. Homoscedasticity means that the variance of the residuals remains constant and does not correlate with any independent variable. If there is a trend in the line, we are dealing with heteroscedasticity, that is, a correlation between the fitted values and the spread of the residuals, which is very problematic for regressions.\n\n**Influential Observations**\n\nThis plot is used to identify influential cases that disproportionately affect the regression (this would be problematic): points should lie within the dashed contour lines. The contours are based on Cook's distance, which shows how much the regression changes when the model is re-fitted without that data point. If influential data points are present, they should be inspected and either down-weighted (e.g., by fitting a robust regression) or, if they represent errors, removed. In addition to the visual check, we can formally test for influential observations using the `check_outliers` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check for influential observations\nperformance::check_outliers(m1.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: No outliers detected.\n- Based on the following method and threshold: cook (0.7).\n- For variable: (Whole model)\n```\n\n\n:::\n:::\n\n\n\n\n**Normality of Residuals**\n\nThis plot is used to examine whether the residuals are normally distributed: it is good if the points follow the straight reference line. If the points fall on the line, the residuals follow a normal distribution. If the points deviate from the line at the top and bottom, this shows that the model does not predict small and large values well and that it therefore does not have a good fit. We can complement the visual checks with formal tests of normality and heteroscedasticity as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# formal test of normality of residuals\nperformance::check_normality(m1.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.873).\n```\n\n\n:::\n\n```{.r .cell-code}\n# formal test of heteroscedasticity\nperformance::check_heteroscedasticity(m1.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.272).\n```\n\n\n:::\n:::\n\n\n\n\nIn our case, the diagnostics do not indicate any severe violations of the model assumptions and we can proceed with the interpretation of the model.\n\nNow, we plot the effect reported by the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate summary table\nsjPlot::plot_model(m1.lm, type = \"pred\", terms = c(\"Date\"))\n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr18a-1.png){width=672}\n:::\n:::\n\n\n\n\nWe end the current analysis by summarizing the results of the regression analysis using the `tab_model` function from the `sjPlot` package [@sjPlot] (as is shown below).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate summary table\nsjPlot::tab_model(m1.lm) \n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Prepositions</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">132.19</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">130.54&nbsp;&ndash;&nbsp;133.84</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Date</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.017</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">537</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.011 / 0.009</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\nTypically, the results of regression analyses are presented in such tables as they include all important measures of model quality and significance, as well as the magnitude of the effects.\n\nIn addition, the results of simple linear regressions should be summarized in writing. We can use the `reports` package [@report] to summarize the analysis.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(m1.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear model (estimated using OLS) to predict Prepositions with\nDate (formula: Prepositions ~ Date). The model explains a statistically\nsignificant and very weak proportion of variance (R2 = 0.01, F(1, 535) = 5.68,\np = 0.017, adj. R2 = 8.66e-03). The model's intercept, corresponding to Date =\n0, is at 132.19 (95% CI [130.54, 133.84], t(535) = 157.62, p < .001). Within\nthis model:\n\n  - The effect of Date is statistically significant and positive (beta = 0.02,\n95% CI [3.05e-03, 0.03], t(535) = 2.38, p = 0.017; Std. beta = 0.10, 95% CI\n[0.02, 0.19])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\n> A simple linear regression has been fitted to the data. A visual assessment of the model diagnostic graphics did not indicate any problematic or disproportionately influential data points (outliers) and performed significantly better compared to an intercept-only base line model but only explained .87 percent of the variance (adjusted R^2^: .0087, F-statistic (1, 535): 5,68, p-value: 0.0175\\*). The final minimal adequate linear regression model is based on 537 data points and confirms a significant and positive correlation between the year in which the text was written and the relative frequency of prepositions (coefficient estimate: .02 (standardized \\beta: 0.10, 95% CI [0.02, 0.19]), SE: 0.01, t-value~535~: 2.38, p-value: .0175\\*). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.\n\n## Example 2: Teaching Styles\n\nIn the previous example, we dealt with two numeric variables, while the following example deals with a categorical independent variable and a numeric dependent variable. The ability for regressions to handle very different types of variables makes regressions a widely used and robust method of analysis.\n\nIn this example, we are dealing with two groups of students that have been randomly assigned to be exposed to different teaching methods. Both groups undergo a language learning test after the lesson with a maximum score of 20 points. \n\nThe question that we will try to answer is whether the students in group A have performed significantly better than those in group B which would indicate that the teaching method to which group A was exposed works better than the teaching method to which group B was exposed.\n\nLet's move on to implementing the regression in R. In a first step, we load the data set and inspect its structure.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nslrdata2  <- base::readRDS(url(\"https://slcladal.github.io/data/sgd.rda\", \"rb\")) |>\n  dplyr::mutate(Group = factor(Group))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-9bf888bc{table-layout:auto;width:75%;}.cl-9becb708{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9becb71c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9bf18332{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9bf18346{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9bf1a92a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a93e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a948{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a952{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a95c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a95d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a966{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a970{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-9bf888bc'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-9bf1a92a\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb708\">Group</span></p></th><th class=\"cl-9bf1a93e\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb708\">Score</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a948\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a952\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">15</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a95c\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a95d\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">12</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a948\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a952\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">11</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a95c\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a95d\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">18</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a948\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a952\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">15</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9bf1a966\"><p class=\"cl-9bf18332\"><span class=\"cl-9becb71c\">A</span></p></td><td class=\"cl-9bf1a970\"><p class=\"cl-9bf18346\"><span class=\"cl-9becb71c\">15</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe also inspect the structure of the data.\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t60 obs. of  2 variables:\n $ Group: Factor w/ 2 levels \"A\",\"B\": 1 1 1 1 1 1 1 1 1 1 ...\n $ Score: int  15 12 11 18 15 15 9 19 14 13 ...\n```\n\n\n:::\n:::\n\n\n\n\nNow, we graphically display the data. In this case, a boxplot represents a good way to visualize the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract means\nslrdata2 |>\n  dplyr::group_by(Group) |>\n  dplyr::mutate(Mean = round(mean(Score), 1), SD = round(sd(Score), 1)) |>\n  ggplot(aes(Group, Score)) + \n  geom_boxplot(fill=c(\"orange\", \"darkgray\")) +\n  geom_text(aes(label = paste(\"M = \", Mean, sep = \"\"), y = 1)) +\n  geom_text(aes(label = paste(\"SD = \", SD, sep = \"\"), y = 0)) +\n  theme_bw(base_size = 15) +\n  labs(x = \"Group\", y = \"Test score (Points)\") +   \n  coord_cartesian(ylim = c(0, 20)) +  \n  guides(fill = FALSE)                \n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr22-1.png){width=672}\n:::\n:::\n\n\n\n\nThe data indicate that group A did significantly better than group B. We will test this impression by generating the regression model and creating the model and extracting the model summary. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate regression model\nm2.lm <- lm(Score ~ Group, data = slrdata2) \n# inspect results\nsummary(m2.lm)                             \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Score ~ Group, data = slrdata2)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-6.767 -1.933  0.150  2.067  6.233 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  14.9333     0.5346  27.935  < 2e-16 ***\nGroupB       -3.1667     0.7560  -4.189 9.67e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.928 on 58 degrees of freedom\nMultiple R-squared:  0.2322,\tAdjusted R-squared:  0.219 \nF-statistic: 17.55 on 1 and 58 DF,  p-value: 9.669e-05\n```\n\n\n:::\n:::\n\n\n\n\nThe model summary reports that Group A performed significantly better compared with Group B. This is shown by the fact that the p-value (the value in the column with the header (Pr(>|t|)) is smaller than .001 as indicated by the three \\* after the p-values). Also, the negative Estimate for Group B indicates that Group B has lower scores than Group A. We will now generate the diagnostic graphics.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate diagnostic plots\nperformance::check_model(m2.lm)\n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr25-1.png){width=672}\n:::\n:::\n\n\n\n\nThese diagnostics also show no problems (note that with a categorical predictor, the fitted values fall into just two groups, which is why the points line up in two vertical bands). We continue by visualizing the results of the model.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate summary table\nsjPlot::plot_model(m2.lm, type = \"pred\", terms = c(\"Group\"))\n```\n\n::: {.cell-output-display}\n![](09-week9_files/figure-html/slr26a-1.png){width=672}\n:::\n:::\n\n\n\n\nNow, we summarize the results of the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate summary table\nsjPlot::tab_model(m2.lm) \n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Score</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">14.93</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">13.86&nbsp;&ndash;&nbsp;16.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Group [B]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;3.17</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;4.68&nbsp;&ndash;&nbsp;-1.65</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">60</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.232 / 0.219</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\nWe can use the `reports` package [@report] to prepare the write-up of the analysis.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(m2.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear model (estimated using OLS) to predict Score with Group\n(formula: Score ~ Group). The model explains a statistically significant and\nmoderate proportion of variance (R2 = 0.23, F(1, 58) = 17.55, p < .001, adj. R2\n= 0.22). The model's intercept, corresponding to Group = A, is at 14.93 (95% CI\n[13.86, 16.00], t(58) = 27.94, p < .001). Within this model:\n\n  - The effect of Group [B] is statistically significant and negative (beta =\n-3.17, 95% CI [-4.68, -1.65], t(58) = -4.19, p < .001; Std. beta = -0.96, 95%\nCI [-1.41, -0.50])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n \n\n> A simple linear regression was fitted to the data. A visual assessment of the model diagnostics did not indicate any problematic or disproportionately influential data points (outliers). The final linear regression model is based on 60 data points, performed significantly better than an intercept-only base line model (F (1, 58): 17.55, p-value <. 001^$***$^), and reported that the model explained 21.9 percent of variance which confirmed a good model fit. According to this final model, group A scored significantly better on the language learning test than group B (coefficient: -3.17, 95% CI [-4.68, -1.65], Std. \\beta: -0.96, 95% CI [-1.41, -0.50], SE: 0.48, t-value~58~: -4.19, p-value <. 001^$***$^). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.\n\n\n\n\n::: {.callout-tip}\n## Exercises: Simple Linear Regression\n:::\n\n**Q1. In a regression predicting reaction time (in ms) from word frequency, the slope coefficient is -25. What does this mean?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W9_Q1\" onsubmit=\"return validate_form_W9_Q1()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W9_Q1\" id=\"answer_W9_Q1_1\" value=\"25 observations were excluded from the model\"/>\n25 observations were excluded from the model\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q1\" id=\"answer_W9_Q1_2\" value=\"Reaction times are 25% faster for frequent words\"/>\nReaction times are 25% faster for frequent words\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q1\" id=\"answer_W9_Q1_3\" value=\"The model explains 25% of the variance\"/>\nThe model explains 25% of the variance\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q1\" id=\"answer_W9_Q1_4\" value=\"For each one-unit increase in word frequency, predicted reaction time decreases by 25 ms\"/>\nFor each one-unit increase in word frequency, predicted reaction time decreases by 25 ms\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W9_Q1\"></div>\n</form>\n<script>function validate_form_W9_Q1() {var x, text; var x = document.forms['form_W9_Q1']['answer_W9_Q1'].value;if (x == 'For each one-unit increase in word frequency, predicted reaction time decreases by 25 ms'){text = 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.';} else {text = 'The slope tells you how much the <em>outcome</em> changes when the <em>predictor</em> increases by one unit.';} document.getElementById('result_W9_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q2. What is a residual?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W9_Q2\" onsubmit=\"return validate_form_W9_Q2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W9_Q2\" id=\"answer_W9_Q2_1\" value=\"The proportion of explained variance\"/>\nThe proportion of explained variance\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q2\" id=\"answer_W9_Q2_2\" value=\"The number of data points in the model\"/>\nThe number of data points in the model\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q2\" id=\"answer_W9_Q2_3\" value=\"The difference between an observed value and the value predicted by the model\"/>\nThe difference between an observed value and the value predicted by the model\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q2\" id=\"answer_W9_Q2_4\" value=\"The slope of the regression line\"/>\nThe slope of the regression line\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W9_Q2\"></div>\n</form>\n<script>function validate_form_W9_Q2() {var x, text; var x = document.forms['form_W9_Q2']['answer_W9_Q2'].value;if (x == 'The difference between an observed value and the value predicted by the model'){text = 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.';} else {text = 'Think of the vertical distance between a data point and the regression line.';} document.getElementById('result_W9_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.'; res2 = document.getElementById('result_W9_Q2').innerText == 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q3. The diagnostic plots show residuals that fan out - small for low fitted values and increasingly spread out for high fitted values. Which assumption is violated?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W9_Q3\" onsubmit=\"return validate_form_W9_Q3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W9_Q3\" id=\"answer_W9_Q3_1\" value=\"Homoscedasticity (constant variance of residuals)\"/>\nHomoscedasticity (constant variance of residuals)\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q3\" id=\"answer_W9_Q3_2\" value=\"Independence of the predictor and the intercept\"/>\nIndependence of the predictor and the intercept\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q3\" id=\"answer_W9_Q3_3\" value=\"Normality of the predictor\"/>\nNormality of the predictor\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W9_Q3\" id=\"answer_W9_Q3_4\" value=\"The assumption that R² is above .5\"/>\nThe assumption that R² is above .5\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W9_Q3\"></div>\n</form>\n<script>function validate_form_W9_Q3() {var x, text; var x = document.forms['form_W9_Q3']['answer_W9_Q3'].value;if (x == 'Homoscedasticity (constant variance of residuals)'){text = 'Correct! A funnel shape means the residual variance grows with the fitted values - heteroscedasticity. Standard errors and p-values become unreliable; transformations or robust standard errors can help.';} else {text = 'A funnel-shaped residual plot indicates that the residual <em>variance</em> is not constant.';} document.getElementById('result_W9_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.'; res2 = document.getElementById('result_W9_Q2').innerText == 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.'; res3 = document.getElementById('result_W9_Q3').innerText == 'Correct! A funnel shape means the residual variance grows with the fitted values - heteroscedasticity. Standard errors and p-values become unreliable; transformations or robust standard errors can help.';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n[Back to top](#week9)\n\n\n\n",
    "supporting": [
      "09-week9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}