{
  "hash": "155c8efe52123710ea59890ad941af64",
  "result": {
    "engine": "knitr",
    "markdown": "\n# Basic Inferential Statistics {#week8}\n\n::: {.callout-tip}\n## What This Session Covers\n\nThis session introduces the first inferential statistical tests - procedures for deciding whether observed differences are likely to reflect real effects.\n\n1. **The chi-square test** - testing associations between categorical variables, assumptions, and effect sizes (Cramér's V / phi)\n2. **Student's t-test** - comparing two group means, assumptions, and Cohen's d\n3. **The Mann-Whitney U-test** - the non-parametric alternative when t-test assumptions are violated\n4. **Reporting results** - how to report test statistics, degrees of freedom, p-values, and effect sizes\n:::\n\nThis tutorial introduces basic inferential procedures for null-hypothesis hypothesis testing. AS such, this tutorial aims at discussing basic concepts of inferential statistics,  explaining the conceptual underpinnings of the most commonly used tests (such as t-tests and $\\chi^2$-tests), and showcasing how to implement these statistical tests in R. \n\nWe start the tutorial by getting to know the most common test used in the language sciences to perform null-hypothesis hypothesis testing: (Pearsons's) $\\chi$^2^ test. The next part of this tutorial then focuses on  independent and dependent t-tests which are the most basic parametric test while the last part of the tutorial introduces the Mann-Whitney U -test which is a rank-based test. \n\n\n## (Pearsons's) Chi-Square Test\n\n::: {.callout-note}\n## Key concept: Test statistic, degrees of freedom, and effect size\n\nEvery significance test produces a *test statistic* (χ², *t*, *U*, ...) that quantifies how far the data deviate from what the null hypothesis predicts, and the *degrees of freedom* describe how much independent information the data contain. Together they yield the *p*-value. But significance alone is not enough: with large samples, even trivially small differences become significant. Always complement the *p*-value with an *effect size* (e.g. Cramér's V for chi-square, Cohen's *d* for t-tests), which quantifies how *large* - and thus how meaningful - the effect is.\n:::\n\n\nOne of the most frequently used statistical test in linguistics is the $\\chi$^2^ test (or Pearsons's chi-square test, chi-squared test, or chi-square test). We will use a simple, practical example to explore how this test works. In this example, we will test whether speakers of American English (AmE) and speakers of British English (BrE) differ in their use of the near-synonyms *sort of* and *kind of* as in \"*He's sort of stupid*\" and \"*He's kind of stupid*\". As a first step, we formulate the hypothesis that we want to test (H~1~) and its null hypothesis (H~0~). The alternative- or test hypothesis reads:\n\nH~1~: Speakers of AmE and BrE differ with respect to their preference for *sort of* and *kind of*.\n\nwhile the Null Hypothesis (H~0~) states \n\nH~0~: Speakers of AmE and BrE do not differ with respect to their preference for *sort of* and *kind of*.\n\nThe H~0~ claims the non-existence of something (which is the more conservative position) and in our example the non-existence of a correlation between variety of English and the use of *sort of* and *kind of*. The question now arises what has to be the case in order to reject the H~0~ in favor of the H~1~.\n\nTo answer this question, we require information about the probability of error, i.e. the probability that the H~0~ does indeed hold for the entire population. Before performing the chi-square test, we follow the convention that the required significance level is 5 percent. In other words, we will reject the H~0~ if the likelihood for the H$_{0}$ being true is less than 5 percent given the distribution of the data. In that case, i.e. in case that the likelihood for the H~0~ being true is less than 5 percent, we consider the result of the  chi-square test as  statistically significant. This means that the observed distribution makes it very unlikely that there is no correlation between the variety of English and the use of *sort of* and *kind of*.\n\nLet us now assume that we have performed a search for *sort of* and *kind of* in two corpora representing American and British English and that we have obtained the following frequencies:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-42a0e912{table-layout:auto;width:75%;}.cl-4295968e{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-429596ac{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-429a735c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-429a7370{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-429aaa84{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaa8e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaa98{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaa99{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaaa2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaaa3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaaac{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaaad{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-429aaab6{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-42a0e912'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-429aaa84\"><p class=\"cl-429a735c\"><span class=\"cl-4295968e\">Hedge</span></p></th><th class=\"cl-429aaa8e\"><p class=\"cl-429a7370\"><span class=\"cl-4295968e\">BrE</span></p></th><th class=\"cl-429aaa98\"><p class=\"cl-429a7370\"><span class=\"cl-4295968e\">AmE</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-429aaa99\"><p class=\"cl-429a735c\"><span class=\"cl-429596ac\">kindof</span></p></td><td class=\"cl-429aaaa2\"><p class=\"cl-429a7370\"><span class=\"cl-429596ac\">181</span></p></td><td class=\"cl-429aaaa3\"><p class=\"cl-429a7370\"><span class=\"cl-429596ac\">655</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-429aaaac\"><p class=\"cl-429a735c\"><span class=\"cl-429596ac\">sortof</span></p></td><td class=\"cl-429aaaad\"><p class=\"cl-429a7370\"><span class=\"cl-429596ac\">177</span></p></td><td class=\"cl-429aaab6\"><p class=\"cl-429a7370\"><span class=\"cl-429596ac\">67</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\nIn a first step, we now have to calculate the row and column sums of our table.\n\n\n\n\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-42be7838{table-layout:auto;width:75%;}.cl-42b4381e{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-42b43828{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-42b73b68{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-42b73b72{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-42b7599a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759a4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759a5{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759ae{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759af{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759b8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759b9{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759ba{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759c2{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759c3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759cc{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42b759cd{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-42be7838'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-42b7599a\"><p class=\"cl-42b73b68\"><span class=\"cl-42b4381e\">Hedge</span></p></th><th class=\"cl-42b759a4\"><p class=\"cl-42b73b72\"><span class=\"cl-42b4381e\">BrE</span></p></th><th class=\"cl-42b759a4\"><p class=\"cl-42b73b72\"><span class=\"cl-42b4381e\">AmE</span></p></th><th class=\"cl-42b759a5\"><p class=\"cl-42b73b72\"><span class=\"cl-42b4381e\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42b759ae\"><p class=\"cl-42b73b68\"><span class=\"cl-42b43828\">kindof</span></p></td><td class=\"cl-42b759af\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">181</span></p></td><td class=\"cl-42b759af\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">655</span></p></td><td class=\"cl-42b759b8\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">836</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42b759b9\"><p class=\"cl-42b73b68\"><span class=\"cl-42b43828\">sortof</span></p></td><td class=\"cl-42b759ba\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">177</span></p></td><td class=\"cl-42b759ba\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">67</span></p></td><td class=\"cl-42b759c2\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">244</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42b759c3\"><p class=\"cl-42b73b68\"><span class=\"cl-42b43828\">Total</span></p></td><td class=\"cl-42b759cc\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">358</span></p></td><td class=\"cl-42b759cc\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">722</span></p></td><td class=\"cl-42b759cd\"><p class=\"cl-42b73b72\"><span class=\"cl-42b43828\">1,080</span></p></td></tr></tbody></table></div>\n```\n\n\n\n\nNext, we calculate, the values that would have expected if there was no correlation between variety of English and the use of *sort of* and *kind of*. In order to get these *expected* frequencies, we apply the equation below to all cells in our table.\n\n\\begin{equation}\n\\frac{Column total*Row total}{Overall total}\n\\end{equation}\n\nIn our example this means that for the cell with `[+]BrE` `[+]kindof` we get:\n\n\\begin{equation}\n\\frac{836*358}{1080} = \\frac{299288}{1080} = 277.1185\n\\end{equation}\n\nFor the entire table this means we get the following expected values:\n\n\n\n\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4304204a{table-layout:auto;width:75%;}.cl-42f44a76{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-42f44a94{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-42fa8abc{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-42fa8ada{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-42fadb8e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadb98{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadba2{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadba3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbb6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbc0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbc1{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbca{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbd4{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbd5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbde{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-42fadbe8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4304204a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-42fadb8e\"><p class=\"cl-42fa8abc\"><span class=\"cl-42f44a76\">Hedge</span></p></th><th class=\"cl-42fadb98\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a76\">BrE</span></p></th><th class=\"cl-42fadb98\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a76\">AmE</span></p></th><th class=\"cl-42fadba2\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a76\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42fadba3\"><p class=\"cl-42fa8abc\"><span class=\"cl-42f44a94\">kindof</span></p></td><td class=\"cl-42fadbb6\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">277.11850</span></p></td><td class=\"cl-42fadbb6\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">558.8815</span></p></td><td class=\"cl-42fadbc0\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">836</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42fadbc1\"><p class=\"cl-42fa8abc\"><span class=\"cl-42f44a94\">sortof</span></p></td><td class=\"cl-42fadbca\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">80.88148</span></p></td><td class=\"cl-42fadbca\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">163.1185</span></p></td><td class=\"cl-42fadbd4\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">244</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-42fadbd5\"><p class=\"cl-42fa8abc\"><span class=\"cl-42f44a94\">Total</span></p></td><td class=\"cl-42fadbde\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">358.00000</span></p></td><td class=\"cl-42fadbde\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">722.0000</span></p></td><td class=\"cl-42fadbe8\"><p class=\"cl-42fa8ada\"><span class=\"cl-42f44a94\">1,080</span></p></td></tr></tbody></table></div>\n```\n\n\n\n\n\nIn a next step, we calculate the contribution of each cell to the overall $\\chi$^2^ value ($\\chi$^2^ contribution). To get $\\chi$^2^ contribution for each cell, we apply the equation below to each cell.\n\n\\begin{equation}\n\\frac{(observed – expected)^{2}}{expected}\n\\end{equation}\n\nIn our example this means that for the cell with `[+]BrE` `[+]kindof` we get:\n\n\\begin{equation}\n\\frac{(181 – 277.1185)^{2}}{277.1185} = \\frac{-96.1185^{2}}{277.1185} = \\frac{9238.766}{277.1185} = 33.33868\n\\end{equation}\n\nFor the entire table this means we get the following $\\chi^{2}$ values:\n\n\n\n\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4327f27c{table-layout:auto;width:75%;}.cl-431a4b18{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-431a4b2c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-431f351a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-431f3524{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-431f6f62{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f6c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f76{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f80{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f81{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f8a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f8b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f94{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f95{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f9e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6f9f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-431f6fa8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4327f27c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-431f6f62\"><p class=\"cl-431f351a\"><span class=\"cl-431a4b18\">Hedge</span></p></th><th class=\"cl-431f6f6c\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b18\">BrE</span></p></th><th class=\"cl-431f6f6c\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b18\">AmE</span></p></th><th class=\"cl-431f6f76\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b18\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-431f6f80\"><p class=\"cl-431f351a\"><span class=\"cl-431a4b2c\">kindof</span></p></td><td class=\"cl-431f6f81\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">33.33869</span></p></td><td class=\"cl-431f6f81\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">16.53082</span></p></td><td class=\"cl-431f6f8a\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">49.86951</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-431f6f8b\"><p class=\"cl-431f351a\"><span class=\"cl-431a4b2c\">sortof</span></p></td><td class=\"cl-431f6f94\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">114.22602</span></p></td><td class=\"cl-431f6f94\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">56.63839</span></p></td><td class=\"cl-431f6f95\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">170.86440</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-431f6f9e\"><p class=\"cl-431f351a\"><span class=\"cl-431a4b2c\">Total</span></p></td><td class=\"cl-431f6f9f\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">147.56470</span></p></td><td class=\"cl-431f6f9f\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">73.16921</span></p></td><td class=\"cl-431f6fa8\"><p class=\"cl-431f3524\"><span class=\"cl-431a4b2c\">220.73390</span></p></td></tr></tbody></table></div>\n```\n\n\n\n\nThe sum of $\\chi$^2^ contributions in our example is 220.7339. To see if this value is statistically significant, we need to calculate the degrees of freedom because the $\\chi$ distribution differs across degrees of freedom.  Degrees of freedom are calculated according to the equation below.\n\n\\begin{equation}\nDF = (rows -1) * (columns – 1) = (2-1) * (2-1) = 1 * 1 = 1\n\\end{equation}\n\nIn a last step, we check whether the $\\chi$^2^ value that we have calculated is higher than a critical value (in which case the correlation in our table is significant). Degrees of freedom are relevant here because the critical values are dependent upon the degrees of freedom: the more degrees of freedom, the higher the critical value, i.e. the harder it is to breach the level of significance.\n\n**But why do the degrees of freedom matter?**\n\nThe simple answer is that the $\\chi$-distribution differs based on the degrees of freedom which then affects the probability of a $\\chi$-value. Have a look at the graph below to see how the degrees of freedom affect the shape of the $\\chi$-distribution.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-week8_files/figure-html/chidist-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\nSince there is only 1 degree of freedom in our case, we need to check the critical $\\chi$-value foe 1 degree of freedom and a significance level of $\\alpha$ = 5 percent.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqchisq(p=.05, df=1, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.841459\n```\n\n\n:::\n:::\n\n\n\n\nWhat does this critical value mean?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-week8_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nThe critical values shows that if we get a value higher than the critical value, we have to reject our H~0~ and can consider our result to be statistically significant because the likelihood of obtaining our or a more extreme result is lower than 5%.\n\nYou can also check the critical values in the table below. as we are dealing with 1 degree of freedom, only the first column in the table of critical values below is relevant for us.\n\n\n\n\n\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4478c4ee{table-layout:auto;width:75%;}.cl-446c7860{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-446c7874{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-44718684{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4471b5be{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5c8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5d2{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5dc{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5e6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5f0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5f1{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5fa{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5fb{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b5fc{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b604{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4471b605{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4478c4ee'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4471b5be\"><p class=\"cl-44718684\"><span class=\"cl-446c7860\">DF</span></p></th><th class=\"cl-4471b5c8\"><p class=\"cl-44718684\"><span class=\"cl-446c7860\">p&lt;.05</span></p></th><th class=\"cl-4471b5c8\"><p class=\"cl-44718684\"><span class=\"cl-446c7860\">p&lt;.01</span></p></th><th class=\"cl-4471b5d2\"><p class=\"cl-44718684\"><span class=\"cl-446c7860\">p&lt;.001</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4471b5dc\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">1</span></p></td><td class=\"cl-4471b5e6\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">3.84</span></p></td><td class=\"cl-4471b5e6\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">6.64</span></p></td><td class=\"cl-4471b5f0\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">10.83</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4471b5f1\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">2</span></p></td><td class=\"cl-4471b5fa\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">5.99</span></p></td><td class=\"cl-4471b5fa\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">9.21</span></p></td><td class=\"cl-4471b5fb\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">13.82</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4471b5dc\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">3</span></p></td><td class=\"cl-4471b5e6\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">7.82</span></p></td><td class=\"cl-4471b5e6\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">11.35</span></p></td><td class=\"cl-4471b5f0\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">16.27</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4471b5f1\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">4</span></p></td><td class=\"cl-4471b5fa\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">9.49</span></p></td><td class=\"cl-4471b5fa\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">13.28</span></p></td><td class=\"cl-4471b5fb\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">18.47</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4471b5fc\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">5</span></p></td><td class=\"cl-4471b604\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">11.07</span></p></td><td class=\"cl-4471b604\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">15.09</span></p></td><td class=\"cl-4471b605\"><p class=\"cl-44718684\"><span class=\"cl-446c7874\">20.52</span></p></td></tr></tbody></table></div>\n```\n\n\n\n\n\nSince the $\\chi$^2^ value that we have calculated is much higher than the critical value provided for p<.05, we can reject the H~0~ and may now claim that speakers of AmE and BrE differ with respect to their preference for *sort of* and *kind of*.\n\n\nBefore we summarize the results, we will calculate the effect size which is a measure for how strong the correlations are.\n\n### Effect Sizes in Chi-Square\n\nEffect sizes are important because they correlations may be highly significant but the effect between variables can be extremely weak. The effect size is therefore a measure how strong the correlation or the explanatory and predictive power between variables is.\n\nThe effect size measure for $\\chi$^2^ tests can be either the $\\phi$-coefficient (phi-coefficient) or Cramer's $\\phi$ (Cramer's phi). The $\\phi$-coefficient is used when dealing with 2x2 tables while Cramer's $\\phi$ is used when dealing with tables with more than 4 cells. The $\\phi$ coefficient can be calculated by using the equation below (N = overall sample size).\n\n\\begin{equation}\n\\phi = \\sqrt{\\frac{\\chi^{2}}{N}}\n\\end{equation}\n\nIn our case, this means:\n\n\\begin{equation}\n\\phi = \\sqrt{\\frac{220.7339}{1080}} = \\sqrt{0.2043832} = 0.4520876\n\\end{equation}\n\nThe $\\phi$ coefficient varies between 0 (no effect) and 1 (perfect correlation). For the division into weak, moderate and strong effects one can follow the division for $\\omega$ (small omega), so that with values beginning with .1 represent weak, values between 0.3 and .5 represent moderate and values above .5 represent strong effects [@buehner2009statistik, 266]. So, in this example we are dealing with a medium-sized effect/correlation.\n\n### Chi-Square in R\n\nBefore we summarize the results, we will see how to perform a chi-square test in R. In addition to what we have done above, we will also visualize the data. To begin with, we will have a look at the data set (which is the same data we have used above).\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-44a590d2{table-layout:auto;width:75%;}.cl-4493d888{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4493d89c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-449b1ecc{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-449b1ee0{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-449b69f4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a08{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a12{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a13{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a1c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a1d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a26{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a30{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-449b6a31{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-44a590d2'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-449b69f4\"><p class=\"cl-449b1ecc\"><span class=\"cl-4493d888\">Hedge</span></p></th><th class=\"cl-449b6a08\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d888\">BrE</span></p></th><th class=\"cl-449b6a12\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d888\">AmE</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-449b6a13\"><p class=\"cl-449b1ecc\"><span class=\"cl-4493d89c\">kindof</span></p></td><td class=\"cl-449b6a1c\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d89c\">181</span></p></td><td class=\"cl-449b6a1d\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d89c\">655</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-449b6a26\"><p class=\"cl-449b1ecc\"><span class=\"cl-4493d89c\">sortof</span></p></td><td class=\"cl-449b6a30\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d89c\">177</span></p></td><td class=\"cl-449b6a31\"><p class=\"cl-449b1ee0\"><span class=\"cl-4493d89c\">67</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe will now visualize the data with an association. Bars above the dashed line indicate that a feature combination occurs more frequently than expected by chance. The width of the bars indicates the frequency of the feature combination. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nassocplot(as.matrix(chidata))   # association plot\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n \nThe fact that the bars are distributed complimentary (top left red and below bar; top right black above bar; bottom left black above bar; bottom right red below bar) indicates that the use of *sort of* and *kind of* differs across AmE and BrE. We will check whether the mosaic plot confirms this impression.\n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaicplot(chidata, shade = TRUE, type = \"pearson\", main = \"\")  # mosaic plot\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nThe color contrasts in the mosaic plot substantiate the impression that the two varieties of English differ significantly. To ascertain whether the differences are statistically significant, we can now apply the chi-square test.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform chi square test without Yate's correction\nchisq.test(chidata, corr = F)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  chidata\nX-squared = 220.73, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe results reported by `R` are identical to the results we derived by hand and confirm that BrE and AmE differ significantly in their use of *sort of* and *kind of*. \n\n\n\nIn a next step, we calculate the effect size.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate effect size\nsqrt(chisq.test(chidata, corr = F)$statistic / sum(chidata) * (min(dim(chidata))-1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-squared \n0.4520877 \n```\n\n\n:::\n:::\n\n\n\n\nThe $\\phi$ coefficient of .45 shows that variety of English correlates moderately with the use of *sort of* and *kind of*. We will now summarize the results.\n\n### Summarizing Chi-Square Results\n\nThe results of our analysis can be summarized as follows: A $\\chi$^2^-test confirms a highly significant correlation of moderate size between the variety of English and the use of the near-synonymous hedges *sort of* and *kind of* ($\\chi$^2^ = 220.73, df = 1, p < .001***, $\\phi$ = .452).\n\n### Requirements of Chi-Square\n\nChi-square tests depend on certain requirements that, if violated, negatively affect the reliability of the results of the test. To provide reliable results, \n\n* 80 percent of cells in a table to which the chi-square test is applied have to have expected values of 5 or higher and at most 20 percent of expected values can be smaller than 5 [see @bortz109verteilungsfreie,  98]  \n* none of the expected values can be smaller than 1 [see @bortz109verteilungsfreie, 136] because then, the estimation, which relies on the $\\chi$^2^-distribution, becomes too imprecise to allow meaningful inferences [@cochran1954somemethods].  \n\n\nIf these requirements are violated, then the *Fisher's Exact Test* is more reliable and offers the additional advantage that these tests can also be applied to data that represent very small sample sizes. When applying the Fisher's Exact Test, the probabilities for all possible outcomes are calculated and the summed probability for the observed or more extreme results are determined. If this sum of probabilities exceeds five percent, then the result is deemed statistically significant.\n\n\n\n## Student's t-test\n\nThere are two basic types of t-tests: the dependent or paired t-test and the independent t-test. Paired t-test are used when the data points are not independent, for example, because they come form the same subjects in a  pre-post test design. In contrast, Independent t-tests are used when the data points are independent and come from two different groups (e.g., from learners and native speakers or from men and women).\n\nThe assumptions of the Student's t-test are that \n\n* the dependent variable is a continuous, numeric variable;\n* the independent variable is a nominal variable (two levels / groups)\n* the variances within each group are approximately normal;\n* the errors within each group are approximately normal (this implies that the distributions of the scores of each group are approximately normal).\n\nIf the variances are not normal, then this indicates that another important variable is confounding the results. In such cases, you should go back to the data and check what other variable could cause the unequal variances. If you decide to proceed with the analysis, you can switch to a Welch t-test which does not assume equal variances within each group.\n\n\n### Theoretical underpinnings: power, effect size, and variability{-}\n\nRemember that we use t-tests to determine if two groups differ significantly. However, what determines if we find a significant difference? Let us explore this issue in a but more detail and let's have a look at some distributions to understand what is going on...\n\n#### Effect size{-}\n\nAnd let's start with trying to understand what role effect size plays in finding a significant difference. To this end, we will create numeric vectors for two groups with varying effect size.\n\n\nLet us start with the distribution of two samples (N = 30) sampled from the same population.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 100, mean2 = 100, sd1 = 10, n = 30, pop = \"the same population\")\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/displot1-1.png){width=672}\n:::\n:::\n\n\n\n\n\nNote that the means are not identical ( the blue and red dots) and we would assume that there may actually be a difference between the groups (i.e., that they are sampled from two different populations). In such cases (and assuming that we actually do not know the population parameters as we do here), we cannot determine if the insignificant result reported by the t-test is due there being no effect or that the result is insignificant because the sample(s) are too small!\n\nNow, lets have a look at at the distribution of two different groups (group has a weak effect, Cohen's *d* = .2)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 99, mean2 = 101, sd1 = 10, n = 30, d = .2, effect = \"weak\", seed = 111)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/weak-1.png){width=672}\n:::\n:::\n\n\n\n\nHere, there is actually a difference between the populations form which we have sampled the groups but the t-test fails to confirm that there is a significant difference between the groups (because of the small sample size, the weak effect size, and the variability in the data).\n\nNow, let's have a look at at the distribution of two different groups (group has a medium effect, Cohen's *d* = .5)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 97.5, mean2 = 102.5, sd1 = 10, n = 30, d = 0.5, effect = \"medium\", seed = 234)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/medium-1.png){width=672}\n:::\n:::\n\n\n\n\nHere we see that the t-test is actually able to detect the difference (meaning that the sample size was sufficient to detect a medium effect **in this case**. However, the p-value is barely below .05 and we could ask ourselves if we just got lucky or if we would be able to detect the difference with confidence.\n\nNow, lets have a look at at the distribution of two different groups (group has a strong effect, Cohen's *d* = .8)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 96, mean2 = 104, sd1 = 10, n = 30, d = 0.8, effect = \"strong\", seed = 444, ylim = 0.08)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/strong-1.png){width=672}\n:::\n:::\n\n\n\n\nHere the situation is pretty clear cut and given the strong effect, the t-test is able to confirm the difference. Given the substantive difference in the means, it would be very likely that a t-test would repeatedly confirm this difference if we continued to draw samples. \n\n\n**From the above, we can conclude that if variability and sample size remain constant, larger effects are easier to detect than smaller effects!**\n\n#### Sample size{-}\n\nAnd let's now look at sample size. In a first example, we draw two samples of 30 observations each. The populations from which the samples are drawn differ with a medium effect size for the difference between groups.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 97.5, mean2 = 102.5, sd1 = 10, n = 30, d = 0.5, effect = \"medium\", seed = 555)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/n30-1.png){width=672}\n:::\n:::\n\n\n\n\nThe t-test reports a non-significant result (which is wrong as we know that the populations differ!). This means that we are dealing with a $\\beta$-error (not detecting an effect although it is there).\n\nLet us now increase the sample size to N = 50.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 97.5, mean2 = 102.5, sd1 = 10, n = 50, d = 0.5, effect = \"medium\", seed = 888)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/n50-1.png){width=672}\n:::\n:::\n\n\n\n\nNow the result is clearly significant which means: **If variability and effect size remain constant, effects are easier to detect with increasing sample size!**\n\n#### Variability{-}\n\nAnd let's now look at variability. Again, we start with a sample size of 30, a medium effect size and equal variances.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 97.5, mean2 = 102.5, sd1 = 10, n = 30, d = 0.5, effect = \"medium\", seed = 345)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/sd10-1.png){width=672}\n:::\n:::\n\n\n\n\nAlthough we are dealing with a medium effect size, the t-test tells us that the samples do not differ significantly (due to the low sample size and the high variability in the data). \n\nLet's decrease the variability to sd = 5.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistplot(mean1 = 97.5, mean2 = 102.5, sd1 = 5, n = 30, d = 0.5, effect = \"medium\", ylim = 0.125, seed = 999)\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/sd5-1.png){width=672}\n:::\n:::\n\n\n\n\nNow, the results is significant which means: **If the sample and effect size remain constant, effects are easier to detect with decreasing variability!**\n\n**In summary**, there are three main factors that determine if a model finds an effect. The accuracy (i.e., the probability of finding an effect):\n\n* the size of the effect (bigger effects are easier to detect)\n* the variability of the effect (less variability makes it easier to detect an effect), and \n* the sample size (the bigger the sample size, the easier it is to detect an effect); \n  + number of subjects/participants\n  + number of items/questions\n  + number of observations per item within subjects/participants\n  \nLet us now continue with implementing t-tests in R.\n\n### Paired t-test\n\nPaired t-tests take into account that the scores (or values) come from the same individuals in two conditions (e.g. before and after a treatment).There are two equations for the paired t-test that are used.\n\n\\begin{equation}\nt = \\frac{\\sum D}{\\sqrt{\\frac{N \\sum D^2 - (\\sum D)^2}{N-1}}}\n\\end{equation}\n\nor \n\n\\begin{equation}\nt = \\frac{\\bar D}{\\frac{s_D}{\\sqrt{N}}}\n\\end{equation}\n\nTo show how a paired t-tests works, we will test if a treatment (a teaching method) reduces the number of spelling errors in a long essay of 6 students. In a  first step, we generate some data representing the errors in two essays of the same length written before and after the teaching method was used for 8 weeks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPretest <- c(78, 65, 71, 68, 76, 59)\nPosttest <- c(71, 62, 70, 60, 66, 48)\nptd <- data.frame(Pretest, Posttest)\n```\n:::\n\n\n\n\nThe data look like as shown in the table below.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4bfc835e{table-layout:auto;width:75%;}.cl-4be8b874{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4be8b892{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4bf03284{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4bf090e4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf090f8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf09102{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf0910c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf09116{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf09120{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf0912a{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4bf0912b{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4bfc835e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4bf090e4\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b874\">Pretest</span></p></th><th class=\"cl-4bf090f8\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b874\">Posttest</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf09102\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">78</span></p></td><td class=\"cl-4bf0910c\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">71</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf09116\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">65</span></p></td><td class=\"cl-4bf09120\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">62</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf09102\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">71</span></p></td><td class=\"cl-4bf0910c\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">70</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf09116\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">68</span></p></td><td class=\"cl-4bf09120\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">60</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf09102\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">76</span></p></td><td class=\"cl-4bf0910c\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">66</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4bf0912a\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">59</span></p></td><td class=\"cl-4bf0912b\"><p class=\"cl-4bf03284\"><span class=\"cl-4be8b892\">48</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nBefore performing the paired t-test, let us just briefly inspect the mans to see if the means of the pre- and post test differ:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(ptd$Pretest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69.5\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(ptd$Posttest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62.83333\n```\n\n\n:::\n:::\n\n\n\n\nThe results show that the mean of the post-test is lower than the mean of the pre-test results.\n\nTo perform a paired t-test in R, we use the `t.test` function and specify the argument `paired` as TRUE.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(ptd$Pretest,\n       ptd$Posttest,\n       paired=TRUE,\n       conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  ptd$Pretest and ptd$Posttest\nt = 4.1523, df = 5, p-value = 0.00889\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n  2.539479 10.793854\nsample estimates:\nmean difference \n       6.666667 \n```\n\n\n:::\n:::\n\n\n\n\nIn addition to testing if the groups differ significantly, we also want to calculate the effect size of the difference. We can use the `effectsize` package to extract Cohen's $d$ which is the standard effect size measure for t-tests.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cohens_d(x = ptd$Pretest, \n                     y = ptd$Posttest,\n                     paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n1.70      | [0.37, 2.96]\n```\n\n\n:::\n:::\n\n\n\n\nTo check if the effect is small or big - that is if a Cohen's $d$ value can be interpreted as being small or big, we can use the following overview.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4c9ca208{table-layout:auto;width:75%;}.cl-4c8c2cde{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4c8c2cf2{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4c93c6ce{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4c93c6e2{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4c9425c4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c9425d8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c9425e2{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c9425ec{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c9425f6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942600{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942601{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942614{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c94261e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942628{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942632{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4c942633{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4c9ca208'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4c9425c4\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cde\">EffectSize</span></p></th><th class=\"cl-4c9425d8\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cde\">d</span></p></th><th class=\"cl-4c9425e2\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cde\">Reference</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c9425ec\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Very small</span></p></td><td class=\"cl-4c9425f6\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">0.01</span></p></td><td class=\"cl-4c942600\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Sawilowsky (2009)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c942601\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Small</span></p></td><td class=\"cl-4c942614\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">0.20</span></p></td><td class=\"cl-4c94261e\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Cohen (1988)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c9425ec\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Medium</span></p></td><td class=\"cl-4c9425f6\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">0.50</span></p></td><td class=\"cl-4c942600\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Cohen (1988)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c942601\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Large</span></p></td><td class=\"cl-4c942614\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">0.80</span></p></td><td class=\"cl-4c94261e\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Cohen (1988)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c9425ec\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Very large</span></p></td><td class=\"cl-4c9425f6\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">1.20</span></p></td><td class=\"cl-4c942600\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Sawilowsky (2009)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4c942628\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Huge</span></p></td><td class=\"cl-4c942632\"><p class=\"cl-4c93c6e2\"><span class=\"cl-4c8c2cf2\">2.00</span></p></td><td class=\"cl-4c942633\"><p class=\"cl-4c93c6ce\"><span class=\"cl-4c8c2cf2\">Sawilowsky (2009)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\nThe classification combines @sawilowsky2009new and @cohen1988statistical. The analysis can be summarized using the `reports` package [@report] as follows.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(t.test(ptd$Pretest,ptd$Posttest, paired=TRUE, conf.level=0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Paired t-test testing the difference between ptd$Pretest and ptd$Posttest\n(mean difference = 6.67) suggests that the effect is positive, statistically\nsignificant, and large (difference = 6.67, 95% CI [2.54, 10.79], t(5) = 4.15, p\n= 0.009; Cohen's d = 1.70, 95% CI [0.37, 2.96])\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\nA paired t-test test was applied to the data and it confirmed that the number of spelling errors after the 8 weeks of using the new teaching method significantly decreased (t~5~: 4.1523, p = .009\\*\\*). The treatment had a very large, statistically significant, positive effect (Cohen's $d$ = 1.70 [CIs: 0.41, 3.25]) [cf. @sawilowsky2009new].\n\n### Independent t-tests\n\nIndependent t-tests are used very widely and they determine if the means of two groups are significantly different. As such, t-tests are used when we have a normally distributed (or parametric), numeric dependent variable and a nominal predictor variable.\n\n\\begin{equation}\nt = \\frac{\\bar X_1 - \\bar X_2}{\\sqrt{\\frac{s^2_p}{N_1} + \\frac{s^2_p}{N_2}}}\n\\end{equation}\n\nwhere\n\n\\begin{equation}\ns^2_p = \\frac{(N_1 - 1)s^2_1 + (N_2 - 1)s^2_2}{N_1 + N_2 - 2}\n\\end{equation}\n\nWe now load some data that we can apply a t-test to. The data represents scores on a proficiency test of native speakers and learners of English. We want to use a t-test to determine if the native speakers and learners differ in their proficiency.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\ntdata <- base::readRDS(url(\"https://slcladal.github.io/data/d03.rda\", \"rb\")) |>\n  dplyr::rename(NativeSpeakers = 1,\n                Learners = 2) |>\n  tidyr::gather(Group, Score, NativeSpeakers:Learners) |>\n  dplyr::mutate(Group = factor(Group))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4d235b0e{table-layout:auto;width:75%;}.cl-4d134a34{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4d134a48{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4d1a02b6{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4d1a02c0{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4d1a2b2e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b38{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b39{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b42{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b4c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b56{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b57{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d1a2b60{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4d235b0e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4d1a2b2e\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a34\">Group</span></p></th><th class=\"cl-4d1a2b38\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a34\">Score</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">65</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">12</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">56</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">45</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">84</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">38</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">46</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">64</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">NativeSpeakers</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">24</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">67</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">16</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">56</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">34</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">54</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">42</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">36</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b4c\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b56\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">47</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b39\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b42\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">54</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d1a2b57\"><p class=\"cl-4d1a02b6\"><span class=\"cl-4d134a48\">Learners</span></p></td><td class=\"cl-4d1a2b60\"><p class=\"cl-4d1a02c0\"><span class=\"cl-4d134a48\">29</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe now apply an independent t-test to the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Score ~ Group, \n       var.equal = T,\n       data = tdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Score by Group\nt = -0.054589, df = 18, p-value = 0.9571\nalternative hypothesis: true difference in means between group Learners and group NativeSpeakers is not equal to 0\n95 percent confidence interval:\n -19.74317  18.74317\nsample estimates:\n      mean in group Learners mean in group NativeSpeakers \n                        43.5                         44.0 \n```\n\n\n:::\n:::\n\n\n\n\nAs the p-value is higher than .05, we cannot reject the H~0~ and we thus have to conclude that our evidence does not suffice to say that learners and Native Speakers differ in their proficiency. However, we still extract the effect size, again using Cohen's $d$. In contrast to the extraction of the effect size for paired t-tests, however, we will set the argument `paired` to `FALSE` (in fact, we could simply leave it out as the `paired = FALSE` is the default).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cohens_d(tdata$Score ~ tdata$Group,\n                     paired = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |        95% CI\n-------------------------\n-0.02     | [-0.90, 0.85]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\n\n\nThe analysis can be summarized using the `reports` package [@report] as follows.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(t.test(Score ~ Group, var.equal = T, data = tdata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Two Sample t-test testing the difference of Score by Group (mean in group\nLearners = 43.50, mean in group NativeSpeakers = 44.00) suggests that the\neffect is negative, statistically not significant, and very small (difference =\n-0.50, 95% CI [-19.74, 18.74], t(18) = -0.05, p = 0.957; Cohen's d = -0.03, 95%\nCI [-0.95, 0.90])\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\nAn independent t-test test was applied to the data and it reported that the scores between the two groups did not differ significantly (t~18~: -0.0546, p = .9571). In addition to not differing significantly, the effect size of the difference between the groups was also very small (Cohen's $d$ = -0.03 [CIs: -0.95, 0.90]) [cf. @sawilowsky2009new].\n\n\n\n## Mann-Whitney U-Test \n\n::: {.callout-note}\n## Key concept: Parametric vs. non-parametric tests\n\n*Parametric* tests (like the t-test) assume that the data follow a particular distribution (typically the normal distribution) and use the actual values in their calculations, which gives them more statistical power *when the assumptions hold*. *Non-parametric* tests (like the Mann-Whitney U-test) work on ranks instead of raw values and make far weaker distributional assumptions - the robust fallback when data are skewed, ordinal, or contain outliers. The price of this robustness is somewhat lower power when the parametric assumptions would in fact have been met.\n:::\n\n\nIt is actually quite common that numeric depend variables need to be transformed or converted into ranks, i.e. ordinal variables, because the distribution of residuals does not allow the application of parametric tests such as t-tests or linear regression. In such cases, as we are dealing with rank (ordinal) data, the application of a chi-square test is unwarranted and we need to use another test. There are different alternatives depending on whether the data are paired (coming from the same individuals) or if all observations are independent. \n\nThe non-parametric alternative for independent t-tests, i.e. for data where we are dealing with two separate groups and a numeric dependent variable that violates parametric assumptions (or an ordinal dependent variable), is the Mann-Whitney U-test. In contrast, if the groups under investigation represent identical participants that are tested under two conditions, the appropriate alternative is a Wilcoxon Signed Rank test (which is thus the alternative for paired t-test).\n\nImagine we wanted to determine if two language families differed with respect to the size of their phoneme inventories. You have already ranked the inventory sizes and would now like to now if language family correlates with inventory size. As such, we are dealing with two independent groups and we want to implement a non-parametric alternative of a t-test. To answer this question, you create the table shown below. \n\n*LanguageFamily* refers to the language family that a language belongs to and *Rank* represent the rank of language based on its phoneme inventory size (1 = largest phoneme inventory, 20 = smallest phoneme inventory).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create table\nRank <- c(1,3,5,6,8,9,10,11,17,19, 2,4,7,12,13,14,15,16,18,20)\nLanguageFamily <- c(rep(\"Kovati\", 10), rep(\"Urudi\", 10))\nlftb <- data.frame(LanguageFamily, Rank)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4d72b028{table-layout:auto;width:75%;}.cl-4d60a5cc{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4d60a5ea{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4d682f0e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4d682f2c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4d6897e6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d6897fa{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d689804{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d68980e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d689818{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d689822{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d68982c{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4d68982d{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4d72b028'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4d6897e6\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5cc\">LanguageFamily</span></p></th><th class=\"cl-4d6897fa\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5cc\">Rank</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">8</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">10</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">11</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">17</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Kovati</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">19</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">12</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">13</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">14</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">15</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689818\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d689822\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">16</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d689804\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68980e\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">18</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4d68982c\"><p class=\"cl-4d682f0e\"><span class=\"cl-4d60a5ea\">Urudi</span></p></td><td class=\"cl-4d68982d\"><p class=\"cl-4d682f2c\"><span class=\"cl-4d60a5ea\">20</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe will also briefly inspect the data visually using a box plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(lftb, aes(x = LanguageFamily, y = Rank, fill = LanguageFamily)) +\n  geom_boxplot() +\n  scale_fill_manual(values = c(\"orange\", \"darkgrey\")) +\n  theme_bw() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/mwu2-1.png){width=672}\n:::\n:::\n\n\n\n\nTo use the Mann-Whitney U test, the dependent variable (Rank) must be ordinal and independent variable (Group) must be a binary factor. We briefly check this by inspecting the structure of the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# inspect structure\nstr(lftb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t20 obs. of  2 variables:\n $ LanguageFamily: chr  \"Kovati\" \"Kovati\" \"Kovati\" \"Kovati\" ...\n $ Rank          : num  1 3 5 6 8 9 10 11 17 19 ...\n```\n\n\n:::\n:::\n\n\n\n\nAs the variables are what we need them to be, we can now perform the Mann-Whitney U test on the table. The null hypothesis is that there is no difference between the 2 groups.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform test\nwilcox.test(lftb$Rank ~ lftb$LanguageFamily) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  lftb$Rank by lftb$LanguageFamily\nW = 34, p-value = 0.2475\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n\n\nSince the p-value is greater than 0.05, we fail to reject the null hypothesis. The results of the Mann-Whitney U test tell us that the two language families do not differ significantly with respect to their phoneme inventory size.\n\n\nThe analysis can be summarized using the `reports` package [@report] as follows.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(wilcox.test(lftb$Rank ~ lftb$LanguageFamily))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Funder's (2019) recommendations.\n\nThe Wilcoxon rank sum exact test testing the difference in ranks between\nlftb$Rank and lftb$LanguageFamily suggests that the effect is negative,\nstatistically not significant, and large (W = 34.00, p = 0.247; r (rank\nbiserial) = -0.32, 95% CI [-0.69, 0.18])\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\nThe Wilcoxon rank sum exact test  suggests that there is no statistically  significant relationship between the size of phoneme inventories and being member of selected language families. Despite being statistically insignificant, the effect may be large (W = 34.00, p = 0.247; r (rank biserial) = -0.32, 95% CI [-0.69, 0.18]).\n\n### Mann-Whitney U tests with continuity correction {-}\n\nThe Mann-Whitney U test can also be used with continuity correction. A continuity correction is necessary when both variables represent numeric values that are non-normal. This is quite handy because it means that we do not need to convert our numeric dependent variable into ranks (an ordered variable). In the following example, we want to test if the reaction time for identifying a word as real is correlated with its token frequency.\n\nFor this example, we generate data is deliberately non-normal.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4e3addf0{table-layout:auto;width:75%;}.cl-4e2adc84{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4e2adc98{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4e324870{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-4e32956e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e329578{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e329579{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e329582{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e329596{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e3295a0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e3295a1{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4e3295aa{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4e3addf0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4e32956e\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc84\">Frequency</span></p></th><th class=\"cl-4e329578\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc84\">Reaction</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329579\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">25,485.43</span></p></td><td class=\"cl-4e329582\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">395.2039</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329596\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">24,468.44</span></p></td><td class=\"cl-4e3295a0\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">370.9637</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329579\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">24,218.94</span></p></td><td class=\"cl-4e329582\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">412.2960</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329596\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">20,405.75</span></p></td><td class=\"cl-4e3295a0\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">425.7529</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329579\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">19,020.88</span></p></td><td class=\"cl-4e329582\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">412.9506</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329596\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">17,363.19</span></p></td><td class=\"cl-4e3295a0\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">404.0559</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329579\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">17,319.49</span></p></td><td class=\"cl-4e329582\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">401.1195</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329596\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">17,042.85</span></p></td><td class=\"cl-4e3295a0\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">434.8484</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e329579\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">15,527.19</span></p></td><td class=\"cl-4e329582\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">390.0054</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4e3295a1\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">14,233.21</span></p></td><td class=\"cl-4e3295aa\"><p class=\"cl-4e324870\"><span class=\"cl-4e2adc98\">456.4710</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWhen we plot the data, we see that both the frequency of words (Frequency) and the reaction times that it took subjects to recognize the token as a word (Reaction) are non-normal (in this case, the distributions are negative skewed).\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-week8_files/figure-html/mwu5c-1.png){width=672}\n:::\n:::\n\n\n\n\nBoth variables are negatively skewed (non-normally distributed) but we can use the `wilcox.test` function to perform the Mann-Whitney U test with continuity correction which takes the skewness into account. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwxdata |>\n  ggplot(aes(Frequency, Reaction)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](08-week8_files/figure-html/mwu6a-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe null hypothesis is that there is no correlation between token frequency and reaction time. The output states that the test that was performed is a *Wilcoxon rank sum test with continuity correction* which is just a different name for the Mann-Whitney U test - this is because the nomenclature for the tests is not unanimous.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform test\nwilcox.test(wxdata$Reaction - wxdata$Frequency) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  wxdata$Reaction - wxdata$Frequency\nV = 81, p-value < 0.00000000000000022\nalternative hypothesis: true location is not equal to 0\n```\n\n\n:::\n:::\n\n\n\n\n\nAgain, we use the `reports` package [@report] to summarize the analysis.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(wilcox.test(wxdata$Reaction - wxdata$Frequency))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Funder's (2019) recommendations.\n\nThe Wilcoxon signed rank test with continuity correction testing the difference\nin rank for wxdata$Reaction - wxdata$Frequency and true location of 0 suggests\nthat the effect is negative, statistically significant, and very large (W =\n81.00, p < .001; r (rank biserial) = -0.99, 95% CI [-0.99, -0.99])\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\nThe Wilcoxon signed rank test with continuity correction suggests that there is a strong, negative, statistically  significant relationship between the reaction time for identifying a word as real and its token frequency (W = 276.00, p < .001; r (rank biserial) = -0.97, 95% CI [-0.98, -0.96]).\n\n\n\n\n::: {.callout-tip}\n## Exercises: Basic Inferential Statistics\n:::\n\n**Q1. You want to test whether the use of a discourse particle (yes/no) is associated with speaker gender (male/female). Which test is appropriate?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W8_Q1\" onsubmit=\"return validate_form_W8_Q1()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W8_Q1\" id=\"answer_W8_Q1_1\" value=\"Chi-square test\"/>\nChi-square test\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q1\" id=\"answer_W8_Q1_2\" value=\"Student&#39;s t-test\"/>\nStudent's t-test\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q1\" id=\"answer_W8_Q1_3\" value=\"Mann-Whitney U-test\"/>\nMann-Whitney U-test\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q1\" id=\"answer_W8_Q1_4\" value=\"Simple linear regression\"/>\nSimple linear regression\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W8_Q1\"></div>\n</form>\n<script>function validate_form_W8_Q1() {var x, text; var x = document.forms['form_W8_Q1']['answer_W8_Q1'].value;if (x == 'Chi-square test'){text = 'Correct! Both variables are categorical (nominal), so a chi-square test of the 2×2 frequency table is the appropriate choice. t-tests and U-tests require a numeric (or at least ordinal) outcome.';} else {text = 'Both variables are categorical - which test works on frequency tables?';} document.getElementById('result_W8_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_W8_Q1').innerText == 'Correct! Both variables are categorical (nominal), so a chi-square test of the 2×2 frequency table is the appropriate choice. t-tests and U-tests require a numeric (or at least ordinal) outcome.';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q2. A t-test comparing essay scores of two groups yields p = .001 with n = 10,000 per group. What should you check before concluding that the difference matters?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W8_Q2\" onsubmit=\"return validate_form_W8_Q2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W8_Q2\" id=\"answer_W8_Q2_1\" value=\"The effect size (e.g. Cohen&#39;s d) - with huge samples, even tiny, practically irrelevant differences become significant\"/>\nThe effect size (e.g. Cohen's d) - with huge samples, even tiny, practically irrelevant differences become significant\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q2\" id=\"answer_W8_Q2_2\" value=\"Whether the groups have identical means\"/>\nWhether the groups have identical means\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q2\" id=\"answer_W8_Q2_3\" value=\"Whether the p-value can be pushed below .0001\"/>\nWhether the p-value can be pushed below .0001\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q2\" id=\"answer_W8_Q2_4\" value=\"Nothing - p &lt; .05 proves the difference is important\"/>\nNothing - p &lt; .05 proves the difference is important\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W8_Q2\"></div>\n</form>\n<script>function validate_form_W8_Q2() {var x, text; var x = document.forms['form_W8_Q2']['answer_W8_Q2'].value;if (x == 'The effect size (e.g. Cohen's d) - with huge samples, even tiny, practically irrelevant differences become significant'){text = 'Correct! Statistical significance answers ‘is there evidence of <em>any</em> difference?’, not ‘is the difference <em>large enough to matter</em>?’. With n = 10,000 per group, a difference of a fraction of a point can be highly significant. Effect sizes quantify practical relevance.';} else {text = 'Significance depends on sample size; what quantifies the <em>magnitude</em> of a difference?';} document.getElementById('result_W8_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_W8_Q1').innerText == 'Correct! Both variables are categorical (nominal), so a chi-square test of the 2×2 frequency table is the appropriate choice. t-tests and U-tests require a numeric (or at least ordinal) outcome.'; res2 = document.getElementById('result_W8_Q2').innerText == 'Correct! Statistical significance answers ‘is there evidence of any difference?’, not ‘is the difference large enough to matter?’. With n = 10,000 per group, a difference of a fraction of a point can be highly significant. Effect sizes quantify practical relevance.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q3. Your reaction-time data are heavily right-skewed with several extreme outliers. You want to compare two groups. What is the most defensible choice?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W8_Q3\" onsubmit=\"return validate_form_W8_Q3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W8_Q3\" id=\"answer_W8_Q3_1\" value=\"Delete all outliers until the data look normal\"/>\nDelete all outliers until the data look normal\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q3\" id=\"answer_W8_Q3_2\" value=\"Use the Mann-Whitney U-test, which works on ranks and is robust to skew and outliers\"/>\nUse the Mann-Whitney U-test, which works on ranks and is robust to skew and outliers\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q3\" id=\"answer_W8_Q3_3\" value=\"Use the t-test anyway - it always works\"/>\nUse the t-test anyway - it always works\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W8_Q3\" id=\"answer_W8_Q3_4\" value=\"Compare only the two largest values\"/>\nCompare only the two largest values\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W8_Q3\"></div>\n</form>\n<script>function validate_form_W8_Q3() {var x, text; var x = document.forms['form_W8_Q3']['answer_W8_Q3'].value;if (x == 'Use the Mann-Whitney U-test, which works on ranks and is robust to skew and outliers'){text = 'Correct! The U-test’s rank-based approach makes it robust to exactly these violations. (Transforming the data or using robust methods are also defensible; silently deleting inconvenient data points is not.)';} else {text = 'Which test makes the weakest assumptions about the distribution of the data?';} document.getElementById('result_W8_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_W8_Q1').innerText == 'Correct! Both variables are categorical (nominal), so a chi-square test of the 2×2 frequency table is the appropriate choice. t-tests and U-tests require a numeric (or at least ordinal) outcome.'; res2 = document.getElementById('result_W8_Q2').innerText == 'Correct! Statistical significance answers ‘is there evidence of any difference?’, not ‘is the difference large enough to matter?’. With n = 10,000 per group, a difference of a fraction of a point can be highly significant. Effect sizes quantify practical relevance.'; res3 = document.getElementById('result_W8_Q3').innerText == 'Correct! The U-test’s rank-based approach makes it robust to exactly these violations. (Transforming the data or using robust methods are also defensible; silently deleting inconvenient data points is not.)';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n[Back to top](#week8)\n\n",
    "supporting": [
      "08-week8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}