{
  "hash": "98e5ed39cb75b862f5f6d0667f3699f0",
  "result": {
    "engine": "knitr",
    "markdown": "# Descriptive Statistics {#week6}\n\n::: {.callout-tip}\n## What This Session Covers\n\nStatistics can be divided into two main branches: *descriptive statistics* (describing and visualising data - this session) and *inferential statistics* (drawing conclusions about populations from samples - from Week 8 onward). This session covers:\n\n1. **Measures of central tendency** - mean, median, and mode, and when to use which\n2. **Measures of variability** - range, variance, standard deviation, and standard error\n3. **Confidence intervals** - parametric and bootstrapped intervals for means and proportions\n:::\n\nThis week, we focus on how to describe and summarize data [see e.g. @bickel2012descriptive; @thompson2009descriptive]. To show why data summaries are useful, think of the following: you are teaching two different classes in the same school, in the same grade, and at the same level. Both classes take the same exam and, after correcting and grading the exams, someone asks you which class performed better. You could of course say something along the lines of *Well, class A had 5 Bs, 10 Cs, 12 Ds, and 2 Fs while class B had 2 As, 8 Bs, 10 Ds, and 4 Fs*.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-006a2036{table-layout:auto;width:95%;}.cl-005ad838{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-005ad856{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00619344{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0061cfd0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061cfe4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061cfe5{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061cfee{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061cff8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061cff9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d002{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d003{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d00c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d00d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d00e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0061d016{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-006a2036'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-0061cfd0\"><p class=\"cl-00619344\"><span class=\"cl-005ad838\">Grade</span></p></th><th class=\"cl-0061cfe4\"><p class=\"cl-00619344\"><span class=\"cl-005ad838\">classA</span></p></th><th class=\"cl-0061cfe5\"><p class=\"cl-00619344\"><span class=\"cl-005ad838\">classB</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0061cfee\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">A</span></p></td><td class=\"cl-0061cff8\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\"></span></p></td><td class=\"cl-0061cff9\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0061d002\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">B</span></p></td><td class=\"cl-0061d003\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">5</span></p></td><td class=\"cl-0061d00c\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">8</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0061cfee\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">C</span></p></td><td class=\"cl-0061cff8\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">10</span></p></td><td class=\"cl-0061cff9\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0061d002\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">D</span></p></td><td class=\"cl-0061d003\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">12</span></p></td><td class=\"cl-0061d00c\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">10</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0061d00d\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">F</span></p></td><td class=\"cl-0061d00e\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">2</span></p></td><td class=\"cl-0061d016\"><p class=\"cl-00619344\"><span class=\"cl-005ad856\">4</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\nBut this answer is not really satisfying. Descriptive statistics enable you to summarize complex data sets in very few words and using only very basic, and easy to understand, concepts. And this is what we will be dealing with in the following. \n\nBefore delving deeper into what descriptive statistics is, it is useful to have a general idea of how it can be contextualized. Thus, on a more general note, we will be dealing only with one particular subbranch of statistics. Statistics in general can be defined as a branch of mathematics that deals with data collection, organization, analysis, interpretation, and presentation. As such, statistics can be subdivided into two main areas. *Descriptive statistics* deals with the description of data and their visualization, while *inferential statistics* deals with data analysis and interpretation. Typically, this means testing assumptions about correlations between variables (see for example [here](https://slcladal.github.io/basicstatzregression.html)). As stated above, here, we will be dealing with the description of data, especially with *measures of central tendency*, *measures of variability* and *confidence intervals*.\n\n\n## Measures of Centrality\n\n::: {.callout-note}\n## Key concept: Mean vs. median\n\nThe *mean* (arithmetic average) uses every value in the data, which makes it efficient but also sensitive to outliers: a single extreme value can pull it far away from the bulk of the data. The *median* (the middle value when the data are ordered) is robust against outliers. Rule of thumb: report the mean for roughly symmetric distributions without extreme values, and the median for skewed distributions or data with outliers (e.g. reaction times, word frequencies, income).\n:::\n\n\nIn linguistics three measures of centrality or measures of central tendency are of particular relevance: the *mean*, the *median* and the *mode* [@gaddis1990introduction]. In addition, there are two more measures of central tendency, the geometric and the harmonic mean which we will only briefly discuss as they are not that relevant for language research. What measure is appropriate depends on the type of variable scaling, the distribution of the data, and what is the intended aim of the data summary.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-00b151c2{table-layout:auto;width:95%;}.cl-00a387fe{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00a38812{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00a80b8a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-00a82fc0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fca{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fd4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fd5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fde{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fdf{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fe8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00a82fe9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-00b151c2'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-00a82fc0\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a387fe\">Means</span></p></th><th class=\"cl-00a82fca\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a387fe\">Use</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00a82fd4\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">(Arithmetic) mean (average)</span></p></td><td class=\"cl-00a82fd5\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Description of normally distributed numeric variables (most common measure of central tendency)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00a82fde\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Median (middle value)</span></p></td><td class=\"cl-00a82fdf\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Description of non-normal numeric variables or ordinal variables (skewed data or influential outliers)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00a82fd4\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Mode (most frequent value)</span></p></td><td class=\"cl-00a82fd5\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Description of nominal and categorical variables</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00a82fde\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Geometric mean (average factor)</span></p></td><td class=\"cl-00a82fdf\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Description of dynamic processes such as growth rates</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00a82fe8\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Harmonic mean (average rate)</span></p></td><td class=\"cl-00a82fe9\"><p class=\"cl-00a80b8a\"><span class=\"cl-00a38812\">Description of dynamic processes such as velocities</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nIn the following we will go over these types of measures of central tendencies, exemplify their use, describe their strengths and weaknesses, and show how to calculate them in R.\n\n### Mean{-}\n\nThe mean is used when the data is numeric and normally distributed. The mean is calculated by applying the formula shown below.\n\n\\begin{equation}\n  \\bar{x}=\\frac{1}{n} \\sum_{i=1}^n x_i = \\frac{x_{1}+x_{2}+ \\dots + x_{n}}{n}\n\\end{equation}\n\nTo calculate the mean, sum up all values and divide by the number of values. See the example below for clarification. \n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds03-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\nConsider, we are interested in the mean length of sentences in a short text, then the first thing we could do would be to list the sentences and their length in a table.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-012acd90{table-layout:auto;width:95%;}.cl-011f01fe{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-011f0212{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0123c52c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0123c536{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0123ed18{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed22{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed23{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed2c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed2d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed36{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed37{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0123ed40{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-012acd90'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-0123ed18\"><p class=\"cl-0123c52c\"><span class=\"cl-011f01fe\">Sentences</span></p></th><th class=\"cl-0123ed22\"><p class=\"cl-0123c536\"><span class=\"cl-011f01fe\">Words</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0123ed23\"><p class=\"cl-0123c52c\"><span class=\"cl-011f0212\">Call me Ishmael</span></p></td><td class=\"cl-0123ed2c\"><p class=\"cl-0123c536\"><span class=\"cl-011f0212\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0123ed2d\"><p class=\"cl-0123c52c\"><span class=\"cl-011f0212\">Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.</span></p></td><td class=\"cl-0123ed36\"><p class=\"cl-0123c536\"><span class=\"cl-011f0212\">40</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0123ed23\"><p class=\"cl-0123c52c\"><span class=\"cl-011f0212\">It is a way I have of driving off the spleen, and regulating the circulation.</span></p></td><td class=\"cl-0123ed2c\"><p class=\"cl-0123c536\"><span class=\"cl-011f0212\">15</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0123ed37\"><p class=\"cl-0123c52c\"><span class=\"cl-011f0212\">Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off--then, I account it high time to get to sea as soon as I can.</span></p></td><td class=\"cl-0123ed40\"><p class=\"cl-0123c536\"><span class=\"cl-011f0212\">87</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\nTo calculate the mean, we need to divide the sum of the number of words per sentence (145) by the number of sentences (7) (see the equation below).\n\n\\begin{equation}\n  \\frac{3+40+15+87}{4} = \\frac{145}{4} = 36.25\n  \\label{eq:mittel2}\n\\end{equation}\n\nThe mean sentences length in our example is 36.25 words\n\nIn R, the *mean* is calculated as follows.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create numeric vector\nfrequencies <- c(3, 40, 15, 87)\n# calculate mean\nmean(frequencies)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.25\n```\n\n\n:::\n:::\n\n\n\n\nThe mean is the most common way to summarize numeric variables and it is very easy and intuitive to understand. A disadvantage of the mean is that it is very strongly affected by outliers which is why the median is the preferable measure of centrality when dealing with data that is not normal or that contains outliers.\n\n\n\n\n### Median{-}\n\nThe median can be used for both numeric and ordinal variables. In contrast to the mean, it is more robust and not as easily affected by outliers. While the mean is commonly associated with numeric data that is normally distributed, the median is typically used when dealing with non-normal numeric or ordinal variables, i.e. variables that are ordered but not truly numeric. The median is the central value in a de- or increasing ordering of values in a vector. In other words, 50 percent of values are above and 50 percent of values are below the median in a given vector.\n\nIf the vector contains an even number of elements, then the two central values are summed up and divided by 2. If the vector contains an uneven number of elements, the median represents the central value.\n\n\\begin{equation}\nmedian_{x}=\n\\begin{cases}\nx_{\\frac{n+1}{2}} & n\\text{ uneven} \\\\\n\\frac{1}{2}\\bigl(x_{\\frac{n}{2}}+x_{\\frac{n+1}{2}}\\bigr) & n\\text{ even}\n\\end{cases}\n\\label{eq:median}\n\\end{equation}\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds07-1.png){width=672}\n:::\n:::\n\n\n\n\n\nLet's have a look at an example. Consider you are interested in the age stratification of speakers in the private dialogue section of the Irish component of the *International Corpus of English* (ICE). When tabulating and plotting the age variable you get the following table and graph.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-01a88726{table-layout:auto;width:50%;}.cl-01970686{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-01970690{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-019d1aa8{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-019d1abc{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-019d5888{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d5892{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d589c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d589d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d58a6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d58b0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d58ba{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-019d58bb{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-01a88726'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-019d5888\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970686\">Age</span></p></th><th class=\"cl-019d5892\"><p class=\"cl-019d1abc\"><span class=\"cl-01970686\">Counts</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d589c\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">0-18</span></p></td><td class=\"cl-019d589d\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d58a6\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">19-25</span></p></td><td class=\"cl-019d58b0\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">160</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d589c\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">26-33</span></p></td><td class=\"cl-019d589d\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">70</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d58a6\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">34-41</span></p></td><td class=\"cl-019d58b0\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">15</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d589c\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">42-49</span></p></td><td class=\"cl-019d589d\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-019d58ba\"><p class=\"cl-019d1aa8\"><span class=\"cl-01970690\">50+</span></p></td><td class=\"cl-019d58bb\"><p class=\"cl-019d1abc\"><span class=\"cl-01970690\">57</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds09-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe age groups represent an order factor which means that there are categories with a natural order (here from old to young or vice versa). If we order speakers according to their age from young to old, we get a vector of length 320. If we then take the central value, i.e. the value of the 160^th^ speaker, we get the median age in the private dialogue section of the Irish component of the *International Corpus of English* (ICE). \n\nIn R, the *median* is calculated as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a vector consisting out of ranks\nranks <- c(rep(1, 9), rep(2, 160), rep(3, 70), rep(4, 15), rep(5, 9), rep(6, 57))\n# calculate median\nmedian(ranks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\nIn our case, the median age is *19-25* because the 160^th^ speaker belongs to the 2^nd^ age group, i.e. the age group with speakers between 19 and 25 years old.  \n\n\n### Mode{-}\n\nThe mode is typically used when dealing with categorical variables and it reports which level of a factor or a categorical variable is the most frequent. \n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds13-1.png){width=672}\n:::\n:::\n\n\n\n\nHere is an example to illustrate the mode. Consider you are interested where most speakers in the private dialogue section of the Irish component of the *International Corpus of English* are currently residing and you get the following distribution.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-0268471e{table-layout:auto;width:50%;}.cl-025cc344{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-025cc34e{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0261d8a2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0261d8ac{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02621182{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0262118c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02621196{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02621197{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026211a0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026211a1{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026211aa{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026211ab{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0268471e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-02621182\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc344\">CurrentResidence</span></p></th><th class=\"cl-0262118c\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc344\">Speakers</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02621196\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc34e\">Belfast</span></p></td><td class=\"cl-02621197\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc34e\">98</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026211a0\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc34e\">Down</span></p></td><td class=\"cl-026211a1\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc34e\">20</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02621196\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc34e\">Dublin (city)</span></p></td><td class=\"cl-02621197\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc34e\">110</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026211a0\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc34e\">Limerick</span></p></td><td class=\"cl-026211a1\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc34e\">13</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026211aa\"><p class=\"cl-0261d8a2\"><span class=\"cl-025cc34e\">Tipperary</span></p></td><td class=\"cl-026211ab\"><p class=\"cl-0261d8ac\"><span class=\"cl-025cc34e\">19</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds15-1.png){width=672}\n:::\n:::\n\n\n\n\nThe tabulated and visualized data show that the mode is *Dublin (City)*, because the largest group (110 speakers) of speakers in the corpus are speakers from the city of Dublin. This means that the *average* speaker in in the private dialogue section of the Irish component of the *International Corpus of English* (ICE) is from Dublin city.\n\nIn R the *mode* is calculated as shown below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a factor with the current residence of speakers\nCurrentResidence <- c(rep(\"Belfast\", 98),         # repeat \"Belfast\" 98 times\n                      rep(\"Down\", 20),            # repeat \"Down\" 20 times\n                      rep(\"Dublin (city)\", 110),  # repeat \"Dublin (city)\" 110 times\n                      rep(\"Limerick\", 13),        # repeat \"Limerick\" 13 times\n                      rep(\"Tipperary\", 19))       # repeat \"Tipperary\" 19 times\n# calculate mode\nnames(which.max(table(CurrentResidence)))         # extract which level occurs most frequently\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Dublin (city)\"\n```\n\n\n:::\n:::\n\n\n\n\nA word of warning is in order here as only the first(!) maximal value is provided by R even if several categories have the same frequency. \n\n### Geometric mean{-}\n\nThe geometric mean represents a measure of central tendency that is used when dealing with dynamic processes where the later elements are dependent on the previous elements. The geometric mean is calculated according to the equation below.\n\n\\begin{equation}\n\\bar{x}_{geometric} = \\sqrt[n]{x_1 \\times x_{i+1} \\times \\dots \\times x_n}\n\\end{equation}\n\nImagine you have the option to buy two different stock packages and you have to buy one of them. Which one would you buy?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-02ce1e9a{table-layout:auto;width:75%;}.cl-02c3a37a{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-02c3a38e{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-02c83962{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02c872ba{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872ce{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872cf{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872d8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872e2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872e3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872ec{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872ed{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872f6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c872f7{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c87300{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02c8730a{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-02ce1e9a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-02c872ba\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a37a\">Year</span></p></th><th class=\"cl-02c872ce\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a37a\">Package1</span></p></th><th class=\"cl-02c872cf\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a37a\">Package2</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02c872d8\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">Year 1</span></p></td><td class=\"cl-02c872e2\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">+5%</span></p></td><td class=\"cl-02c872e3\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">+20%</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02c872ec\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">Year 2</span></p></td><td class=\"cl-02c872ed\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">-5%</span></p></td><td class=\"cl-02c872f6\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">-20%</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02c872d8\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">Year 3</span></p></td><td class=\"cl-02c872e2\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">+5%</span></p></td><td class=\"cl-02c872e3\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">+20%</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02c872f7\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">Year 4</span></p></td><td class=\"cl-02c87300\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">-5%</span></p></td><td class=\"cl-02c8730a\"><p class=\"cl-02c83962\"><span class=\"cl-02c3a38e\">-20%</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\n\nIs one package better than the other? Did one package perform better than the other?\n\n\n* Package 1:\n    + Return: $1.05 \\times .95 \\times 1.05 \\times .95  = .995$ (0.5% loss)\n    + Year-over-year average: $.995^{1/4}$ = ~0.125% loss per year\n* Package 2:\n    + Return: $1.2 \\times .8 \\times 1.2 \\times .8 = 0.9216$ (7.84% loss)\n    + Year-over-year average: $.9216^{1/4}$ = ~2% loss per year.\n\nPackage 2 performs substantially worse because here, the changes in growth depend on the previous growth rates.\n\n### Harmonic mean{-}\n\nThe harmonic mean is a measure of central tendency that provides us with the average rate and is used when dealing with dynamic processes that involve velocities and distances. The harmonic mean is calculated according to the equation below.\n\n\\begin{equation}\n\\bar{x}_{harmonic} = \n\\frac{n}{\\frac{1}{x_i} + \\frac{1}{x_{i+1}} + \\frac{1}{x_{i+\\dots}} + \\frac{1}{x_n}}\n\\end{equation}\n\nLet's use an example to see what the harmonic mean describes. For example, we make a round trip to work and back. The way to work is 60 kilometers. On the way to work, we can only travel at 30 kmh while we can go 60 kmh on the way back. The distance is the same but, crucially, the time we spend on the road is different for the trip to work (2 hours) compared to the trip back home (1 hour). Half of the results (distance traveled) comes from the first rate (30 kilometers per hour) and the other half from the second rate (60 kilometers per hour). The result is that is takes us 3 hours to get to work and back.\n\n\\begin{equation}\n\\bar{x}_{harmonic} = \n\\frac{2}{\\frac{1}{30} + \\frac{1}{60}} = \\frac{2}{\\frac{2}{60} + \\frac{1}{60}} = \\frac{2}{\\frac{3}{60}} = \\frac{2}{1} \\times \\frac{60}{3} = \\frac{120}{3} = 40\n\\end{equation}\n\nThe reason why using the arithmetic mean is inappropriate in such cases is the following: The idea behind the arithmetic mean is that *we calculate a single value that can replace all values in a given distribution and the sum of the mean values is identical to the sum of the observed values*. \n\nApplied to this example, taking the geometric mean would translate into driving 3 hours with an average speed of 45 kmh which would amount to 135 km (and this is wrong!). Thus, we need to take the speed at which we travel as well as the time with which we travel with a specific speed into account.\n\nSo, the average is a single element that replaces each element. In our example, we have to drive at 40 kilometers per hour (instead of 30) to work and 40 kilometers per hour (instead of 60) to get back from work to get to the same place in the same time. \n\n### Notes on Measures of Centrality{-}\n\nAs suggested above, the mean is strongly affected by outliers (which is why in such cases, the median is the more appropriate measure of central tendency). To illustrate this, imagine you are interested whether the use of discourse particles differs across two corpora. The two corpora represent the speech of the same five speakers but in different situations and the speech thus represents different registers. In a first step, you calculate the relative frequency of discourse particle use and both corpora have a mean of 13.4 particles per 1,000 words. Given the mean, the two corpora do not seem to differ. However, when tabulating and plotting the use of particles by speaker and across these two corpora, it becomes immediately clear that the mean is not the appropriate measure of  central tendency as the distributions are very dissimilar.  \n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-02ef07fe{table-layout:auto;width:50%;}.cl-02e21bac{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-02e21bb6{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-02e6fa46{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02e6fa50{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02e71ad0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71ada{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71adb{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71ae4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71aee{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71aef{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71af8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71af9{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71b02{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71b0c{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71b0d{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02e71b16{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-02ef07fe'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-02e71ad0\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bac\">Corpus</span></p></th><th class=\"cl-02e71ada\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bac\">Speaker</span></p></th><th class=\"cl-02e71adb\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bac\">Frequency</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71ae4\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C1</span></p></td><td class=\"cl-02e71aee\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">A</span></p></td><td class=\"cl-02e71aef\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">11.4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71af8\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C1</span></p></td><td class=\"cl-02e71af9\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">B</span></p></td><td class=\"cl-02e71b02\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">5.2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71ae4\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C1</span></p></td><td class=\"cl-02e71aee\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C</span></p></td><td class=\"cl-02e71aef\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">27.1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71af8\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C1</span></p></td><td class=\"cl-02e71af9\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">D</span></p></td><td class=\"cl-02e71b02\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">9.6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71ae4\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C1</span></p></td><td class=\"cl-02e71aee\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">E</span></p></td><td class=\"cl-02e71aef\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">13.7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71af8\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C2</span></p></td><td class=\"cl-02e71af9\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">A</span></p></td><td class=\"cl-02e71b02\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">0.2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71ae4\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C2</span></p></td><td class=\"cl-02e71aee\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">B</span></p></td><td class=\"cl-02e71aef\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">0.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71af8\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C2</span></p></td><td class=\"cl-02e71af9\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C</span></p></td><td class=\"cl-02e71b02\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">1.1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71ae4\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C2</span></p></td><td class=\"cl-02e71aee\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">D</span></p></td><td class=\"cl-02e71aef\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">65.3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02e71b0c\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">C2</span></p></td><td class=\"cl-02e71b0d\"><p class=\"cl-02e6fa46\"><span class=\"cl-02e21bb6\">E</span></p></td><td class=\"cl-02e71b16\"><p class=\"cl-02e6fa50\"><span class=\"cl-02e21bb6\">0.4</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds20a-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\nThe Figure above shows that the use of discourse particles is distributed rather evenly across speakers in Corpus 1 while the distribution is very uneven in corpus 2. In corpus 2, 4 out of 5 speakers use almost no discourse particles and only one speaker, speaker D, makes excessive use of discourse particles in corpus 2. The high usage frequency of discourse particles by speaker D in corpus 2 causes the mean of corpus 2 to be identical to the mean reported for corpus 1 although the distribution of usage rates differs drastically. This means that reporting the median in addition to the mean can be useful if the distribution of values is very uneven (or non-normal or skewed).\n\nTo exemplify, we will summarize the distribution of discourse particles in the two corpora: the use of discourse particles in corpus 1 (mean = 13.4, median = 11.4) is substantially different from the use of discourse particles in corpus 2 (mean = 13.4, median = 0.4).\n\n\n## Measures of Variability\n\n::: {.callout-note}\n## Key concept: Standard deviation vs. standard error\n\nThe *standard deviation* (SD) describes how much individual data points vary around the mean - it is a property of the *data*. The *standard error* (SE) describes how much the *sample mean* would vary if we repeated the study many times - it is a measure of the *precision of an estimate* and shrinks as the sample grows (SE = SD/√n). Confusing the two is a classic error: error bars showing SE look much tighter than error bars showing SD, so always state which one you report.\n:::\n\n\nMeasures of variability provide information about the distribution of values such as whether the data are distributed evenly and do not differ substantially or whether the data are rather heterogeneous and are distributed very unevenly [@thompson2009descriptive]. In the following, we will have a look at the *variance* and the *standard deviation*. \n\nAs before, we will use a practical example to see the usefulness of applying measures of variability. Imagine you dealing with two cities, let's say Moscow and Hamburg, that have the same mean temperature per year. However, the variability of temperatures varies differs dramatically between the Moscow and Hamburg.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-0375dcb6{table-layout:auto;width:75%;}.cl-036ad7c6{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-036ad7d0{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-036e842a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-036e8434{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-036ead74{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036ead7e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036ead88{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036ead92{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036ead93{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036ead9c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eada6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eada7{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eada8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eadb0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eadb1{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-036eadba{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0375dcb6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-036ead74\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7c6\">Month</span></p></th><th class=\"cl-036ead7e\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7c6\">Moscow</span></p></th><th class=\"cl-036ead88\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7c6\">Hamburg</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">January</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">-5.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">7.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">February</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">-12.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">7.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">March</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">5.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">8.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">April</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">12.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">9.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">May</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">15.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">10.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">June</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">18.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">13.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">July</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">22.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">15.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">August</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">23.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">15.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">September</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">20.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">13.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">October</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">16.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">11.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036ead92\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">November</span></p></td><td class=\"cl-036ead93\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">8.00</span></p></td><td class=\"cl-036ead9c\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">8.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eada6\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">December</span></p></td><td class=\"cl-036eada7\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">1.00</span></p></td><td class=\"cl-036eada8\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">7.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-036eadb0\"><p class=\"cl-036e842a\"><span class=\"cl-036ad7d0\">Mean</span></p></td><td class=\"cl-036eadb1\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">10.25</span></p></td><td class=\"cl-036eadba\"><p class=\"cl-036e8434\"><span class=\"cl-036ad7d0\">10.25</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-week6_files/figure-html/ds22-1.png){width=672}\n:::\n:::\n\n\n\n\n\nIn the following, we will discuss and calculate different measures of variability for the two cities.\n\n### Range{-}\n\nThe range is the simplest measure of variability and reports the lowest and highest value of a distribution. That is, the range provides minimum and maximum of a vector to show the span of values within a distribution.\n\nIn R, the *range* is extracted as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a numeric vector\nMoscow <- c(-5, -12, 5, 12, 15, 18, 22, 23, 20, 16, 8, 1)\nmin(Moscow); max(Moscow) # extract range\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -12\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23\n```\n\n\n:::\n:::\n\n\n\n\nThe lowest temperature value for Moscow is -12 degrees Celsius and the highest value is 23 degrees Celsius. The range thus spans from -12 to 23. \n\n### Interquartile range (IQR){-}\n\nThe interquartile range (IQR) denotes the range that encompasses the central 50 percent of data points and thus  informs about how values are distributed. This means that the IQR spans from the first quartile that encompasses 25 percent of the data to the third quartile that encompasses 75 percent of the data. \n\nThe easiest way to extract the IQR in R is to apply the `summary` function to a vector as shown below and then subtract the value of the  1^st^ quartile from the value of the 3^rd^ quartile.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Moscow) # extract IQR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n -12.00    4.00   13.50   10.25   18.50   23.00 \n```\n\n\n:::\n:::\n\n\n\n\nThe `summary` function reports that the minimum temperature is -12 degrees Celsius and that the maximum temperature is 23 degrees Celsius. Also, the lower 25 percent of the data fall within -12 and 4 degrees Celsius (from the minimum value to the 1^st^ quartile) and the upper 25 percent fall within 18.5 and 23 degrees Celsius (from the 3^rd^ quartile to the maximum value). The IQR range represents a range that encompasses the central 50% of the data and thus represents the value that can be calculated by subtracting the value of the 1^st^ from the value of the 3^rd^ quartile..\n\nThus, the IQR is 18.5 - 4 = 14.5 \n\n.\n\n### Variance{-}\n\nThe variance is calculated according to the formula below. To calculate the variance, each value is subtracted from the mean and the result is squared. The squared values are then added and the resulting sum is divided by the number of values minus 1.\n\n\n$s = \\sigma^2 = \\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^{2}$\n\n\nFor our example, the variance of temperatures for Moscow is 123.6591 and 9.477273 for Hamburg.\n\nIn R, the *variance* is calculated as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(Moscow)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 123.6591\n```\n\n\n:::\n:::\n\n\n\n\n\n### Standard deviation{-}\n\nThe standard deviation (abbreviated with capital $sigma$ $\\sigma$) is calculated according to first equation shown below or, alternatively, according to second equation shown below and it is the square root of the squared variance.\n\n$\\sigma = \\sqrt{s} = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^2}$\n\n$\\sigma = \\sqrt{\\frac{ \\sum_{i=1}^{n} (x_i - \\bar{x})^2}{n-1}}$\n\nFor our example, the first equation shown above provides a standard deviation of 11.12 for Moscow and a standard deviation of 3.08 for Hamburg.\n\nIn R, the *standard deviation* is calculated as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate standard deviation\nsd(Moscow) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.12021\n```\n\n\n:::\n:::\n\n\n\n\nThe standard deviation of temperature values of Moscow is 11.12.\n\n\n\n### Standard Error{-}\n\nThe standard error is a measure of variability and it reports the average distance from some parameters (most often from the mean). It is calculated as the standard deviation of the residuals of the parameter in question. To exemplify the standard error, we will have a look at reaction times which show how fast participants realized that a sequence of letters were either existing words or just a sequence of letters. \n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-04370b5c{table-layout:auto;width:75%;}.cl-042919e8{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-042919f2{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-042f00ce{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-042f00e2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-042f40ac{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40b6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40ca{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40cb{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40d4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40d5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40de{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40df{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40e8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40f2{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40f3{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-042f40fc{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-04370b5c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-042f40ac\"><p class=\"cl-042f00ce\"><span class=\"cl-042919e8\">RT</span></p></th><th class=\"cl-042f40b6\"><p class=\"cl-042f00e2\"><span class=\"cl-042919e8\">State</span></p></th><th class=\"cl-042f40ca\"><p class=\"cl-042f00e2\"><span class=\"cl-042919e8\">Gender</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">429.276</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">435.473</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">394.535</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">377.325</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">430.294</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">289.102</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">411.505</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">366.191</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">365.792</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">334.034</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Sober</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">444.188</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">540.866</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">468.531</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">476.011</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">412.473</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Male</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">520.845</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">435.682</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40de\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">463.421</span></p></td><td class=\"cl-042f40df\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40e8\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40cb\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">536.036</span></p></td><td class=\"cl-042f40d4\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40d5\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-042f40f2\"><p class=\"cl-042f00ce\"><span class=\"cl-042919f2\">494.936</span></p></td><td class=\"cl-042f40f3\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Drunk</span></p></td><td class=\"cl-042f40fc\"><p class=\"cl-042f00e2\"><span class=\"cl-042919f2\">Female</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nThe standard error of the mean is calculated using the equation below.\n\n\\begin{equation}\n\\sigma~{\\bar{x}}~ =\\frac{\\sigma}{\\sqrt{n}} \n\\end{equation}\n\nThe standard error can be calculated manually (see below) by implementing the equation from above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(rts$RT, na.rm=TRUE) /  \n   sqrt(length(rts$RT[!is.na(rts$RT)]))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.76925\n```\n\n\n:::\n:::\n\n\n\n\nAn easier way to extract standard errors is to use the `describe` function from the `psych` package (see below)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# describe data\npsych::describe(rts$RT, type=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   vars  n   mean    sd median trimmed  mad   min    max  range skew kurtosis\nX1    1 20 431.33 66.05 432.88   432.9 60.4 289.1 540.87 251.76 -0.2    -0.13\n      se\nX1 14.77\n```\n\n\n:::\n:::\n\n\n\n\n## Confidence Intervals\n\nConfidence intervals provide an estimation of in-between which values the reported value would lie in the population with a confidence of, e.g., 95 percent. \n\n\\begin{equation}\n  \\bar{x} \\mp z \\frac{s}{\\sqrt{n}}\n\\end{equation}\n\nThe z-value for 95% probability (a two-tailed) of a normal distribution is 1.96. To check this, we can use the `qnorm` function and extract the z-value for a probability of .975 - we do not use .95 because we want 2.5% of the lower tail (-1.96) and 2.5% of the higher tail (1.96). \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.975)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\n\nThis means that for a 95% confidence interval for normally distributed data, we can use the formula shown below.\n\n\\begin{equation}\n  \\bar{x} \\mp 1.96 \\frac{s}{\\sqrt{n}}\n\\end{equation}\n\nIf we have a vector of values (e.g., 4,5,2,3,1,4,3,6,3,2,4,1), we can easily calculate the confidence intervals for the mean as follows.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate mean\nm <- mean(c(4,5,2,3,1,4,3,6,3,2,4,1))\n# calculate standard deviation\ns <- sd(c(4,5,2,3,1,4,3,6,3,2,4,1))\n# calculate n\nn <- length(c(4,5,2,3,1,4,3,6,3,2,4,1))\n# calculate lower and upper ci\nlower <- m-1.96*(s/sqrt(n))\nupper <- m+1.96*(s/sqrt(n))\n# show lower ci, mean, and upper ci\nlower; m; upper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.302388\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.166667\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.030945\n```\n\n\n:::\n:::\n\n\n\n\n\nThere are several functions in R to extract confidence intervals. To show how you can do this for different types of elements, we will continue to work with the reaction times data.\n\n\n\n### Confidence Intervals for Simple Vectors{-}\n\nConfidence intervals (CIs) give a range that's likely to include a population value with a certain degree of confidence. As such, CIs tell us how likely it is to get a value within a certain range if we drew another sample from the same population. \n\nOne easy method for extracting confidence intervals is to apply the `CI` function from the `Rmisc` package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract mean and confidence intervals\nRmisc::CI(rts$RT, ci=0.95)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   upper     mean    lower \n462.2382 431.3258 400.4134 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\nThe `CI` function provides the mean reaction time (431.3258) and the 95 percent confidence band. With 95 percent confidence, the mean reaction time will have a mean between 400.41  and 462.24 milliseconds (ms).\n\n\nAnother alternative to extract the man ans the confidence interval from a range of values is to use the `MeanCI` function from the `DescTools` package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract mean and confidence intervals\nDescTools::MeanCI(rts$RT, conf.level=0.95)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean   lwr.ci   upr.ci \n431.3258 400.4134 462.2382 \n```\n\n\n:::\n:::\n\n\n\n\n This method is particularly interesting because it uses bootstrapping or resampling the data. As such, it is an empirical method to extract the mean and the confidence intervals. The values will differ given how many samples are drawn and we can get very precise estimates using this method.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract mean CIs\nDescTools::MeanCI(rts$RT, method=\"boot\", type=\"norm\", R=1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean   lwr.ci   upr.ci \n431.3258 402.0659 459.5996 \n```\n\n\n:::\n:::\n\n\n\n\nBecause this is a data-driven approach, the results will vary, depending on the characteristics of the resampled data. To illustrate, compare the values provided above to the values generated below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract mean CIs\nDescTools::MeanCI(rts$RT, method=\"boot\", type=\"norm\", R=1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean   lwr.ci   upr.ci \n431.3258 403.2725 458.8470 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::: {.callout-tip}\n## Exercises: The Mean\n:::\n\n**Q1. What is the arithmetic mean of: 1, 2, 3, 4, 5, 6?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_M_Q1\" onsubmit=\"return validate_form_M_Q1()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_M_Q1\" id=\"answer_M_Q1_1\" value=\"3.5\"/>\n3.5\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q1\" id=\"answer_M_Q1_2\" value=\"3\"/>\n3\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q1\" id=\"answer_M_Q1_3\" value=\"4\"/>\n4\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q1\" id=\"answer_M_Q1_4\" value=\"21\"/>\n21\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_M_Q1\"></div>\n</form>\n<script>function validate_form_M_Q1() {var x, text; var x = document.forms['form_M_Q1']['answer_M_Q1'].value;if (x == '3.5'){text = 'Correct! (1+2+3+4+5+6)/6 = 21/6 = 3.5. In R: mean(c(1,2,3,4,5,6))';} else {text = 'Sum all values and divide by the count. (1+2+3+4+5+6)/6 = ?';} document.getElementById('result_M_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_M_Q1').innerText == 'Correct! (1+2+3+4+5+6)/6 = 21/6 = 3.5. In R: mean(c(1,2,3,4,5,6))';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q2. Which R function calculates the arithmetic mean of a numeric vector?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_M_Q2\" onsubmit=\"return validate_form_M_Q2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_M_Q2\" id=\"answer_M_Q2_1\" value=\"mean()\"/>\nmean()\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q2\" id=\"answer_M_Q2_2\" value=\"median()\"/>\nmedian()\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q2\" id=\"answer_M_Q2_3\" value=\"average()\"/>\naverage()\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q2\" id=\"answer_M_Q2_4\" value=\"sum()/n()\"/>\nsum()/n()\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_M_Q2\"></div>\n</form>\n<script>function validate_form_M_Q2() {var x, text; var x = document.forms['form_M_Q2']['answer_M_Q2'].value;if (x == 'mean()'){text = 'Correct! mean() is the base R function for the arithmetic mean. Example: mean(c(4,3,6,2,1,5,6,8)) returns 4.375.';} else {text = 'R has a dedicated base function for the mean. It shares its name with the statistical concept.';} document.getElementById('result_M_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_M_Q1').innerText == 'Correct! (1+2+3+4+5+6)/6 = 21/6 = 3.5. In R: mean(c(1,2,3,4,5,6))'; res2 = document.getElementById('result_M_Q2').innerText == 'Correct! mean() is the base R function for the arithmetic mean. Example: mean(c(4,3,6,2,1,5,6,8)) returns 4.375.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q3. A corpus contains five texts with the following word counts: 200, 250, 210, 180, and 1500. Why might the mean NOT be the best summary of typical text length here?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_M_Q3\" onsubmit=\"return validate_form_M_Q3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_M_Q3\" id=\"answer_M_Q3_1\" value=\"There are too few texts to calculate a mean\"/>\nThere are too few texts to calculate a mean\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q3\" id=\"answer_M_Q3_2\" value=\"The mean requires equal word counts across texts\"/>\nThe mean requires equal word counts across texts\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q3\" id=\"answer_M_Q3_3\" value=\"The value 1500 is an outlier that inflates the mean far above the length of the other four texts\"/>\nThe value 1500 is an outlier that inflates the mean far above the length of the other four texts\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_M_Q3\" id=\"answer_M_Q3_4\" value=\"The mean is only valid for ordinal data\"/>\nThe mean is only valid for ordinal data\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_M_Q3\"></div>\n</form>\n<script>function validate_form_M_Q3() {var x, text; var x = document.forms['form_M_Q3']['answer_M_Q3'].value;if (x == 'The value 1500 is an outlier that inflates the mean far above the length of the other four texts'){text = 'Correct! The mean of these five values is (200+250+210+180+1500)/5 = 468 - far above the four ‘typical’ texts (180-250 words). The outlier at 1500 pulls the mean upward so it no longer represents the typical text. The median (210) is more representative here.';} else {text = 'Calculate the mean: (200+250+210+180+1500)/5 = 468. Does 468 represent a ‘typical’ text in this set?';} document.getElementById('result_M_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_M_Q1').innerText == 'Correct! (1+2+3+4+5+6)/6 = 21/6 = 3.5. In R: mean(c(1,2,3,4,5,6))'; res2 = document.getElementById('result_M_Q2').innerText == 'Correct! mean() is the base R function for the arithmetic mean. Example: mean(c(4,3,6,2,1,5,6,8)) returns 4.375.'; res3 = document.getElementById('result_M_Q3').innerText == 'Correct! The mean of these five values is (200+250+210+180+1500)/5 = 468 - far above the four ‘typical’ texts (180-250 words). The outlier at 1500 pulls the mean upward so it no longer represents the typical text. The median (210) is more representative here.';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n\n[Back to top](#week6)\n\n\n",
    "supporting": [
      "06-week6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}