{
  "hash": "d2186a4096c3f1f1b80963206ec70152",
  "result": {
    "engine": "knitr",
    "markdown": "# Multiple Linear Regression {#week10}\n\n::: {.callout-tip}\n## What This Session Covers\n\nThis session extends linear regression to multiple predictors - including interactions between them.\n\n1. **The basic principle** - modeling an outcome as a function of several predictors simultaneously\n2. **Interactions** - when the effect of one predictor depends on another\n3. **Model fitting** - finding a minimal adequate model via model comparison (AIC)\n4. **Model diagnostics** - `check_model()`, collinearity (VIFs), and influential observations\n5. **Sample size considerations**, effect visualization, and reporting standards\n:::\n\nThis tutorial introduces regression analysis (also called regression modeling). Regression models are among the most widely used quantitative methods in the language sciences to assess if and how predictors (variables or interactions between variables) correlate with a certain response. \n\nRegression models are so popular because they can\n\n* incorporate many predictors in a single model (multivariate: allows to test the impact of one predictor while the impact of (all) other predictors is controlled for)\n\n* extremely flexible and and can be fitted to different types of predictors and dependent variables\n\n* provide output that can be easily interpreted\n\n* conceptually relative simple and not overly complex from a  mathematical perspective\n\n\nThe major difference between these types of models is that they take different types of dependent variables: linear regressions take numeric, logistic regressions take nominal variables, ordinal regressions take ordinal variables, and Poisson regressions take dependent variables that reflect counts of (rare) events. \n\n## The Basic Principle\n\nIn contrast to simple linear regression, which estimates the effect of a single predictor, multiple linear regression estimates the effect of various predictors simultaneously (see the equation below).\n\n\\begin{equation}\n\nf_{(x)} = \\alpha + \\beta_{1}x_{i} + \\beta_{2}x_{i+1} + \\dots + \\beta_{n}x_{i+n} + \\epsilon\n\n\\end{equation}\n\nThe model diagnostics we are dealing with here are partly identical to the diagnostic methods for simple linear regression. Because of this overlap, diagnostics will only be described in more detail if they have not been described in the section on simple linear regression.\n\n## Example: Gifts and Availability\n\n::: {.callout-note}\n## Key concept: What is an interaction?\n\nAn *interaction* means that the effect of one predictor on the outcome *depends on the value of another predictor*. Example: attraction may increase with the money spent on gifts - but only for emotionally available partners; for unavailable partners, spending has no effect. Neither predictor alone captures this: the effect of *money* differs across levels of *availability*. In R, interactions are specified with `*` (e.g. `attraction ~ money * status` estimates both main effects *and* their interaction). When an interaction is significant, the main effects involved in it can no longer be interpreted in isolation.\n:::\n\n\nThe example we will go through here is taken from @field2012discovering. In this example, the research question is if the money that men spend on presents for women depends on the women's attractiveness and their relationship status. To answer this research question, we will implement a multiple linear regression and start by loading the data and inspect its structure and properties.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nmlrdata  <- base::readRDS(url(\"https://slcladal.github.io/data/mld.rda\", \"rb\"))\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-3b0785c0{table-layout:auto;width:75%;}.cl-3af8d0de{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3af8d106{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3afef4b4{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3afef4be{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3aff44f0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4504{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4505{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff450e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4518{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4519{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4522{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4523{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff452c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff452d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4536{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3aff4537{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-3b0785c0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-3aff44f0\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d0de\">status</span></p></th><th class=\"cl-3aff4504\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d0de\">attraction</span></p></th><th class=\"cl-3aff4505\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d0de\">money</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">86.33</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">45.58</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">68.43</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">52.93</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">61.86</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">48.47</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">32.79</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">35.91</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">30.98</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">44.82</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">35.05</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">64.49</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff450e\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4518\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4519\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">54.50</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff4522\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4523\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff452c\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">61.48</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-3aff452d\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">Relationship</span></p></td><td class=\"cl-3aff4536\"><p class=\"cl-3afef4b4\"><span class=\"cl-3af8d106\">NotInterested</span></p></td><td class=\"cl-3aff4537\"><p class=\"cl-3afef4be\"><span class=\"cl-3af8d106\">55.51</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nThe data set consist of three variables stored in three columns. The first column contains the relationship status of the present receiver (in this study, this were women), the second whether the present givers (in this study this were men) are interested in the  present receiver, and the third column represents the money spend on the present. The data set represents 100 cases and the mean amount of money spend on a present is 88.38 dollars. In a next step, we visualize the data to get a more detailed impression of the relationships between variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create plots\np1 <- ggplot(mlrdata, aes(status, money)) +   \n  geom_boxplot() + \n  theme_bw()\n# plot 2\np2 <- ggplot(mlrdata, aes(attraction, money)) +\n  geom_boxplot() +\n  theme_bw()\n# plot 3\np3 <- ggplot(mlrdata, aes(x = money)) +\n  geom_histogram(aes(y=..density..)) +           \n  theme_bw() +                               \n  geom_density()\n# plot 4\np4 <- ggplot(mlrdata, aes(status, money)) +\n  geom_boxplot(aes(fill = factor(status))) + \n  facet_wrap(~ attraction) +       \n  guides(fill = FALSE) +\n  theme_bw()\n# show plots\ngridExtra::grid.arrange(grobs = list(p1, p2, p3, p4), widths = c(1, 1), layout_matrix = rbind(c(1, 2), c(3, 4)))\n```\n\n::: {.cell-output-display}\n![](10-week10_files/figure-html/mlr3-1.png){width=672}\n:::\n:::\n\n\n\n\nThe upper left figure consists of a boxplot which shows how much money was spent by relationship status. The figure suggests that men spend more on women if they are not in a relationship. The next figure shows the relationship between the money spend on presents and whether or not the men were interested in the women.\n\nThe boxplot in the upper right panel suggests that men spend substantially more on women if the men are interested in them. The next figure depicts the distribution of the amounts of money spend on the presents for the women. In addition, the figure indicates the existence of two outliers (dots in the boxplot)\n\nThe histogram in the lower left panel shows that, although the mean amount of money spent on presents is 88.38 dollars, the distribution peaks around 50 dollars indicating that on average, men spend about 50 dollars on presents. Finally, we will plot the amount of money spend on presents against relationship status by attraction in order to check whether the money spent on presents is affected by an interaction between attraction and relationship status.\n\nThe boxplot in the lower right panel confirms the existence of an interaction (a non-additive term) as men only spend more money on  women if the men single *and* they are interested in the women. If men are not interested in the women, then the relationship has no effect as they spend an equal amount of money on the women regardless of whether they are in a relationship or not.\n\nWe will now start to implement the regression model. In a first step, we create a saturated model that contain all possible predictors (main effects and interactions). \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1.mlr = lm(                      # generate lm regression object\n  money ~ attraction*status,      # def. regression formula\n  data = mlrdata)                 # def. data\n```\n:::\n\n\n\n\nAfter generating the saturated models we can now start with the model fitting. Model fitting refers to a process that aims at find the model that explains a maximum of variance with a minimum of predictors [see @field2012discovering 318]. Model fitting is therefore based on the *principle of parsimony* which is related to Occam's razor according to which explanations that require fewer assumptions are more likely to be true.\n\n## Model Fitting\n\nModel fitting means that we check what of the predictors should be included in the model and what predictors do not have any impact on the outcome and thus should not be part of the model (because they merely add noise to the data.\n\nIn this example, we use the `glmulti` function to find the model with the lowest AIC (*Akaike Information Criterion*) as the criterion to find the model with the best fit: the lower the AIC value, the better the balance between explained variance and the number of predictors. AIC values can and should only be compared for models that are fit on the same data set with the same (number of) cases (*LL* stands for *logged likelihood* or *LogLikelihood* and *k* represents the number of predictors in the model (including the intercept); the LL represents a measure of how good the model fits the data).\n\n\\begin{equation}\nAkaike Information Criterion (AIC) = -2LL + 2k\n\\end{equation}\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(glmulti)\nmfit <- glmulti(money ~ attraction + status, data = mlrdata, crit = aic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialization...\nTASK: Exhaustive screening of candidate set.\nFitting...\nCompleted.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$name\n[1] \"glmulti.analysis\"\n\n$method\n[1] \"h\"\n\n$fitting\n[1] \"glm\"\n\n$crit\n[1] \"aic\"\n\n$level\n[1] 2\n\n$marginality\n[1] FALSE\n\n$confsetsize\n[1] 100\n\n$bestic\n[1] 878.3089\n\n$icvalues\n[1]  878.3089  878.3089  878.3089  878.3089  930.6519  953.8269 1057.8180\n[8] 1063.3911\n\n$bestmodel\n[1] \"money ~ 1 + status:attraction\"\n\n$modelweights\n[1] 2.500000e-01 2.500000e-01 2.500000e-01 2.500000e-01 1.075929e-12\n[6] 9.986248e-18 2.618317e-40 1.613778e-41\n\n$includeobjects\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n\nThe `glmulti` function reports `money ~ 1 + status:attraction` as the best model. However, if a variable is part of a significant interaction, we also need to include the main effect which means that our best model is `money ~ 1 + status + attraction + status:attraction`, or, simplified: `money ~ status * attraction` (which is the same as the previous formula). The saturated model is thus also the final minimal adequate model, i.e. the model with the best fit and the lowest number of predictors. We will now inspect the final minimal model and go over the model report.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2.mlr = lm(                    # generate lm regression object\n  money ~ status * attraction,  # def. regression formula, x1 * x2 = x1 + x2 + x1:x2\n  data = mlrdata)               # def. data\n# inspect final minimal model\nsummary(m2.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = money ~ status * attraction, data = mlrdata)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-45.08 -14.26   0.46  11.93  44.14 \n\nCoefficients:\n                                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                            99.155      3.795  26.131  < 2e-16 ***\nstatusSingle                           57.693      5.366  10.751  < 2e-16 ***\nattractionNotInterested               -47.663      5.366  -8.882 3.75e-14 ***\nstatusSingle:attractionNotInterested  -63.179      7.589  -8.325 5.81e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.97 on 96 degrees of freedom\nMultiple R-squared:  0.852,\tAdjusted R-squared:  0.8474 \nF-statistic: 184.3 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe first element of the report is called *Call* and it reports the regression formula of the model. Then, the report provides the residual distribution (the range, median and quartiles of the residuals) which allows drawing inferences about the distribution of differences between observed and expected values. If the residuals are distributed non-normally, then this is a strong indicator that the model is unstable and unreliable because mathematical assumptions on which the model is based are violated.\n\nNext, the model summary reports the most important part: a table with model statistics of the fixed-effects structure of the model. The table contains the estimates (coefficients of the predictors), standard errors, t-values, and the p-values which show whether a predictor significantly correlates with the dependent variable that the model investigates.\n\nAll main effects (status and attraction) as well as the interaction between status and attraction is reported as being significantly correlated with the dependent variable (money). An interaction occurs if a correlation between the dependent variable and a predictor is affected by another predictor.\n\nThe top most term is called intercept and has a value of 99.15 which represents the base estimate to which all other estimates refer. To exemplify what this means, let us consider what the model would predict a man would spend on a present if he is interested in a woman but she is in a relationship. The amount he would spend (based on the model would be 99.15 dollars (which is the intercept). This means that the intercept represents the predicted value if all predictors take the base or reference level. And since being in relationship but being interested are the case, and because the interaction does not apply, the predicted value in our example is exactly the intercept (see below). \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#intercept  Single  NotInterested  Single:NotInterested\n99.15     + 57.69  + 0           + 0     # 156.8 single + interested\n99.15     + 57.69  - 47.66       - 63.18 # 46.00 single + not interested\n99.15     - 0      + 0           - 0     # 99.15 relationship + interested\n99.15     - 0      - 47.66       - 0     # 51.49 relationship + not interested\n```\n:::\n\n\n\n\nNow, let us consider what a man would spend if she is in a relationship and he is not attracted to the women. In that case, the model predicts that the man would spend only  51.49 dollars on a present: the intercept (99.15) minus 47.66 because the man is not interested (and no additional subtraction because the interaction does not apply). \n\nWe can derive the same results easier using the `predict` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make prediction based on the model for original data\nprediction <- predict(m2.mlr, newdata = mlrdata)\n# inspect predictions\ntable(round(prediction,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 46.01  51.49  99.15 156.85 \n    25     25     25     25 \n```\n\n\n:::\n:::\n\n\n\n\nBelow the table of coefficients, the regression summary reports model statistics that provide information about how well the model performs. The difference between the values and the values in the coefficients table is that the model statistics refer to the model as a whole rather than focusing on individual predictors.\n\nThe multiple R^2^-value is a measure of how much variance the model explains. A multiple R^2^-value of 0 would inform us that the model does not explain any variance while a value of .852 mean that the model explains 85.2 percent of the variance. A value of 1 would inform us that the model explains 100 percent of the variance and that the predictions of the model match the observed values perfectly. Multiplying the multiple R^2^-value thus provides the percentage of explained variance. \n\nThe adjusted R^2^-value considers the amount of explained variance in light of the number of predictors in the model (it is thus somewhat similar to the AIC and BIC) and informs about how well the model would perform if it were applied to the population that the sample is drawn from. Ideally, the difference between multiple and adjusted R^2^-value should be very small as this means that the model is not overfitted. If, however, the difference between multiple and adjusted R^2^-value is substantial, then this would strongly suggest that the model is unstable and overfitted to the data while being inadequate for drawing inferences about the population. Differences between multiple and adjusted R^2^-values indicate that the data contains outliers that cause the distribution of the data on which the model is based to differ from the distributions that the model mathematically requires to provide reliable estimates. The difference between multiple and adjusted R^2^-value in our model is very small (85.2-84.7=.05) and should not cause concern.\n\nNow, we compare the final minimal adequate model to the base-line model to test whether then final model significantly outperforms the baseline model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compare baseline- and minimal adequate model\nm0.mlr <- lm(money ~ 1, data = mlrdata)\nanova(m0.mlr, m2.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: money ~ 1\nModel 2: money ~ status * attraction\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1     99 233562                                  \n2     96  34558  3    199005 184.28 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe comparison between the two models confirms that the minimal adequate model performs significantly better (makes significantly more accurate estimates of the outcome variable) compared with the baseline model.\n\n## Model Diagnostics \n\n::: {.callout-note}\n## Key concept: What is (multi)collinearity?\n\n*Collinearity* arises when predictors are correlated with each other - when one predictor can be (partly) predicted from the others. The model then cannot cleanly separate their individual contributions: coefficient estimates become unstable, standard errors inflate, and interpretation becomes unreliable, even though the model's overall predictions may be fine. Collinearity is quantified by *variance inflation factors* (VIFs): values above 10 (conservatively: above 5) signal a problem. Remedies include removing or combining correlated predictors. Note: elevated VIFs for terms involved in an interaction are expected and unproblematic.\n:::\n\n\nAfter implementing the multiple regression, we now need to check the model assumptions and look for influential observations, i.e. data points whose removal would disproportionately change the model fit. As in the section on simple linear regression, we use the `check_model` function from the `performance` package [@performance] to generate the diagnostic plots (have a look at the explanations of what to look for and how to interpret these diagnostic plots in the section on simple linear regression).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate diagnostic plots\nperformance::check_model(m2.mlr)\n```\n\n::: {.cell-output-display}\n![](10-week10_files/figure-html/mlr11-1.png){width=672}\n:::\n:::\n\n\n\n\nBecause we are now dealing with more than one predictor, the panel includes an additional plot: the *Collinearity* panel. This panel shows the variance inflation factor (VIF) for each model term, which quantifies how strongly a predictor can be predicted from the other predictors in the model. High collinearity (VIFs above 10; some scholars use the more conservative threshold of 5) is problematic because it renders the coefficient estimates unstable and their interpretation unreliable. We can also extract the VIFs directly, as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check collinearity\nperformance::check_collinearity(m2.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n              Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n            status 2.00 [1.58, 2.73]     1.41      0.50     [0.37, 0.63]\n        attraction 2.00 [1.58, 2.73]     1.41      0.50     [0.37, 0.63]\n status:attraction 3.00 [2.26, 4.16]     1.73      0.33     [0.24, 0.44]\n```\n\n\n:::\n:::\n\n\n\n\n*A note on VIFs in models with interactions:* elevated VIFs of terms involved in an interaction are expected (a predictor and an interaction containing that predictor are necessarily correlated) and are not by themselves a cause for concern.\n\nThe plots do not show severe problems such as funnel-shaped patterns in the homogeneity-of-variance panel or drastic deviations from the reference line in the normality panel. To make sure that no data points over-proportionately impact the model fit, we formally check for influential observations based on Cook's distance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check for influential observations\nperformance::check_outliers(m2.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: No outliers detected.\n- Based on the following method and threshold: cook (0.5).\n- For variable: (Whole model)\n```\n\n\n:::\n:::\n\n\n\n\nThe diagnostics indicate that no data points overly affect the results (no observation exceeds the Cook's distance threshold) and we can thus proceed with the interpretation of the model.\n\n\n## A Word about Sample Size\n\nOne common issue when doing null-hypothesis significance testing is sample size (which is related to the probability of $\\beta$-errors). Remember, $\\beta$-errors (or beta errors) mean overlooking a significant effect typically because the sample size is too low.  The probability of a $\\beta$-error ranges between 0 and 1, where lower values are better.\n\nDespite there being no ultimate rule of thumb, @field2012discovering[273-275], based on @green1991many, provide data-driven suggestions for the minimal size of data required for regression models that aim to find medium sized effects (k = number of predictors; categorical variables with more than two levels should be transformed into dummy variables):\n\n>  If one is only interested in the effect of specific variables, then the sample size should be at least 104 + k (k = number of predictors in model).\n\n\n## Visualizing effects\n\nNow, we visualize the effects of the predictors reported as being significant.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tabulate model results\nsjPlot::plot_model(m2.mlr, type = \"pred\", terms = c(\"status\", \"attraction\"))\n```\n\n::: {.cell-output-display}\n![](10-week10_files/figure-html/mlr25a-1.png){width=672}\n:::\n:::\n\n\n\n\n## Reporting Results\n\nAs a last step, we summarize the results of the regression analysis.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tabulate model results\nsjPlot::tab_model(m2.mlr)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">money</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">99.15</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">91.62&nbsp;&ndash;&nbsp;106.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">status [Single]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">57.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">47.04&nbsp;&ndash;&nbsp;68.34</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">attraction<br>[NotInterested]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;47.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;58.31&nbsp;&ndash;&nbsp;-37.01</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">status [Single] ×<br>attraction<br>[NotInterested]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;63.18</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;78.24&nbsp;&ndash;&nbsp;-48.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">100</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.852 / 0.847</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\nAdditionally, we can inspect the summary of the regression model as shown below to extract additional information. We can use the `reports` package [@report] to summarize the analysis.\n\nAlthough @field2012discovering suggest that the main effects of the predictors involved in the interaction should not be interpreted, they are interpreted here to illustrate how the results of a multiple linear regression can be reported. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(m2.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear model (estimated using OLS) to predict money with status and\nattraction (formula: money ~ status * attraction). The model explains a\nstatistically significant and substantial proportion of variance (R2 = 0.85,\nF(3, 96) = 184.28, p < .001, adj. R2 = 0.85). The model's intercept,\ncorresponding to status = Relationship and attraction = Interested, is at 99.15\n(95% CI [91.62, 106.69], t(96) = 26.13, p < .001). Within this model:\n\n  - The effect of status [Single] is statistically significant and positive (beta\n= 57.69, 95% CI [47.04, 68.34], t(96) = 10.75, p < .001; Std. beta = 1.19, 95%\nCI [0.97, 1.41])\n  - The effect of attraction [NotInterested] is statistically significant and\nnegative (beta = -47.66, 95% CI [-58.31, -37.01], t(96) = -8.88, p < .001; Std.\nbeta = -0.98, 95% CI [-1.20, -0.76])\n  - The effect of status [Single] × attraction [NotInterested] is statistically\nsignificant and negative (beta = -63.18, 95% CI [-78.24, -48.11], t(96) =\n-8.32, p < .001; Std. beta = -1.30, 95% CI [-1.61, -0.99])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\n\n\n\nWe can use the output of the `report` function to write up a final report: \n\n\n> A multiple linear regression was fitted to the data using an automated AIC-based (Akaike's Information Criterion) procedure. The model fitting arrived at a final minimal model. \n>\n> The model explains a statistically significant and substantial proportion of variance (R2 = 0.85, F(3, 96) = 184.28, p < .001, adj. R^2^ = 0.85). The model's intercept, corresponding to status = Relationship, is at 99.15 ([91.62, 106.69], t(96) = 26.13, p < .001). \n>\n> The effect of status [Single] is statistically significant and positive (beta = 57.69 [47.04, 68.34], t(96) = 10.75, p < .001; Std. beta = 1.19 [0.97, 1.41]) which means that men spend 57.69 AUD more on gifts for women, if the women are not in a relationship.\n> \n> The effect of attraction [NotInterested] is statistically significant and negative (beta =\n-47.66 [-58.31, -37.01], t(96) = -8.88, p < .001; Std. beta = -0.98 [-1.20,\n-0.76]) which means that men spend 47.66 AUD less on gifts for women if the men are not interested in the women.\n> \n> The interaction effect of attraction [NotInterested] on status [Single] is statistically\nsignificant and negative (beta = -63.18 [-78.24, -48.11], t(96) = -8.32, p < .001;\nStd. beta = -1.30 [-1.61, -0.99]) which means that if men are not interested in the women and the women are single, men spend 63.18 AUD less on presents.\n\n\n::: {.callout-tip}\n## Exercises: Multiple Linear Regression\n:::\n\n**Q1. A model of L2 fluency finds an interaction between practice time and anxiety: practice improves fluency for low-anxiety learners but not for high-anxiety learners. What does this interaction mean for interpretation?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W10_Q1\" onsubmit=\"return validate_form_W10_Q1()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W10_Q1\" id=\"answer_W10_Q1_1\" value=\"Anxiety and practice are the same variable\"/>\nAnxiety and practice are the same variable\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q1\" id=\"answer_W10_Q1_2\" value=\"Practice has the same effect for everyone\"/>\nPractice has the same effect for everyone\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q1\" id=\"answer_W10_Q1_3\" value=\"The effect of practice cannot be interpreted without taking anxiety into account\"/>\nThe effect of practice cannot be interpreted without taking anxiety into account\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q1\" id=\"answer_W10_Q1_4\" value=\"The model must be refitted without anxiety\"/>\nThe model must be refitted without anxiety\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W10_Q1\"></div>\n</form>\n<script>function validate_form_W10_Q1() {var x, text; var x = document.forms['form_W10_Q1']['answer_W10_Q1'].value;if (x == 'The effect of practice cannot be interpreted without taking anxiety into account'){text = 'Correct! An interaction means the effect of one predictor depends on another - so a single ‘effect of practice’ does not exist; it must be reported separately for different anxiety levels (e.g. via effect plots).';} else {text = 'If the effect of practice <em>depends on</em> anxiety, can you state one single effect of practice?';} document.getElementById('result_W10_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_W10_Q1').innerText == 'Correct! An interaction means the effect of one predictor depends on another - so a single ‘effect of practice’ does not exist; it must be reported separately for different anxiety levels (e.g. via effect plots).';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q2. In your model, two predictors have VIF values of 12. What does this indicate?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W10_Q2\" onsubmit=\"return validate_form_W10_Q2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W10_Q2\" id=\"answer_W10_Q2_1\" value=\"The predictors have very strong effects on the outcome\"/>\nThe predictors have very strong effects on the outcome\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q2\" id=\"answer_W10_Q2_2\" value=\"The sample is 12 times too small\"/>\nThe sample is 12 times too small\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q2\" id=\"answer_W10_Q2_3\" value=\"The predictors are highly collinear, making their coefficient estimates unstable and hard to interpret\"/>\nThe predictors are highly collinear, making their coefficient estimates unstable and hard to interpret\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q2\" id=\"answer_W10_Q2_4\" value=\"The model explains 12% of the variance\"/>\nThe model explains 12% of the variance\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W10_Q2\"></div>\n</form>\n<script>function validate_form_W10_Q2() {var x, text; var x = document.forms['form_W10_Q2']['answer_W10_Q2'].value;if (x == 'The predictors are highly collinear, making their coefficient estimates unstable and hard to interpret'){text = 'Correct! VIFs above 10 signal severe collinearity: the predictors overlap so much that the model cannot cleanly attribute effects to either one. Consider removing or combining them.';} else {text = 'VIF measures how strongly a predictor can be predicted <em>from the other predictors</em>.';} document.getElementById('result_W10_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_W10_Q1').innerText == 'Correct! An interaction means the effect of one predictor depends on another - so a single ‘effect of practice’ does not exist; it must be reported separately for different anxiety levels (e.g. via effect plots).'; res2 = document.getElementById('result_W10_Q2').innerText == 'Correct! VIFs above 10 signal severe collinearity: the predictors overlap so much that the model cannot cleanly attribute effects to either one. Consider removing or combining them.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q3. Model A (3 predictors) has an AIC of 210; Model B (6 predictors) has an AIC of 214. Which model should you prefer?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W10_Q3\" onsubmit=\"return validate_form_W10_Q3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W10_Q3\" id=\"answer_W10_Q3_1\" value=\"Neither - AIC cannot compare models\"/>\nNeither - AIC cannot compare models\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q3\" id=\"answer_W10_Q3_2\" value=\"Model B - more predictors always mean a better model\"/>\nModel B - more predictors always mean a better model\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q3\" id=\"answer_W10_Q3_3\" value=\"Model A - lower AIC indicates the better trade-off between fit and complexity\"/>\nModel A - lower AIC indicates the better trade-off between fit and complexity\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W10_Q3\" id=\"answer_W10_Q3_4\" value=\"Model B - higher AIC values are better\"/>\nModel B - higher AIC values are better\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W10_Q3\"></div>\n</form>\n<script>function validate_form_W10_Q3() {var x, text; var x = document.forms['form_W10_Q3']['answer_W10_Q3'].value;if (x == 'Model A - lower AIC indicates the better trade-off between fit and complexity'){text = 'Correct! AIC rewards good fit but penalizes complexity; the model with the <em>lower</em> AIC is preferred. Model B’s three extra predictors do not improve fit enough to justify their inclusion.';} else {text = 'AIC balances fit against complexity - and lower values win.';} document.getElementById('result_W10_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_W10_Q1').innerText == 'Correct! An interaction means the effect of one predictor depends on another - so a single ‘effect of practice’ does not exist; it must be reported separately for different anxiety levels (e.g. via effect plots).'; res2 = document.getElementById('result_W10_Q2').innerText == 'Correct! VIFs above 10 signal severe collinearity: the predictors overlap so much that the model cannot cleanly attribute effects to either one. Consider removing or combining them.'; res3 = document.getElementById('result_W10_Q3').innerText == 'Correct! AIC rewards good fit but penalizes complexity; the model with the lower AIC is preferred. Model B’s three extra predictors do not improve fit enough to justify their inclusion.';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n[Back to top](#week10)\n\n",
    "supporting": [
      "10-week10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}