{
  "hash": "93db039d763dd325545e06d8880dad4c",
  "result": {
    "engine": "knitr",
    "markdown": "# Mixed-Effects Regression {#week12}\n\n::: {.callout-tip}\n## What This Session Covers\n\nThis session introduces mixed-effects models - the standard tool for hierarchical or repeated-measures data in linguistics.\n\n1. **Fixed vs. random effects** - and why repeated or nested observations violate independence\n2. **Linear mixed-effects regression** - random intercepts, ICC, model fitting, and diagnostics\n3. **Mixed-effects logistic regression** - modeling binary outcomes with random effects\n4. **Model diagnostics** - `check_model()`, singularity, and influential observations\n5. **Reporting** - summarizing mixed models in tables and prose\n:::\n\nMixed-effects models (or mixed models) have become extremely popular in the language sciences. In contrast to fixed-effects regressions, mixed models allow us to model dependency of data points and they are thus used when dealing with hierarchical data structure in which data points are grouped or nested in higher order categories (e.g. students within classes). Therefore, mixed models have a wide range of applications  and they have the following advantages:\n\n* Mixed-effects models are multivariate, i.e. they test the effect of several predictors simultaneously while controlling for the effect of all other predictors.\n\n* Mixed models allow to statistically incorporate within-speaker variability and are thus fit to model hierarchical or nested data structures. This applies if several observations are produced by an individual speaker, for instance.\n\n* Mixed-models provide a wealth of diagnostic statistics which enables us to control e.g. multicollinearity, i.e. correlations between predictors, and to test whether conditions or requirements are violated (e.g. homogeneity of variance, etc.).\n\n\nA disadvantage of mixed models is that they are prone to producing high $\\beta$-errors [see @johnson2009getting] and that they require rather large data sets.\n\nIn the following, we will go over  mixed-effects linear regression models and mixed-effects binomial logistic regression models. \n\n## Linear Mixed-Effects Regression\n\n::: {.callout-note}\n## Key concept: Fixed vs. random effects\n\n*Fixed effects* are the predictors whose specific effects we want to estimate and interpret (e.g. *Date*, *Gender*, *Priming*) - their levels are of direct interest and would recur in a replication. *Random effects* are grouping factors whose levels are a sample from a larger population (e.g. individual speakers, texts, genres, schools): we are not interested in, say, speaker 17 specifically, but we must account for the fact that observations from the same speaker are not independent. Random intercepts allow each group its own baseline; ignoring this structure (pseudoreplication) produces overconfident, anti-conservative results - one of the most common serious errors in quantitative linguistics.\n:::\n\n\nSo far, the regression models that we have used only had fixed-effects which means that all data points are treated as if they are completely independent and thus on the same hierarchical level. However, it is very common that the data is nested in the sense that data points are not independent because they are, for instance, produced by the same speaker or are grouped by some other characteristic.\n\nWith respect to regression modeling, hierarchical structures are incorporated by what is called *random effects*. When models only have a fixed-effects structure, then they make use of only a single intercept and/or slope (as in the left panel in the figure below), while mixed effects models have intercepts for each level of a random effect. If the random effect structure represents speakers then this would mean that a mixed-model would have a separate intercept and/or slope for each speaker (in addition to the overall intercept that is shown as an orange line in the figure below). \n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-week12_files/figure-html/lmm1-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe equation below represents a formal representation of a mixed-effects regression with varying intercepts [see @winter2019statistics, 235].\n\n\\begin{equation}\nf_{(x)} = \\alpha_{i} + \\beta x + \\epsilon\n\\end{equation}\n\nIn this random intercept model, each level of a random variable has a different intercept. To predict the value of a data point, we would thus take the appropriate intercept value (the model intercept + the intercept of the random effect) and add the product of the predictor coefficient and the value of x. \n\nFinally, the equation below represents a formal representation of a mixed-effects regression with varying intercepts and varying slopes [see @winter2019statistics, 235].\n\n\\begin{equation}\nf_{(x)} = \\alpha_{i} + \\beta_{i}x + \\epsilon\n\\end{equation}\n\nIn this last model, each level of a random variable has a different intercept and a different slope. To predict the value of a data point, we would thus take the appropriate intercept value (the model intercept + the intercept of the random effect) and add the coefficient of that random effect level multiplied by the value of x. \n\n### Random Effects{-}\n\n*Random Effects* can be visualized using two parameters: the intercept (the point where the regression line crosses the y-axis at x = 0) and the slope (the acclivity of the regression line). In contrast to fixed-effects models, that have only 1 intercept and one slope (left panel in the figure above), mixed-effects models can therefore have various *random intercepts* (center panel) or various *random slopes*, or both, various *random intercepts* and various *random slopes* (right panel). \n\nWhat features do distinguish random and fixed effects? \n\n1) Random effects represent a higher level variable under which data points are grouped. This implies that random effects must be categorical (or nominal but *they cannot be continuous*!) [see @winter2019statistics, p. 236].\n\n2) Random effects represent a sample of an infinite number of possible levels. For instance, speakers, trials, items, subjects, or words represent a potentially infinite pool of elements from which many different samples can be drawn. Thus, random effects represent a random sample. Fixed effects, on the other hand, typically do not represent a random sample but a fixed set of variable levels (e.g. Age groups, or parts-of-speech).\n\n3) Random effects typically represent many different levels while fixed effects typically have only a few. @zuur2013beginner propose that a variable may be used as a fixed effect if it has less than 5 levels while it should be treated as a random effect if it has more than 10 levels. Variables with 5 to 10 levels can be used as both. However, this is a rule of thumb and ignores the theoretical reasons (random sample and nestedness) for considering something as a random effect and it also is at odds with the way that repeated measures are modeled (namely as mixed effects) although they typically only have very few levels.  \n\n4) Fixed effects represent an effect that if we draw many samples, the effect would be consistent across samples [@winter2019statistics] while random effects should vary for each new sample that is drawn.\n\nIn terms of general procedure, random effects are added first and only then include the fixed effects.\n\n**Preparation and session set up**\n\nFor this week's content, we need to install certain *packages* from an R *library* so that the scripts shown below are executed without errors. Hence, before turning to the code below, please install the packages by running the code below this paragraph.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install\ninstall.packages(\"Boruta\")\ninstall.packages(\"flextable\")\ninstall.packages(\"ggplot2\")\ninstall.packages(\"gridExtra\")\ninstall.packages(\"glmulti\")\ninstall.packages(\"lme4\")\ninstall.packages(\"rms\")\ninstall.packages(\"sjPlot\")\ninstall.packages(\"performance\")\ninstall.packages(\"see\")\n```\n:::\n\n\n\n\nNow that we have installed the packages, we activate them as shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set options\noptions(\"scipen\" = 100, \"digits\" = 12) # suppress math annotation\n# load packages\nlibrary(flextable)\nlibrary(ggplot2)\nlibrary(gridExtra)\nlibrary(glmulti)\nlibrary(lme4)\nlibrary(rms)\nlibrary(sjPlot)\nlibrary(performance)\nlibrary(see)\n```\n:::\n\n\n\n\n### Example: Preposition Use across Time by Genre{-}\n\nTo explore how to implement a mixed-effects model in R we revisit the preposition data that contains relative frequencies of prepositions in English texts written between 1150 and 1913. As a first step, and to prepare our analysis, we load necessary R packages, specify options, and load as well as provide an overview of the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nlmmdata  <- base::readRDS(url(\"https://slcladal.github.io/data/lmd.rda\", \"rb\")) |>\n  # convert date into a numeric variable\n  dplyr::mutate(Date = as.numeric(Date))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-6895b2fa{table-layout:auto;width:75%;}.cl-6881c70e{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6881c722{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6889ba54{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6889ba68{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-688a098c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a0996{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09a0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09a1{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09b4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09be{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09c8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09c9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09ca{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09d2{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09dc{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09dd{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09e6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09f0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a09fa{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-688a0a04{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-6895b2fa'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-688a098c\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c70e\">Date</span></p></th><th class=\"cl-688a0996\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c70e\">Genre</span></p></th><th class=\"cl-688a0996\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c70e\">Text</span></p></th><th class=\"cl-688a09a0\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c70e\">Prepositions</span></p></th><th class=\"cl-688a09a1\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c70e\">Region</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,736</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Science</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">albin</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">166.01</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,711</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Education</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">anon</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">139.86</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,808</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">PrivateLetter</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">austen</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">130.78</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,878</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Education</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">bain</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">151.29</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,743</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Education</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">barclay</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">145.72</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,908</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Education</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">benson</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">120.77</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,906</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Diary</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">benson</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">119.17</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,897</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Philosophy</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">boethja</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">132.96</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,785</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Philosophy</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">boethri</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">130.49</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,776</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Diary</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">boswell</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">135.94</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,905</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Travel</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">bradley</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">154.20</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,711</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Education</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">brightland</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">149.14</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09b4\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,762</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Sermon</span></p></td><td class=\"cl-688a09be\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">burton</span></p></td><td class=\"cl-688a09c8\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">159.71</span></p></td><td class=\"cl-688a09c9\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09ca\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,726</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">Sermon</span></p></td><td class=\"cl-688a09d2\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">butler</span></p></td><td class=\"cl-688a09dc\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">157.49</span></p></td><td class=\"cl-688a09dd\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-688a09e6\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">1,835</span></p></td><td class=\"cl-688a09f0\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">PrivateLetter</span></p></td><td class=\"cl-688a09f0\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">carlyle</span></p></td><td class=\"cl-688a09fa\"><p class=\"cl-6889ba54\"><span class=\"cl-6881c722\">124.16</span></p></td><td class=\"cl-688a0a04\"><p class=\"cl-6889ba68\"><span class=\"cl-6881c722\">North</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nThe data set contains the date when the text was written (*Date*), the genre of the text (*Genre*), the name of the text (*Text*), the relative frequency of prepositions in the text (*Prepositions*), and the region in which the text was written (*Region*). We now plot the data to get a first impression of its structure.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(lmmdata, aes(Date, Prepositions)) +\n  geom_point() +\n  labs(x = \"Year\", y = \"Prepositions per 1,000 words\") +\n  geom_smooth(method = \"lm\")  + \n  theme_bw()\np2 <- ggplot(lmmdata, aes(Region, Prepositions)) +\n  geom_boxplot() +\n  labs(x = \"Region\", y = \"Prepositions per 1,000 words\") +\n  geom_smooth(method = \"lm\")  + \n  theme_bw()\np3 <- ggplot(lmmdata, aes(x = reorder(Genre, -Prepositions), y = Prepositions)) +\n  geom_boxplot() +\n  theme_bw() + \n  theme(axis.text.x = element_text(angle=90)) +\n  labs(x = \"Genre\", y = \"Frequency\\n(Prepositions)\")\np4 <- ggplot(lmmdata, aes(Prepositions)) +\n  geom_histogram() +\n  theme_bw() + \n  labs(y = \"Count\", x = \"Frequency (Prepositions)\")\ngrid.arrange(p1, p2, p3, p4, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/lmm4-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe scatter plot in the upper panel indicates that the use of prepositions has moderately increased over time while the boxplots in the lower left panel show that the genres differ quite substantially with respect to their median frequencies of prepositions per text. Finally, the histogram in the lower right panel show that preposition use is distributed normally with a mean of 132.2 prepositions per text. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lmmdata, aes(Date, Prepositions)) +\n  geom_point() +\n  facet_wrap(~ Genre, nrow = 4) +\n  geom_smooth(method = \"lm\") +\n  theme_bw() +\n  labs(x = \"Date of composition\", y = \"Prepositions per 1,000 words\") +\n  coord_cartesian(ylim = c(0, 220))\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/lmm6-1.png){width=672}\n:::\n:::\n\n\n\n\nCentering numeric variables is useful for later interpretation of regression models: if the date variable were not centered, the regression would show the effects of variables at year 0(!). If numeric variables are centered, other variables are variables are considered relative not to 0 but to the mean of that variable (in this case the mean of years in our data). Centering simply means that the mean of the numeric variable is subtracted from each value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmmdata <- lmmdata |>\n  dplyr::mutate(DateUnscaled = Date,\n                Date = scale(Date, scale = F))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-6bf4834a{table-layout:auto;width:75%;}.cl-6beaa898{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6beaa8a2{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6bee7e6e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6bee7e82{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6beea2ea{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea2f4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea2f5{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea2f6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea2fe{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea2ff{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea308{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea309{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea30a{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea312{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea313{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea314{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea31c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea31d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea31e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6beea326{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-6bf4834a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-6beea2ea\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa898\">Date</span></p></th><th class=\"cl-6beea2f4\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa898\">Genre</span></p></th><th class=\"cl-6beea2f4\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa898\">Text</span></p></th><th class=\"cl-6beea2f5\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa898\">Prepositions</span></p></th><th class=\"cl-6beea2f4\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa898\">Region</span></p></th><th class=\"cl-6beea2f6\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa898\">DateUnscaled</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">109.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Science</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">albin</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">166.01</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,736</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">84.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Education</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">anon</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">139.86</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,711</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">181.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">PrivateLetter</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">austen</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">130.78</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,808</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">251.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Education</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">bain</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">151.29</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,878</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">116.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Education</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">barclay</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">145.72</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,743</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">281.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Education</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">benson</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">120.77</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,908</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">279.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Diary</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">benson</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">119.17</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,906</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">270.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Philosophy</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">boethja</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">132.96</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,897</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">158.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Philosophy</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">boethri</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">130.49</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,785</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">149.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Diary</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">boswell</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">135.94</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,776</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">278.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Travel</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">bradley</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">154.20</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,905</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">84.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Education</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">brightland</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">149.14</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,711</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea2fe\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">135.8696461825</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Sermon</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">burton</span></p></td><td class=\"cl-6beea308\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">159.71</span></p></td><td class=\"cl-6beea2ff\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea309\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,762</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea30a\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">99.8696461825</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">Sermon</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">butler</span></p></td><td class=\"cl-6beea313\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">157.49</span></p></td><td class=\"cl-6beea312\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea314\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,726</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-6beea31c\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">208.8696461825</span></p></td><td class=\"cl-6beea31d\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">PrivateLetter</span></p></td><td class=\"cl-6beea31d\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">carlyle</span></p></td><td class=\"cl-6beea31e\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">124.16</span></p></td><td class=\"cl-6beea31d\"><p class=\"cl-6bee7e82\"><span class=\"cl-6beaa8a2\">North</span></p></td><td class=\"cl-6beea326\"><p class=\"cl-6bee7e6e\"><span class=\"cl-6beaa8a2\">1,835</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWe now set up a mixed-effects model using the `lmer` function from the `lme4` package [@lme4] with Genre as a random effect.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate models\nm0.lmer = lmer(Prepositions ~ 1 + (1|Genre), REML = T, data = lmmdata)\n```\n:::\n\n\n\n\nBefore we start adding fixed effects, we check whether including the random effect structure is justified. To do this, we use two functions from the `performance` package [@performance]: the `icc` function, which reports the *intra-class correlation coefficient* (ICC), i.e. the proportion of the total variance that is accounted for by the grouping structure (here: Genre) - substantial ICC values indicate that observations within the same group are more similar to each other than to observations from other groups, which warrants the inclusion of the random effect - and the `check_singularity` function, which tests whether the random effect structure is too complex to be supported by the data (a singular fit means that the variance of (parts of) the random effect structure is estimated to be (close to) zero, which indicates that the random effect structure should be simplified).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# intra-class correlation coefficient\nperformance::icc(m0.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.409\n  Unadjusted ICC: 0.409\n```\n\n\n:::\n\n```{.r .cell-code}\n# check for singular fit\nperformance::check_singularity(m0.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\nThe ICC shows that a substantive proportion of the variance is accounted for by Genre and the model does not suffer from a singular fit. Including the random effect structure is thus justified and we can continue to fit the model to the data.\n\n\n\n### Model Fitting{-}\n\nAfter having determined that including a random effect structure is justified, we can continue by fitting the model and including diagnostics as we go. Including diagnostics in the model fitting process can save time and prevent relying on models which only turn out to be unstable if we would perform the diagnostics after the fact.\n\nWe begin fitting our model by adding *Date* as a fixed effect and compare this model to our mixed-effects base-line model to see if *Date* improved the model fit by explaining variance and if *Date* significantly correlates with our dependent variable (this means that the difference between the models is the effect (size) of *Date*!)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1.lmer <- lmer(Prepositions ~ (1|Genre) + Date, REML = T, data = lmmdata)\nanova(m1.lmer, m0.lmer, test = \"Chi\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: lmmdata\nModels:\nm0.lmer: Prepositions ~ 1 + (1 | Genre)\nm1.lmer: Prepositions ~ (1 | Genre) + Date\n        npar         AIC         BIC       logLik   -2*log(L)  Chisq Df\nm0.lmer    3 4501.947337 4514.805331 -2247.973668 4495.947337          \nm1.lmer    4 4495.017736 4512.161728 -2243.508868 4487.017736 8.9296  1\n        Pr(>Chisq)   \nm0.lmer              \nm1.lmer  0.0028059 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nThe model with *Date* is the better model (significant p-value and lower AIC). The significant p-value shows that *Date* correlates significantly with *Prepositions* ($\\chi$^2^(1): 8.929600937903, p  = 0.00281) . The $\\chi$^2^ value here is labeled *Chisq* and the degrees of freedom are calculated by subtracting the smaller number of DFs from the larger number of DFs.\n\nWe now test whether *Region* should also be part of the final minimal adequate model. The easiest way to add predictors is by using the `update` function (it saves time and typing).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate model\nm2.lmer <- update(m1.lmer, .~.+ Region)\n# check collinearity\nperformance::check_collinearity(m2.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n   Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n   Date 1.20 [1.11, 1.36]     1.10      0.83     [0.73, 0.90]\n Region 1.20 [1.11, 1.36]     1.10      0.83     [0.73, 0.90]\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare models                \nanova(m2.lmer, m1.lmer, test = \"Chi\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: lmmdata\nModels:\nm1.lmer: Prepositions ~ (1 | Genre) + Date\nm2.lmer: Prepositions ~ (1 | Genre) + Date + Region\n        npar         AIC         BIC       logLik   -2*log(L)   Chisq Df\nm1.lmer    4 4495.017736 4512.161728 -2243.508868 4487.017736           \nm2.lmer    5 4494.624343 4516.054333 -2242.312171 4484.624343 2.39339  1\n        Pr(>Chisq)\nm1.lmer           \nm2.lmer    0.12185\n```\n\n\n:::\n:::\n\n\n\n\nThree things tell us that *Region* should not be included: \n\n1. the AIC does not decrease, \n\n2. the BIC increases(!), and \n\n3. the p-value is higher than .05. \n\nThis means, that we will continue fitting the model without having *Region* included. Well... not quite - just as a note on including variables: while *Region* is not significant as a main effect, it must still be included in a model if it were part of a significant interaction. To test if this is indeed the case, we fit another model with the interaction between *Date* and *Region* as predictor.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate model\nm3.lmer <- update(m1.lmer, .~.+ Region*Date)\n# check collinearity\nperformance::check_collinearity(m3.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n        Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n        Date 1.97 [1.75, 2.25]     1.40      0.51     [0.44, 0.57]\n      Region 1.20 [1.11, 1.36]     1.10      0.83     [0.73, 0.90]\n Date:Region 1.78 [1.59, 2.03]     1.33      0.56     [0.49, 0.63]\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare models                \nanova(m3.lmer, m1.lmer, test = \"Chi\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: lmmdata\nModels:\nm1.lmer: Prepositions ~ (1 | Genre) + Date\nm3.lmer: Prepositions ~ (1 | Genre) + Date + Region + Date:Region\n        npar         AIC         BIC       logLik   -2*log(L)   Chisq Df\nm1.lmer    4 4495.017736 4512.161728 -2243.508868 4487.017736           \nm3.lmer    6 4496.124872 4521.840861 -2242.062436 4484.124872 2.89286  2\n        Pr(>Chisq)\nm1.lmer           \nm3.lmer    0.23541\n```\n\n\n:::\n:::\n\n\n\n\nAgain, the high p-value and the increase in AIC and BIC show that we have found our minimal adequate model which only contains *Date* as a main effect. In a next step, we can inspect the final minimal adequate model, i.e. the most parsimonious (the model that explains a maximum of variance with a minimum of predictors).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# inspect results\nsummary(m1.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Prepositions ~ (1 | Genre) + Date\n   Data: lmmdata\n\nREML criterion at convergence: 4491.1\n\nScaled residuals: \n         Min           1Q       Median           3Q          Max \n-3.734915441 -0.657038004  0.005865025  0.661298615  3.596659863 \n\nRandom effects:\n Groups   Name        Variance   Std.Dev.  \n Genre    (Intercept) 159.021120 12.6103576\n Residual             228.764179 15.1249522\nNumber of obs: 537, groups:  Genre, 16\n\nFixed effects:\n                   Estimate      Std. Error  t value\n(Intercept) 133.88516211469   3.24749296248 41.22724\nDate          0.01894493515   0.00632363682  2.99589\n\nCorrelation of Fixed Effects:\n     (Intr)\nDate 0.005 \n```\n\n\n:::\n:::\n\n\n\n\n### Model Diagnostics{-}\n\nWe now perform the model diagnostics. What we wish to see in the residual-based diagnostic plots is a cloud of dots without any structure. What we do not want to see is a funnel-shaped cloud because this indicates an increase of the errors/residuals with an increase of the predictor(s) (because this would indicate heteroscedasticity) [@pinheiro2000mixedmodels 182]. As with fixed-effects regression models, we use the `check_model` function from the `performance` package [@performance] to evaluate the goodness of fit of the model and to check if mathematical requirements and assumptions have been violated.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate diagnostic plots\nperformance::check_model(m1.lmer)\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/lmm14-1.png){width=672}\n:::\n:::\n\n\n\n\nThe panels for linearity, homogeneity of variance, influential observations, and normality of residuals are interpreted exactly as in the previous weeks. In addition to these familiar panels, `check_model` produces a panel that is specific to mixed-effects models: the *Normality of Random Effects* panel. This panel shows whether the estimated random intercepts (here: the intercept adjustments for the individual genres) follow a normal distribution, which is an assumption of mixed-effects models - the dots should follow the reference line.\n\nWe complement the visual inspection with formal checks for influential observations and singularity.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check for influential observations\nperformance::check_outliers(m1.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: No outliers detected.\n- Based on the following method and threshold: cook (0.7).\n- For variable: (Whole model)\n```\n\n\n:::\n\n```{.r .cell-code}\n# check for singular fit\nperformance::check_singularity(m1.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\nThe diagnostics do not show any severe violations of the model assumptions (some minor deviations in the tails of the distribution of the residuals are common when dealing with real-life data and no reason for concern here) which tells us that the model is \"healthy\" and that we can proceed with the interpretation of the model.\n\n\n### Summarizing the results{-}\n\nWe will now summarize the results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::tab_model(m1.lmer)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Prepositions</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">133.89</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">127.51&nbsp;&ndash;&nbsp;140.26</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Date</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.01&nbsp;&ndash;&nbsp;0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.003</strong></td>\n</tr>\n<tr>\n<td colspan=\"4\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">228.76</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>Genre</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">159.02</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.41</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>Genre</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">16</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">537</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.012 / 0.417</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\nThe *marginal R^2^* (marginal coefficient of determination) represents the variance explained by the fixed effects while the *conditional R^2^* is interpreted as a variance explained by the entire model, including both fixed and random effects [@barton2020mumin].\n\n\n\nThe effects can be visualized using the `plot_model` function from the `sjPlot` package [@sjPlot].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::plot_model(m1.lmer, type = \"pred\", terms = c(\"Date\")) +\n  # show uncentered date rather than centered date\n  scale_x_continuous(name = \"Date\", \n                     breaks = seq(-500, 300, 100), \n                     labels = seq(1150, 1950, 100))\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/lmm21d-1.png){width=672}\n:::\n:::\n\n\n\n\nWhile we have already shown that the effect of *Date* is significant, it is small which means that the number of prepositions per text does not correlate very strongly with time. This suggests that other factors that are not included in the model also impact the frequency of prepositions (and probably more meaningfully, too).\n\n\n### Reporting Results {-}\n\nWe can use the `reports` package [@report] to summarize the analysis.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(m1.lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear mixed model (estimated using REML and nloptwrap optimizer)\nto predict Prepositions with Date (formula: Prepositions ~ Date). The model\nincluded Genre as random effect (formula: ~1 | Genre). The model's total\nexplanatory power is substantial (conditional R2 = 0.42) and the part related\nto the fixed effects alone (marginal R2) is of 0.01. The model's intercept,\ncorresponding to Date = 0, is at 133.89 (95% CI [127.51, 140.26], t(533) =\n41.23, p < .001). Within this model:\n\n  - The effect of Date is statistically significant and positive (beta = 0.02,\n95% CI [6.52e-03, 0.03], t(533) = 3.00, p = 0.003; Std. beta = 0.11, 95% CI\n[0.04, 0.19])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\nWe fitted a linear mixed model to predict the relative frequency of prepositions in historical English texts based on the year when the text was written (formula: Prepositions ~ Date). The model included the genre of the text as random effect (formula: ~1 | Genre). The model's total explanatory power is substantial (conditional R^2^ = 0.42) and the part related to the fixed effects alone (marginal R^2^) is of 0.01. The model reported that the effect of the year when the text was written is statistically significant and positive (beta = 0.02 [6.52e-03, 0.03], t(533) = 3.00, p = 0.003; Std. beta = 0.11 [0.04, 0.19]).\n\n\n## Mixed-Effects Logistic Regression\n\n\nAs is the case with linear mixed-effects models, binomial logistic mixed-effect models are multivariate analyses that treat data points as hierarchical or grouped in some way. In other words, they take into account that the data is nested in the sense that data points are produced by the same speaker or are grouped by some other characteristics. In mixed-models, hierarchical structures are modelled as *random effects*. If the random effect structure represents speakers then this means that a mixed-model would have a separate intercept and/or slope for each speaker. \n\n*Random Effects* in linear models can be visualized using two parameters: the intercept (the point where the regression line crosses the y-axis at x = 0) and the slope (the acclivity of the regression line). In contrast to linear mixed-effects models, random effects differ in the position and the slope of the logistic function that is applied to the likelihood of the dependent variable.  *random intercepts* (upper right panel) or various *random slopes* (lower left panel), or both, various *random intercepts* and various *random slopes* (lower right panel). In the following, we will only focus on models with random intercepts because this is the by far more common method and because including both random intercepts and random slopes requires huge amounts of data. Consider the Figure below to understand what is meant by \"random intercepts\".\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-week12_files/figure-html/blmm1-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe upper left panel merely shows the logistic curve representing the predictions of a fixed-effects logistic regression with a single intercept and slope. The upper right panel shows the logistic curves representing the predictions of a mixed-effects logistic regression with random intercepts for each level of a grouping variable. The lower left panel shows the logistic curves representing the predictions of a mixed-effects logistic regression with one intercept but random slopes for each level of a grouping variable. The lower right panel shows the logistic curves representing the predictions of a mixed-effects logistic regression with random intercepts and random slopes for each level of a grouping variable.\n\nAfter adding random intercepts, predictors (or fixed effects) are added to the model (just like with multiple regression). So mixed-effects are called mixed-effects because they contain both random and fixed effects.\n\nIn terms of general procedure, random effects are added first, and only after we have ascertained that including random effects is warranted, we test whether including fixed-effects is warranted [@field2012discovering]. We test whether including random effects is warranted by comparing a model, that bases its estimates of the dependent variable solely on the base intercept, with a model that bases its estimates of the dependent variable solely on the intercepts of the random effect. If the mixed-effects model explains significantly more variance than the fixed-effects model without random effect structure, then we continue with the mixed-effects model. In other words, including random effects is justified.\n\n### Example: Discourse LIKE in Irish English\n\nIn this example we will investigate which factors correlate with the use of *final discourse like* (e.g. \"*The weather is shite, like!*\") in Irish English. The data set represents speech units in a corpus that were coded for the speaker who uttered a given speech unit, the gender (Gender: Men versus Women) and age of that speaker (Age: Old versus Young), whether the interlocutors were of the same or a different gender (ConversationType: SameGender  versus MixedGender), and whether another *final discourse like* had been used up to three speech units before (Priming: NoPrime versus Prime), whether or not the speech unit contained a *final discourse like* (SUFlike: 1 = yes, 0 = no). To begin with, we load the data and inspect the structure of the data set,\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nmblrdata  <- base::readRDS(url(\"https://slcladal.github.io/data/mbd.rda\", \"rb\"))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7432929a{table-layout:auto;width:75%;}.cl-7420c8c6{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7420c8ee{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7427c1c6{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7427c1da{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7427f952{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f953{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f95c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f966{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f970{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f97a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f97b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f984{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f98e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f998{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f999{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7427f99a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7432929a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7427f952\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8c6\">ID</span></p></th><th class=\"cl-7427f953\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8c6\">Gender</span></p></th><th class=\"cl-7427f953\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8c6\">Age</span></p></th><th class=\"cl-7427f953\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8c6\">ConversationType</span></p></th><th class=\"cl-7427f953\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8c6\">Priming</span></p></th><th class=\"cl-7427f95c\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8c6\">SUFlike</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-061$C</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-023$B</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-054$A</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-090$B</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-009$B</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Old</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Prime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-085$E</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Men</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Prime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-003$C</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-084$C</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-076$A</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-083$D</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Men</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Old</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-068$A</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-066$B</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f966\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-061$A</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Men</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Old</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f970\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f97a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f97b\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-049$A</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">SameGender</span></p></td><td class=\"cl-7427f984\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f98e\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7427f998\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">S1A-022$B</span></p></td><td class=\"cl-7427f999\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Women</span></p></td><td class=\"cl-7427f999\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">Young</span></p></td><td class=\"cl-7427f999\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">MixedGender</span></p></td><td class=\"cl-7427f999\"><p class=\"cl-7427c1c6\"><span class=\"cl-7420c8ee\">NoPrime</span></p></td><td class=\"cl-7427f99a\"><p class=\"cl-7427c1da\"><span class=\"cl-7420c8ee\">0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nAs all variables except for the dependent variable (`SUFlike`) are character strings, we\nfactorize the independent variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# def. variables to be factorized\nmblrdata <- mblrdata |>\n  dplyr::mutate_if(is.character, factor) |>\n  dplyr::mutate(Age = relevel(Age, \"Young\")) |>\n  dplyr::arrange(ID)\n```\n:::\n\n\n\n\n\nWe now plot the data to inspect the relationships within the data set. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mblrdata, aes(Priming, SUFlike, color = Gender)) +\n  facet_wrap(~ConversationType) +\n  stat_summary(fun = mean, geom = \"point\") +\n  stat_summary(fun.data = mean_cl_boot, geom = \"errorbar\", width = 0.2) +\n  theme_set(theme_bw(base_size = 10)) +\n  theme(legend.position = \"top\") +\n  labs(x = \"\", y = \"Observed Probabilty of discourse like\")\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/blmm8-1.png){width=672}\n:::\n:::\n\n\n\n\nThe figure above indicates that men use discourse *like* more frequently than women and that priming increases the likelihood of discourse *like* being used. Speakers also appear to use discourse *like* more frequently in mixed-gender conversations. In addition, the figure suggests an interaction between gender and conversation type, as women appear to use discourse *like* less frequently in same-gender conversations while the conversation type does not seem to have an effect on men. After visualizing the data, we will now turn to the model building process.\n\n### Model Building\n\nIn a first step, we set the options.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set options\noptions(contrasts  =c(\"contr.treatment\", \"contr.poly\"))\nmblrdata.dist <- datadist(mblrdata)\noptions(datadist = \"mblrdata.dist\")\n```\n:::\n\n\n\n\nIn a next step, we generate a base-line mixed-model using the `glmer` function with a random intercept for ID.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base-line mixed-model\nm0.glmer = glmer(SUFlike ~ (1|ID), data = mblrdata, family = binomial) \n```\n:::\n\n\n\n\n\n### Model Fitting\n\nThe next step is to fit the model which means that we aim to find the \"best\" model, i.e. the minimal adequate model. In this case, we will use the `glmulti` package to find the model with the lowest *Bayesian Information Criterion* (BIC) of all possible models.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# wrapper function for linear mixed-models\nglmer.glmulti <- function(formula,data, random=\"\",...){\n  glmer(paste(deparse(formula),random), family = binomial, data=data, ...)\n}\n# define formular\nform_glmulti = as.formula(paste(\"SUFlike ~ Gender + Age + ConversationType + Priming\"))\n```\n:::\n\n\n\n\nExtract best 5 models.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# multi selection for glmer\nmfit <- glmulti(form_glmulti,random=\"+(1 | ID)\", \n                data = mblrdata, method = \"h\", fitfunc = glmer.glmulti,\n                crit = \"bic\", intercept = TRUE, marginality = FALSE, level = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialization...\nTASK: Exhaustive screening of candidate set.\nFitting...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAfter 50 models:\nBest model: SUFlike~1+Gender+ConversationType+Priming\nCrit= 1696.58773399859\nMean crit= 1753.96253326009\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/glmulti2-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAfter 100 models:\nBest model: SUFlike~1+Gender+ConversationType+Priming\nCrit= 1696.58773399859\nMean crit= 1731.8900101622\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/glmulti2-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted.\n```\n\n\n:::\n\n```{.r .cell-code}\n# extract best models\ntop <- weightable(mfit)\ntop <- top[1:5,]\n# inspect top 5 models\ntop\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                                          model\n1                                             SUFlike ~ 1 + Gender + ConversationType + Priming\n2                            SUFlike ~ 1 + Gender + ConversationType + Priming + Priming:Gender\n3 SUFlike ~ 1 + Gender + ConversationType + Priming + Priming:Gender + Priming:ConversationType\n4                                               SUFlike ~ 1 + Gender + Priming + Priming:Gender\n5                  SUFlike ~ 1 + Gender + ConversationType + Priming + Priming:ConversationType\n            bic         weights\n1 1696.58773400 0.2567900986201\n2 1696.76989553 0.2344349730577\n3 1696.76989553 0.2344349730577\n4 1699.62465885 0.0562494682007\n5 1699.83927869 0.0505259299057\n```\n\n\n:::\n:::\n\n\n\n\n\nWe now define our final minimal model and check its output.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.glmer <- glmer(SUFlike ~ (1 | ID) + Gender + ConversationType + Priming, \n                   family = binomial, data = mblrdata)\n# inspect final minimal adequate model\nsummary(mlr.glmer, corr = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: SUFlike ~ (1 | ID) + Gender + ConversationType + Priming\n   Data: mblrdata\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1668.6    1696.6    -829.3    1658.6      1995 \n\nScaled residuals: \n         Min           1Q       Median           3Q          Max \n-1.579356769 -0.415524274 -0.330409172 -0.312054871  3.247877854 \n\nRandom effects:\n Groups Name        Variance     Std.Dev.   \n ID     (Intercept) 0.0837487102 0.289393694\nNumber of obs: 2000, groups:  ID, 208\n\nFixed effects:\n                               Estimate   Std. Error  z value\n(Intercept)                -1.067433309  0.149187449 -7.15498\nGenderWomen                -0.642882903  0.175331323 -3.66667\nConversationTypeSameGender -0.536428992  0.148820273 -3.60454\nPrimingPrime                1.866249507  0.163248506 11.43195\n                                         Pr(>|z|)    \n(Intercept)                   0.00000000000083685 ***\nGenderWomen                            0.00024573 ***\nConversationTypeSameGender             0.00031270 ***\nPrimingPrime               < 0.000000000000000222 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nWe now test whether the final minimal model performs significantly better than the minimal base-line model, and print the regression summary. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# final model better than base-line model\nanova(mlr.glmer, m0.glmer, test = \"Chi\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: mblrdata\nModels:\nm0.glmer: SUFlike ~ (1 | ID)\nmlr.glmer: SUFlike ~ (1 | ID) + Gender + ConversationType + Priming\n          npar         AIC         BIC       logLik   -2*log(L)     Chisq Df\nm0.glmer     2 1828.492271 1839.694076 -912.2461355 1824.492271             \nmlr.glmer    5 1668.583222 1696.587734 -829.2916109 1658.583222 165.90905  3\n                      Pr(>Chisq)    \nm0.glmer                            \nmlr.glmer < 0.000000000000000222 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n### Visualizing Effects\n\nAs we will see the effects in the final summary, we visualize the effects here  using the `sjPlot` package [@sjPlot].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::plot_model(mlr.glmer, type = \"pred\", terms = c(\"Gender\", \"Priming\", \"ConversationType\"))\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/blmm33b-1.png){width=672}\n:::\n:::\n\n\n\n\nWe can see that discourse *like* is more likely to surface in primed contexts and among men. In same-gender conversations, speakers use discourse *like* less than in mixed-gender conversations.\n \n\n### Extracting Model Fit Parameters\n\nWe now  extract model fit parameters [@baayen2008analyzing 281].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprobs = 1/(1+exp(-fitted(mlr.glmer)))\nprobs = binomial()$linkinv(fitted(mlr.glmer))\nsomers2(probs, as.numeric(mblrdata$SUFlike))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                C               Dxy                 n           Missing \n   0.760226203516    0.520452407033 2000.000000000000    0.000000000000 \n```\n\n\n:::\n:::\n\n\n\n\nThe two lines that start with `probs` are simply two different ways to do the same thing (you only need one of these).\n\nThe model fit parameters indicate a suboptimal fit. Both the C-value (the concordance statistic) and Somers' $\\delta$ (Somers'delta) show an acceptable fit between predicted and observed occurrences of discourse *like*.  If the C-value is 0.5, the predictions are random, while the predictions are perfect if the C-value is 1. C-values above 0.8 indicate real predictive capacity [@baayen2008analyzing 204]. Somers’ D~xy~ is a value that represents a rank correlation between predicted probabilities and observed responses. Somers’ D~xy~ values range between 0, which indicates complete randomness, and 1, which indicates perfect prediction [@baayen2008analyzing 204]. The C-value of 0.76 suggests that the model has some predictive and explanatory power, but not at an optimal level. We will now perform the model diagnostics: as with the fixed-effects binomial logistic regression, we check the binned residuals, collinearity, and influential observations, and, as with the linear mixed-effects model, we additionally check the normality of the random effects and whether the model suffers from a singular fit.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate diagnostic plots\nperformance::check_model(mlr.glmer)\n```\n\n::: {.cell-output-display}\n![](12-week12_files/figure-html/blmm36-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# check collinearity\nperformance::check_collinearity(mlr.glmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n             Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n           Gender 1.16 [1.11, 1.23]     1.08      0.86     [0.82, 0.90]\n ConversationType 1.18 [1.13, 1.25]     1.09      0.85     [0.80, 0.88]\n          Priming 1.02 [1.00, 1.17]     1.01      0.98     [0.85, 1.00]\n```\n\n\n:::\n\n```{.r .cell-code}\n# check for influential observations (Cook's distances; values > 1 are problematic)\nmax(cooks.distance(mlr.glmer))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.253783361853\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(cooks.distance(mlr.glmer) > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnamed integer(0)\n```\n\n\n:::\n\n```{.r .cell-code}\n# check for singular fit\nperformance::check_singularity(mlr.glmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\nThe diagnostics do not indicate any severe problems.\n\nIn a final step, we summarize our findings in tabulated form.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summarize final model\nsjPlot::tab_model(mlr.glmer)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">SUFlike</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.34</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.26&nbsp;&ndash;&nbsp;0.46</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Gender [Women]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.53</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.37&nbsp;&ndash;&nbsp;0.74</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ConversationType<br>[SameGender]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.58</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.44&nbsp;&ndash;&nbsp;0.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Priming [Prime]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">6.46</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">4.69&nbsp;&ndash;&nbsp;8.90</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td colspan=\"4\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">3.29</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>ID</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.08</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.02</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>ID</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">208</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">2000</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.131 / 0.152</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\nWe can use the `reports` package [@report] to summarize the analysis.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(mlr.glmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a logistic mixed model (estimated using ML and Nelder-Mead optimizer)\nto predict SUFlike with Gender, ConversationType and Priming (formula: SUFlike\n~ Gender + ConversationType + Priming). The model included ID as random effect\n(formula: ~1 | ID). The model's total explanatory power is moderate\n(conditional R2 = 0.15) and the part related to the fixed effects alone\n(marginal R2) is of 0.13. The model's intercept, corresponding to Gender = Men,\nConversationType = MixedGender and Priming = NoPrime, is at -1.07 (95% CI\n[-1.36, -0.78], p < .001). Within this model:\n\n  - The effect of Gender [Women] is statistically significant and negative (beta\n= -0.64, 95% CI [-0.99, -0.30], p < .001; Std. beta = -0.64, 95% CI [-0.99,\n-0.30])\n  - The effect of ConversationType [SameGender] is statistically significant and\nnegative (beta = -0.54, 95% CI [-0.83, -0.24], p < .001; Std. beta = -0.54, 95%\nCI [-0.83, -0.24])\n  - The effect of Priming [Prime] is statistically significant and positive (beta\n= 1.87, 95% CI [1.55, 2.19], p < .001; Std. beta = 1.87, 95% CI [1.55, 2.19])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald z-distribution approximation.\n```\n\n\n:::\n:::\n\n\n\n\nWe can use this output to write up a final report: \n\n\nWe fitted a logistic mixed model to predict the use of discourse *like*. The model included speakers as random effect (formula: ~1 | ID). The model's total explanatory power is moderate (conditional R^2^ = 0.15) and the part related to the fixed effects alone (marginal R^2^) is of 0.13.\n\nRegarding fixed effects, the model reported that \n* women use discourse *like* statistically less compared to men (beta =\n-0.64 [-0.99, -0.30], p < .001; Std. beta = -0.64 [-0.99,\n-0.30])  \n* speakers in conversations with other speakers of the same gender use discourse *like* significantly less compared to their use in mixed-gender conversations (beta = -0.54 [-0.83, -0.24], p < .001; Std. beta = -0.54 [-0.83, -0.24])  \n* Priming is  significantly positively correlated with the use of discourse *like* (beta = 1.87 [1.55, 2.19], p < .001; Std. beta = 1.87 [1.55, 2.19])\n\n\n\n\n::: {.callout-tip}\n## Exercises: Mixed-Effects Regression\n:::\n\n**Q1. You analyze 2,000 reaction times from 40 participants (50 trials each). Why is an ordinary regression on all 2,000 data points problematic?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W12_Q1\" onsubmit=\"return validate_form_W12_Q1()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W12_Q1\" id=\"answer_W12_Q1_1\" value=\"Observations from the same participant are not independent, so the model overstates the amount of independent information\"/>\nObservations from the same participant are not independent, so the model overstates the amount of independent information\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q1\" id=\"answer_W12_Q1_2\" value=\"Reaction times cannot be modeled with regressions\"/>\nReaction times cannot be modeled with regressions\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q1\" id=\"answer_W12_Q1_3\" value=\"Ordinary regressions do not accept more than one predictor\"/>\nOrdinary regressions do not accept more than one predictor\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q1\" id=\"answer_W12_Q1_4\" value=\"2,000 data points are too many for a regression\"/>\n2,000 data points are too many for a regression\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W12_Q1\"></div>\n</form>\n<script>function validate_form_W12_Q1() {var x, text; var x = document.forms['form_W12_Q1']['answer_W12_Q1'].value;if (x == 'Observations from the same participant are not independent, so the model overstates the amount of independent information'){text = 'Correct! The 50 trials per participant are correlated - fast participants are fast throughout. Treating them as 2,000 independent observations (pseudoreplication) deflates standard errors and produces spuriously significant results. A random intercept for participant fixes this.';} else {text = 'Are 50 measurements from the same person really 50 independent pieces of information?';} document.getElementById('result_W12_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_W12_Q1').innerText == 'Correct! The 50 trials per participant are correlated - fast participants are fast throughout. Treating them as 2,000 independent observations (pseudoreplication) deflates standard errors and produces spuriously significant results. A random intercept for participant fixes this.';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q2. In a study of preposition use across texts from different genres, which specification treats genre correctly as a random effect?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W12_Q2\" onsubmit=\"return validate_form_W12_Q2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W12_Q2\" id=\"answer_W12_Q2_1\" value=\"Prepositions ~ (Date | 1) + Genre\"/>\nPrepositions ~ (Date | 1) + Genre\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q2\" id=\"answer_W12_Q2_2\" value=\"Prepositions ~ Date + Genre\"/>\nPrepositions ~ Date + Genre\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q2\" id=\"answer_W12_Q2_3\" value=\"Prepositions ~ Date + (1 | Genre)\"/>\nPrepositions ~ Date + (1 | Genre)\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q2\" id=\"answer_W12_Q2_4\" value=\"Prepositions ~ Date * Genre\"/>\nPrepositions ~ Date * Genre\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W12_Q2\"></div>\n</form>\n<script>function validate_form_W12_Q2() {var x, text; var x = document.forms['form_W12_Q2']['answer_W12_Q2'].value;if (x == 'Prepositions ~ Date + (1 | Genre)'){text = 'Correct! (1 | Genre) gives each genre its own random intercept, treating genres as a sample of grouping units whose baseline differences must be accounted for. Including Genre as a fixed effect instead would estimate a separate coefficient for every genre - a different research question.';} else {text = 'The lme4 syntax for a random intercept is (1 | grouping_factor).';} document.getElementById('result_W12_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_W12_Q1').innerText == 'Correct! The 50 trials per participant are correlated - fast participants are fast throughout. Treating them as 2,000 independent observations (pseudoreplication) deflates standard errors and produces spuriously significant results. A random intercept for participant fixes this.'; res2 = document.getElementById('result_W12_Q2').innerText == 'Correct! (1 | Genre) gives each genre its own random intercept, treating genres as a sample of grouping units whose baseline differences must be accounted for. Including Genre as a fixed effect instead would estimate a separate coefficient for every genre - a different research question.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n---\n\n**Q3. What does a high intra-class correlation coefficient (ICC) of the null model indicate?**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_W12_Q3\" onsubmit=\"return validate_form_W12_Q3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_W12_Q3\" id=\"answer_W12_Q3_1\" value=\"The outcome variable is normally distributed\"/>\nThe outcome variable is normally distributed\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q3\" id=\"answer_W12_Q3_2\" value=\"A substantial share of the total variance is due to differences between the grouping units, so including the random effect is warranted\"/>\nA substantial share of the total variance is due to differences between the grouping units, so including the random effect is warranted\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q3\" id=\"answer_W12_Q3_3\" value=\"The fixed effects are all significant\"/>\nThe fixed effects are all significant\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_W12_Q3\" id=\"answer_W12_Q3_4\" value=\"The model suffers from collinearity\"/>\nThe model suffers from collinearity\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_W12_Q3\"></div>\n</form>\n<script>function validate_form_W12_Q3() {var x, text; var x = document.forms['form_W12_Q3']['answer_W12_Q3'].value;if (x == 'A substantial share of the total variance is due to differences between the grouping units, so including the random effect is warranted'){text = 'Correct! The ICC is the proportion of total variance attributable to the grouping structure. A high ICC means observations within the same group are much more similar to each other than to observations from other groups - exactly the non-independence that random effects are designed to handle.';} else {text = 'The ICC partitions the variance: how much of it lies <em>between</em> the groups?';} document.getElementById('result_W12_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_W12_Q1').innerText == 'Correct! The 50 trials per participant are correlated - fast participants are fast throughout. Treating them as 2,000 independent observations (pseudoreplication) deflates standard errors and produces spuriously significant results. A random intercept for participant fixes this.'; res2 = document.getElementById('result_W12_Q2').innerText == 'Correct! (1 | Genre) gives each genre its own random intercept, treating genres as a sample of grouping units whose baseline differences must be accounted for. Including Genre as a fixed effect instead would estimate a separate coefficient for every genre - a different research question.'; res3 = document.getElementById('result_W12_Q3').innerText == 'Correct! The ICC is the proportion of total variance attributable to the grouping structure. A high ICC means observations within the same group are much more similar to each other than to observations from other groups - exactly the non-independence that random effects are designed to handle.';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n[Back to top](#week12)\n\n\n\n",
    "supporting": [
      "12-week12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}