<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Simple Linear Regression – SLAT7855 – Statistics for Linguists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-week10.html" rel="next">
<link href="./08-week8.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-baf7457b58093534c7052efdef5f4d86.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-week9.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SLAT7855 – Statistics for Linguists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Hypotheses and Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Significance, Probability and the Normal Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting Started with R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with Tables in R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic Inferential Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-week9.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-week10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">(Different) Types of Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mixed-Effects Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Tree-Based Models, Machine Learning, and AI</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-basic-principle" id="toc-the-basic-principle" class="nav-link active" data-scroll-target="#the-basic-principle"><span class="header-section-number">9.1</span> The Basic Principle</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">9.2</span> Assumptions</a></li>
  <li><a href="#example-1-preposition-use-across-real-time" id="toc-example-1-preposition-use-across-real-time" class="nav-link" data-scroll-target="#example-1-preposition-use-across-real-time"><span class="header-section-number">9.3</span> Example 1: Preposition Use across Real-Time</a></li>
  <li><a href="#example-2-teaching-styles" id="toc-example-2-teaching-styles" class="nav-link" data-scroll-target="#example-2-teaching-styles"><span class="header-section-number">9.4</span> Example 2: Teaching Styles</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="week9" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What This Session Covers
</div>
</div>
<div class="callout-body-container callout-body">
<p>This session introduces the workhorse of statistical modeling: linear regression with a single predictor.</p>
<ol type="1">
<li><strong>The basic principle</strong> - fitting a line that minimizes squared residuals</li>
<li><strong>Assumptions</strong> - linearity, normality of residuals, homoscedasticity, independence</li>
<li><strong>Example 1</strong> - preposition use across real time (numeric predictor)</li>
<li><strong>Model diagnostics</strong> - <code>performance::check_model()</code> and formal checks</li>
<li><strong>Example 2</strong> - teaching styles (categorical predictor)</li>
<li><strong>Interpreting and reporting</strong> - coefficients, R², model comparison, and summary tables</li>
</ol>
</div>
</div>
<p>This tutorial introduces regression analysis (also called regression modeling). Regression models are among the most widely used quantitative methods in the language sciences to assess if and how predictors (variables or interactions between variables) correlate with a certain response.</p>
<p>Regression models are so popular because they can</p>
<ul>
<li><p>incorporate many predictors in a single model (multivariate: allows to test the impact of one predictor while the impact of (all) other predictors is controlled for)</p></li>
<li><p>extremely flexible and and can be fitted to different types of predictors and dependent variables</p></li>
<li><p>provide output that can be easily interpreted</p></li>
<li><p>conceptually relative simple and not overly complex from a mathematical perspective</p></li>
</ul>
<p>The major difference between these types of models is that they take different types of dependent variables: linear regressions take numeric, logistic regressions take nominal variables, ordinal regressions take ordinal variables, and Poisson regressions take dependent variables that reflect counts of (rare) events.</p>
<section id="the-basic-principle" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="the-basic-principle"><span class="header-section-number">9.1</span> The Basic Principle</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key concept: Residuals
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <em>residual</em> is the difference between an observed value and the value the model predicts for that observation - the vertical distance between a data point and the regression line. Residuals are the raw material of regression: the line is chosen to minimize the sum of <em>squared</em> residuals, the model assumptions are checked <em>on the residuals</em> (normality, constant variance), and the size of the residuals determines how well the model fits (R² measures the proportion of variance that is <em>not</em> left in the residuals).</p>
</div>
</div>
<p>The idea behind regression analysis is expressed formally in the equation below where <span class="math inline">\(f_{(x)}\)</span> is the <span class="math inline">\(y\)</span>-value we want to predict, <span class="math inline">\(\alpha\)</span> is the intercept (the point where the regression line crosses the <span class="math inline">\(y\)</span>-axis), <span class="math inline">\(\beta\)</span> is the coefficient (the slope of the regression line).</p>
<p><span class="math display">\[\begin{equation}
f_{(x)} = \alpha + \beta_{i}x + \epsilon
\end{equation}\]</span></p>
<p>To understand what this means, let us imagine that we have collected information about the how tall people are and what they weigh. Now we want to predict the weight of people of a certain height - let’s say 180cm.</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-95cd9d6a{table-layout:auto;width:75%;}.cl-95c32ea2{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-95c32ec0{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-95c75644{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-95c77660{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7766a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77674{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7767e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c7767f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77680{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77688{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-95c77689{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-95cd9d6a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-95c77660"><p class="cl-95c75644"><span class="cl-95c32ea2">Height</span></p></th><th class="cl-95c7766a"><p class="cl-95c75644"><span class="cl-95c32ea2">Weight</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-95c77674"><p class="cl-95c75644"><span class="cl-95c32ec0">173</span></p></td><td class="cl-95c7767e"><p class="cl-95c75644"><span class="cl-95c32ec0">80</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c7767f"><p class="cl-95c75644"><span class="cl-95c32ec0">169</span></p></td><td class="cl-95c77680"><p class="cl-95c75644"><span class="cl-95c32ec0">68</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c77674"><p class="cl-95c75644"><span class="cl-95c32ec0">176</span></p></td><td class="cl-95c7767e"><p class="cl-95c75644"><span class="cl-95c32ec0">72</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c7767f"><p class="cl-95c75644"><span class="cl-95c32ec0">166</span></p></td><td class="cl-95c77680"><p class="cl-95c75644"><span class="cl-95c32ec0">75</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c77674"><p class="cl-95c75644"><span class="cl-95c32ec0">161</span></p></td><td class="cl-95c7767e"><p class="cl-95c75644"><span class="cl-95c32ec0">70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c7767f"><p class="cl-95c75644"><span class="cl-95c32ec0">164</span></p></td><td class="cl-95c77680"><p class="cl-95c75644"><span class="cl-95c32ec0">65</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c77674"><p class="cl-95c75644"><span class="cl-95c32ec0">160</span></p></td><td class="cl-95c7767e"><p class="cl-95c75644"><span class="cl-95c32ec0">62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c7767f"><p class="cl-95c75644"><span class="cl-95c32ec0">158</span></p></td><td class="cl-95c77680"><p class="cl-95c75644"><span class="cl-95c32ec0">60</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c77674"><p class="cl-95c75644"><span class="cl-95c32ec0">180</span></p></td><td class="cl-95c7767e"><p class="cl-95c75644"><span class="cl-95c32ec0">85</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-95c77688"><p class="cl-95c75644"><span class="cl-95c32ec0">187</span></p></td><td class="cl-95c77689"><p class="cl-95c75644"><span class="cl-95c32ec0">92</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>We can run a simple linear regression on the data and we get the following output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model for upper panels</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(Weight <span class="sc">~</span> Height, <span class="at">data =</span> df)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weight ~ Height, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.3939 -2.3610  0.0096  3.1142  5.4453 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -93.7759    27.0379  -3.468 0.008464 ** 
Height        0.9839     0.1594   6.173 0.000267 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.532 on 8 degrees of freedom
Multiple R-squared:  0.8265,    Adjusted R-squared:  0.8048 
F-statistic: 38.11 on 1 and 8 DF,  p-value: 0.0002671</code></pre>
</div>
</div>
<p>To estimate how much some weights who is 180cm tall, we would multiply the coefficient (slope of the line) with 180 (<span class="math inline">\(x\)</span>) and add the value of the intercept (point where line crosses the <span class="math inline">\(y\)</span>-axis). If we plug in the numbers from the regression model below, we get</p>
<p><span class="math display">\[\begin{equation}
-93.77 + 0.98 ∗ 180 = 83.33 (kg)
\end{equation}\]</span></p>
<p>A person who is 180cm tall is predicted to weigh 83.33kg. Thus, the predictions of the weights are visualized as the red line in the figure below. Such lines are called <em>regression lines</em>. Regression lines are those lines where the sum of the red lines should be minimal. The slope of the regression line is called <em>coefficient</em> and the point where the regression line crosses the y-axis at x = 0 is called the <em>intercept</em>. Other important concepts in regression analysis are <em>variance</em> and <em>residuals</em>. <em>Residuals</em> are the distance between the line and the points (the red lines) and it is also called <em>variance</em>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/intro01-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Some words about the plots in the figure above: the upper left panel shows the raw observed data (black dots). The upper right panel shows the mean weight (blue line) and the residuals (in red). residuals are the distances from the expected or predicted values to the observed values (in this case the mean is the most most basic model which we use to predict values while the observed values simply represent the actual data points). The lower left panel shows observed values and the regression line, i.e, that line which, when drawn through the data points, will have the lowest sum of residuals. The lower right panel shows the regression line and the residuals, i.e.&nbsp;the distances between the expected or predicted values to the actual observed values (in red). Note that the sum of residuals in the lower right panel is much smaller than the sum of residuals in the upper right panel. This suggest that considering Height is a good idea as it explains a substantive amount of residual error and reduces the sum of residuals (or variance).</p>
</section>
<section id="assumptions" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">9.2</span> Assumptions</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key concept: R² (R-squared)
</div>
</div>
<div class="callout-body-container callout-body">
<p>R² is the proportion of the variance in the outcome that the model accounts for, ranging from 0 (the model explains nothing beyond the mean) to 1 (perfect fit). An R² of .30 means the predictor accounts for 30% of the variability in the outcome. In multiple regression, report the <em>adjusted</em> R², which corrects for the number of predictors - plain R² can only ever increase when predictors are added, even useless ones.</p>
</div>
</div>
<p>Linear regression makes several assumptions about the data. If these assumptions are not met, then this can mean that results of the model can be misleading, inaccurate, or plainly wrong. All these assumptions and potential problems can be checked by producing some diagnostic plots visualizing the residual errors (we will do this below). The assumptions of regression models are:</p>
<ul>
<li><strong>Linearity</strong>: The relationship between the predictor (x) and the outcome (y) is assumed to be linear.<br>
</li>
<li><strong>Normality of residuals</strong>: The residual errors are assumed to be normally distributed.<br>
</li>
<li><strong>Homogeneity</strong>: The residuals are assumed to have a constant variance (homoscedasticity)<br>
</li>
<li><strong>Independence of residuals</strong>: The residuals are assumed not to be correlated.</li>
</ul>
<p>You should check whether or not these assumptions hold true. Potential problems include:</p>
<ul>
<li><strong>Non-linearity</strong>: The predictor affects the dependent variable differently for different values.<br>
</li>
<li><strong>Heteroscedasticity</strong>: Non-constant variance of error terms (this means that at least one other important predictor is not included in the model).</li>
<li><strong>Presence of influential observations</strong>:
<ul>
<li><strong>Outliers</strong>: extreme values in the dependent variable<br>
</li>
<li><strong>High-leverage points</strong>: extreme values in the predictors</li>
</ul></li>
</ul>
<p>Now that we are familiar with the basic principle of regression modeling - i.e.&nbsp;finding the line through data that has the smallest sum of residuals, we will apply this to a linguistic example.</p>
</section>
<section id="example-1-preposition-use-across-real-time" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="example-1-preposition-use-across-real-time"><span class="header-section-number">9.3</span> Example 1: Preposition Use across Real-Time</h2>
<p>We will now turn to our first example. In this example, we will investigate whether the frequency of prepositions has changed from Middle English to Late Modern English. The reasoning behind this example is that Old English was highly synthetic compared with Present-Day English which comparatively analytic. In other words, while Old English speakers used case to indicate syntactic relations, speakers of Present-Day English use word order and prepositions to indicate syntactic relationships. This means that the loss of case had to be compensated by different strategies and maybe these strategies continued to develop and increase in frequency even after the change from synthetic to analytic had been mostly accomplished. And this prolonged change in compensatory strategies is what this example will focus on.</p>
<p>The analysis is based on data extracted from the <em>Penn Corpora of Historical English</em> (see http://www.ling.upenn.edu/hist-corpora/), that consists of 603 texts written between 1125 and 1900. In preparation of this example, all elements that were part-of-speech tagged as prepositions were extracted from the PennCorpora.</p>
<p>Then, the relative frequencies (per 1,000 words) of prepositions per text were calculated. This frequency of prepositions per 1,000 words represents our dependent variable. In a next step, the date when each letter had been written was extracted. The resulting two vectors were combined into a table which thus contained for each text, when it was written (independent variable) and its relative frequency of prepositions (dependent or outcome variable).</p>
<p>A regression analysis will follow the steps described below:</p>
<ol type="1">
<li><p>Extraction and processing of the data</p></li>
<li><p>Data visualization</p></li>
<li><p>Applying the regression analysis to the data</p></li>
<li><p>Diagnosing the regression model and checking whether or not basic model assumptions have been violated.</p></li>
</ol>
<p>In a first step, we load and inspect the data to get a first impression of its properties.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>slrdata  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">"https://slcladal.github.io/data/sld.rda"</span>, <span class="st">"rb"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-97f0edcc{table-layout:auto;width:75%;}.cl-97e437f8{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97e4380c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97e90f44{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-97e90f58{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-97e94bbc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bc6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bd0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bd1{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bda{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bdb{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94be4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94be5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bee{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94bf8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c02{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c03{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c0e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97e94c16{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-97f0edcc"><thead><tr style="overflow-wrap:break-word;"><th class="cl-97e94bbc"><p class="cl-97e90f44"><span class="cl-97e437f8">Date</span></p></th><th class="cl-97e94bc6"><p class="cl-97e90f58"><span class="cl-97e437f8">Genre</span></p></th><th class="cl-97e94bc6"><p class="cl-97e90f58"><span class="cl-97e437f8">Text</span></p></th><th class="cl-97e94bd0"><p class="cl-97e90f44"><span class="cl-97e437f8">Prepositions</span></p></th><th class="cl-97e94bd1"><p class="cl-97e90f58"><span class="cl-97e437f8">Region</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,736</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Science</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">albin</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">166.01</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,711</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Education</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">anon</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">139.86</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,808</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">PrivateLetter</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">austen</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">130.78</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,878</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Education</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">bain</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">151.29</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,743</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Education</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">barclay</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">145.72</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,908</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Education</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">benson</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">120.77</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,906</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Diary</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">benson</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">119.17</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,897</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Philosophy</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">boethja</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">132.96</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,785</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Philosophy</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">boethri</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">130.49</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,776</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Diary</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">boswell</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">135.94</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,905</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Travel</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">bradley</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">154.20</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,711</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Education</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">brightland</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">149.14</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bda"><p class="cl-97e90f44"><span class="cl-97e4380c">1,762</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">Sermon</span></p></td><td class="cl-97e94bdb"><p class="cl-97e90f58"><span class="cl-97e4380c">burton</span></p></td><td class="cl-97e94be4"><p class="cl-97e90f44"><span class="cl-97e4380c">159.71</span></p></td><td class="cl-97e94be5"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94bee"><p class="cl-97e90f44"><span class="cl-97e4380c">1,726</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">Sermon</span></p></td><td class="cl-97e94bf8"><p class="cl-97e90f58"><span class="cl-97e4380c">butler</span></p></td><td class="cl-97e94c02"><p class="cl-97e90f44"><span class="cl-97e4380c">157.49</span></p></td><td class="cl-97e94c03"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-97e94c0c"><p class="cl-97e90f44"><span class="cl-97e4380c">1,835</span></p></td><td class="cl-97e94c0d"><p class="cl-97e90f58"><span class="cl-97e4380c">PrivateLetter</span></p></td><td class="cl-97e94c0d"><p class="cl-97e90f58"><span class="cl-97e4380c">carlyle</span></p></td><td class="cl-97e94c0e"><p class="cl-97e90f44"><span class="cl-97e4380c">124.16</span></p></td><td class="cl-97e94c16"><p class="cl-97e90f58"><span class="cl-97e4380c">North</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Inspecting the data is very important because it can happen that a data set may not load completely or that variables which should be numeric have been converted to character variables. If unchecked, then such issues could go unnoticed and cause trouble.</p>
<p>We will now plot the data to get a better understanding of what the data looks like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(slrdata, <span class="fu">aes</span>(Date, Prepositions)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Prepositions per 1,000 words"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Before beginning with the regression analysis, we will center the year. We center the values of year by subtracting each value from the mean of year. This can be useful when dealing with numeric variables because if we did not center year, we would get estimated values for year 0 (a year when English did not even exist yet). If a variable is centered, the regression provides estimates of the model refer to the mean of that numeric variable. In other words, centering can be very helpful, especially with respect to the interpretation of the results that regression models report.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># center date</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>slrdata<span class="sc">$</span>Date <span class="ot">&lt;-</span> slrdata<span class="sc">$</span>Date <span class="sc">-</span> <span class="fu">mean</span>(slrdata<span class="sc">$</span>Date) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will now begin the regression analysis by generating a first regression model and inspect its results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create initial model</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>m1.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prepositions <span class="sc">~</span> Date, <span class="at">data =</span> slrdata)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect results</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prepositions ~ Date, data = slrdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-69.101 -13.855   0.578  13.321  62.858 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.322e+02  8.386e-01 157.625   &lt;2e-16 ***
Date        1.732e-02  7.267e-03   2.383   0.0175 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.43 on 535 degrees of freedom
Multiple R-squared:  0.01051,   Adjusted R-squared:  0.008657 
F-statistic: 5.681 on 1 and 535 DF,  p-value: 0.0175</code></pre>
</div>
</div>
<p>The summary output starts by repeating the regression equation. Then, the model provides the distribution of the residuals. The residuals should be distributed normally with the absolute values of the Min and Max as well as the 1Q (first quartile) and 3Q (third quartile) being similar or ideally identical. In our case, the values are very similar which suggests that the residuals are distributed evenly and follow a normal distribution. The next part of the report is the coefficients table. The estimate for the intercept is the value of y at x = 0. The estimate for Date represents the slope of the regression line and tells us that with each year, the predicted frequency of prepositions increase by .01732 prepositions. The t-value is the Estimate divided by the standard error (Std. Error). Based on the t-value, the p-value can be calculated manually as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use pt function (which uses t-values and the degrees of freedom)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.383</span>, <span class="fu">nrow</span>(slrdata)<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01751964</code></pre>
</div>
</div>
<p>The R<sup>2</sup>-values tell us how much variance is explained by our model. The baseline value represents a model that uses merely the mean. 0.0105 means that our model explains only 1.05 percent of the variance (0.010 x 100) - which is a tiny amount. The problem of the multiple R<sup>2</sup> is that it will increase even if we add variables that explain almost no variance. Hence, multiple R<sup>2</sup> encourages the inclusion of <em>junk</em> variables.</p>
<p><span class="math display">\[\begin{equation}
R^2 = R^2_{multiple} = 1 - \frac{\sum (y_i - \hat{y_i})^2}{\sum (y_i - \bar y)^2}
\end{equation}\]</span></p>
<p>The adjusted R<sup>2</sup>-value takes the number of predictors into account and, thus, the adjusted R<sup>2</sup> will always be lower than the multiple R<sup>2</sup>. This is so because the adjusted R<sup>2</sup> penalizes models for having predictors. The equation for the adjusted R<sup>2</sup> below shows that the amount of variance that is explained by all the variables in the model (the top part of the fraction) must outweigh the inclusion of the number of variables (k) (lower part of the fraction). Thus, the adjusted R<sup>2</sup> will decrease when variables are added that explain little or even no variance while it will increase if variables are added that explain a lot of variance.</p>
<p><span class="math display">\[\begin{equation}
R^2_{adjusted} = 1 - (\frac{(1 - R^2)(n - 1)}{n - k - 1})
\end{equation}\]</span></p>
<p>If there is a big difference between the two R<sup>2</sup>-values, then the model contains (many) predictors that do not explain much variance which is not good. The F-statistic and the associated p-value tell us that the model, despite explaining almost no variance, is still significantly better than an intercept-only base-line model (or using the overall mean to predict the frequency of prepositions per text).</p>
<p>We can test this and also see where the F-values comes from by comparing the</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create intercept-only base-line model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>m0.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prepositions <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> slrdata)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the base-line and the more saturated model</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1.lm, m0.lm, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Prepositions ~ Date
Model 2: Prepositions ~ 1
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)  
1    535 202058                             
2    536 204204 -1   -2145.6 5.6809 0.0175 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The F- and p-values are exactly those reported by the summary which shows where the F-values comes from and what it means; namely it denote the difference between the base-line and the more saturated model.</p>
<p>The degrees of freedom associated with the residual standard error are the number of cases in the model minus the number of predictors (including the intercept). The residual standard error is square root of the sum of the squared residuals of the model divided by the degrees of freedom. Have a look at he following to clear this up:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DF = N - number of predictors (including intercept)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>DegreesOfFreedom <span class="ot">&lt;-</span> <span class="fu">nrow</span>(slrdata)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">coef</span>(m1.lm))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># sum of the squared residuals</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>SumSquaredResiduals <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(m1.lm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual Standard Error</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(SumSquaredResiduals<span class="sc">/</span>DegreesOfFreedom); DegreesOfFreedom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.43396</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 535</code></pre>
</div>
</div>
<p>We will now check the model assumptions using diagnostic plots. To do this, we use the <code>check_model</code> function from the <code>performance</code> package <span class="citation" data-cites="performance">(<a href="#ref-performance" role="doc-biblioref">Lüdecke et al. 2021</a>)</span> which generates a panel of diagnostic plots and - very conveniently - tells us in the subtitle of each panel what we should be looking for.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate diagnostic plots</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will go through the panels one by one:</p>
<p><strong>Posterior Predictive Check</strong></p>
<p>This plot compares the distribution of the observed data (green line) with distributions of data simulated from the fitted model (blue lines). If the model captures the data well, the simulated distributions should closely resemble the observed distribution. Strong discrepancies indicate that the model fails to reproduce important characteristics of the data (e.g., skewness or multimodality).</p>
<p><strong>Linearity</strong></p>
<p>This plot is used to check the linearity assumption: the reference line should be flat and horizontal. If a trend becomes visible in the line (e.g., a curve or a zigzag pattern), the relationship between predictor(s) and outcome is not adequately captured by a straight line and the model is problematic (in such cases, transforming variables or adding non-linear terms can help).</p>
<p><strong>Homogeneity of Variance</strong></p>
<p>This plot is used to check the homogeneity of variance of the residuals (homoscedasticity): a flat, horizontal reference line with equally spread points indicates homoscedasticity. Homoscedasticity means that the variance of the residuals remains constant and does not correlate with any independent variable. If there is a trend in the line, we are dealing with heteroscedasticity, that is, a correlation between the fitted values and the spread of the residuals, which is very problematic for regressions.</p>
<p><strong>Influential Observations</strong></p>
<p>This plot is used to identify influential cases that disproportionately affect the regression (this would be problematic): points should lie within the dashed contour lines. The contours are based on Cook’s distance, which shows how much the regression changes when the model is re-fitted without that data point. If influential data points are present, they should be inspected and either down-weighted (e.g., by fitting a robust regression) or, if they represent errors, removed. In addition to the visual check, we can formally test for influential observations using the <code>check_outliers</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check for influential observations</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_outliers</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: No outliers detected.
- Based on the following method and threshold: cook (0.7).
- For variable: (Whole model)</code></pre>
</div>
</div>
<p><strong>Normality of Residuals</strong></p>
<p>This plot is used to examine whether the residuals are normally distributed: it is good if the points follow the straight reference line. If the points fall on the line, the residuals follow a normal distribution. If the points deviate from the line at the top and bottom, this shows that the model does not predict small and large values well and that it therefore does not have a good fit. We can complement the visual checks with formal tests of normality and heteroscedasticity as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># formal test of normality of residuals</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_normality</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.873).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># formal test of heteroscedasticity</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_heteroscedasticity</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.272).</code></pre>
</div>
</div>
<p>In our case, the diagnostics do not indicate any severe violations of the model assumptions and we can proceed with the interpretation of the model.</p>
<p>Now, we plot the effect reported by the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate summary table</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_model</span>(m1.lm, <span class="at">type =</span> <span class="st">"pred"</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Date"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr18a-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We end the current analysis by summarizing the results of the regression analysis using the <code>tab_model</code> function from the <code>sjPlot</code> package <span class="citation" data-cites="sjPlot">(<a href="#ref-sjPlot" role="doc-biblioref">Lüdecke 2021</a>)</span> (as is shown below).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate summary table</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m1.lm) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Prepositions</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">132.19</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">130.54&nbsp;–&nbsp;133.84</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Date</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.02</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00&nbsp;–&nbsp;0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.017</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">537</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.011 / 0.009</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Typically, the results of regression analyses are presented in such tables as they include all important measures of model quality and significance, as well as the magnitude of the effects.</p>
<p>In addition, the results of simple linear regressions should be summarized in writing. We can use the <code>reports</code> package <span class="citation" data-cites="report">(<a href="#ref-report" role="doc-biblioref">Makowski et al. 2021</a>)</span> to summarize the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Prepositions with
Date (formula: Prepositions ~ Date). The model explains a statistically
significant and very weak proportion of variance (R2 = 0.01, F(1, 535) = 5.68,
p = 0.017, adj. R2 = 8.66e-03). The model's intercept, corresponding to Date =
0, is at 132.19 (95% CI [130.54, 133.84], t(535) = 157.62, p &lt; .001). Within
this model:

  - The effect of Date is statistically significant and positive (beta = 0.02,
95% CI [3.05e-03, 0.03], t(535) = 2.38, p = 0.017; Std. beta = 0.10, 95% CI
[0.02, 0.19])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.</code></pre>
</div>
</div>
<p>We can use this output to write up a final report:</p>
<blockquote class="blockquote">
<p>A simple linear regression has been fitted to the data. A visual assessment of the model diagnostic graphics did not indicate any problematic or disproportionately influential data points (outliers) and performed significantly better compared to an intercept-only base line model but only explained .87 percent of the variance (adjusted R<sup>2</sup>: .0087, F-statistic (1, 535): 5,68, p-value: 0.0175*). The final minimal adequate linear regression model is based on 537 data points and confirms a significant and positive correlation between the year in which the text was written and the relative frequency of prepositions (coefficient estimate: .02 (standardized : 0.10, 95% CI [0.02, 0.19]), SE: 0.01, t-value<sub>535</sub>: 2.38, p-value: .0175*). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</p>
</blockquote>
</section>
<section id="example-2-teaching-styles" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="example-2-teaching-styles"><span class="header-section-number">9.4</span> Example 2: Teaching Styles</h2>
<p>In the previous example, we dealt with two numeric variables, while the following example deals with a categorical independent variable and a numeric dependent variable. The ability for regressions to handle very different types of variables makes regressions a widely used and robust method of analysis.</p>
<p>In this example, we are dealing with two groups of students that have been randomly assigned to be exposed to different teaching methods. Both groups undergo a language learning test after the lesson with a maximum score of 20 points.</p>
<p>The question that we will try to answer is whether the students in group A have performed significantly better than those in group B which would indicate that the teaching method to which group A was exposed works better than the teaching method to which group B was exposed.</p>
<p>Let’s move on to implementing the regression in R. In a first step, we load the data set and inspect its structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>slrdata2  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">"https://slcladal.github.io/data/sgd.rda"</span>, <span class="st">"rb"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">factor</span>(Group))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-9bf888bc{table-layout:auto;width:75%;}.cl-9becb708{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9becb71c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9bf18332{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9bf18346{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9bf1a92a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a93e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a948{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a952{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a95c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a95d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a966{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9bf1a970{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-9bf888bc"><thead><tr style="overflow-wrap:break-word;"><th class="cl-9bf1a92a"><p class="cl-9bf18332"><span class="cl-9becb708">Group</span></p></th><th class="cl-9bf1a93e"><p class="cl-9bf18346"><span class="cl-9becb708">Score</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a948"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a952"><p class="cl-9bf18346"><span class="cl-9becb71c">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a95c"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a95d"><p class="cl-9bf18346"><span class="cl-9becb71c">12</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a948"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a952"><p class="cl-9bf18346"><span class="cl-9becb71c">11</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a95c"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a95d"><p class="cl-9bf18346"><span class="cl-9becb71c">18</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a948"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a952"><p class="cl-9bf18346"><span class="cl-9becb71c">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9bf1a966"><p class="cl-9bf18332"><span class="cl-9becb71c">A</span></p></td><td class="cl-9bf1a970"><p class="cl-9bf18346"><span class="cl-9becb71c">15</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>We also inspect the structure of the data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   60 obs. of  2 variables:
 $ Group: Factor w/ 2 levels "A","B": 1 1 1 1 1 1 1 1 1 1 ...
 $ Score: int  15 12 11 18 15 15 9 19 14 13 ...</code></pre>
</div>
</div>
<p>Now, we graphically display the data. In this case, a boxplot represents a good way to visualize the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract means</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>slrdata2 <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Group) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Score), <span class="dv">1</span>), <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Score), <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Group, Score)) <span class="sc">+</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="fu">c</span>(<span class="st">"orange"</span>, <span class="st">"darkgray"</span>)) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"M = "</span>, Mean, <span class="at">sep =</span> <span class="st">""</span>), <span class="at">y =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"SD = "</span>, SD, <span class="at">sep =</span> <span class="st">""</span>), <span class="at">y =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Group"</span>, <span class="at">y =</span> <span class="st">"Test score (Points)"</span>) <span class="sc">+</span>   </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>)) <span class="sc">+</span>  </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>)                </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The data indicate that group A did significantly better than group B. We will test this impression by generating the regression model and creating the model and extracting the model summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate regression model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>m2.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Group, <span class="at">data =</span> slrdata2) </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect results</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.lm)                             </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Group, data = slrdata2)

Residuals:
   Min     1Q Median     3Q    Max 
-6.767 -1.933  0.150  2.067  6.233 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.9333     0.5346  27.935  &lt; 2e-16 ***
GroupB       -3.1667     0.7560  -4.189 9.67e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.928 on 58 degrees of freedom
Multiple R-squared:  0.2322,    Adjusted R-squared:  0.219 
F-statistic: 17.55 on 1 and 58 DF,  p-value: 9.669e-05</code></pre>
</div>
</div>
<p>The model summary reports that Group A performed significantly better compared with Group B. This is shown by the fact that the p-value (the value in the column with the header (Pr(&gt;|t|)) is smaller than .001 as indicated by the three * after the p-values). Also, the negative Estimate for Group B indicates that Group B has lower scores than Group A. We will now generate the diagnostic graphics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate diagnostic plots</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(m2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These diagnostics also show no problems (note that with a categorical predictor, the fitted values fall into just two groups, which is why the points line up in two vertical bands). We continue by visualizing the results of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate summary table</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_model</span>(m2.lm, <span class="at">type =</span> <span class="st">"pred"</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Group"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-week9_files/figure-html/slr26a-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, we summarize the results of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate summary table</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m2.lm) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Score</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">14.93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13.86&nbsp;–&nbsp;16.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Group [B]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-3.17</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-4.68&nbsp;–&nbsp;-1.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">60</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.232 / 0.219</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We can use the <code>reports</code> package <span class="citation" data-cites="report">(<a href="#ref-report" role="doc-biblioref">Makowski et al. 2021</a>)</span> to prepare the write-up of the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Score with Group
(formula: Score ~ Group). The model explains a statistically significant and
moderate proportion of variance (R2 = 0.23, F(1, 58) = 17.55, p &lt; .001, adj. R2
= 0.22). The model's intercept, corresponding to Group = A, is at 14.93 (95% CI
[13.86, 16.00], t(58) = 27.94, p &lt; .001). Within this model:

  - The effect of Group [B] is statistically significant and negative (beta =
-3.17, 95% CI [-4.68, -1.65], t(58) = -4.19, p &lt; .001; Std. beta = -0.96, 95%
CI [-1.41, -0.50])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.</code></pre>
</div>
</div>
<p>We can use this output to write up a final report:</p>
<blockquote class="blockquote">
<p>A simple linear regression was fitted to the data. A visual assessment of the model diagnostics did not indicate any problematic or disproportionately influential data points (outliers). The final linear regression model is based on 60 data points, performed significantly better than an intercept-only base line model (F (1, 58): 17.55, p-value &lt;. 001<sup><span class="math inline">\(***\)</span></sup>), and reported that the model explained 21.9 percent of variance which confirmed a good model fit. According to this final model, group A scored significantly better on the language learning test than group B (coefficient: -3.17, 95% CI [-4.68, -1.65], Std. : -0.96, 95% CI [-1.41, -0.50], SE: 0.48, t-value<sub>58</sub>: -4.19, p-value &lt;. 001<sup><span class="math inline">\(***\)</span></sup>). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercises: Simple Linear Regression
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p><strong>Q1. In a regression predicting reaction time (in ms) from word frequency, the slope coefficient is -25. What does this mean?</strong></p>
<div class="cell">
<div class="cell-output-display">
<form name="form_W9_Q1" onsubmit="return validate_form_W9_Q1()" method="post">
<label>
<input type="radio" name="answer_W9_Q1" id="answer_W9_Q1_1" value="25 observations were excluded from the model">
25 observations were excluded from the model
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q1" id="answer_W9_Q1_2" value="Reaction times are 25% faster for frequent words">
Reaction times are 25% faster for frequent words
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q1" id="answer_W9_Q1_3" value="The model explains 25% of the variance">
The model explains 25% of the variance
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q1" id="answer_W9_Q1_4" value="For each one-unit increase in word frequency, predicted reaction time decreases by 25 ms">
For each one-unit increase in word frequency, predicted reaction time decreases by 25 ms
</label>
<br>
<input type="submit" value="Check answer">
<div id="result_W9_Q1"></div>
</form>
<script>function validate_form_W9_Q1() {var x, text; var x = document.forms['form_W9_Q1']['answer_W9_Q1'].value;if (x == 'For each one-unit increase in word frequency, predicted reaction time decreases by 25 ms'){text = 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.';} else {text = 'The slope tells you how much the <em>outcome</em> changes when the <em>predictor</em> increases by one unit.';} document.getElementById('result_W9_Q1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){
         element = document.getElementById('checkdown_final_score');
         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.';text = res1;element.innerHTML = text;
         return false;
         }}</script>
</div>
</div>
<hr>
<p><strong>Q2. What is a residual?</strong></p>
<div class="cell">
<div class="cell-output-display">
<form name="form_W9_Q2" onsubmit="return validate_form_W9_Q2()" method="post">
<label>
<input type="radio" name="answer_W9_Q2" id="answer_W9_Q2_1" value="The proportion of explained variance">
The proportion of explained variance
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q2" id="answer_W9_Q2_2" value="The number of data points in the model">
The number of data points in the model
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q2" id="answer_W9_Q2_3" value="The difference between an observed value and the value predicted by the model">
The difference between an observed value and the value predicted by the model
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q2" id="answer_W9_Q2_4" value="The slope of the regression line">
The slope of the regression line
</label>
<br>
<input type="submit" value="Check answer">
<div id="result_W9_Q2"></div>
</form>
<script>function validate_form_W9_Q2() {var x, text; var x = document.forms['form_W9_Q2']['answer_W9_Q2'].value;if (x == 'The difference between an observed value and the value predicted by the model'){text = 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.';} else {text = 'Think of the vertical distance between a data point and the regression line.';} document.getElementById('result_W9_Q2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){
         element = document.getElementById('checkdown_final_score');
         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.'; res2 = document.getElementById('result_W9_Q2').innerText == 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.';text = res1 + res2;element.innerHTML = text;
         return false;
         }}</script>
</div>
</div>
<hr>
<p><strong>Q3. The diagnostic plots show residuals that fan out - small for low fitted values and increasingly spread out for high fitted values. Which assumption is violated?</strong></p>
<div class="cell">
<div class="cell-output-display">
<form name="form_W9_Q3" onsubmit="return validate_form_W9_Q3()" method="post">
<label>
<input type="radio" name="answer_W9_Q3" id="answer_W9_Q3_1" value="Homoscedasticity (constant variance of residuals)">
Homoscedasticity (constant variance of residuals)
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q3" id="answer_W9_Q3_2" value="Independence of the predictor and the intercept">
Independence of the predictor and the intercept
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q3" id="answer_W9_Q3_3" value="Normality of the predictor">
Normality of the predictor
</label>
<br>
<label>
<input type="radio" name="answer_W9_Q3" id="answer_W9_Q3_4" value="The assumption that R² is above .5">
The assumption that R² is above .5
</label>
<br>
<input type="submit" value="Check answer">
<div id="result_W9_Q3"></div>
</form>
<script>function validate_form_W9_Q3() {var x, text; var x = document.forms['form_W9_Q3']['answer_W9_Q3'].value;if (x == 'Homoscedasticity (constant variance of residuals)'){text = 'Correct! A funnel shape means the residual variance grows with the fitted values - heteroscedasticity. Standard errors and p-values become unreliable; transformations or robust standard errors can help.';} else {text = 'A funnel-shaped residual plot indicates that the residual <em>variance</em> is not constant.';} document.getElementById('result_W9_Q3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){
         element = document.getElementById('checkdown_final_score');
         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_W9_Q1').innerText == 'Correct! The slope is the predicted change in the outcome per one-unit change in the predictor. The negative sign means higher frequency predicts faster (lower) reaction times.'; res2 = document.getElementById('result_W9_Q2').innerText == 'Correct! Residuals are the model’s errors for the individual observations - and both model fitting (least squares) and assumption checking operate on them.'; res3 = document.getElementById('result_W9_Q3').innerText == 'Correct! A funnel shape means the residual variance grows with the fitted values - heteroscedasticity. Standard errors and p-values become unreliable; transformations or robust standard errors can help.';text = res1 + res2 + res3;element.innerHTML = text;
         return false;
         }}</script>
</div>
</div>
<p><a href="#week9">Back to top</a></p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-sjPlot" class="csl-entry" role="listitem">
Lüdecke, Daniel. 2021. <em>sjPlot: Data Visualization for Statistics in Social Science</em>. <a href="https://CRAN.R-project.org/package=sjPlot">https://CRAN.R-project.org/package=sjPlot</a>.
</div>
<div id="ref-performance" class="csl-entry" role="listitem">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, and Dominique Makowski. 2021. <span>“Performance: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models.”</span> <em>Journal of Open Source Software</em> 6 (60): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-report" class="csl-entry" role="listitem">
Makowski, Dominique, Mattan S. Ben-Shachar, Indrajeet Patil, and Daniel Lüdecke. 2021. <span>“Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.”</span> <em>CRAN</em>. <a href="https://github.com/easystats/report">https://github.com/easystats/report</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-week8.html" class="pagination-link" aria-label="Basic Inferential Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic Inferential Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-week10.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>