<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 10 Multiple Linear Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics</title>
  <meta name="description" content="Week 10 Multiple Linear Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 10 Multiple Linear Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 10 Multiple Linear Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  
  
  

<meta name="author" content="Martin Schweinberger" />


<meta name="date" content="2022-08-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-linear-regression.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<link href="libs/tabwid-1.0.0/scrool.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SLAT7855</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#basic-course-information"><i class="fa fa-check"></i>Basic Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-introduction"><i class="fa fa-check"></i>Course Introduction</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-staff"><i class="fa fa-check"></i>Course Staff</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#timetable"><i class="fa fa-check"></i>Timetable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aims-objectives-graduate-attributes"><i class="fa fa-check"></i>Aims, Objectives &amp; Graduate Attributes</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-aims"><i class="fa fa-check"></i>Course Aims</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i>Learning Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-resources"><i class="fa fa-check"></i>Learning Resources</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#required-resources"><i class="fa fa-check"></i>Required Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#recommended-resources"><i class="fa fa-check"></i>Recommended Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#university-learning-resources"><i class="fa fa-check"></i>University Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#school-of-languages-and-cultures-learning-resources"><i class="fa fa-check"></i>School of Languages and Cultures Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-learning-resources-information"><i class="fa fa-check"></i>Other Learning Resources &amp; Information</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-learning-activities"><i class="fa fa-check"></i>Teaching &amp; Learning Activities</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-activities"><i class="fa fa-check"></i>Learning Activities</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-plan"><i class="fa fa-check"></i>Course plan</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#weekly-oline-study-tasks"><i class="fa fa-check"></i>Weekly Oline Study Tasks</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#annotated-bibliography"><i class="fa fa-check"></i>Annotated Bibliography</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#research-project"><i class="fa fa-check"></i>Research Project</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-grading"><i class="fa fa-check"></i>Course Grading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#why-do-we-need-science"><i class="fa fa-check"></i><b>1.1</b> Why do we need science?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#errare-humanum-est"><i class="fa fa-check"></i><b>1.2</b> Errare Humanum Est</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#the-monty-hall-problem"><i class="fa fa-check"></i><b>1.2.1</b> The Monty Hall Problem</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#the-birthday-conundrum"><i class="fa fa-check"></i><b>1.2.2</b> The Birthday Conundrum</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction.html"><a href="introduction.html#fast-and-slow-thinking"><i class="fa fa-check"></i><b>1.2.3</b> Fast and Slow Thinking</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction.html"><a href="introduction.html#randomness"><i class="fa fa-check"></i><b>1.2.4</b> Randomness</a></li>
<li class="chapter" data-level="1.2.5" data-path="introduction.html"><a href="introduction.html#patterns-and-matters-of-habit"><i class="fa fa-check"></i><b>1.2.5</b> Patterns and Matters of Habit</a></li>
<li class="chapter" data-level="1.2.6" data-path="introduction.html"><a href="introduction.html#locical-fallacies-and-biases"><i class="fa fa-check"></i><b>1.2.6</b> Locical Fallacies and Biases</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#what-is-science"><i class="fa fa-check"></i><b>1.3</b> What is science?</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#clever-hans"><i class="fa fa-check"></i><b>1.3.1</b> Clever Hans</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#popper-falsification-and-scientific-progress"><i class="fa fa-check"></i><b>1.3.2</b> Popper, falsification, and scientific progress</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#what-is-empirical-linguistics"><i class="fa fa-check"></i><b>1.3.3</b> What is (empirical) Linguistics?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#tutorial"><i class="fa fa-check"></i>Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html"><i class="fa fa-check"></i><b>2</b> Hypotheses and Variables</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#hypotheses"><i class="fa fa-check"></i><b>2.1</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#types-of-hypotheses"><i class="fa fa-check"></i>Types of Hypotheses</a></li>
<li class="chapter" data-level="" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#why-test-the-h0"><i class="fa fa-check"></i>Why test the H0?!</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#data-and-research-designs"><i class="fa fa-check"></i><b>2.2</b> Data and Research Designs</a>
<ul>
<li class="chapter" data-level="" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#research-designs"><i class="fa fa-check"></i>Research Designs</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#variables-and-validity"><i class="fa fa-check"></i><b>2.3</b> Variables and Validity</a>
<ul>
<li class="chapter" data-level="" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#variable-types-scaling"><i class="fa fa-check"></i>Variable Types (Scaling)</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#relationships-between-variables"><i class="fa fa-check"></i><b>2.4</b> Relationships between variables</a></li>
<li class="chapter" data-level="" data-path="hypotheses-and-variables.html"><a href="hypotheses-and-variables.html#tutorial-1"><i class="fa fa-check"></i>Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html"><i class="fa fa-check"></i><b>3</b> Significance, Probability and the Normal Distribution</a>
<ul>
<li class="chapter" data-level="3.1" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#significance-and-probability"><i class="fa fa-check"></i><b>3.1</b> Significance and Probability</a>
<ul>
<li class="chapter" data-level="" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#significance-levels"><i class="fa fa-check"></i>Significance Levels</a></li>
<li class="chapter" data-level="" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#probability"><i class="fa fa-check"></i>Probability</a></li>
<li class="chapter" data-level="" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#non-normality-skewness-and-kurtosis"><i class="fa fa-check"></i>Non-normality: skewness and kurtosis</a></li>
<li class="chapter" data-level="" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#the-binomial-distribution"><i class="fa fa-check"></i>The Binomial Distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#z-scores"><i class="fa fa-check"></i><b>3.2</b> z-scores</a></li>
<li class="chapter" data-level="3.3" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#alpha-and-beta-errors"><i class="fa fa-check"></i><b>3.3</b> Alpha and Beta Errors</a></li>
<li class="chapter" data-level="3.4" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#independence"><i class="fa fa-check"></i><b>3.4</b> Independence</a></li>
<li class="chapter" data-level="3.5" data-path="significance-probability-and-the-normal-distribution.html"><a href="significance-probability-and-the-normal-distribution.html#corrections"><i class="fa fa-check"></i><b>3.5</b> Corrections</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html"><i class="fa fa-check"></i><b>4</b> Getting Started with R and RStudio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#goals-of-this-section"><i class="fa fa-check"></i><b>4.1</b> Goals of this section</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#why-r"><i class="fa fa-check"></i><b>4.2</b> Why R?</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#full-flexibility"><i class="fa fa-check"></i>Full flexibility</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#great-for-learners"><i class="fa fa-check"></i>Great for learners!</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#free-and-open-source"><i class="fa fa-check"></i>Free and Open Source</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#rstudio-and-ease-of-use"><i class="fa fa-check"></i>RStudio and ease of use</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-is-a-community-effort"><i class="fa fa-check"></i>R is a community effort</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#reproducibilty-and-transparency"><i class="fa fa-check"></i>Reproducibilty and Transparency</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#tools-versus-scripts"><i class="fa fa-check"></i>Tools versus Scripts</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#widely-used"><i class="fa fa-check"></i>Widely used</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#employability"><i class="fa fa-check"></i>Employability</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>4.3</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="4.4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#preparation"><i class="fa fa-check"></i><b>4.4</b> Preparation</a></li>
<li class="chapter" data-level="4.5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#folder-structure-and-r-projects"><i class="fa fa-check"></i><b>4.5</b> Folder Structure and R projects</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#create-a-folder-for-your-project"><i class="fa fa-check"></i><b>4.5.1</b> Create a folder for your project</a></li>
<li class="chapter" data-level="4.5.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#open-rstudio"><i class="fa fa-check"></i><b>4.5.2</b> Open RStudio</a></li>
<li class="chapter" data-level="4.5.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-projects"><i class="fa fa-check"></i><b>4.5.3</b> R Projects</a></li>
<li class="chapter" data-level="4.5.4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-notebooks"><i class="fa fa-check"></i><b>4.5.4</b> R Notebooks</a></li>
<li class="chapter" data-level="4.5.5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#updating-r"><i class="fa fa-check"></i><b>4.5.5</b> Updating R</a></li>
<li class="chapter" data-level="4.5.6" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#optimizing-r-project-options"><i class="fa fa-check"></i><b>4.5.6</b> Optimizing R project options</a></li>
<li class="chapter" data-level="4.5.7" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-started-with-r-notebooks"><i class="fa fa-check"></i><b>4.5.7</b> Getting started with R Notebooks</a></li>
<li class="chapter" data-level="4.5.8" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-markdown"><i class="fa fa-check"></i><b>4.5.8</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-and-rstudio-basics"><i class="fa fa-check"></i><b>4.6</b> R and RStudio Basics</a></li>
<li class="chapter" data-level="4.7" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#rstudio-panes"><i class="fa fa-check"></i><b>4.7</b> RStudio: Panes</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-console-bottom-left-pane"><i class="fa fa-check"></i><b>4.7.1</b> R Console (bottom left pane)</a></li>
<li class="chapter" data-level="4.7.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#running-commands-from-a-script"><i class="fa fa-check"></i><b>4.7.2</b> Running commands from a script</a></li>
<li class="chapter" data-level="4.7.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#script-editor-top-left-pane"><i class="fa fa-check"></i><b>4.7.3</b> Script Editor (top left pane)</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.8</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#setting-up-an-r-session"><i class="fa fa-check"></i><b>4.8.1</b> Setting up an R session</a></li>
<li class="chapter" data-level="4.8.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#packages"><i class="fa fa-check"></i><b>4.8.2</b> Packages</a></li>
<li class="chapter" data-level="4.8.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-help"><i class="fa fa-check"></i><b>4.8.3</b> Getting help</a></li>
<li class="chapter" data-level="4.8.4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#finding-help-within-r"><i class="fa fa-check"></i><b>4.8.4</b> Finding help within R</a></li>
<li class="chapter" data-level="4.8.5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#finding-help-online"><i class="fa fa-check"></i><b>4.8.5</b> Finding help online</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#working-with-data"><i class="fa fa-check"></i><b>4.9</b> Working with Data</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-data"><i class="fa fa-check"></i><b>4.9.1</b> Loading data</a></li>
<li class="chapter" data-level="4.9.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#inspecting-data"><i class="fa fa-check"></i><b>4.9.2</b> Inspecting data</a></li>
<li class="chapter" data-level="4.9.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#a-first-plot"><i class="fa fa-check"></i><b>4.9.3</b> A first plot</a></li>
<li class="chapter" data-level="4.9.4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#changing-data"><i class="fa fa-check"></i><b>4.9.4</b> Changing data</a></li>
<li class="chapter" data-level="4.9.5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#saving-data"><i class="fa fa-check"></i><b>4.9.5</b> Saving data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html"><i class="fa fa-check"></i><b>5</b> Working with Tables in R and RStudio</a>
<ul>
<li class="chapter" data-level="5.1" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#working-with-tables"><i class="fa fa-check"></i><b>5.1</b> Working with tables</a></li>
<li class="chapter" data-level="5.2" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#functions-and-objects"><i class="fa fa-check"></i><b>5.2</b> Functions and Objects</a></li>
<li class="chapter" data-level="5.3" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#inspecting-data-1"><i class="fa fa-check"></i><b>5.3</b> Inspecting data</a></li>
<li class="chapter" data-level="5.4" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#accessing-individual-cells-in-a-table"><i class="fa fa-check"></i><b>5.4</b> Accessing individual cells in a table</a></li>
<li class="chapter" data-level="5.5" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#tabulating-data"><i class="fa fa-check"></i><b>5.5</b> Tabulating data</a></li>
<li class="chapter" data-level="5.6" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#saving-data-to-your-computer"><i class="fa fa-check"></i><b>5.6</b> Saving data to your computer</a></li>
<li class="chapter" data-level="5.7" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#loading-data-from-your-computer"><i class="fa fa-check"></i><b>5.7</b> Loading data from your computer</a></li>
<li class="chapter" data-level="5.8" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#loading-excel-data"><i class="fa fa-check"></i><b>5.8</b> Loading Excel data</a></li>
<li class="chapter" data-level="5.9" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#renaming-piping-and-filtering"><i class="fa fa-check"></i><b>5.9</b> Renaming, Piping, and Filtering</a></li>
<li class="chapter" data-level="5.10" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#ordering-data"><i class="fa fa-check"></i><b>5.10</b> Ordering data</a></li>
<li class="chapter" data-level="5.11" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#creating-and-changing-variables"><i class="fa fa-check"></i><b>5.11</b> Creating and changing variables</a></li>
<li class="chapter" data-level="5.12" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#if-statements"><i class="fa fa-check"></i><b>5.12</b> If-statements</a></li>
<li class="chapter" data-level="5.13" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#summarizing-data"><i class="fa fa-check"></i><b>5.13</b> Summarizing data</a></li>
<li class="chapter" data-level="5.14" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#gathering-and-spreading-data"><i class="fa fa-check"></i><b>5.14</b> Gathering and spreading data</a></li>
<li class="chapter" data-level="5.15" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#ending-r-sessions"><i class="fa fa-check"></i><b>5.15</b> Ending R sessions</a></li>
<li class="chapter" data-level="5.16" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#extracting-session-information"><i class="fa fa-check"></i><b>5.16</b> Extracting session information</a></li>
<li class="chapter" data-level="5.17" data-path="working-with-tables-in-r-and-rstudio.html"><a href="working-with-tables-in-r-and-rstudio.html#going-further"><i class="fa fa-check"></i><b>5.17</b> Going further</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-centrality"><i class="fa fa-check"></i><b>6.1</b> Measures of Centrality</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i>Mode</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#geometric-mean"><i class="fa fa-check"></i>Geometric mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#harmonic-mean"><i class="fa fa-check"></i>Harmonic mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#notes-on-measures-of-centrality"><i class="fa fa-check"></i>Notes on Measures of Centrality</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-variability"><i class="fa fa-check"></i><b>6.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i>Range</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interquartile-range-iqr"><i class="fa fa-check"></i>Interquartile range (IQR)</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i>Standard deviation</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-error"><i class="fa fa-check"></i>Standard Error</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals-for-simple-vectors"><i class="fa fa-check"></i>Confidence Intervals for Simple Vectors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html"><i class="fa fa-check"></i><b>7</b> Introduction to Data Visualization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#the-ggplot-framework"><i class="fa fa-check"></i><b>7.1</b> The ggplot framework</a></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#basic-principles-of-data-vis"><i class="fa fa-check"></i><b>7.2</b> Basic principles of data vis</a></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#creating-a-simple-graph"><i class="fa fa-check"></i><b>7.3</b> Creating a simple graph</a></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#modifying-axes-and-titles"><i class="fa fa-check"></i><b>7.4</b> Modifying axes and titles</a></li>
<li class="chapter" data-level="7.5" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#line-graphs"><i class="fa fa-check"></i><b>7.5</b> Line Graphs</a></li>
<li class="chapter" data-level="7.6" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#histograms"><i class="fa fa-check"></i><b>7.6</b> Histograms</a></li>
<li class="chapter" data-level="7.7" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#bar-plots"><i class="fa fa-check"></i><b>7.7</b> Bar plots</a></li>
<li class="chapter" data-level="7.8" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#boxplots"><i class="fa fa-check"></i><b>7.8</b> Boxplots</a></li>
<li class="chapter" data-level="7.9" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#modifying-symbols-and-adding-text"><i class="fa fa-check"></i><b>7.9</b> Modifying symbols and adding text</a></li>
<li class="chapter" data-level="7.10" data-path="introduction-to-data-visualization.html"><a href="introduction-to-data-visualization.html#modifying-themes-and-legends"><i class="fa fa-check"></i><b>7.10</b> Modifying themes and legends</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html"><i class="fa fa-check"></i><b>8</b> Basic Inferential Statistics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#pearsonss-chi-square-test"><i class="fa fa-check"></i><b>8.1</b> (Pearsons’s) Chi-Square Test</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#effect-sizes-in-chi-square"><i class="fa fa-check"></i><b>8.1.1</b> Effect Sizes in Chi-Square</a></li>
<li class="chapter" data-level="8.1.2" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#chi-square-in-r"><i class="fa fa-check"></i><b>8.1.2</b> Chi-Square in R</a></li>
<li class="chapter" data-level="8.1.3" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#summarizing-chi-square-results"><i class="fa fa-check"></i><b>8.1.3</b> Summarizing Chi-Square Results</a></li>
<li class="chapter" data-level="8.1.4" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#requirements-of-chi-square"><i class="fa fa-check"></i><b>8.1.4</b> Requirements of Chi-Square</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#students-t-test"><i class="fa fa-check"></i><b>8.2</b> Student’s t-test</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#paired-t-test"><i class="fa fa-check"></i><b>8.2.1</b> Paired t-test</a></li>
<li class="chapter" data-level="8.2.2" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#independent-t-tests"><i class="fa fa-check"></i><b>8.2.2</b> Independent t-tests</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="basic-inferential-statistics.html"><a href="basic-inferential-statistics.html#mann-whitney-u-test"><i class="fa fa-check"></i><b>8.3</b> Mann-Whitney U-Test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>9</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#the-basic-principle"><i class="fa fa-check"></i><b>9.1</b> The Basic Principle</a></li>
<li class="chapter" data-level="9.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#example-1-preposition-use-across-real-time"><i class="fa fa-check"></i><b>9.2</b> Example 1: Preposition Use across Real-Time</a></li>
<li class="chapter" data-level="9.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#example-2-teaching-styles"><i class="fa fa-check"></i><b>9.3</b> Example 2: Teaching Styles</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>10</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-basic-principle-1"><i class="fa fa-check"></i><b>10.1</b> The Basic Principle</a></li>
<li class="chapter" data-level="10.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#example-gifts-and-availability"><i class="fa fa-check"></i><b>10.2</b> Example: Gifts and Availability</a></li>
<li class="chapter" data-level="10.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#model-fitting"><i class="fa fa-check"></i><b>10.3</b> Model Fitting</a></li>
<li class="chapter" data-level="10.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#model-diagnostics"><i class="fa fa-check"></i><b>10.4</b> Model Diagnostics</a></li>
<li class="chapter" data-level="10.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#a-word-about-sample-size"><i class="fa fa-check"></i><b>10.5</b> A Word about Sample Size</a></li>
<li class="chapter" data-level="10.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#reporting-results"><i class="fa fa-check"></i><b>10.6</b> Reporting Results</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SLAT7855 Quantitative Research Methods in Applied Linguistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-linear-regression" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Week 10</span> Multiple Linear Regression<a href="multiple-linear-regression.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This tutorial introduces regression analysis (also called regression modeling). Regression models are among the most widely used quantitative methods in the language sciences to assess if and how predictors (variables or interactions between variables) correlate with a certain response.</p>
<p>Regression models are so popular because they can</p>
<ul>
<li><p>incorporate many predictors in a single model (multivariate: allows to test the impact of one predictor while the impact of (all) other predictors is controlled for)</p></li>
<li><p>extremely flexible and and can be fitted to different types of predictors and dependent variables</p></li>
<li><p>provide output that can be easily interpreted</p></li>
<li><p>conceptually relative simple and not overly complex from a mathematical perspective</p></li>
</ul>
<p>The major difference between these types of models is that they take different types of dependent variables: linear regressions take numeric, logistic regressions take nominal variables, ordinal regressions take ordinal variables, and Poisson regressions take dependent variables that reflect counts of (rare) events.</p>
<div id="the-basic-principle-1" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> The Basic Principle<a href="multiple-linear-regression.html#the-basic-principle-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In contrast to simple linear regression, which estimates the effect of a single predictor, multiple linear regression estimates the effect of various predictors simultaneously (see the equation below).</p>
<p><span class="math display">\[\begin{equation}

f_{(x)} = \alpha + \beta_{1}x_{i} + \beta_{2}x_{i+1} + \dots + \beta_{n}x_{i+n} + \epsilon

\end{equation}\]</span></p>
<p>The model diagnostics we are dealing with here are partly identical to the diagnostic methods for simple linear regression. Because of this overlap, diagnostics will only be described in more detail if they have not been described in the section on simple linear regression.</p>
</div>
<div id="example-gifts-and-availability" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Example: Gifts and Availability<a href="multiple-linear-regression.html#example-gifts-and-availability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The example we will go through here is taken from <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span>. In this example, the research question is if the money that men spend on presents for women depends on the women’s attractiveness and their relationship status. To answer this research question, we will implement a multiple linear regression and start by loading the data and inspect its structure and properties.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="multiple-linear-regression.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb1-2"><a href="multiple-linear-regression.html#cb1-2" aria-hidden="true" tabindex="-1"></a>mlrdata  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">&quot;https://slcladal.github.io/data/mld.rda&quot;</span>, <span class="st">&quot;rb&quot;</span>))</span></code></pre></div>
<template id="7c701c0c-93e4-4f5f-ada5-ee06759d9311"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
.katex-display {
    margin: 0 0 !important;
}
</style><div class="tabwid"><style>.cl-ab4fc22c{table-layout:auto;width:75%;}.cl-ab374a62{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ab374a6c{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ab376f2e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ab376f38{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ab37ba60{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba6a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba6b{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba6c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba74{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba75{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba76{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba7e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba7f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba80{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba81{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ab37ba88{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-ab4fc22c'>
<caption class="Table Caption">
<p><span id="tab:intro00">Table 10.1: </span>First 15 rows of the mlrdata.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba81"><p class="cl-ab376f2e"><span class="cl-ab374a62">status</span></p></td><td class="cl-ab37ba80"><p class="cl-ab376f2e"><span class="cl-ab374a62">attraction</span></p></td><td class="cl-ab37ba88"><p class="cl-ab376f38"><span class="cl-ab374a62">money</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">86.33</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">45.58</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">68.43</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">52.93</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">61.86</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">48.47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">32.79</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">35.91</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">30.98</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">44.82</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">35.05</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">64.49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba6b"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba60"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba6a"><p class="cl-ab376f38"><span class="cl-ab374a6c">54.50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba75"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba6c"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba74"><p class="cl-ab376f38"><span class="cl-ab374a6c">61.48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ab37ba7f"><p class="cl-ab376f2e"><span class="cl-ab374a6c">Relationship</span></p></td><td class="cl-ab37ba7e"><p class="cl-ab376f2e"><span class="cl-ab374a6c">NotInterested</span></p></td><td class="cl-ab37ba76"><p class="cl-ab376f38"><span class="cl-ab374a6c">55.51</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="15725ce1-0eb9-45e0-895d-f6f6fb96775d"></div>
<script>
var dest = document.getElementById("15725ce1-0eb9-45e0-895d-f6f6fb96775d");
var template = document.getElementById("7c701c0c-93e4-4f5f-ada5-ee06759d9311");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>The data set consist of three variables stored in three columns. The first column contains the relationship status of the present giver (in this study this were men), the second whether the man is interested in the woman (the present receiver in this study), and the third column represents the money spend on the present. The data set represents 100 cases and the mean amount of money spend on a present is 88.38 dollars. In a next step, we visualize the data to get a more detailed impression of the relationships between variables.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multiple-linear-regression.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create plots</span></span>
<span id="cb2-2"><a href="multiple-linear-regression.html#cb2-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(status, money)) <span class="sc">+</span>   </span>
<span id="cb2-3"><a href="multiple-linear-regression.html#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb2-4"><a href="multiple-linear-regression.html#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb2-5"><a href="multiple-linear-regression.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 2</span></span>
<span id="cb2-6"><a href="multiple-linear-regression.html#cb2-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(attraction, money)) <span class="sc">+</span></span>
<span id="cb2-7"><a href="multiple-linear-regression.html#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb2-8"><a href="multiple-linear-regression.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb2-9"><a href="multiple-linear-regression.html#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 3</span></span>
<span id="cb2-10"><a href="multiple-linear-regression.html#cb2-10" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(<span class="at">x =</span> money)) <span class="sc">+</span></span>
<span id="cb2-11"><a href="multiple-linear-regression.html#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..)) <span class="sc">+</span>           </span>
<span id="cb2-12"><a href="multiple-linear-regression.html#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span>                               </span>
<span id="cb2-13"><a href="multiple-linear-regression.html#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span>
<span id="cb2-14"><a href="multiple-linear-regression.html#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 4</span></span>
<span id="cb2-15"><a href="multiple-linear-regression.html#cb2-15" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(status, money)) <span class="sc">+</span></span>
<span id="cb2-16"><a href="multiple-linear-regression.html#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">factor</span>(status))) <span class="sc">+</span> </span>
<span id="cb2-17"><a href="multiple-linear-regression.html#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> attraction) <span class="sc">+</span>       </span>
<span id="cb2-18"><a href="multiple-linear-regression.html#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb2-19"><a href="multiple-linear-regression.html#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb2-20"><a href="multiple-linear-regression.html#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># show plots</span></span>
<span id="cb2-21"><a href="multiple-linear-regression.html#cb2-21" aria-hidden="true" tabindex="-1"></a>vip<span class="sc">::</span><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> <span class="fu">list</span>(p1, p2, p3, p4), <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">layout_matrix =</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>)))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr3-1.png" width="672" /></p>
<p>The upper left figure consists of a boxplot which shows how much money was spent by relationship status. The figure suggests that men spend more on women if they are not in a relationship. The next figure shows the relationship between the money spend on presents and whether or not the men were interested in the women.</p>
<p>The boxplot in the upper right panel suggests that men spend substantially more on women if the men are interested in them. The next figure depicts the distribution of the amounts of money spend on the presents for the women. In addition, the figure indicates the existence of two outliers (dots in the boxplot)</p>
<p>The histogram in the lower left panel shows that, although the mean amount of money spent on presents is 88.38 dollars, the distribution peaks around 50 dollars indicating that on average, men spend about 50 dollars on presents. Finally, we will plot the amount of money spend on presents against relationship status by attraction in order to check whether the money spent on presents is affected by an interaction between attraction and relationship status.</p>
<p>The boxplot in the lower right panel confirms the existence of an interaction (a non-additive term) as men only spend more money on women if the men single <em>and</em> they are interested in the women. If men are not interested in the women, then the relationship has no effect as they spend an equal amount of money on the women regardless of whether they are in a relationship or not.</p>
<p>We will now start to implement the regression model. In a first step, we create a saturated model that contain all possible predictors (main effects and interactions).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multiple-linear-regression.html#cb3-1" aria-hidden="true" tabindex="-1"></a>m1.mlr <span class="ot">=</span> <span class="fu">lm</span>(                      <span class="co"># generate lm regression object</span></span>
<span id="cb3-2"><a href="multiple-linear-regression.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> attraction<span class="sc">*</span>status,  <span class="co"># def. regression formula</span></span>
<span id="cb3-3"><a href="multiple-linear-regression.html#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                 <span class="co"># def. data</span></span></code></pre></div>
<p>After generating the saturated models we can now start with the model fitting. Model fitting refers to a process that aims at find the model that explains a maximum of variance with a minimum of predictors <span class="citation">(see <a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 318</a>)</span>. Model fitting is therefore based on the <em>principle of parsimony</em> which is related to Occam’s razor according to which explanations that require fewer assumptions are more likely to be true.</p>
</div>
<div id="model-fitting" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Model Fitting<a href="multiple-linear-regression.html#model-fitting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Model fitting means that we check what of the predictors should be included in the model and what predictors do not have any impact on the outcome and thus should not be part of the model (because they merely add noise to the data.</p>
<p>In this example, we use the <code>glmulti</code> function to find the model with the lowest AIC (<em>Akaike Information Criterion</em>) as the criterion to find the model with the best fit: the lower the AIC value, the better the balance between explained variance and the number of predictors. AIC values can and should only be compared for models that are fit on the same data set with the same (number of) cases (<em>LL</em> stands for <em>logged likelihood</em> or <em>LogLikelihood</em> and <em>k</em> represents the number of predictors in the model (including the intercept); the LL represents a measure of how good the model fits the data).</p>
<p><span class="math display">\[\begin{equation}
Akaike Information Criterion (AIC) = -2LL + 2k
\end{equation}\]</span></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="multiple-linear-regression.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmulti)</span>
<span id="cb4-2"><a href="multiple-linear-regression.html#cb4-2" aria-hidden="true" tabindex="-1"></a>mfit <span class="ot">&lt;-</span> <span class="fu">glmulti</span>(money <span class="sc">~</span> attraction <span class="sc">+</span> status, <span class="at">data =</span> mlrdata, <span class="at">crit =</span> aic)</span></code></pre></div>
<pre><code>## Initialization...
## TASK: Exhaustive screening of candidate set.
## Fitting...
## Completed.</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="multiple-linear-regression.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mfit)</span></code></pre></div>
<pre><code>## $name
## [1] &quot;glmulti.analysis&quot;
## 
## $method
## [1] &quot;h&quot;
## 
## $fitting
## [1] &quot;glm&quot;
## 
## $crit
## [1] &quot;aic&quot;
## 
## $level
## [1] 2
## 
## $marginality
## [1] FALSE
## 
## $confsetsize
## [1] 100
## 
## $bestic
## [1] 878.3089
## 
## $icvalues
## [1]  878.3089  878.3089  878.3089  878.3089  930.6519  953.8269 1057.8180
## [8] 1063.3911
## 
## $bestmodel
## [1] &quot;money ~ 1 + status:attraction&quot;
## 
## $modelweights
## [1] 2.500000e-01 2.500000e-01 2.500000e-01 2.500000e-01 1.075929e-12
## [6] 9.986248e-18 2.618317e-40 1.613778e-41
## 
## $includeobjects
## [1] TRUE</code></pre>
<p>The <code>glmulti</code> function reports <code>money ~ 1 + status:attraction</code> as the best model. However, if a variable is part of a significant interaction, we also need to include the main effect which means that our best model is <code>money ~ 1 + status + attraction + status:attraction</code>, or, simplified: <code>money ~ status * attraction</code> (which is the same as the previous formula). The saturated model is thus also the final minimal adequate model, i.e. the model with the best fit and the lowest number of predictors. We will now inspect the final minimal model and go over the model report.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="multiple-linear-regression.html#cb8-1" aria-hidden="true" tabindex="-1"></a>m2.mlr <span class="ot">=</span> <span class="fu">lm</span>(                       <span class="co"># generate lm regression object</span></span>
<span id="cb8-2"><a href="multiple-linear-regression.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> (status <span class="sc">+</span> attraction)<span class="sc">^</span><span class="dv">2</span>, <span class="co"># def. regression formula</span></span>
<span id="cb8-3"><a href="multiple-linear-regression.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                  <span class="co"># def. data</span></span>
<span id="cb8-4"><a href="multiple-linear-regression.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect final minimal model</span></span>
<span id="cb8-5"><a href="multiple-linear-regression.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = money ~ (status + attraction)^2, data = mlrdata)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -45.08 -14.26   0.46  11.93  44.14 
## 
## Coefficients:
##                                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                            99.155      3.795  26.131  &lt; 2e-16 ***
## statusSingle                           57.693      5.366  10.751  &lt; 2e-16 ***
## attractionNotInterested               -47.663      5.366  -8.882 3.75e-14 ***
## statusSingle:attractionNotInterested  -63.179      7.589  -8.325 5.81e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.97 on 96 degrees of freedom
## Multiple R-squared:  0.852,  Adjusted R-squared:  0.8474 
## F-statistic: 184.3 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The first element of the report is called <em>Call</em> and it reports the regression formula of the model. Then, the report provides the residual distribution (the range, median and quartiles of the residuals) which allows drawing inferences about the distribution of differences between observed and expected values. If the residuals are distributed non-normally, then this is a strong indicator that the model is unstable and unreliable because mathematical assumptions on which the model is based are violated.</p>
<p>Next, the model summary reports the most important part: a table with model statistics of the fixed-effects structure of the model. The table contains the estimates (coefficients of the predictors), standard errors, t-values, and the p-values which show whether a predictor significantly correlates with the dependent variable that the model investigates.</p>
<p>All main effects (status and attraction) as well as the interaction between status and attraction is reported as being significantly correlated with the dependent variable (money). An interaction occurs if a correlation between the dependent variable and a predictor is affected by another predictor.</p>
<p>The top most term is called intercept and has a value of 99.15 which represents the base estimate to which all other estimates refer. To exemplify what this means, let us consider what the model would predict that a man would spend on a present if he interested in the woman but he is also in a relationship. The amount he would spend (based on the model would be 99.15 dollars (which is the intercept). This means that the intercept represents the predicted value if all predictors take the base or reference level. And since being in relationship but being interested are the case, and because the interaction does not apply, the predicted value in our example is exactly the intercept (see below).</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="multiple-linear-regression.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intercept  Single  NotInterested  Single:NotInterested</span></span>
<span id="cb10-2"><a href="multiple-linear-regression.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">+</span> <span class="fl">57.69</span>  <span class="sc">+</span> <span class="dv">0</span>           <span class="sc">+</span> <span class="dv">0</span>     <span class="co"># 156.8 single + interested</span></span>
<span id="cb10-3"><a href="multiple-linear-regression.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">+</span> <span class="fl">57.69</span>  <span class="sc">-</span> <span class="fl">47.66</span>       <span class="sc">-</span> <span class="fl">63.18</span> <span class="co"># 46.00 single + not interested</span></span>
<span id="cb10-4"><a href="multiple-linear-regression.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">-</span> <span class="dv">0</span>      <span class="sc">+</span> <span class="dv">0</span>           <span class="sc">-</span> <span class="dv">0</span>     <span class="co"># 99.15 relationship + interested</span></span>
<span id="cb10-5"><a href="multiple-linear-regression.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">-</span> <span class="dv">0</span>      <span class="sc">-</span> <span class="fl">47.66</span>       <span class="sc">-</span> <span class="dv">0</span>     <span class="co"># 51.49 relationship + not interested</span></span></code></pre></div>
<p>Now, let us consider what a man would spend if he is in a relationship and he is not attracted to the women. In that case, the model predicts that the man would spend only 51.49 dollars on a present: the intercept (99.15) minus 47.66 because the man is not interested (and no additional subtraction because the interaction does not apply).</p>
<p>We can derive the same results easier using the <code>predict</code> function.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multiple-linear-regression.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make prediction based on the model for original data</span></span>
<span id="cb11-2"><a href="multiple-linear-regression.html#cb11-2" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2.mlr, <span class="at">newdata =</span> mlrdata)</span>
<span id="cb11-3"><a href="multiple-linear-regression.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect predictions</span></span>
<span id="cb11-4"><a href="multiple-linear-regression.html#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">round</span>(prediction,<span class="dv">2</span>))</span></code></pre></div>
<pre><code>## 
##  46.01  51.49  99.15 156.85 
##     25     25     25     25</code></pre>
<p>Below the table of coefficients, the regression summary reports model statistics that provide information about how well the model performs. The difference between the values and the values in the coefficients table is that the model statistics refer to the model as a whole rather than focusing on individual predictors.</p>
<p>The multiple R<sup>2</sup>-value is a measure of how much variance the model explains. A multiple R<sup>2</sup>-value of 0 would inform us that the model does not explain any variance while a value of .852 mean that the model explains 85.2 percent of the variance. A value of 1 would inform us that the model explains 100 percent of the variance and that the predictions of the model match the observed values perfectly. Multiplying the multiple R<sup>2</sup>-value thus provides the percentage of explained variance.</p>
<p>The adjusted R<sup>2</sup>-value considers the amount of explained variance in light of the number of predictors in the model (it is thus somewhat similar to the AIC and BIC) and informs about how well the model would perform if it were applied to the population that the sample is drawn from. Ideally, the difference between multiple and adjusted R<sup>2</sup>-value should be very small as this means that the model is not overfitted. If, however, the difference between multiple and adjusted R<sup>2</sup>-value is substantial, then this would strongly suggest that the model is unstable and overfitted to the data while being inadequate for drawing inferences about the population. Differences between multiple and adjusted R<sup>2</sup>-values indicate that the data contains outliers that cause the distribution of the data on which the model is based to differ from the distributions that the model mathematically requires to provide reliable estimates. The difference between multiple and adjusted R<sup>2</sup>-value in our model is very small (85.2-84.7=.05) and should not cause concern.</p>
<p>Now, we compare the final minimal adequate model to the base-line model to test whether then final model significantly outperforms the baseline model.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multiple-linear-regression.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare baseline- and minimal adequate model</span></span>
<span id="cb13-2"><a href="multiple-linear-regression.html#cb13-2" aria-hidden="true" tabindex="-1"></a>m0.mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(money <span class="sc">~</span><span class="dv">1</span>, <span class="at">data =</span> mlrdata)</span>
<span id="cb13-3"><a href="multiple-linear-regression.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0.mlr, m2.mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: money ~ 1
## Model 2: money ~ (status + attraction)^2
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     99 233562                                  
## 2     96  34558  3    199005 184.28 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The comparison between the two model confirms that the minimal adequate model performs significantly better (makes significantly more accurate estimates of the outcome variable) compared with the baseline model.</p>
</div>
<div id="model-diagnostics" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Model Diagnostics<a href="multiple-linear-regression.html#model-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After implementing the multiple regression, we now need to look for outliers and perform the model diagnostics by testing whether removing data points disproportionately decreases model fit. To begin with, we generate diagnostic plots.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="multiple-linear-regression.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate plots</span></span>
<span id="cb15-2"><a href="multiple-linear-regression.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(m2.mlr) <span class="sc">+</span> </span>
<span id="cb15-3"><a href="multiple-linear-regression.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb15-4"><a href="multiple-linear-regression.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr11-1.png" width="672" /></p>
<p>The plots do not show severe problems such as funnel shaped patterns or drastic deviations from the diagonal line in Normal Q-Q plot (have a look at the explanation of what to look for and how to interpret these diagnostic plots in the section on simple linear regression) but data points 52, 64, and 83 are repeatedly indicated as potentially problematic cases.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="multiple-linear-regression.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb16-2"><a href="multiple-linear-regression.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(m2.mlr, <span class="at">main=</span><span class="st">&quot;QQ Plot&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr12-1.png" width="672" /></p>
<pre><code>## [1] 52 83</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="multiple-linear-regression.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2.mlr, <span class="at">which=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr12-2.png" width="672" /></p>
<p>The graphs indicate that data points 52, 64, and 83 do not seem to overly affect the results as they are within the acceptable range (indicated by the blue area around the Q-Q plot) and their Cook’s distance is elevated but not excessively high. and we can thus ignore this issue here.</p>
<p>When the diagnostic plots indicate potential outliers the following parameters should be considered:</p>
<ol style="list-style-type: decimal">
<li><p>If more than 1 percent of data points have standardized residuals exceeding values &gt; 2.58, then the error rate of the model is problematic <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span>.</p></li>
<li><p>If more than 5 percent of data points have standardized residuals exceeding values &gt; 1.96, then the error rate of the model is problematic <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span></p></li>
<li><p>In addition, data points with Cook’s D-values &gt; 1 are problematic <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span></p></li>
<li><p>Also, data points with leverage values higher than <span class="math inline">\(3(k + 1)/N\)</span> or <span class="math inline">\(2(k + 1)/N\)</span> (k = Number of predictors, N = Number of cases in model) are problematic <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 270</a>)</span></p></li>
<li><p>There should not be (any) autocorrelation among predictors. This means that independent variables cannot be correlated with itself (for instance, because data points come from the same subject). If there is autocorrelation among predictors, then a Repeated Measures Design or a (hierarchical) mixed-effects model should be implemented instead.</p></li>
<li><p>Predictors cannot substantially correlate with each other (multicollinearity) and a model contains predictors that have variance inflation factors (VIF) &gt; 3 <span class="citation">(see <a href="#ref-zuur2010protocol" role="doc-biblioref">Zuur, Ieno, and Elphick 2010</a>)</span>.</p></li>
</ol>
<p>The following code chunk creates and evaluates these criteria.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="multiple-linear-regression.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add model diagnostics to the data</span></span>
<span id="cb19-2"><a href="multiple-linear-regression.html#cb19-2" aria-hidden="true" tabindex="-1"></a>mlrdata <span class="ot">&lt;-</span> mlrdata <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="multiple-linear-regression.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">residuals =</span> <span class="fu">resid</span>(m2.mlr),</span>
<span id="cb19-4"><a href="multiple-linear-regression.html#cb19-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">standardized.residuals =</span> <span class="fu">rstandard</span>(m2.mlr),</span>
<span id="cb19-5"><a href="multiple-linear-regression.html#cb19-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">studentized.residuals =</span> <span class="fu">rstudent</span>(m2.mlr),</span>
<span id="cb19-6"><a href="multiple-linear-regression.html#cb19-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">cooks.distance =</span> <span class="fu">cooks.distance</span>(m2.mlr),</span>
<span id="cb19-7"><a href="multiple-linear-regression.html#cb19-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">dffit =</span> <span class="fu">dffits</span>(m2.mlr),</span>
<span id="cb19-8"><a href="multiple-linear-regression.html#cb19-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">leverage =</span> <span class="fu">hatvalues</span>(m2.mlr),</span>
<span id="cb19-9"><a href="multiple-linear-regression.html#cb19-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">covariance.ratios =</span> <span class="fu">covratio</span>(m2.mlr),</span>
<span id="cb19-10"><a href="multiple-linear-regression.html#cb19-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">fitted =</span> m2.mlr<span class="sc">$</span>fitted.values)</span></code></pre></div>
<p>And we can now statistically assess the model fit.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="multiple-linear-regression.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1: optimal = 1</span></span>
<span id="cb20-2"><a href="multiple-linear-regression.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb20-3"><a href="multiple-linear-regression.html#cb20-3" aria-hidden="true" tabindex="-1"></a>stdres_258 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">sapply</span>(mlrdata<span class="sc">$</span>standardized.residuals, <span class="cf">function</span>(x) {</span>
<span id="cb20-4"><a href="multiple-linear-regression.html#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">sqrt</span>((x<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">&gt;</span> <span class="fl">2.58</span>, <span class="dv">1</span>, <span class="dv">0</span>) } ))</span>
<span id="cb20-5"><a href="multiple-linear-regression.html#cb20-5" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(stdres_258) <span class="sc">/</span> <span class="fu">length</span>(stdres_258)) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="multiple-linear-regression.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2: optimal = 5</span></span>
<span id="cb22-2"><a href="multiple-linear-regression.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb22-3"><a href="multiple-linear-regression.html#cb22-3" aria-hidden="true" tabindex="-1"></a>stdres_196 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">sapply</span>(mlrdata<span class="sc">$</span>standardized.residuals, <span class="cf">function</span>(x) {</span>
<span id="cb22-4"><a href="multiple-linear-regression.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">sqrt</span>((x<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">&gt;</span> <span class="fl">1.96</span>, <span class="dv">1</span>, <span class="dv">0</span>) } ))</span>
<span id="cb22-5"><a href="multiple-linear-regression.html#cb22-5" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(stdres_196) <span class="sc">/</span> <span class="fu">length</span>(stdres_196)) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="multiple-linear-regression.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3: optimal = 0</span></span>
<span id="cb24-2"><a href="multiple-linear-regression.html#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb24-3"><a href="multiple-linear-regression.html#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(mlrdata<span class="sc">$</span>cooks.distance <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## named integer(0)</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="multiple-linear-regression.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4: optimal = 0</span></span>
<span id="cb26-2"><a href="multiple-linear-regression.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (data points should be removed if cooks distance is close to 1)</span></span>
<span id="cb26-3"><a href="multiple-linear-regression.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(mlrdata<span class="sc">$</span>leverage <span class="sc">&gt;=</span> (<span class="dv">3</span><span class="sc">*</span><span class="fu">mean</span>(mlrdata<span class="sc">$</span>leverage)))</span></code></pre></div>
<pre><code>## named integer(0)</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="multiple-linear-regression.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5: checking autocorrelation:</span></span>
<span id="cb28-2"><a href="multiple-linear-regression.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Durbin-Watson test (optimal: high p-value)</span></span>
<span id="cb28-3"><a href="multiple-linear-regression.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dwt</span>(m2.mlr)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1       0.0225138      1.898854   0.402
##  Alternative hypothesis: rho != 0</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="multiple-linear-regression.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6: test multicollinearity (should  not be greater than 3)</span></span>
<span id="cb30-2"><a href="multiple-linear-regression.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(m2.mlr)</span></code></pre></div>
<pre><code>## there are higher-order terms (interactions) in this model
## consider setting type = &#39;predictor&#39;; see ?vif</code></pre>
<pre><code>##            status        attraction status:attraction 
##                 2                 2                 3</code></pre>
<p>All diagnostics are acceptable. We will now test whether the sample size is sufficient for our model. With respect to the minimal sample size and based on <span class="citation">Green (<a href="#ref-green1991many" role="doc-biblioref">1991</a>)</span>, <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012, 273–74</a>)</span> offer the following rules of thumb for an adequate sample size (k = number of predictors; categorical predictors with more than two levels should be recoded as dummy variables):</p>
<ul>
<li><p>if you are interested in the overall model: 50 + 8k (k = number of predictors)</p></li>
<li><p>if you are interested in individual predictors: 104 + k</p></li>
<li><p>if you are interested in both: take the higher value!</p></li>
</ul>
</div>
<div id="a-word-about-sample-size" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> A Word about Sample Size<a href="multiple-linear-regression.html#a-word-about-sample-size" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One common issue when doing null-hypothesis hypothesis testing is sample size (which is related to the probability of <span class="math inline">\(\beta\)</span>-errors). Remember, <span class="math inline">\(\beta\)</span>-errors (or beta errors) mean overlooking a significant effect typically because the sample size is too low. The test statistics ranges between 0 and 1 where lower values are better.</p>
<p>Despite there being no ultimate rule of thumb, <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012, 273–75</a>)</span>, based on <span class="citation">Green (<a href="#ref-green1991many" role="doc-biblioref">1991</a>)</span>, provide data-driven suggestions for the minimal size of data required for regression models that aim to find medium sized effects (k = number of predictors; categorical variables with more than two levels should be transformed into dummy variables):</p>
<blockquote>
<p>If one is only interested in the effect of specific variables, then the sample size should be at least 104 + k (k = number of predictors in model).</p>
</blockquote>
</div>
<div id="reporting-results" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Reporting Results<a href="multiple-linear-regression.html#reporting-results" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As a last step, we summarize the results of the regression analysis.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="multiple-linear-regression.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tabulate model results</span></span>
<span id="cb33-2"><a href="multiple-linear-regression.html#cb33-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m2.mlr)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;parameters&#39;:
##   method                         from      
##   format.parameters_distribution datawizard</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;effectsize&#39;:
##   method              from      
##   standardize.Surv    datawizard
##   standardize.bcplm   datawizard
##   standardize.clm2    datawizard
##   standardize.default datawizard
##   standardize.mediate datawizard
##   standardize.wbgee   datawizard
##   standardize.wbm     datawizard</code></pre>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
money
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
99.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
91.62 – 106.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
status [Single]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
57.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
47.04 – 68.34
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
attraction<br>[NotInterested]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-47.66
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-58.31 – -37.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
status [Single] *<br>attraction<br>[NotInterested]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-63.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-78.24 – -48.11
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
100
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.852 / 0.847
</td>
</tr>
</table>
<p>Additionally, we can inspect the summary of the regression model as shown below to extract additional information. We can use the <code>reports</code> package <span class="citation">(<a href="#ref-report" role="doc-biblioref">Makowski et al. 2021</a>)</span> to summarize the analysis.</p>
<p>Although <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span> suggest that the main effects of the predictors involved in the interaction should not be interpreted, they are interpreted here to illustrate how the results of a multiple linear regression can be reported.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="multiple-linear-regression.html#cb36-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m2.mlr)</span></code></pre></div>
<pre><code>## We fitted a linear model (estimated using OLS) to predict money with status and attraction (formula: money ~ (status + attraction)^2). The model explains a statistically significant and substantial proportion of variance (R2 = 0.85, F(3, 96) = 184.28, p &lt; .001, adj. R2 = 0.85). The model&#39;s intercept, corresponding to status = Relationship and attraction = Interested, is at 99.15 (95% CI [91.62, 106.69], t(96) = 26.13, p &lt; .001). Within this model:
## 
##   - The effect of status [Single] is statistically significant and positive (beta = 57.69, 95% CI [47.04, 68.34], t(96) = 10.75, p &lt; .001; Std. beta = 1.19, 95% CI [0.97, 1.41])
##   - The effect of attraction [NotInterested] is statistically significant and negative (beta = -47.66, 95% CI [-58.31, -37.01], t(96) = -8.88, p &lt; .001; Std. beta = -0.98, 95% CI [-1.20, -0.76])
##   - The interaction effect of attraction [NotInterested] on status [Single] is statistically significant and negative (beta = -63.18, 95% CI [-78.24, -48.11], t(96) = -8.32, p &lt; .001; Std. beta = -1.30, 95% CI [-1.61, -0.99])
## 
## Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
<p>Although <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span> suggest that the main effects of the predictors involved in the interaction should not be interpreted, they are interpreted here to illustrate how the results of a multiple linear regression can be reported.</p>
<p>We can use the output of the <code>report</code> function to write up a final report:</p>
<blockquote>
<p>A multiple linear regression was fitted to the data using an automated AIC-based (Akaike’s Information Criterion) procedure. The model fitting arrived at a final minimal model. During the model diagnostics, two outliers were detected and removed. Further diagnostics did not find other issues after the removal.</p>
<p>The final minimal adequate regression model is based on 98 data points and performs highly significantly better than a minimal baseline model (multiple R<sup>2</sup>: .857, adjusted R<sup>2</sup>: .853, F-statistic (3, 94): 154.4, AIC: 850.4, BIC: 863.32, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). The final minimal adequate regression model reports <em>attraction</em> and <em>status</em> as significant main effects. The relationship status of men correlates highly significantly and positively with the amount of money spend on the women’s presents (SE: 5.14, t-value: 10.87, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). This shows that men spend 156.8 dollars on presents if they are single while they spend 99,15 dollars if they are in a relationship. Whether men are attracted to women also correlates highly significantly and positively with the money they spend on women (SE: 5.09, t-values: -9.37, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). If men are not interested in women, they spend 47.66 dollar less on a present for women compared with women the men are interested in.</p>
</blockquote>
<p>Furthermore, the final minimal adequate regression model reports a highly significant interaction between relationship <em>status</em> and <em>attraction</em> (SE: 7.27, t-value: -8.18, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>): If men are single but they are not interested in a women, a man would spend only 59.46 dollars on a present compared to all other constellations.</p>
<p><a href="#multiple_linear_regression">Back to top</a></p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Field, Andy, Jeremy Miles, and Zoe Field. 2012. <em>Discovering Statistics Using r</em>. Sage.
</div>
<div class="csl-entry">
Green, Samuel B. 1991. <span>“How Many Subjects Does It Take to Do a Regression Analysis.”</span> <em>Multivariate Behavioral Research</em> 26 (3): 499–510.
</div>
<div class="csl-entry">
Makowski, Dominique, Mattan S. Ben-Shachar, Indrajeet Patil, and Daniel Lüdecke. 2021. <span>“Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.”</span> <em>CRAN</em>. <a href="https://github.com/easystats/report">https://github.com/easystats/report</a>.
</div>
<div class="csl-entry">
Zuur, Alain F., Elena N. Ieno, and Chris S. Elphick. 2010. <span>“A Protocol for Data Exploration to Avoid Common Statistical Problems.”</span> <em>Methods in Ecology and Evolution</em> 1 (1): 3–14.
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-field2012discovering" class="csl-entry">
Field, Andy, Jeremy Miles, and Zoe Field. 2012. <em>Discovering Statistics Using r</em>. Sage.
</div>
<div id="ref-green1991many" class="csl-entry">
Green, Samuel B. 1991. <span>“How Many Subjects Does It Take to Do a Regression Analysis.”</span> <em>Multivariate Behavioral Research</em> 26 (3): 499–510.
</div>
<div id="ref-report" class="csl-entry">
Makowski, Dominique, Mattan S. Ben-Shachar, Indrajeet Patil, and Daniel Lüdecke. 2021. <span>“Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.”</span> <em>CRAN</em>. <a href="https://github.com/easystats/report">https://github.com/easystats/report</a>.
</div>
<div id="ref-zuur2010protocol" class="csl-entry">
Zuur, Alain F., Elena N. Ieno, and Chris S. Elphick. 2010. <span>“A Protocol for Data Exploration to Avoid Common Statistical Problems.”</span> <em>Methods in Ecology and Evolution</em> 1 (1): 3–14.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-linear-regression.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/edit/master/10-week10.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/blob/master/10-week10.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
