<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 9 Multiple and Logistic Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics</title>
  <meta name="description" content="Week 9 Multiple and Logistic Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 9 Multiple and Logistic Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 9 Multiple and Logistic Regression | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  
  
  

<meta name="author" content="Martin Schweinberger" />


<meta name="date" content="2022-05-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-inferential-statistics-regression-analysis.html"/>
<link rel="next" href="logistic-regression-and-model-diagnostics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SLAT7855</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#basic-course-information"><i class="fa fa-check"></i>Basic Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-introduction"><i class="fa fa-check"></i>Course Introduction</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-staff"><i class="fa fa-check"></i>Course Staff</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#timetable"><i class="fa fa-check"></i>Timetable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aims-objectives-graduate-attributes"><i class="fa fa-check"></i>Aims, Objectives &amp; Graduate Attributes</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-aims"><i class="fa fa-check"></i>Course Aims</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i>Learning Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-resources"><i class="fa fa-check"></i>Learning Resources</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#required-resources"><i class="fa fa-check"></i>Required Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#recommended-resources"><i class="fa fa-check"></i>Recommended Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#university-learning-resources"><i class="fa fa-check"></i>University Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#school-of-languages-and-cultures-learning-resources"><i class="fa fa-check"></i>School of Languages and Cultures Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-learning-resources-information"><i class="fa fa-check"></i>Other Learning Resources &amp; Information</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-learning-activities"><i class="fa fa-check"></i>Teaching &amp; Learning Activities</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-activities"><i class="fa fa-check"></i>Learning Activities</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-plan"><i class="fa fa-check"></i>Course plan</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#why-do-we-need-science"><i class="fa fa-check"></i><b>1.1</b> Why do we need science?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#errare-humanum-est"><i class="fa fa-check"></i><b>1.2</b> Errare Humanum Est</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#the-monty-hall-problem"><i class="fa fa-check"></i><b>1.2.1</b> The Monty Hall Problem</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#the-birthday-conundrum"><i class="fa fa-check"></i><b>1.2.2</b> The Birthday Conundrum</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction.html"><a href="introduction.html#fast-and-slow-thinking"><i class="fa fa-check"></i><b>1.2.3</b> Fast and Slow Thinking</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction.html"><a href="introduction.html#randomness"><i class="fa fa-check"></i><b>1.2.4</b> Randomness</a></li>
<li class="chapter" data-level="1.2.5" data-path="introduction.html"><a href="introduction.html#patterns-and-matters-of-habit"><i class="fa fa-check"></i><b>1.2.5</b> Patterns and Matters of Habit</a></li>
<li class="chapter" data-level="1.2.6" data-path="introduction.html"><a href="introduction.html#locical-fallacies-and-biases"><i class="fa fa-check"></i><b>1.2.6</b> Locical Fallacies and Biases</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#what-is-science"><i class="fa fa-check"></i><b>1.3</b> What is science?</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#clever-hans"><i class="fa fa-check"></i><b>1.3.1</b> Clever Hans</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#popper-falsification-and-scientific-progress"><i class="fa fa-check"></i><b>1.3.2</b> Popper, falsification, and scientific progress</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#what-is-empirical-linguistics"><i class="fa fa-check"></i><b>1.3.3</b> What is (empirical) Linguistics?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html"><i class="fa fa-check"></i><b>2</b> Basic Concepts in Quantitative Research 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#hypotheses"><i class="fa fa-check"></i><b>2.1</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#types-of-hypotheses"><i class="fa fa-check"></i>Types of Hypotheses</a></li>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#why-test-the-h0"><i class="fa fa-check"></i>Why test the H0?!</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#data-and-research-designs"><i class="fa fa-check"></i><b>2.2</b> Data and Research Designs</a>
<ul>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#research-designs"><i class="fa fa-check"></i>Research Designs</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#variables-and-validity"><i class="fa fa-check"></i><b>2.3</b> Variables and Validity</a>
<ul>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#variable-types-scaling"><i class="fa fa-check"></i>Variable Types (Scaling)</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basic-concepts-in-quantitative-research-1.html"><a href="basic-concepts-in-quantitative-research-1.html#relationships-between-variables"><i class="fa fa-check"></i><b>2.4</b> Relationships between variables</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html"><i class="fa fa-check"></i><b>3</b> Basic Concepts in Quantitative Research 2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#significance-and-probability"><i class="fa fa-check"></i><b>3.1</b> Significance and Probability</a>
<ul>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#significance-levels"><i class="fa fa-check"></i>Significance Levels</a></li>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#probability"><i class="fa fa-check"></i>Probability</a></li>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#non-normality-skewness-and-kurtosis"><i class="fa fa-check"></i>Non-normality: skewness and kurtosis</a></li>
<li class="chapter" data-level="" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#the-binomial-distribution"><i class="fa fa-check"></i>The Binomial Distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#z-scores"><i class="fa fa-check"></i><b>3.2</b> z-scores</a></li>
<li class="chapter" data-level="3.3" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#alpha-and-beta-errors"><i class="fa fa-check"></i><b>3.3</b> Alpha and Beta Errors</a></li>
<li class="chapter" data-level="3.4" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#independence"><i class="fa fa-check"></i><b>3.4</b> Independence</a></li>
<li class="chapter" data-level="3.5" data-path="basic-concepts-in-quantitative-research-2.html"><a href="basic-concepts-in-quantitative-research-2.html#corrections"><i class="fa fa-check"></i><b>3.5</b> Corrections</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html"><i class="fa fa-check"></i><b>4</b> Getting Started with R and RStudio 1</a>
<ul>
<li class="chapter" data-level="4.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#goals-of-this-tutorial"><i class="fa fa-check"></i><b>4.1</b> Goals of this tutorial</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#audience"><i class="fa fa-check"></i><b>4.2</b> Audience</a></li>
<li class="chapter" data-level="4.3" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>4.3</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#how-to-use-the-workshop-materials"><i class="fa fa-check"></i><b>4.3.1</b> How to use the workshop materials</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#preparation"><i class="fa fa-check"></i><b>4.4</b> Preparation</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#folder-structure-and-r-projects"><i class="fa fa-check"></i><b>4.4.1</b> Folder Structure and R projects</a></li>
<li class="chapter" data-level="4.4.2" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#create-a-folder-for-your-project"><i class="fa fa-check"></i><b>4.4.2</b> 1. Create a folder for your project</a></li>
<li class="chapter" data-level="4.4.3" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#open-rstudio"><i class="fa fa-check"></i><b>4.4.3</b> 3. Open RStudio</a></li>
<li class="chapter" data-level="4.4.4" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#r-projects"><i class="fa fa-check"></i><b>4.4.4</b> 4. R Projects</a></li>
<li class="chapter" data-level="4.4.5" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#r-notebooks"><i class="fa fa-check"></i><b>4.4.5</b> 5. R Notebooks</a></li>
<li class="chapter" data-level="4.4.6" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#updating-r"><i class="fa fa-check"></i><b>4.4.6</b> 6. Updating R</a></li>
<li class="chapter" data-level="4.4.7" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#optimizing-r-project-options"><i class="fa fa-check"></i><b>4.4.7</b> 7. Optimizing R project options</a></li>
<li class="chapter" data-level="4.4.8" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#getting-started-with-r-notebooks"><i class="fa fa-check"></i><b>4.4.8</b> 8. Getting started with R Notebooks</a></li>
<li class="chapter" data-level="4.4.9" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#r-markdown"><i class="fa fa-check"></i><b>4.4.9</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#r-and-rstudio-basics"><i class="fa fa-check"></i><b>4.5</b> R and RStudio Basics</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#rstudio-panes"><i class="fa fa-check"></i><b>4.5.1</b> RStudio: Panes</a></li>
<li class="chapter" data-level="4.5.2" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#r-console-bottom-left-pane"><i class="fa fa-check"></i><b>4.5.2</b> R Console (bottom left pane)</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#running-commands-from-a-script"><i class="fa fa-check"></i><b>4.6</b> Running commands from a script</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#script-editor-top-left-pane"><i class="fa fa-check"></i><b>4.6.1</b> Script Editor (top left pane)</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.7</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#setting-up-an-r-session"><i class="fa fa-check"></i><b>4.7.1</b> Setting up an R session</a></li>
<li class="chapter" data-level="4.7.2" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#packages"><i class="fa fa-check"></i><b>4.7.2</b> Packages</a></li>
<li class="chapter" data-level="4.7.3" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#getting-help"><i class="fa fa-check"></i><b>4.7.3</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#working-with-tables"><i class="fa fa-check"></i><b>4.8</b> Working with tables</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#loading-data-from-the-web"><i class="fa fa-check"></i><b>4.8.1</b> Loading data from the web</a></li>
<li class="chapter" data-level="4.8.2" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#functions-and-objects"><i class="fa fa-check"></i><b>4.8.2</b> Functions and Objects</a></li>
<li class="chapter" data-level="4.8.3" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#inspecting-data"><i class="fa fa-check"></i><b>4.8.3</b> Inspecting data</a></li>
<li class="chapter" data-level="4.8.4" data-path="getting-started-with-r-and-rstudio-1.html"><a href="getting-started-with-r-and-rstudio-1.html#accessing-individual-cells-in-a-table"><i class="fa fa-check"></i><b>4.8.4</b> Accessing individual cells in a table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html"><i class="fa fa-check"></i><b>5</b> Getting Started with R and RStudio 2</a>
<ul>
<li class="chapter" data-level="5.1" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#working-with-tables-1"><i class="fa fa-check"></i><b>5.1</b> Working with tables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#tabulating-data"><i class="fa fa-check"></i><b>5.1.1</b> Tabulating data</a></li>
<li class="chapter" data-level="5.1.2" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#saving-data-to-your-computer"><i class="fa fa-check"></i><b>5.1.2</b> Saving data to your computer</a></li>
<li class="chapter" data-level="5.1.3" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#loading-data-from-your-computer"><i class="fa fa-check"></i><b>5.1.3</b> Loading data from your computer</a></li>
<li class="chapter" data-level="5.1.4" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#loading-excel-data"><i class="fa fa-check"></i><b>5.1.4</b> Loading Excel data</a></li>
<li class="chapter" data-level="5.1.5" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#loading-text-data"><i class="fa fa-check"></i><b>5.1.5</b> Loading text data</a></li>
<li class="chapter" data-level="5.1.6" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#renaming-piping-and-filtering"><i class="fa fa-check"></i><b>5.1.6</b> Renaming, Piping, and Filtering</a></li>
<li class="chapter" data-level="5.1.7" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#ordering-data"><i class="fa fa-check"></i><b>5.1.7</b> Ordering data</a></li>
<li class="chapter" data-level="5.1.8" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#creating-and-changing-variables"><i class="fa fa-check"></i><b>5.1.8</b> Creating and changing variables</a></li>
<li class="chapter" data-level="5.1.9" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#if-statements"><i class="fa fa-check"></i><b>5.1.9</b> If-statements</a></li>
<li class="chapter" data-level="5.1.10" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#summarizing-data"><i class="fa fa-check"></i><b>5.1.10</b> Summarizing data</a></li>
<li class="chapter" data-level="5.1.11" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#gathering-and-spreading-data"><i class="fa fa-check"></i><b>5.1.11</b> Gathering and spreading data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#ending-r-sessions"><i class="fa fa-check"></i><b>5.2</b> Ending R sessions</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#extracting-session-information"><i class="fa fa-check"></i><b>5.2.1</b> Extracting session information</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="getting-started-with-r-and-rstudio-2.html"><a href="getting-started-with-r-and-rstudio-2.html#going-further"><i class="fa fa-check"></i><b>5.3</b> Going further</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-centrality"><i class="fa fa-check"></i><b>6.1</b> Measures of Centrality</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i>Mode</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#geometric-mean"><i class="fa fa-check"></i>Geometric mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#harmonic-mean"><i class="fa fa-check"></i>Harmonic mean</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#notes-on-measures-of-centrality"><i class="fa fa-check"></i>Notes on Measures of Centrality</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-variability"><i class="fa fa-check"></i><b>6.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i>Range</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interquartile-range-iqr"><i class="fa fa-check"></i>Interquartile range (IQR)</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i>Standard deviation</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-error"><i class="fa fa-check"></i>Standard Error</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals-for-simple-vectors"><i class="fa fa-check"></i>Confidence Intervals for Simple Vectors</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals-for-grouped-data"><i class="fa fa-check"></i>Confidence Intervals for Grouped Data</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals-for-nominal-data"><i class="fa fa-check"></i>Confidence Intervals for Nominal Data</a></li>
<li class="chapter" data-level="" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confidence-intervals-for-multinomial-data"><i class="fa fa-check"></i>Confidence Intervals for Multinomial Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>7</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-visualization.html"><a href="data-visualization.html#getting-started"><i class="fa fa-check"></i><b>7.1</b> Getting started</a></li>
<li class="chapter" data-level="7.2" data-path="data-visualization.html"><a href="data-visualization.html#dot-and-scatter-plots"><i class="fa fa-check"></i><b>7.2</b> Dot and Scatter Plots</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plots-in-base"><i class="fa fa-check"></i><b>7.2.1</b> Scatter Plots in base</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plots-in-ggplot2"><i class="fa fa-check"></i><b>7.2.2</b> Scatter Plots in ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-visualization.html"><a href="data-visualization.html#line-graphs"><i class="fa fa-check"></i><b>7.3</b> Line Graphs</a></li>
<li class="chapter" data-level="7.4" data-path="data-visualization.html"><a href="data-visualization.html#histograms"><i class="fa fa-check"></i><b>7.4</b> Histograms</a></li>
<li class="chapter" data-level="7.5" data-path="data-visualization.html"><a href="data-visualization.html#bar-plots"><i class="fa fa-check"></i><b>7.5</b> Bar plots</a></li>
<li class="chapter" data-level="7.6" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>7.6</b> Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="basic-inferential-statistics-regression-analysis.html"><a href="basic-inferential-statistics-regression-analysis.html"><i class="fa fa-check"></i><b>8</b> Basic Inferential Statistics: Regression Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="basic-inferential-statistics-regression-analysis.html"><a href="basic-inferential-statistics-regression-analysis.html#the-basic-principle"><i class="fa fa-check"></i><b>8.1</b> The basic principle</a></li>
<li class="chapter" data-level="8.2" data-path="basic-inferential-statistics-regression-analysis.html"><a href="basic-inferential-statistics-regression-analysis.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.2</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="basic-inferential-statistics-regression-analysis.html"><a href="basic-inferential-statistics-regression-analysis.html#example-1-preposition-use-across-real-time"><i class="fa fa-check"></i><b>8.2.1</b> Example 1: Preposition Use across Real-Time</a></li>
<li class="chapter" data-level="8.2.2" data-path="basic-inferential-statistics-regression-analysis.html"><a href="basic-inferential-statistics-regression-analysis.html#example-2-teaching-styles"><i class="fa fa-check"></i><b>8.2.2</b> Example 2: Teaching Styles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html"><i class="fa fa-check"></i><b>9</b> Multiple and Logistic Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>9.1</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#example-gifts-and-availability"><i class="fa fa-check"></i><b>9.1.1</b> Example: Gifts and Availability</a></li>
<li class="chapter" data-level="9.1.2" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#automatic-model-fitting-and-why-you-should-not-use-it"><i class="fa fa-check"></i><b>9.1.2</b> Automatic Model Fitting and Why You Should Not Use It</a></li>
<li class="chapter" data-level="9.1.3" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#outlier-detection"><i class="fa fa-check"></i><b>9.1.3</b> Outlier Detection</a></li>
<li class="chapter" data-level="9.1.4" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#rerun-regression"><i class="fa fa-check"></i><b>9.1.4</b> Rerun Regression</a></li>
<li class="chapter" data-level="9.1.5" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#additional-model-diagnostics"><i class="fa fa-check"></i><b>9.1.5</b> Additional Model Diagnostics</a></li>
<li class="chapter" data-level="9.1.6" data-path="multiple-and-logistic-regression.html"><a href="multiple-and-logistic-regression.html#evaluation-of-sample-size"><i class="fa fa-check"></i><b>9.1.6</b> Evaluation of Sample Size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html"><i class="fa fa-check"></i><b>10</b> Logistic Regression and Model Diagnostics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#multiple-binomial-logistic-regression"><i class="fa fa-check"></i><b>10.1</b> Multiple Binomial Logistic Regression</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#example-1-eh-in-kiwi-english"><i class="fa fa-check"></i><b>10.1.1</b> Example 1: EH in Kiwi English</a></li>
<li class="chapter" data-level="10.1.2" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#model-building"><i class="fa fa-check"></i><b>10.1.2</b> Model Building</a></li>
<li class="chapter" data-level="10.1.3" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#model-fitting"><i class="fa fa-check"></i><b>10.1.3</b> Model fitting</a></li>
<li class="chapter" data-level="10.1.4" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#model-validation"><i class="fa fa-check"></i><b>10.1.4</b> Model Validation</a></li>
<li class="chapter" data-level="10.1.5" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#effect-size"><i class="fa fa-check"></i><b>10.1.5</b> Effect Size</a></li>
<li class="chapter" data-level="10.1.6" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#prediction-accuracy"><i class="fa fa-check"></i><b>10.1.6</b> Prediction Accuracy</a></li>
<li class="chapter" data-level="10.1.7" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#model-diagnostics"><i class="fa fa-check"></i><b>10.1.7</b> Model Diagnostics</a></li>
<li class="chapter" data-level="10.1.8" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#multicollinearity"><i class="fa fa-check"></i><b>10.1.8</b> Multicollinearity</a></li>
<li class="chapter" data-level="10.1.9" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#outlier-detection-1"><i class="fa fa-check"></i><b>10.1.9</b> Outlier detection</a></li>
<li class="chapter" data-level="10.1.10" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#sample-size"><i class="fa fa-check"></i><b>10.1.10</b> Sample Size</a></li>
<li class="chapter" data-level="10.1.11" data-path="logistic-regression-and-model-diagnostics.html"><a href="logistic-regression-and-model-diagnostics.html#summarizing-results"><i class="fa fa-check"></i><b>10.1.11</b> Summarizing Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html"><i class="fa fa-check"></i><b>11</b> Mixed-Effects Regression</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#introduction-1"><i class="fa fa-check"></i><b>11.0.1</b> Introduction</a></li>
<li class="chapter" data-level="11.0.2" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#random-effects"><i class="fa fa-check"></i><b>11.0.2</b> Random Effects</a></li>
<li class="chapter" data-level="11.0.3" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#example-preposition-use-across-time-by-genre"><i class="fa fa-check"></i><b>11.0.3</b> Example: Preposition Use across Time by Genre</a></li>
<li class="chapter" data-level="11.0.4" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#testing-random-effects"><i class="fa fa-check"></i><b>11.0.4</b> Testing Random Effects</a></li>
<li class="chapter" data-level="11.0.5" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-fitting-1"><i class="fa fa-check"></i><b>11.0.5</b> Model Fitting</a></li>
<li class="chapter" data-level="11.0.6" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-diagnostics-1"><i class="fa fa-check"></i><b>11.0.6</b> Model Diagnostics</a></li>
<li class="chapter" data-level="11.0.7" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#effect-sizes"><i class="fa fa-check"></i><b>11.0.7</b> Effect Sizes</a></li>
<li class="chapter" data-level="11.0.8" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-diagnostics-2"><i class="fa fa-check"></i><b>11.0.8</b> Model Diagnostics</a></li>
<li class="chapter" data-level="11.0.9" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#reporting-results"><i class="fa fa-check"></i><b>11.0.9</b> Reporting Results</a></li>
<li class="chapter" data-level="11.0.10" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#remarks-on-prediction"><i class="fa fa-check"></i><b>11.0.10</b> Remarks on Prediction</a></li>
<li class="chapter" data-level="11.1" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#mixed-effects-binomial-logistic-regression"><i class="fa fa-check"></i><b>11.1</b> Mixed-Effects Binomial Logistic Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#introduction-2"><i class="fa fa-check"></i><b>11.1.1</b> Introduction</a></li>
<li class="chapter" data-level="11.1.2" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#example-discourse-like-in-irish-english"><i class="fa fa-check"></i><b>11.1.2</b> Example: Discourse LIKE in Irish English</a></li>
<li class="chapter" data-level="11.1.3" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-building-1"><i class="fa fa-check"></i><b>11.1.3</b> Model Building</a></li>
<li class="chapter" data-level="11.1.4" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#testing-the-random-effect"><i class="fa fa-check"></i><b>11.1.4</b> Testing the Random Effect</a></li>
<li class="chapter" data-level="11.1.5" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-fitting-2"><i class="fa fa-check"></i><b>11.1.5</b> Model Fitting</a></li>
<li class="chapter" data-level="11.1.6" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#visualizing-effects"><i class="fa fa-check"></i><b>11.1.6</b> Visualizing Effects</a></li>
<li class="chapter" data-level="11.1.7" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#extracting-model-fit-parameters"><i class="fa fa-check"></i><b>11.1.7</b> Extracting Model Fit Parameters</a></li>
<li class="chapter" data-level="11.1.8" data-path="mixed-effects-regression.html"><a href="mixed-effects-regression.html#model-diagnostics-3"><i class="fa fa-check"></i><b>11.1.8</b> Model Diagnostics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="tree-based-models-in-r.html"><a href="tree-based-models-in-r.html"><i class="fa fa-check"></i><b>12</b> Tree-Based Models in R</a>
<ul>
<li class="chapter" data-level="" data-path="tree-based-models-in-r.html"><a href="tree-based-models-in-r.html#splitting-numeric-ordinal-and-true-categorical-variables"><i class="fa fa-check"></i>Splitting numeric, ordinal, and true categorical variables</a></li>
<li class="chapter" data-level="" data-path="tree-based-models-in-r.html"><a href="tree-based-models-in-r.html#prettifying-your-cit-tree"><i class="fa fa-check"></i>Prettifying your CIT tree</a></li>
<li class="chapter" data-level="" data-path="tree-based-models-in-r.html"><a href="tree-based-models-in-r.html#problems-of-conditional-inference-trees"><i class="fa fa-check"></i>Problems of Conditional Inference Trees</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SLAT7855 Quantitative Research Methods in Applied Linguistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-and-logistic-regression" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Week 9</span> Multiple and Logistic Regression<a href="multiple-and-logistic-regression.html#multiple-and-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This week, we continue with regression analyses and expand on last week by including multiple predictors and by using a regression to analyse a nominal dependent variable.</p>
<p><strong>Preparation and session set up</strong></p>
<p>This tutorial is based on R. If you have not installed R or are new to it, you will find an introduction to and more information how to use R <a href="https://slcladal.github.io/intror.html">here</a>. For this tutorials, we need to install certain <em>packages</em> from an R <em>library</em> so that the scripts shown below are executed without errors. Before turning to the code below, please install the packages by running the code below this paragraph. If you have already installed the packages mentioned below, then you can skip ahead and ignore this section. To install the necessary packages, simply run the following code - it may take some time (between 1 and 5 minutes to install all of the libraries so you do not need to worry if it takes some time).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="multiple-and-logistic-regression.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install</span></span>
<span id="cb1-2"><a href="multiple-and-logistic-regression.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;Boruta&quot;</span>)</span>
<span id="cb1-3"><a href="multiple-and-logistic-regression.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb1-4"><a href="multiple-and-logistic-regression.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;emmeans&quot;</span>)</span>
<span id="cb1-5"><a href="multiple-and-logistic-regression.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;effects&quot;</span>)</span>
<span id="cb1-6"><a href="multiple-and-logistic-regression.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;flextable&quot;</span>)</span>
<span id="cb1-7"><a href="multiple-and-logistic-regression.html#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb1-8"><a href="multiple-and-logistic-regression.html#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb1-9"><a href="multiple-and-logistic-regression.html#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;Hmisc&quot;</span>)</span>
<span id="cb1-10"><a href="multiple-and-logistic-regression.html#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;knitr&quot;</span>)</span>
<span id="cb1-11"><a href="multiple-and-logistic-regression.html#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lme4&quot;</span>)</span>
<span id="cb1-12"><a href="multiple-and-logistic-regression.html#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;MASS&quot;</span>)</span>
<span id="cb1-13"><a href="multiple-and-logistic-regression.html#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;mclogit&quot;</span>)</span>
<span id="cb1-14"><a href="multiple-and-logistic-regression.html#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;MuMIn&quot;</span>)</span>
<span id="cb1-15"><a href="multiple-and-logistic-regression.html#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;nlme&quot;</span>)</span>
<span id="cb1-16"><a href="multiple-and-logistic-regression.html#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ordinal&quot;</span>)</span>
<span id="cb1-17"><a href="multiple-and-logistic-regression.html#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;rms&quot;</span>)</span>
<span id="cb1-18"><a href="multiple-and-logistic-regression.html#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;robustbase&quot;</span>)</span>
<span id="cb1-19"><a href="multiple-and-logistic-regression.html#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;sjPlot&quot;</span>)</span>
<span id="cb1-20"><a href="multiple-and-logistic-regression.html#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;stringr&quot;</span>)</span>
<span id="cb1-21"><a href="multiple-and-logistic-regression.html#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tibble&quot;</span>)</span>
<span id="cb1-22"><a href="multiple-and-logistic-regression.html#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb1-23"><a href="multiple-and-logistic-regression.html#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;vcd&quot;</span>)</span>
<span id="cb1-24"><a href="multiple-and-logistic-regression.html#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;vip&quot;</span>)</span>
<span id="cb1-25"><a href="multiple-and-logistic-regression.html#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># install klippy for copy-to-clipboard button in code chunks</span></span>
<span id="cb1-26"><a href="multiple-and-logistic-regression.html#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;remotes&quot;</span>)</span>
<span id="cb1-27"><a href="multiple-and-logistic-regression.html#cb1-27" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;rlesur/klippy&quot;</span>)</span></code></pre></div>
<p>Now that we have installed the packages, we activate them as shown below.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multiple-and-logistic-regression.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set options</span></span>
<span id="cb2-2"><a href="multiple-and-logistic-regression.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">stringsAsFactors =</span> F)          <span class="co"># no automatic data transformation</span></span>
<span id="cb2-3"><a href="multiple-and-logistic-regression.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="st">&quot;scipen&quot;</span> <span class="ot">=</span> <span class="dv">100</span>, <span class="st">&quot;digits&quot;</span> <span class="ot">=</span> <span class="dv">12</span>) <span class="co"># suppress math annotation</span></span>
<span id="cb2-4"><a href="multiple-and-logistic-regression.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb2-5"><a href="multiple-and-logistic-regression.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-6"><a href="multiple-and-logistic-regression.html#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Boruta)</span>
<span id="cb2-7"><a href="multiple-and-logistic-regression.html#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb2-8"><a href="multiple-and-logistic-regression.html#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb2-9"><a href="multiple-and-logistic-regression.html#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb2-10"><a href="multiple-and-logistic-regression.html#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span>
<span id="cb2-11"><a href="multiple-and-logistic-regression.html#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb2-12"><a href="multiple-and-logistic-regression.html#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-13"><a href="multiple-and-logistic-regression.html#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb2-14"><a href="multiple-and-logistic-regression.html#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb2-15"><a href="multiple-and-logistic-regression.html#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-16"><a href="multiple-and-logistic-regression.html#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb2-17"><a href="multiple-and-logistic-regression.html#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb2-18"><a href="multiple-and-logistic-regression.html#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mclogit)</span>
<span id="cb2-19"><a href="multiple-and-logistic-regression.html#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span>
<span id="cb2-20"><a href="multiple-and-logistic-regression.html#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb2-21"><a href="multiple-and-logistic-regression.html#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span>
<span id="cb2-22"><a href="multiple-and-logistic-regression.html#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb2-23"><a href="multiple-and-logistic-regression.html#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robustbase)</span>
<span id="cb2-24"><a href="multiple-and-logistic-regression.html#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb2-25"><a href="multiple-and-logistic-regression.html#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb2-26"><a href="multiple-and-logistic-regression.html#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb2-27"><a href="multiple-and-logistic-regression.html#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb2-28"><a href="multiple-and-logistic-regression.html#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span>
<span id="cb2-29"><a href="multiple-and-logistic-regression.html#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># activate klippy for copy-to-clipboard button</span></span>
<span id="cb2-30"><a href="multiple-and-logistic-regression.html#cb2-30" aria-hidden="true" tabindex="-1"></a>klippy<span class="sc">::</span><span class="fu">klippy</span>()</span></code></pre></div>
<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>Once you have installed R and RStudio and initiated the session by executing the code shown above, you are good to go.</p>
<div id="multiple-linear-regression" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Multiple Linear Regression<a href="multiple-and-logistic-regression.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In contrast to simple linear regression, which estimates the effect of a single predictor, multiple linear regression estimates the effect of various predictor (see the equation below). A multiple linear regression can thus test the effects of various predictors simultaneously.</p>
<p><span class="math display">\[\begin{equation}

f_{(x)} = \alpha + \beta_{1}x_{i} + \beta_{2}x_{i+1} + \dots + \beta_{n}x_{i+n} + \epsilon

\end{equation}\]</span></p>
<p>There exists a wealth of literature focusing on multiple linear regressions and the concepts it is based on. For instance, there are <span class="citation">Achen (<a href="#ref-achen1982interpreting" role="doc-biblioref">1982</a>)</span>, <span class="citation">Bortz (<a href="#ref-bortz2006statistik" role="doc-biblioref">2006</a>)</span>, <span class="citation">Crawley (<a href="#ref-crawley2005statistics" role="doc-biblioref">2005</a>)</span>, <span class="citation">Faraway (<a href="#ref-faraway2002practical" role="doc-biblioref">2002</a>)</span>, <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span> (my personal favorite), <span class="citation">Gries (<a href="#ref-gries2021statistics" role="doc-biblioref">2021</a>)</span>, <span class="citation">Levshina (<a href="#ref-levshina2015linguistics" role="doc-biblioref">2015</a>)</span>, and <span class="citation">Wilcox (<a href="#ref-wilcox2009basic" role="doc-biblioref">2009</a>)</span> to name just a few. Introductions to regression modeling in R are <span class="citation">Baayen (<a href="#ref-baayen2008analyzing" role="doc-biblioref">2008</a>)</span>, <span class="citation">Crawley (<a href="#ref-crawley2012r" role="doc-biblioref">2012</a>)</span>, <span class="citation">Gries (<a href="#ref-gries2021statistics" role="doc-biblioref">2021</a>)</span>, or <span class="citation">Levshina (<a href="#ref-levshina2015linguistics" role="doc-biblioref">2015</a>)</span>.</p>
<p>The model diagnostics we are dealing with here are partly identical to the diagnostic methods discussed in the section on simple linear regression. Because of this overlap, diagnostics will only be described in more detail if they have not been described in the section on simple linear regression.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXCURSION</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<details>
<summary>
A note on sample size and power
</summary>
<p>A brief note on minimum necessary sample or data set size appears necessary here. Although there appears to be a general assumption that 25 data points per group are sufficient, this is not necessarily correct (it is merely a general rule of thumb that is actually often incorrect). Such rules of thumb are inadequate because the required sample size depends on the number of variables in a given model, the size of the effect and the variance of the effect - in other words, the minimum necessary sample size relates to <em>statistical power</em> (see <a href="https://slcladal.github.io/pwr.html">here</a> for a tutorial on power). If a model contains many variables, then this requires a larger sample size than a model which only uses very few predictors.</p>
<p>Also, to detect an effect with a very minor effect size, one needs a substantially larger sample compared to cases where the effect is very strong. In fact, when dealing with small effects, model require a minimum of 600 cases to reliably detect these effects. Finally, effects that are very robust and do not vary much require a much smaller sample size compared with effects that are spurious and vary substantially. Since the sample size depends on the effect size and variance as well as the number of variables, there is no final one-size-fits-all answer to what the best sample size is.</p>
Another, slightly better but still incorrect, rule of thumb is that the more data, the better. This is not correct because models based on too many cases are prone for overfitting and thus report correlations as being significant that are not. However, given that there are procedures that can correct for overfitting, larger data sets are still preferable to data sets that are simply too small to warrant reliable results. In conclusion, it remains true that the sample size depends on the effect under investigation.
</details>
</div>
<p>`</p>
<hr />
<p>Despite there being no ultimate rule of thumb, <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012, 273–75</a>)</span>, based on <span class="citation">Green (<a href="#ref-green1991many" role="doc-biblioref">1991</a>)</span>, provide data-driven suggestions for the minimal size of data required for regression models that aim to find medium sized effects (k = number of predictors; categorical variables with more than two levels should be transformed into dummy variables):</p>
<ul>
<li><p>If one is merely interested in the overall model fit (something I have not encountered), then the sample size should be at least 50 + k (k = number of predictors in model).</p></li>
<li><p>If one is only interested in the effect of specific variables, then the sample size should be at least 104 + k (k = number of predictors in model).</p></li>
<li><p>If one is only interested in both model fit and the effect of specific variables, then the sample size should be at least the higher value of 50 + k or 104 + k (k = number of predictors in model).</p></li>
</ul>
<p>You will see in the R code below that there is already a function that tests whether the sample size is sufficient.</p>
<div id="example-gifts-and-availability" class="section level3 hasAnchor" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Example: Gifts and Availability<a href="multiple-and-logistic-regression.html#example-gifts-and-availability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The example we will go through here is taken from <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span>. In this example, the research question is if the money that men spend on presents for women depends on the women’s attractiveness and their relationship status. To answer this research question, we will implement a multiple linear regression and start by loading the data and inspect its structure and properties.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multiple-and-logistic-regression.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb3-2"><a href="multiple-and-logistic-regression.html#cb3-2" aria-hidden="true" tabindex="-1"></a>mlrdata  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">&quot;https://slcladal.github.io/data/mld.rda&quot;</span>, <span class="st">&quot;rb&quot;</span>))</span></code></pre></div>
<template id="64b79920-7850-4b23-b039-03510fd795d9"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-c32c094c{table-layout:auto;width:75%;}.cl-c3213968{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c3213986{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c3216d8e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c3216da2{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c321e188{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e192{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e19c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e19d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1a6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1a7{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1b0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1b1{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1b2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1ba{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1bb{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c321e1bc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-c32c094c'>
<caption class="Table Caption">
<p><span id="tab:mlr2b">Table 9.1: </span>First 15 rows of the mlrdata.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-c321e1bb"><p class="cl-c3216d8e"><span class="cl-c3213968">status</span></p></td><td class="cl-c321e1ba"><p class="cl-c3216d8e"><span class="cl-c3213968">attraction</span></p></td><td class="cl-c321e1bc"><p class="cl-c3216da2"><span class="cl-c3213968">money</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">86.33</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">45.58</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">68.43</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">52.93</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">61.86</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">48.47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">32.79</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">35.91</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">30.98</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">44.82</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">35.05</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">64.49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e19c"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e188"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e192"><p class="cl-c3216da2"><span class="cl-c3213986">54.50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1a7"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e19d"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1a6"><p class="cl-c3216da2"><span class="cl-c3213986">61.48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c321e1b2"><p class="cl-c3216d8e"><span class="cl-c3213986">Relationship</span></p></td><td class="cl-c321e1b1"><p class="cl-c3216d8e"><span class="cl-c3213986">NotInterested</span></p></td><td class="cl-c321e1b0"><p class="cl-c3216da2"><span class="cl-c3213986">55.51</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="155777d5-faa8-4d9a-81de-29bc2422c360"></div>
<script>
var dest = document.getElementById("155777d5-faa8-4d9a-81de-29bc2422c360");
var template = document.getElementById("64b79920-7850-4b23-b039-03510fd795d9");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>The data set consist of three variables stored in three columns. The first column contains the relationship status of the present giver (in this study this were men), the second whether the man is interested in the woman (the present receiver in this study), and the third column represents the money spend on the present. The data set represents 100 cases and the mean amount of money spend on a present is 88.38 dollars. In a next step, we visualize the data to get a more detailed impression of the relationships between variables.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="multiple-and-logistic-regression.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create plots</span></span>
<span id="cb4-2"><a href="multiple-and-logistic-regression.html#cb4-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(status, money)) <span class="sc">+</span>   <span class="co"># data + x/y-axes</span></span>
<span id="cb4-3"><a href="multiple-and-logistic-regression.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="fu">c</span>(<span class="st">&quot;grey30&quot;</span>, <span class="st">&quot;grey70&quot;</span>)) <span class="sc">+</span>  <span class="co"># def. col.</span></span>
<span id="cb4-4"><a href="multiple-and-logistic-regression.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>)<span class="sc">+</span>   <span class="co"># black and white theme</span></span>
<span id="cb4-5"><a href="multiple-and-logistic-regression.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span>                              <span class="co"># x-axis label</span></span>
<span id="cb4-6"><a href="multiple-and-logistic-regression.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Money spent on present (AUD)&quot;</span>, <span class="at">cex =</span> .<span class="dv">75</span>) <span class="sc">+</span>   <span class="co"># y-axis label</span></span>
<span id="cb4-7"><a href="multiple-and-logistic-regression.html#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">250</span>)) <span class="sc">+</span>         <span class="co"># y-axis range</span></span>
<span id="cb4-8"><a href="multiple-and-logistic-regression.html#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>                      <span class="co"># no legend</span></span>
<span id="cb4-9"><a href="multiple-and-logistic-regression.html#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Status&quot;</span>)                           <span class="co"># title</span></span>
<span id="cb4-10"><a href="multiple-and-logistic-regression.html#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 2</span></span>
<span id="cb4-11"><a href="multiple-and-logistic-regression.html#cb4-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(attraction, money)) <span class="sc">+</span></span>
<span id="cb4-12"><a href="multiple-and-logistic-regression.html#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="fu">c</span>(<span class="st">&quot;grey30&quot;</span>, <span class="st">&quot;grey70&quot;</span>)) <span class="sc">+</span></span>
<span id="cb4-13"><a href="multiple-and-logistic-regression.html#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb4-14"><a href="multiple-and-logistic-regression.html#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span>                              <span class="co"># x-axis label</span></span>
<span id="cb4-15"><a href="multiple-and-logistic-regression.html#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Money spent on present (AUD)&quot;</span>) <span class="sc">+</span>  <span class="co"># y-axis label</span></span>
<span id="cb4-16"><a href="multiple-and-logistic-regression.html#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">250</span>)) <span class="sc">+</span></span>
<span id="cb4-17"><a href="multiple-and-logistic-regression.html#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="multiple-and-logistic-regression.html#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Attraction&quot;</span>)</span>
<span id="cb4-19"><a href="multiple-and-logistic-regression.html#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 3</span></span>
<span id="cb4-20"><a href="multiple-and-logistic-regression.html#cb4-20" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(<span class="at">x =</span> money)) <span class="sc">+</span></span>
<span id="cb4-21"><a href="multiple-and-logistic-regression.html#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..),          <span class="co"># add density statistic</span></span>
<span id="cb4-22"><a href="multiple-and-logistic-regression.html#cb4-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">10</span>,               <span class="co"># def. bin width</span></span>
<span id="cb4-23"><a href="multiple-and-logistic-regression.html#cb4-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>,            <span class="co"># def. bar edge colour</span></span>
<span id="cb4-24"><a href="multiple-and-logistic-regression.html#cb4-24" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span>            <span class="co"># def. bar col.</span></span>
<span id="cb4-25"><a href="multiple-and-logistic-regression.html#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span>                                <span class="co"># black-white theme</span></span>
<span id="cb4-26"><a href="multiple-and-logistic-regression.html#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span>.<span class="dv">2</span>, <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>) <span class="sc">+</span>   <span class="co"># def. col. of overlay</span></span>
<span id="cb4-27"><a href="multiple-and-logistic-regression.html#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Money spent on present (AUD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-28"><a href="multiple-and-logistic-regression.html#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density of frequency&quot;</span>)</span>
<span id="cb4-29"><a href="multiple-and-logistic-regression.html#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 4</span></span>
<span id="cb4-30"><a href="multiple-and-logistic-regression.html#cb4-30" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(status, money)) <span class="sc">+</span></span>
<span id="cb4-31"><a href="multiple-and-logistic-regression.html#cb4-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">notch =</span> F, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">factor</span>(status))) <span class="sc">+</span> <span class="co"># create boxplot</span></span>
<span id="cb4-32"><a href="multiple-and-logistic-regression.html#cb4-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;grey30&quot;</span>, <span class="st">&quot;grey70&quot;</span>)) <span class="sc">+</span>   <span class="co"># def. col. palette</span></span>
<span id="cb4-33"><a href="multiple-and-logistic-regression.html#cb4-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> attraction, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span>        <span class="co"># separate panels for attraction</span></span>
<span id="cb4-34"><a href="multiple-and-logistic-regression.html#cb4-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-35"><a href="multiple-and-logistic-regression.html#cb4-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Money spent on present (AUD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-36"><a href="multiple-and-logistic-regression.html#cb4-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">250</span>)) <span class="sc">+</span></span>
<span id="cb4-37"><a href="multiple-and-logistic-regression.html#cb4-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-38"><a href="multiple-and-logistic-regression.html#cb4-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>)</span>
<span id="cb4-39"><a href="multiple-and-logistic-regression.html#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="co"># show plots</span></span>
<span id="cb4-40"><a href="multiple-and-logistic-regression.html#cb4-40" aria-hidden="true" tabindex="-1"></a>vip<span class="sc">::</span><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> <span class="fu">list</span>(p1, p2, p3, p4), <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">layout_matrix =</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>)))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr3-1.png" width="672" /></p>
<p>The upper left figure consists of a boxplot which shows how much money was spent by relationship status. The figure suggests that men spend more on women if they are not in a relationship. The next figure shows the relationship between the money spend on presents and whether or not the men were interested in the women.</p>
<p>The boxplot in the upper right panel suggests that men spend substantially more on women if the men are interested in them. The next figure depicts the distribution of the amounts of money spend on the presents for the women. In addition, the figure indicates the existence of two outliers (dots in the boxplot)</p>
<p>The histogram in the lower left panel shows that, although the mean amount of money spent on presents is 88.38 dollars, the distribution peaks around 50 dollars indicating that on average, men spend about 50 dollars on presents. Finally, we will plot the amount of money spend on presents against relationship status by attraction in order to check whether the money spent on presents is affected by an interaction between attraction and relationship status.</p>
<p>The boxplot in the lower right panel confirms the existence of an interaction (a non-additive term) as men only spend more money on women if the men single <em>and</em> they are interested in the women. If men are not interested in the women, then the relationship has no effect as they spend an equal amount of money on the women regardless of whether they are in a relationship or not.</p>
<p>We will now start to implement the regression model. In a first step, we create two saturated models that contain all possible predictors (main effects and interactions). The two models are identical but one is generated with the <code>lm</code> and the other with the <code>glm</code> function as these functions offer different model parameters in their output.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="multiple-and-logistic-regression.html#cb5-1" aria-hidden="true" tabindex="-1"></a>m1.mlr <span class="ot">=</span> <span class="fu">lm</span>(                      <span class="co"># generate lm regression object</span></span>
<span id="cb5-2"><a href="multiple-and-logistic-regression.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> attraction<span class="sc">*</span>status,  <span class="co"># def. regression formula (1 = intercept)</span></span>
<span id="cb5-3"><a href="multiple-and-logistic-regression.html#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                 <span class="co"># def. data</span></span>
<span id="cb5-4"><a href="multiple-and-logistic-regression.html#cb5-4" aria-hidden="true" tabindex="-1"></a>m1.glm <span class="ot">=</span> <span class="fu">glm</span>(                     <span class="co"># generate glm regression object</span></span>
<span id="cb5-5"><a href="multiple-and-logistic-regression.html#cb5-5" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> attraction<span class="sc">*</span>status,  <span class="co"># def. regression formula (1 = intercept)</span></span>
<span id="cb5-6"><a href="multiple-and-logistic-regression.html#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> gaussian,              <span class="co"># def. linkage function</span></span>
<span id="cb5-7"><a href="multiple-and-logistic-regression.html#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                 <span class="co"># def. data</span></span></code></pre></div>
<p>After generating the saturated models we can now start with the model fitting. Model fitting refers to a process that aims at find the model that explains a maximum of variance with a minimum of predictors <span class="citation">(see <a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 318</a>)</span>. Model fitting is therefore based on the <em>principle of parsimony</em> which is related to Occam’s razor according to which explanations that require fewer assumptions are more likely to be true.</p>
</div>
<div id="automatic-model-fitting-and-why-you-should-not-use-it" class="section level3 hasAnchor" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Automatic Model Fitting and Why You Should Not Use It<a href="multiple-and-logistic-regression.html#automatic-model-fitting-and-why-you-should-not-use-it" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section, we will use a step-wise step-down procedure that uses decreases in AIC (<em>Akaike Information Criterion</em>) as the criterion to minimize the model in a step-wise manner. This procedure aims at finding the model with the lowest AIC values by evaluating - step-by-step - whether the removal of a predictor (term) leads to a lower AIC value.</p>
<p>We use this method here just so that you know it exists and how to implement it but you should rather avoid using automated model fitting. The reason for avoiding automated model fitting is that the algorithm only checks if the AIC has decreased but not if the model is stable or reliable. Thus, automated model fitting has the problem that you can never be sure that the way that lead you to the final model is reliable and that all models were indeed stable. Imagine you want to climb down from a roof top and you have a ladder. The problem is that you do not know if and how many steps are broken. This is similar to using automated model fitting. In other sections, we will explore better methods to fit models (manual step-wise step-up and step-down procedures, for example).</p>
<p>The AIC is calculated using the equation below. The lower the AIC value, the better the balance between explained variance and the number of predictors. AIC values can and should only be compared for models that are fit on the same data set with the same (number of) cases (<em>LL</em> stands for <em>logged likelihood</em> or <em>LogLikelihood</em> and <em>k</em> represents the number of predictors in the model (including the intercept); the LL represents a measure of how good the model fits the data).</p>
<p><span class="math display">\[\begin{equation}
Akaike Information Criterion (AIC) = -2LL + 2k
\end{equation}\]</span></p>
<p>An alternative to the AIC is the BIC (Bayesian Information Criterion). Both AIC and BIC penalize models for including variables in a model. The penalty of the BIC is bigger than the penalty of the AIC and it includes the number of cases in the model (<em>LL</em> stands for <em>logged likelihood</em> or <em>LogLikelihood</em>, <em>k</em> represents the number of predictors in the model (including the intercept), and <em>N</em> represents the number of cases in the model).</p>
<p><span class="math display">\[\begin{equation}
Bayesian Information Criterion (BIC) = -2LL + 2k * log(N)
\end{equation}\]</span></p>
<p>Interactions are evaluated first and only if all insignificant interactions have been removed would the procedure start removing insignificant main effects (that are not part of significant interactions). Other model fitting procedures (forced entry, step-wise step up, hierarchical) are discussed during the implementation of other regression models. We cannot discuss all procedures here as model fitting is rather complex and a discussion of even the most common procedures would to lengthy and time consuming at this point. It is important to note though that there is not perfect model fitting procedure and automated approaches should be handled with care as they are likely to ignore violations of model parameters that can be detected during manual - but time consuming - model fitting procedures. As a general rule of thumb, it is advisable to fit models as carefully and deliberately as possible. We will now begin to fit the model.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="multiple-and-logistic-regression.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># automated AIC based model fitting</span></span>
<span id="cb6-2"><a href="multiple-and-logistic-regression.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(m1.mlr, <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=592.52
## money ~ 1 + attraction * status
## 
##                     Df   Sum of Sq         RSS         AIC
## &lt;none&gt;                             34557.56428 592.5211556
## - attraction:status  1 24947.25481 59504.81909 644.8642395</code></pre>
<pre><code>## 
## Call:
## lm(formula = money ~ 1 + attraction * status, data = mlrdata)
## 
## Coefficients:
##                          (Intercept)               attractionNotInterested  
##                              99.1548                              -47.6628  
##                         statusSingle  attractionNotInterested:statusSingle  
##                              57.6928                              -63.1788</code></pre>
<p>The automated model fitting procedure informs us that removing predictors has not caused a decrease in the AIC. The saturated model is thus also the final minimal adequate model. We will now inspect the final minimal model and go over the model report.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="multiple-and-logistic-regression.html#cb9-1" aria-hidden="true" tabindex="-1"></a>m2.mlr <span class="ot">=</span> <span class="fu">lm</span>(                       <span class="co"># generate lm regression object</span></span>
<span id="cb9-2"><a href="multiple-and-logistic-regression.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> (status <span class="sc">+</span> attraction)<span class="sc">^</span><span class="dv">2</span>, <span class="co"># def. regression formula</span></span>
<span id="cb9-3"><a href="multiple-and-logistic-regression.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                  <span class="co"># def. data</span></span>
<span id="cb9-4"><a href="multiple-and-logistic-regression.html#cb9-4" aria-hidden="true" tabindex="-1"></a>m2.glm <span class="ot">=</span> <span class="fu">glm</span>(                      <span class="co"># generate glm regression object</span></span>
<span id="cb9-5"><a href="multiple-and-logistic-regression.html#cb9-5" aria-hidden="true" tabindex="-1"></a>  money <span class="sc">~</span> (status <span class="sc">+</span> attraction)<span class="sc">^</span><span class="dv">2</span>, <span class="co"># def. regression formula</span></span>
<span id="cb9-6"><a href="multiple-and-logistic-regression.html#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> gaussian,               <span class="co"># def. linkage function</span></span>
<span id="cb9-7"><a href="multiple-and-logistic-regression.html#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mlrdata)                  <span class="co"># def. data</span></span>
<span id="cb9-8"><a href="multiple-and-logistic-regression.html#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect final minimal model</span></span>
<span id="cb9-9"><a href="multiple-and-logistic-regression.html#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = money ~ (status + attraction)^2, data = mlrdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -45.0760 -14.2580   0.4596  11.9315  44.1424 
## 
## Coefficients:
##                                          Estimate   Std. Error  t value
## (Intercept)                           99.15480000   3.79459947 26.13050
## statusSingle                          57.69280000   5.36637403 10.75080
## attractionNotInterested              -47.66280000   5.36637403 -8.88175
## statusSingle:attractionNotInterested -63.17880000   7.58919893 -8.32483
##                                                    Pr(&gt;|t|)    
## (Intercept)                          &lt; 0.000000000000000222 ***
## statusSingle                         &lt; 0.000000000000000222 ***
## attractionNotInterested                 0.00000000000003751 ***
## statusSingle:attractionNotInterested    0.00000000000058085 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.9729973 on 96 degrees of freedom
## Multiple R-squared:  0.852041334,    Adjusted R-squared:  0.847417626 
## F-statistic: 184.276619 on 3 and 96 DF,  p-value: &lt; 0.0000000000000002220446</code></pre>
<p>The first element of the report is called <em>Call</em> and it reports the regression formula of the model. Then, the report provides the residual distribution (the range, median and quartiles of the residuals) which allows drawing inferences about the distribution of differences between observed and expected values. If the residuals are distributed non-normally, then this is a strong indicator that the model is unstable and unreliable because mathematical assumptions on which the model is based are violated.</p>
<p>Next, the model summary reports the most important part: a table with model statistics of the fixed-effects structure of the model. The table contains the estimates (coefficients of the predictors), standard errors, t-values, and the p-values which show whether a predictor significantly correlates with the dependent variable that the model investigates.</p>
<p>All main effects (status and attraction) as well as the interaction between status and attraction is reported as being significantly correlated with the dependent variable (money). An interaction occurs if a correlation between the dependent variable and a predictor is affected by another predictor.</p>
<p>The top most term is called intercept and has a value of 99.15 which represents the base estimate to which all other estimates refer. To exemplify what this means, let us consider what the model would predict that a man would spend on a present if he interested in the woman but he is also in a relationship. The amount he would spend (based on the model would be 99.15 dollars (which is the intercept). This means that the intercept represents the predicted value if all predictors take the base or reference level. And since being in relationship but being interested are the case, and because the interaction does not apply, the predicted value in our example is exactly the intercept (see below).</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multiple-and-logistic-regression.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intercept  Single  NotInterested  Single:NotInterested</span></span>
<span id="cb11-2"><a href="multiple-and-logistic-regression.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">+</span> <span class="fl">57.69</span>  <span class="sc">+</span> <span class="dv">0</span>           <span class="sc">+</span> <span class="dv">0</span>     <span class="co"># 156.8 single + interested</span></span></code></pre></div>
<pre><code>## [1] 156.84</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multiple-and-logistic-regression.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">+</span> <span class="fl">57.69</span>  <span class="sc">-</span> <span class="fl">47.66</span>       <span class="sc">-</span> <span class="fl">63.18</span> <span class="co"># 46.00 single + not interested</span></span></code></pre></div>
<pre><code>## [1] 46</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="multiple-and-logistic-regression.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">-</span> <span class="dv">0</span>      <span class="sc">+</span> <span class="dv">0</span>           <span class="sc">-</span> <span class="dv">0</span>     <span class="co"># 99.15 relationship + interested</span></span></code></pre></div>
<pre><code>## [1] 99.15</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="multiple-and-logistic-regression.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">99.15</span>     <span class="sc">-</span> <span class="dv">0</span>      <span class="sc">-</span> <span class="fl">47.66</span>       <span class="sc">-</span> <span class="dv">0</span>     <span class="co"># 51.49 relationship + not interested</span></span></code></pre></div>
<pre><code>## [1] 51.49</code></pre>
<p>Now, let us consider what a man would spend if he is in a relationship and he is not attracted to the women. In that case, the model predicts that the man would spend only 51.49 dollars on a present: the intercept (99.15) minus 47.66 because the man is not interested (and no additional subtraction because the interaction does not apply).</p>
<p>We can derive the same results easier using the <code>predict</code> function.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="multiple-and-logistic-regression.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make prediction based on the model for original data</span></span>
<span id="cb19-2"><a href="multiple-and-logistic-regression.html#cb19-2" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2.mlr, <span class="at">newdata =</span> mlrdata)</span>
<span id="cb19-3"><a href="multiple-and-logistic-regression.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect predictions</span></span>
<span id="cb19-4"><a href="multiple-and-logistic-regression.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">round</span>(prediction,<span class="dv">2</span>))</span></code></pre></div>
<pre><code>## 
##  46.01  51.49  99.15 156.85 
##     25     25     25     25</code></pre>
<p>Below the table of coefficients, the regression summary reports model statistics that provide information about how well the model performs. The difference between the values and the values in the coefficients table is that the model statistics refer to the model as a whole rather than focusing on individual predictors.</p>
<p>The multiple R<sup>2</sup>-value is a measure of how much variance the model explains. A multiple R<sup>2</sup>-value of 0 would inform us that the model does not explain any variance while a value of .852 mean that the model explains 85.2 percent of the variance. A value of 1 would inform us that the model explains 100 percent of the variance and that the predictions of the model match the observed values perfectly. Multiplying the multiple R<sup>2</sup>-value thus provides the percentage of explained variance. Models that have a multiple R<sup>2</sup>-value equal or higher than .05 are deemed substantially significant <span class="citation">(see <a href="#ref-szmrecsanyi2006morphosyntactic" role="doc-biblioref">Szmrecsanyi 2006, 55</a>)</span>. It has been claimed that models should explain a minimum of 5 percent of variance but this is problematic as it is not uncommon for models to have very low explanatory power while still performing significantly and systematically better than chance. In addition, the total amount of variance is negligible in cases where one is interested in very weak but significant effects. It is much more important for model to perform significantly better than minimal base-line models because if this is not the case, then the model does not have any predictive and therefore no explanatory power.</p>
<p>The adjusted R<sup>2</sup>-value considers the amount of explained variance in light of the number of predictors in the model (it is thus somewhat similar to the AIC and BIC) and informs about how well the model would perform if it were applied to the population that the sample is drawn from. Ideally, the difference between multiple and adjusted R<sup>2</sup>-value should be very small as this means that the model is not overfitted. If, however, the difference between multiple and adjusted R<sup>2</sup>-value is substantial, then this would strongly suggest that the model is unstable and overfitted to the data while being inadequate for drawing inferences about the population. Differences between multiple and adjusted R<sup>2</sup>-values indicate that the data contains outliers that cause the distribution of the data on which the model is based to differ from the distributions that the model mathematically requires to provide reliable estimates. The difference between multiple and adjusted R<sup>2</sup>-value in our model is very small (85.2-84.7=.05) and should not cause concern.</p>
<p>Before continuing, we will calculate the confidence intervals of the coefficients.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="multiple-and-logistic-regression.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract confidence intervals of the coefficients</span></span>
<span id="cb21-2"><a href="multiple-and-logistic-regression.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2.mlr)</span></code></pre></div>
<pre><code>##                                               2.5 %         97.5 %
## (Intercept)                           91.6225795890 106.6870204110
## statusSingle                          47.0406317400  68.3449682600
## attractionNotInterested              -58.3149682600 -37.0106317400
## statusSingle:attractionNotInterested -78.2432408219 -48.1143591781</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="multiple-and-logistic-regression.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create and compare baseline- and minimal adequate model</span></span>
<span id="cb23-2"><a href="multiple-and-logistic-regression.html#cb23-2" aria-hidden="true" tabindex="-1"></a>m0.mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(money <span class="sc">~</span><span class="dv">1</span>, <span class="at">data =</span> mlrdata)</span>
<span id="cb23-3"><a href="multiple-and-logistic-regression.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0.mlr, m2.mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: money ~ 1
## Model 2: money ~ (status + attraction)^2
##   Res.Df          RSS Df   Sum of Sq         F                 Pr(&gt;F)    
## 1     99 233562.28650                                                    
## 2     96  34557.56428  3 199004.7222 184.27662 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now, we compare the final minimal adequate model to the base-line model to test whether then final model significantly outperforms the baseline model.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="multiple-and-logistic-regression.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare baseline- and minimal adequate model</span></span>
<span id="cb25-2"><a href="multiple-and-logistic-regression.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(m0.mlr, m2.mlr, <span class="at">type =</span> <span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: money
##                  Sum Sq Df    F value                 Pr(&gt;F)    
## (Intercept) 781015.8300  1 2169.64133 &lt; 0.000000000000000222 ***
## Residuals    34557.5643 96                                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The comparison between the two model confirms that the minimal adequate model performs significantly better (makes significantly more accurate estimates of the outcome variable) compared with the baseline model.</p>
</div>
<div id="outlier-detection" class="section level3 hasAnchor" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Outlier Detection<a href="multiple-and-logistic-regression.html#outlier-detection" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After implementing the multiple regression, we now need to look for outliers and perform the model diagnostics by testing whether removing data points disproportionately decreases model fit. To begin with, we generate diagnostic plots.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="multiple-and-logistic-regression.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate plots</span></span>
<span id="cb27-2"><a href="multiple-and-logistic-regression.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(m2.mlr) <span class="sc">+</span> </span>
<span id="cb27-3"><a href="multiple-and-logistic-regression.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb27-4"><a href="multiple-and-logistic-regression.html#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr11-1.png" width="672" /></p>
<p>The plots do not show severe problems such as funnel shaped patterns or drastic deviations from the diagonal line in Normal Q-Q plot (have a look at the explanation of what to look for and how to interpret these diagnostic plots in the section on simple linear regression) but data points 52, 64, and 83 are repeatedly indicated as potential outliers.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="multiple-and-logistic-regression.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine a cutoff for data points that have D-values higher than 4/(n-k-1)</span></span>
<span id="cb28-2"><a href="multiple-and-logistic-regression.html#cb28-2" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>((<span class="fu">nrow</span>(mlrdata)<span class="sc">-</span><span class="fu">length</span>(m2.mlr<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">2</span>))</span>
<span id="cb28-3"><a href="multiple-and-logistic-regression.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># start plotting</span></span>
<span id="cb28-4"><a href="multiple-and-logistic-regression.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))           <span class="co"># display plots in 3 rows/2 columns</span></span>
<span id="cb28-5"><a href="multiple-and-logistic-regression.html#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(m2.mlr, <span class="at">main=</span><span class="st">&quot;QQ Plot&quot;</span>) <span class="co"># create qq-plot</span></span></code></pre></div>
<pre><code>## [1] 52 83</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="multiple-and-logistic-regression.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2.mlr, <span class="at">which=</span><span class="dv">4</span>, <span class="at">cook.levels =</span> cutoff); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr12-1.png" width="672" /></p>
<p>The graphs indicate that data points 52, 64, and 83 may be problematic. We will therefore statistically evaluate whether these data points need to be removed. In order to find out which data points require removal, we extract the influence measure statistics and add them to out data set.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="multiple-and-logistic-regression.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract influence statistics</span></span>
<span id="cb31-2"><a href="multiple-and-logistic-regression.html#cb31-2" aria-hidden="true" tabindex="-1"></a>infl <span class="ot">&lt;-</span> <span class="fu">influence.measures</span>(m2.mlr)</span>
<span id="cb31-3"><a href="multiple-and-logistic-regression.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># add infl. statistics to data</span></span>
<span id="cb31-4"><a href="multiple-and-logistic-regression.html#cb31-4" aria-hidden="true" tabindex="-1"></a>mlrdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mlrdata, infl[[<span class="dv">1</span>]], infl[[<span class="dv">2</span>]])</span>
<span id="cb31-5"><a href="multiple-and-logistic-regression.html#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># annotate too influential data points</span></span>
<span id="cb31-6"><a href="multiple-and-logistic-regression.html#cb31-6" aria-hidden="true" tabindex="-1"></a>remove <span class="ot">&lt;-</span> <span class="fu">apply</span>(infl<span class="sc">$</span>is.inf, <span class="dv">1</span>, <span class="cf">function</span>(x) {</span>
<span id="cb31-7"><a href="multiple-and-logistic-regression.html#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="cn">TRUE</span>, <span class="fu">return</span>(<span class="st">&quot;remove&quot;</span>), <span class="fu">return</span>(<span class="st">&quot;keep&quot;</span>)) } )</span>
<span id="cb31-8"><a href="multiple-and-logistic-regression.html#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># add annotation to data</span></span>
<span id="cb31-9"><a href="multiple-and-logistic-regression.html#cb31-9" aria-hidden="true" tabindex="-1"></a>mlrdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mlrdata, remove)</span>
<span id="cb31-10"><a href="multiple-and-logistic-regression.html#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># number of rows before removing outliers</span></span>
<span id="cb31-11"><a href="multiple-and-logistic-regression.html#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mlrdata)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="multiple-and-logistic-regression.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove outliers</span></span>
<span id="cb33-2"><a href="multiple-and-logistic-regression.html#cb33-2" aria-hidden="true" tabindex="-1"></a>mlrdata <span class="ot">&lt;-</span> mlrdata[mlrdata<span class="sc">$</span>remove <span class="sc">==</span> <span class="st">&quot;keep&quot;</span>, ]</span>
<span id="cb33-3"><a href="multiple-and-logistic-regression.html#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># number of rows after removing outliers</span></span>
<span id="cb33-4"><a href="multiple-and-logistic-regression.html#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mlrdata)</span></code></pre></div>
<pre><code>## [1] 98</code></pre>
<p>The difference in row in the data set before and after removing data points indicate that two data points which represented outliers have been removed.</p>
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
<b>NOTE</b><br><br>In general, outliers should not simply be removed unless there are good reasons for it (this could be that the outliers represent measurement errors). If a data set contains outliers, one should rather switch to methods that are better at handling outliers, e.g. by using weights to account for data points with high leverage. One alternative would be to switch to a robust regression (see <a href="https://slcladal.github.io/regression.html#16_Robust_Regression">here</a>). However, here we show how to proceed by removing outliers as this is a common, though potentially problematic, method of dealing with outliers.
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<p><br></p>
</div>
<div id="rerun-regression" class="section level3 hasAnchor" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> Rerun Regression<a href="multiple-and-logistic-regression.html#rerun-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As we have decided to remove the outliers which means that we are now dealing with a different data set, we need to rerun the regression analysis. As the steps are identical to the regression analysis performed above, the steps will not be described in greater detail.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="multiple-and-logistic-regression.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># recreate regression models on new data</span></span>
<span id="cb35-2"><a href="multiple-and-logistic-regression.html#cb35-2" aria-hidden="true" tabindex="-1"></a>m0.mlr <span class="ot">=</span> <span class="fu">lm</span>(money <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mlrdata)</span>
<span id="cb35-3"><a href="multiple-and-logistic-regression.html#cb35-3" aria-hidden="true" tabindex="-1"></a>m0.glm <span class="ot">=</span> <span class="fu">glm</span>(money <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> gaussian, <span class="at">data =</span> mlrdata)</span>
<span id="cb35-4"><a href="multiple-and-logistic-regression.html#cb35-4" aria-hidden="true" tabindex="-1"></a>m1.mlr <span class="ot">=</span> <span class="fu">lm</span>(money <span class="sc">~</span> (status <span class="sc">+</span> attraction)<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> mlrdata)</span>
<span id="cb35-5"><a href="multiple-and-logistic-regression.html#cb35-5" aria-hidden="true" tabindex="-1"></a>m1.glm <span class="ot">=</span> <span class="fu">glm</span>(money <span class="sc">~</span> status <span class="sc">*</span> attraction, <span class="at">family =</span> gaussian,</span>
<span id="cb35-6"><a href="multiple-and-logistic-regression.html#cb35-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> mlrdata)</span>
<span id="cb35-7"><a href="multiple-and-logistic-regression.html#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># automated AIC based model fitting</span></span>
<span id="cb35-8"><a href="multiple-and-logistic-regression.html#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(m1.mlr, <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=570.29
## money ~ (status + attraction)^2
## 
##                     Df   Sum of Sq         RSS         AIC
## &lt;none&gt;                             30411.31714 570.2850562
## - status:attraction  1 21646.86199 52058.17914 620.9646729</code></pre>
<pre><code>## 
## Call:
## lm(formula = money ~ (status + attraction)^2, data = mlrdata)
## 
## Coefficients:
##                          (Intercept)                          statusSingle  
##                           99.1548000                            55.8535333  
##              attractionNotInterested  statusSingle:attractionNotInterested  
##                          -47.6628000                           -59.4613667</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="multiple-and-logistic-regression.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new final models</span></span>
<span id="cb38-2"><a href="multiple-and-logistic-regression.html#cb38-2" aria-hidden="true" tabindex="-1"></a>m2.mlr <span class="ot">=</span> <span class="fu">lm</span>(money <span class="sc">~</span> (status <span class="sc">+</span> attraction)<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> mlrdata)</span>
<span id="cb38-3"><a href="multiple-and-logistic-regression.html#cb38-3" aria-hidden="true" tabindex="-1"></a>m2.glm <span class="ot">=</span> <span class="fu">glm</span>(money <span class="sc">~</span> status <span class="sc">*</span> attraction, <span class="at">family =</span> gaussian,</span>
<span id="cb38-4"><a href="multiple-and-logistic-regression.html#cb38-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> mlrdata)</span>
<span id="cb38-5"><a href="multiple-and-logistic-regression.html#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect final minimal model</span></span>
<span id="cb38-6"><a href="multiple-and-logistic-regression.html#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = money ~ (status + attraction)^2, data = mlrdata)
## 
## Residuals:
##          Min           1Q       Median           3Q          Max 
## -35.76416667 -13.50520000  -0.98948333  10.59887500  38.77166667 
## 
## Coefficients:
##                                          Estimate   Std. Error  t value
## (Intercept)                           99.15480000   3.59735820 27.56323
## statusSingle                          55.85353333   5.14015367 10.86612
## attractionNotInterested              -47.66280000   5.08743275 -9.36873
## statusSingle:attractionNotInterested -59.46136667   7.26927504 -8.17982
##                                                    Pr(&gt;|t|)    
## (Intercept)                          &lt; 0.000000000000000222 ***
## statusSingle                         &lt; 0.000000000000000222 ***
## attractionNotInterested               0.0000000000000040429 ***
## statusSingle:attractionNotInterested  0.0000000000013375166 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 17.986791 on 94 degrees of freedom
## Multiple R-squared:  0.857375902,    Adjusted R-squared:  0.852824069 
## F-statistic: 188.358387 on 3 and 94 DF,  p-value: &lt; 0.0000000000000002220446</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="multiple-and-logistic-regression.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract confidence intervals of the coefficients</span></span>
<span id="cb40-2"><a href="multiple-and-logistic-regression.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2.mlr)</span></code></pre></div>
<pre><code>##                                               2.5 %         97.5 %
## (Intercept)                           92.0121609656 106.2974390344
## statusSingle                          45.6476377202  66.0594289465
## attractionNotInterested              -57.7640169936 -37.5615830064
## statusSingle:attractionNotInterested -73.8946826590 -45.0280506744</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="multiple-and-logistic-regression.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare baseline with final model</span></span>
<span id="cb42-2"><a href="multiple-and-logistic-regression.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0.mlr, m2.mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: money ~ 1
## Model 2: money ~ (status + attraction)^2
##   Res.Df          RSS Df   Sum of Sq         F                 Pr(&gt;F)    
## 1     97 213227.06081                                                    
## 2     94  30411.31714  3 182815.7437 188.35839 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="multiple-and-logistic-regression.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare baseline with final model</span></span>
<span id="cb44-2"><a href="multiple-and-logistic-regression.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(m0.mlr, m2.mlr, <span class="at">type =</span> <span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: money
##                  Sum Sq Df    F value                 Pr(&gt;F)    
## (Intercept) 760953.2107  1 2352.07181 &lt; 0.000000000000000222 ***
## Residuals    30411.3171 94                                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="additional-model-diagnostics" class="section level3 hasAnchor" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> Additional Model Diagnostics<a href="multiple-and-logistic-regression.html#additional-model-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After rerunning the regression analysis on the updated data set, we again create diagnostic plots in order to check whether there are potentially problematic data points.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="multiple-and-logistic-regression.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate plots</span></span>
<span id="cb46-2"><a href="multiple-and-logistic-regression.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(m2.mlr) <span class="sc">+</span> </span>
<span id="cb46-3"><a href="multiple-and-logistic-regression.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb46-4"><a href="multiple-and-logistic-regression.html#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr19-1.png" width="672" /></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="multiple-and-logistic-regression.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine a cutoff for data points that have</span></span>
<span id="cb47-2"><a href="multiple-and-logistic-regression.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># D-values higher than 4/(n-k-1)</span></span>
<span id="cb47-3"><a href="multiple-and-logistic-regression.html#cb47-3" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>((<span class="fu">nrow</span>(mlrdata)<span class="sc">-</span><span class="fu">length</span>(m2.mlr<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">2</span>))</span>
<span id="cb47-4"><a href="multiple-and-logistic-regression.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># start plotting</span></span>
<span id="cb47-5"><a href="multiple-and-logistic-regression.html#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))           <span class="co"># display plots in 1 row/2 columns</span></span>
<span id="cb47-6"><a href="multiple-and-logistic-regression.html#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(m2.mlr, <span class="at">main=</span><span class="st">&quot;QQ Plot&quot;</span>) <span class="co"># create qq-plot</span></span></code></pre></div>
<pre><code>## 84 88 
## 82 86</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="multiple-and-logistic-regression.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2.mlr, <span class="at">which=</span><span class="dv">4</span>, <span class="at">cook.levels =</span> cutoff); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr20-1.png" width="672" /></p>
<p>Although the diagnostic plots indicate that additional points may be problematic, but these data points deviate substantially less from the trend than was the case with the data points that have already been removed. To make sure that retaining the data points that are deemed potentially problematic by the diagnostic plots, is acceptable, we extract diagnostic statistics and add them to the data.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="multiple-and-logistic-regression.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add model diagnostics to the data</span></span>
<span id="cb50-2"><a href="multiple-and-logistic-regression.html#cb50-2" aria-hidden="true" tabindex="-1"></a>mlrdata <span class="ot">&lt;-</span> mlrdata <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="multiple-and-logistic-regression.html#cb50-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">residuals =</span> <span class="fu">resid</span>(m2.mlr),</span>
<span id="cb50-4"><a href="multiple-and-logistic-regression.html#cb50-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">standardized.residuals =</span> <span class="fu">rstandard</span>(m2.mlr),</span>
<span id="cb50-5"><a href="multiple-and-logistic-regression.html#cb50-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">studentized.residuals =</span> <span class="fu">rstudent</span>(m2.mlr),</span>
<span id="cb50-6"><a href="multiple-and-logistic-regression.html#cb50-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">cooks.distance =</span> <span class="fu">cooks.distance</span>(m2.mlr),</span>
<span id="cb50-7"><a href="multiple-and-logistic-regression.html#cb50-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">dffit =</span> <span class="fu">dffits</span>(m2.mlr),</span>
<span id="cb50-8"><a href="multiple-and-logistic-regression.html#cb50-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">leverage =</span> <span class="fu">hatvalues</span>(m2.mlr),</span>
<span id="cb50-9"><a href="multiple-and-logistic-regression.html#cb50-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">covariance.ratios =</span> <span class="fu">covratio</span>(m2.mlr),</span>
<span id="cb50-10"><a href="multiple-and-logistic-regression.html#cb50-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">fitted =</span> m2.mlr<span class="sc">$</span>fitted.values)</span></code></pre></div>
<p>We can now use these diagnostic statistics to create more precise diagnostic plots.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="multiple-and-logistic-regression.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 5</span></span>
<span id="cb51-2"><a href="multiple-and-logistic-regression.html#cb51-2" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata,</span>
<span id="cb51-3"><a href="multiple-and-logistic-regression.html#cb51-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(studentized.residuals)) <span class="sc">+</span></span>
<span id="cb51-4"><a href="multiple-and-logistic-regression.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-5"><a href="multiple-and-logistic-regression.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..),</span>
<span id="cb51-6"><a href="multiple-and-logistic-regression.html#cb51-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> .<span class="dv">2</span>,</span>
<span id="cb51-7"><a href="multiple-and-logistic-regression.html#cb51-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">colour=</span><span class="st">&quot;black&quot;</span>,</span>
<span id="cb51-8"><a href="multiple-and-logistic-regression.html#cb51-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">&quot;gray90&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-9"><a href="multiple-and-logistic-regression.html#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Studentized Residual&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-10"><a href="multiple-and-logistic-regression.html#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm,</span>
<span id="cb51-11"><a href="multiple-and-logistic-regression.html#cb51-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(mlrdata<span class="sc">$</span>studentized.residuals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-12"><a href="multiple-and-logistic-regression.html#cb51-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fu">sd</span>(mlrdata<span class="sc">$</span>studentized.residuals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb51-13"><a href="multiple-and-logistic-regression.html#cb51-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb51-14"><a href="multiple-and-logistic-regression.html#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>)</span>
<span id="cb51-15"><a href="multiple-and-logistic-regression.html#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 6</span></span>
<span id="cb51-16"><a href="multiple-and-logistic-regression.html#cb51-16" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mlrdata, <span class="fu">aes</span>(fitted, studentized.residuals)) <span class="sc">+</span></span>
<span id="cb51-17"><a href="multiple-and-logistic-regression.html#cb51-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb51-18"><a href="multiple-and-logistic-regression.html#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;Red&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-19"><a href="multiple-and-logistic-regression.html#cb51-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>)<span class="sc">+</span></span>
<span id="cb51-20"><a href="multiple-and-logistic-regression.html#cb51-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Fitted Values&quot;</span>,</span>
<span id="cb51-21"><a href="multiple-and-logistic-regression.html#cb51-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Studentized Residual&quot;</span>)</span>
<span id="cb51-22"><a href="multiple-and-logistic-regression.html#cb51-22" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 7</span></span>
<span id="cb51-23"><a href="multiple-and-logistic-regression.html#cb51-23" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">qplot</span>(<span class="at">sample =</span> mlrdata<span class="sc">$</span>studentized.residuals, <span class="at">stat=</span><span class="st">&quot;qq&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-24"><a href="multiple-and-logistic-regression.html#cb51-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb51-25"><a href="multiple-and-logistic-regression.html#cb51-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Theoretical Values&quot;</span>,</span>
<span id="cb51-26"><a href="multiple-and-logistic-regression.html#cb51-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Observed Values&quot;</span>)</span>
<span id="cb51-27"><a href="multiple-and-logistic-regression.html#cb51-27" aria-hidden="true" tabindex="-1"></a>vip<span class="sc">::</span><span class="fu">grid.arrange</span>(p5, p6, p7, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/mlr22-1.png" width="672" /></p>
<p>The new diagnostic plots do not indicate outliers that require removal. With respect to such data points the following parameters should be considered:</p>
<ol style="list-style-type: decimal">
<li><p>Data points with standardized residuals &gt; 3.29 should be removed <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span></p></li>
<li><p>If more than 1 percent of data points have standardized residuals exceeding values &gt; 2.58, then the error rate of the model is unacceptable <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span>.</p></li>
<li><p>If more than 5 percent of data points have standardized residuals exceeding values &gt; 1.96, then the error rate of the model is unacceptable <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span></p></li>
<li><p>In addition, data points with Cook’s D-values &gt; 1 should be removed <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 269</a>)</span></p></li>
<li><p>Also, data points with leverage values higher than <span class="math inline">\(3(k + 1)/N\)</span> or <span class="math inline">\(2(k + 1)/N\)</span> (k = Number of predictors, N = Number of cases in model) should be removed <span class="citation">(<a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 270</a>)</span></p></li>
<li><p>There should not be (any) autocorrelation among predictors. This means that independent variables cannot be correlated with itself (for instance, because data points come from the same subject). If there is autocorrelation among predictors, then a Repeated Measures Design or a (hierarchical) mixed-effects model should be implemented instead.</p></li>
<li><p>Predictors cannot substantially correlate with each other (multicollinearity) (see the <a href="https://slcladal.github.io/regression.html#Multicollinearity">subsection on (multi-)collinearity</a> in the section of multiple binomial logistic regression for more details about (multi-)collinearity). If a model contains predictors that have variance inflation factors (VIF) &gt; 10 the model is unreliable <span class="citation">(<a href="#ref-myers1990classical" role="doc-biblioref">Myers 1990</a>)</span> and predictors causing such VIFs should be removed. Indeed, even VIFs of 2.5 can be problematic <span class="citation">(<a href="#ref-szmrecsanyi2006morphosyntactic" role="doc-biblioref">Szmrecsanyi 2006, 215</a>)</span> Indeed, <span class="citation">Zuur, Ieno, and Elphick (<a href="#ref-zuur2010protocol" role="doc-biblioref">2010</a>)</span> propose that variables with VIFs exceeding 3 should be removed!</p></li>
</ol>
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
<b>NOTE</b><br><br>However, (multi-)collinearity is only an issue if one is interested in interpreting regression results! If the interpretation is irrelevant because what is relevant is prediction(!), then it does not matter if the model contains collinear predictors! See <span class="citation">Gries (<a href="#ref-gries2021statistics" role="doc-biblioref">2021</a>)</span> for a more elaborate explanation.
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<p><br></p>
<ol start="8" style="list-style-type: decimal">
<li>The mean value of VIFs should be ~ 1 <span class="citation">(<a href="#ref-bowerman1990linear" role="doc-biblioref">Bowerman and O’Connell 1990</a>)</span>.</li>
</ol>
<p>The following code chunk evaluates these criteria.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="multiple-and-logistic-regression.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1: optimal = 0</span></span>
<span id="cb52-2"><a href="multiple-and-logistic-regression.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb52-3"><a href="multiple-and-logistic-regression.html#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(mlrdata<span class="sc">$</span>standardized.residuals <span class="sc">&gt;</span> <span class="fl">3.29</span>)</span></code></pre></div>
<pre><code>## named integer(0)</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="multiple-and-logistic-regression.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2: optimal = 1</span></span>
<span id="cb54-2"><a href="multiple-and-logistic-regression.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb54-3"><a href="multiple-and-logistic-regression.html#cb54-3" aria-hidden="true" tabindex="-1"></a>stdres_258 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">sapply</span>(mlrdata<span class="sc">$</span>standardized.residuals, <span class="cf">function</span>(x) {</span>
<span id="cb54-4"><a href="multiple-and-logistic-regression.html#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">sqrt</span>((x<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">&gt;</span> <span class="fl">2.58</span>, <span class="dv">1</span>, <span class="dv">0</span>) } ))</span>
<span id="cb54-5"><a href="multiple-and-logistic-regression.html#cb54-5" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(stdres_258) <span class="sc">/</span> <span class="fu">length</span>(stdres_258)) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="multiple-and-logistic-regression.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3: optimal = 5</span></span>
<span id="cb56-2"><a href="multiple-and-logistic-regression.html#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb56-3"><a href="multiple-and-logistic-regression.html#cb56-3" aria-hidden="true" tabindex="-1"></a>stdres_196 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">sapply</span>(mlrdata<span class="sc">$</span>standardized.residuals, <span class="cf">function</span>(x) {</span>
<span id="cb56-4"><a href="multiple-and-logistic-regression.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">sqrt</span>((x<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">&gt;</span> <span class="fl">1.96</span>, <span class="dv">1</span>, <span class="dv">0</span>) } ))</span>
<span id="cb56-5"><a href="multiple-and-logistic-regression.html#cb56-5" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(stdres_196) <span class="sc">/</span> <span class="fu">length</span>(stdres_196)) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 6.12244897959</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="multiple-and-logistic-regression.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4: optimal = 0</span></span>
<span id="cb58-2"><a href="multiple-and-logistic-regression.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (listed data points should be removed)</span></span>
<span id="cb58-3"><a href="multiple-and-logistic-regression.html#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(mlrdata<span class="sc">$</span>cooks.distance <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## named integer(0)</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="multiple-and-logistic-regression.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5: optimal = 0</span></span>
<span id="cb60-2"><a href="multiple-and-logistic-regression.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (data points should be removed if cooks distance is close to 1)</span></span>
<span id="cb60-3"><a href="multiple-and-logistic-regression.html#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(mlrdata<span class="sc">$</span>leverage <span class="sc">&gt;=</span> (<span class="dv">3</span><span class="sc">*</span><span class="fu">mean</span>(mlrdata<span class="sc">$</span>leverage)))</span></code></pre></div>
<pre><code>## named integer(0)</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="multiple-and-logistic-regression.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6: checking autocorrelation:</span></span>
<span id="cb62-2"><a href="multiple-and-logistic-regression.html#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Durbin-Watson test (optimal: high p-value)</span></span>
<span id="cb62-3"><a href="multiple-and-logistic-regression.html#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dwt</span>(m2.mlr)</span></code></pre></div>
<pre><code>##  lag  Autocorrelation D-W Statistic p-value
##    1 -0.0143324675649  1.9680423527   0.638
##  Alternative hypothesis: rho != 0</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="multiple-and-logistic-regression.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7: test multicollinearity 1</span></span>
<span id="cb64-2"><a href="multiple-and-logistic-regression.html#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(m2.mlr)</span></code></pre></div>
<pre><code>##                         statusSingle              attractionNotInterested 
##                                 2.00                                 1.96 
## statusSingle:attractionNotInterested 
##                                 2.96</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="multiple-and-logistic-regression.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 8: test multicollinearity 2</span></span>
<span id="cb66-2"><a href="multiple-and-logistic-regression.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="fu">vif</span>(m2.mlr)</span></code></pre></div>
<pre><code>##                         statusSingle              attractionNotInterested 
##                       0.500000000000                       0.510204081633 
## statusSingle:attractionNotInterested 
##                       0.337837837838</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="multiple-and-logistic-regression.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9: mean vif should not exceed 1</span></span>
<span id="cb68-2"><a href="multiple-and-logistic-regression.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">vif</span>(m2.mlr))</span></code></pre></div>
<pre><code>## [1] 2.30666666667</code></pre>
<p>Except for the mean VIF value (2.307) which should not exceed 1, all diagnostics are acceptable. We will now test whether the sample size is sufficient for our model. With respect to the minimal sample size and based on <span class="citation">Green (<a href="#ref-green1991many" role="doc-biblioref">1991</a>)</span>, <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012, 273–74</a>)</span> offer the following rules of thumb for an adequate sample size (k = number of predictors; categorical predictors with more than two levels should be recoded as dummy variables):</p>
<ul>
<li><p>if you are interested in the overall model: 50 + 8k (k = number of predictors)</p></li>
<li><p>if you are interested in individual predictors: 104 + k</p></li>
<li><p>if you are interested in both: take the higher value!</p></li>
</ul>
</div>
<div id="evaluation-of-sample-size" class="section level3 hasAnchor" number="9.1.6">
<h3><span class="header-section-number">9.1.6</span> Evaluation of Sample Size<a href="multiple-and-logistic-regression.html#evaluation-of-sample-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After performing the diagnostics, we will now test whether the sample size is adequate and what the values of R would be based on a random distribution in order to be able to estimate how likely a <span class="math inline">\(\beta\)</span>-error is given the present sample size <span class="citation">(see <a href="#ref-field2012discovering" role="doc-biblioref">Field, Miles, and Field 2012, 274</a>)</span>. Beta errors (or <span class="math inline">\(\beta\)</span>-errors) refer to the erroneous assumption that a predictor is not significant (based on the analysis and given the sample) although it does have an effect in the population. In other words, <span class="math inline">\(\beta\)</span>-error means to overlook a significant effect because of weaknesses of the analysis. The test statistics ranges between 0 and 1 where lower values are better. If the values approximate 1, then there is serious concern as the model is not reliable given the sample size. In such cases, unfortunately, the best option is to increase the sample size.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="multiple-and-logistic-regression.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load functions</span></span>
<span id="cb70-2"><a href="multiple-and-logistic-regression.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;https://slcladal.github.io/rscripts/SampleSizeMLR.r&quot;</span>)</span>
<span id="cb70-3"><a href="multiple-and-logistic-regression.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;https://slcladal.github.io/rscripts/ExpR.r&quot;</span>)</span>
<span id="cb70-4"><a href="multiple-and-logistic-regression.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check if sample size is sufficient</span></span>
<span id="cb70-5"><a href="multiple-and-logistic-regression.html#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">smplesz</span>(m2.mlr)</span></code></pre></div>
<pre><code>## [1] &quot;Sample too small: please increase your sample by  9  data points&quot;</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="multiple-and-logistic-regression.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check beta-error likelihood</span></span>
<span id="cb72-2"><a href="multiple-and-logistic-regression.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">expR</span>(m2.mlr)</span></code></pre></div>
<pre><code>## [1] &quot;Based on the sample size expect a false positive correlation of 0.0309 between the predictors and the predicted&quot;</code></pre>
<p>The function <code>smplesz</code> reports that the sample size is insufficient by 9 data points according to <span class="citation">Green (<a href="#ref-green1991many" role="doc-biblioref">1991</a>)</span>. The likelihood of <span class="math inline">\(\beta\)</span>-errors, however, is very small (0.0309). As a last step, we summarize the results of the regression analysis.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="multiple-and-logistic-regression.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tabulate model results</span></span>
<span id="cb74-2"><a href="multiple-and-logistic-regression.html#cb74-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m0.glm, m2.glm)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
money
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
money
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
88.12
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
78.72 – 97.52
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
99.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
92.10 – 106.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
status [Single]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
55.85
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
45.78 – 65.93
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
attraction<br>[NotInterested]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-47.66
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-57.63 – -37.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
status [Single] *<br>attraction<br>[NotInterested]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-59.46
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-73.71 – -45.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.000
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.857
</td>
</tr>
</table>
<hr />
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
<b>NOTE</b><br><br>The R<sup>2</sup> values in this report is incorrect! As we have seen above, and is also shown in the table below, the correct R<sup>2</sup> values are: multiple R<sup>2</sup> 0.8574, adjusted R<sup>2</sup> 0.8528.<br>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<p><br></p>
<p>Additionally, we can inspect the summary of the regression model as shown below to extract additional information.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="multiple-and-logistic-regression.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = money ~ (status + attraction)^2, data = mlrdata)
## 
## Residuals:
##          Min           1Q       Median           3Q          Max 
## -35.76416667 -13.50520000  -0.98948333  10.59887500  38.77166667 
## 
## Coefficients:
##                                          Estimate   Std. Error  t value
## (Intercept)                           99.15480000   3.59735820 27.56323
## statusSingle                          55.85353333   5.14015367 10.86612
## attractionNotInterested              -47.66280000   5.08743275 -9.36873
## statusSingle:attractionNotInterested -59.46136667   7.26927504 -8.17982
##                                                    Pr(&gt;|t|)    
## (Intercept)                          &lt; 0.000000000000000222 ***
## statusSingle                         &lt; 0.000000000000000222 ***
## attractionNotInterested               0.0000000000000040429 ***
## statusSingle:attractionNotInterested  0.0000000000013375166 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 17.986791 on 94 degrees of freedom
## Multiple R-squared:  0.857375902,    Adjusted R-squared:  0.852824069 
## F-statistic: 188.358387 on 3 and 94 DF,  p-value: &lt; 0.0000000000000002220446</code></pre>
<p>Although <span class="citation">Field, Miles, and Field (<a href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span> suggest that the main effects of the predictors involved in the interaction should not be interpreted, they are interpreted here to illustrate how the results of a multiple linear regression can be reported.</p>
<p>We can use the <code>reports</code> package <span class="citation">(<a href="#ref-report" role="doc-biblioref">Makowski et al. 2021</a>)</span> to summarize the analysis.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="multiple-and-logistic-regression.html#cb77-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m2.mlr)</span></code></pre></div>
<pre><code>## We fitted a linear model (estimated using OLS) to predict money with status and attraction (formula: money ~ (status + attraction)^2). The model explains a statistically significant and substantial proportion of variance (R2 = 0.86, F(3, 94) = 188.36, p &lt; .001, adj. R2 = 0.85). The model&#39;s intercept, corresponding to status = Relationship and attraction = Interested, is at 99.15 (95% CI [92.01, 106.30], t(94) = 27.56, p &lt; .001). Within this model:
## 
##   - The effect of status [Single] is statistically significant and positive (beta = 55.85, 95% CI [45.65, 66.06], t(94) = 10.87, p &lt; .001; Std. beta = 1.19, 95% CI [0.97, 1.41])
##   - The effect of attraction [NotInterested] is statistically significant and negative (beta = -47.66, 95% CI [-57.76, -37.56], t(94) = -9.37, p &lt; .001; Std. beta = -1.02, 95% CI [-1.23, -0.80])
##   - The interaction effect of attraction [NotInterested] on status [Single] is statistically significant and negative (beta = -59.46, 95% CI [-73.89, -45.03], t(94) = -8.18, p &lt; .001; Std. beta = -1.27, 95% CI [-1.58, -0.96])
## 
## Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
<p>We can use this output to write up a final report:</p>
<p>A multiple linear regression was fitted to the data using an automated, step-wise, AIC-based (Akaike’s Information Criterion) procedure. The model fitting arrived at a final minimal model. During the model diagnostics, two outliers were detected and removed. Further diagnostics did not find other issues after the removal.</p>
<p>The final minimal adequate regression model is based on 98 data points and performs highly significantly better than a minimal baseline model (multiple R<sup>2</sup>: .857, adjusted R<sup>2</sup>: .853, F-statistic (3, 94): 154.4, AIC: 850.4, BIC: 863.32, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). The final minimal adequate regression model reports <em>attraction</em> and <em>status</em> as significant main effects. The relationship status of men correlates highly significantly and positively with the amount of money spend on the women’s presents (SE: 5.14, t-value: 10.87, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). This shows that men spend 156.8 dollars on presents if they are single while they spend 99,15 dollars if they are in a relationship. Whether men are attracted to women also correlates highly significantly and positively with the money they spend on women (SE: 5.09, t-values: -9.37, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>). If men are not interested in women, they spend 47.66 dollar less on a present for women compared with women the men are interested in.</p>
<p>Furthermore, the final minimal adequate regression model reports a highly significant interaction between relationship <em>status</em> and <em>attraction</em> (SE: 7.27, t-value: -8.18, p&lt;.001<sup><span class="math inline">\(***\)</span></sup>): If men are single but they are not interested in a women, a man would spend only 59.46 dollars on a present compared to all other constellations.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="multiple-and-logistic-regression.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.2.0 (2022-04-22 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19043)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
## [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.utf8    
## 
## attached base packages:
## [1] grid      stats     graphics  grDevices datasets  utils     methods  
## [8] base     
## 
## other attached packages:
##  [1] vip_0.3.2          vcd_1.4-9          tibble_3.1.7       stringr_1.4.0     
##  [5] sjPlot_2.8.10      robustbase_0.95-0  rms_6.3-0          SparseM_1.81      
##  [9] ordinal_2019.12-10 nlme_3.1-157       MuMIn_1.46.0       mclogit_0.9.4.2   
## [13] MASS_7.3-56        lme4_1.1-29        Matrix_1.4-1       knitr_1.39        
## [17] Hmisc_4.7-0        Formula_1.2-4      survival_3.3-1     lattice_0.20-45   
## [21] ggpubr_0.4.0       ggfortify_0.4.14   ggplot2_3.3.6      flextable_0.7.0   
## [25] emmeans_1.7.3      effects_4.2-1      car_3.0-13         carData_3.0-5     
## [29] Boruta_7.0.0       dplyr_1.0.9       
## 
## loaded via a namespace (and not attached):
##   [1] uuid_1.1-0          backports_1.4.1     systemfonts_1.0.4  
##   [4] repr_1.1.4          splines_4.2.0       TH.data_1.1-1      
##   [7] digest_0.6.29       htmltools_0.5.2     fansi_1.0.3        
##  [10] magrittr_2.0.3      checkmate_2.1.0     cluster_2.1.3      
##  [13] modelr_0.1.8        officer_0.4.2       sandwich_3.0-1     
##  [16] jpeg_0.1-9          colorspace_2.0-3    mitools_2.4        
##  [19] xfun_0.30           crayon_1.5.1        jsonlite_1.8.0     
##  [22] zoo_1.8-10          glue_1.6.2          gtable_0.3.0       
##  [25] MatrixModels_0.5-0  sjstats_0.18.1      sjmisc_2.8.9       
##  [28] DEoptimR_1.0-11     abind_1.4-5         scales_1.2.0       
##  [31] mvtnorm_1.1-3       DBI_1.1.2           rstatix_0.7.0      
##  [34] ggeffects_1.1.2     Rcpp_1.0.8.3        xtable_1.8-4       
##  [37] performance_0.9.0   htmlTable_2.4.0     klippy_0.0.0.9500  
##  [40] foreign_0.8-82      stats4_4.2.0        survey_4.1-1       
##  [43] datawizard_0.4.0    htmlwidgets_1.5.4   RColorBrewer_1.1-3 
##  [46] ellipsis_0.3.2      farver_2.1.0        pkgconfig_2.0.3    
##  [49] nnet_7.3-17         sass_0.4.1          utf8_1.2.2         
##  [52] labeling_0.4.2      tidyselect_1.1.2    rlang_1.0.2        
##  [55] effectsize_0.6.0.1  munsell_0.5.0       tools_4.2.0        
##  [58] cli_3.3.0           generics_0.1.2      sjlabelled_1.2.0   
##  [61] broom_0.8.0         evaluate_0.15       fastmap_1.1.0      
##  [64] yaml_2.3.5          zip_2.2.0           purrr_0.3.4        
##  [67] memisc_0.99.30.7    quantreg_5.93       report_0.5.1       
##  [70] xml2_1.3.3          compiler_4.2.0      rstudioapi_0.13    
##  [73] png_0.1-7           ggsignif_0.6.3      bslib_0.3.1        
##  [76] stringi_1.7.6       highr_0.9           parameters_0.17.0  
##  [79] gdtools_0.2.4       nloptr_2.0.1        vctrs_0.4.1        
##  [82] pillar_1.7.0        lifecycle_1.0.1     lmtest_0.9-40      
##  [85] jquerylib_0.1.4     ucminf_1.1-4        estimability_1.3   
##  [88] data.table_1.14.2   insight_0.17.0      R6_2.5.1           
##  [91] latticeExtra_0.6-29 bookdown_0.26       renv_0.15.4        
##  [94] gridExtra_2.3       codetools_0.2-18    polspline_1.1.20   
##  [97] boot_1.3-28         assertthat_0.2.1    withr_2.5.0        
## [100] multcomp_1.4-19     mgcv_1.8-40         bayestestR_0.12.1  
## [103] rpart_4.1.16        tidyr_1.2.0         coda_0.19-4        
## [106] minqa_1.2.4         rmarkdown_2.14      numDeriv_2016.8-1.1
## [109] base64enc_0.1-3</code></pre>
<p><a href="introduction.html#introduction">Back to top</a></p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-achen1982interpreting" class="csl-entry">
Achen, Christopher H. 1982. <em>Interpreting and Using Regression</em>. Vol. 29. Sage.
</div>
<div id="ref-baayen2008analyzing" class="csl-entry">
Baayen, R Harald. 2008. <em>Analyzing Linguistic Data. A Practical Introduction to Statistics Using r</em>. Cambridge: Cambridge University press.
</div>
<div id="ref-bortz2006statistik" class="csl-entry">
Bortz, Jürgen. 2006. <em>Statistik: F<span>ü</span>r Human-Und Sozialwissenschaftler</em>. Springer-Verlag.
</div>
<div id="ref-bowerman1990linear" class="csl-entry">
Bowerman, Bruce L, and Richard T O’Connell. 1990. <em>Linear Statistical Models: An Applied Approach</em>. Boston: PWS-Kent.
</div>
<div id="ref-crawley2005statistics" class="csl-entry">
Crawley, Michael J. 2005. <em>Statistics: An Introduction Using r. 2005</em>. Chichester, West Sussex: John Wiley &amp; Sons.
</div>
<div id="ref-crawley2012r" class="csl-entry">
———. 2012. <em>The r Book</em>. John Wiley &amp; Sons.
</div>
<div id="ref-faraway2002practical" class="csl-entry">
Faraway, Julian J. 2002. <em>Practical Regression and ANOVA Using r.</em> University of Bath.
</div>
<div id="ref-field2012discovering" class="csl-entry">
Field, Andy, Jeremy Miles, and Zoe Field. 2012. <em>Discovering Statistics Using r</em>. Sage.
</div>
<div id="ref-green1991many" class="csl-entry">
Green, Samuel B. 1991. <span>“How Many Subjects Does It Take to Do a Regression Analysis.”</span> <em>Multivariate Behavioral Research</em> 26 (3): 499–510.
</div>
<div id="ref-gries2021statistics" class="csl-entry">
Gries, Stefan Th. 2021. <em>Statistics for Linguistics Using r: A Practical Introduction</em>. Berlin &amp; New York: Mouton de Gruyter.
</div>
<div id="ref-levshina2015linguistics" class="csl-entry">
Levshina, Natalia. 2015. <em>How to Do Linguistics with r: Data Exploration and Statistical Analysis</em>. Amsterdam: John Benjamins Publishing Company.
</div>
<div id="ref-report" class="csl-entry">
Makowski, Dominique, Mattan S. Ben-Shachar, Indrajeet Patil, and Daniel Lüdecke. 2021. <span>“Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.”</span> <em>CRAN</em>. <a href="https://github.com/easystats/report">https://github.com/easystats/report</a>.
</div>
<div id="ref-myers1990classical" class="csl-entry">
Myers, Raymond H. 1990. <em>Classical and Modern Regression with Applications</em>. Vol. 2. Duxbury Press Belmont, CA.
</div>
<div id="ref-szmrecsanyi2006morphosyntactic" class="csl-entry">
Szmrecsanyi, Benedikt. 2006. <em>Morphosyntactic Persistence in Spoken English: A Corpus Study at the Intersection of Variationist Sociolinguistics, Psycholinguistics, and Discourse Analysis</em>. Berlin &amp; New York: Walter de Gruyter.
</div>
<div id="ref-wilcox2009basic" class="csl-entry">
Wilcox, Rand R. 2009. <em>Basic Statistics: Understanding Conventional Methods and Modern Insights</em>. Oxford University Press.
</div>
<div id="ref-zuur2010protocol" class="csl-entry">
Zuur, Alain F., Elena N. Ieno, and Chris S. Elphick. 2010. <span>“A Protocol for Data Exploration to Avoid Common Statistical Problems.”</span> <em>Methods in Ecology and Evolution</em> 1 (1): 3–14.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basic-inferential-statistics-regression-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression-and-model-diagnostics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/edit/master/09-multreg.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/blob/master/09-multreg.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
