<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 8 Significance and Probability | SLAT7855 Quantitative Research Methods in Applied Linguistics</title>
  <meta name="description" content="Week 8 Significance and Probability | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 8 Significance and Probability | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 8 Significance and Probability | SLAT7855 Quantitative Research Methods in Applied Linguistics" />
  
  
  

<meta name="author" content="Martin Schweinberger" />


<meta name="date" content="2022-05-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="relationsships-between-variables.html"/>
<link rel="next" href="z-scores.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SLAT7855</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#basic-course-information"><i class="fa fa-check"></i>Basic Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-introduction"><i class="fa fa-check"></i>Course Introduction</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-staff"><i class="fa fa-check"></i>Course Staff</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#timetable"><i class="fa fa-check"></i>Timetable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aims-objectives-graduate-attributes"><i class="fa fa-check"></i>Aims, Objectives &amp; Graduate Attributes</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-aims"><i class="fa fa-check"></i>Course Aims</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i>Learning Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-resources"><i class="fa fa-check"></i>Learning Resources</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#required-resources"><i class="fa fa-check"></i>Required Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#recommended-resources"><i class="fa fa-check"></i>Recommended Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#university-learning-resources"><i class="fa fa-check"></i>University Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#school-of-languages-and-cultures-learning-resources"><i class="fa fa-check"></i>School of Languages and Cultures Learning Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-learning-resources-information"><i class="fa fa-check"></i>Other Learning Resources &amp; Information</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-learning-activities"><i class="fa fa-check"></i>Teaching &amp; Learning Activities</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-activities"><i class="fa fa-check"></i>Learning Activities</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-plan"><i class="fa fa-check"></i>Course plan</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#why-do-we-need-science"><i class="fa fa-check"></i><b>1.1</b> Why do we need science?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#errare-humanum-est"><i class="fa fa-check"></i><b>1.2</b> Errare Humanum Est</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#the-monty-hall-problem"><i class="fa fa-check"></i><b>1.2.1</b> The Monty Hall Problem</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#the-birthday-conundrum"><i class="fa fa-check"></i><b>1.2.2</b> The Birthday Conundrum</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction.html"><a href="introduction.html#fast-and-slow-thinking"><i class="fa fa-check"></i><b>1.2.3</b> Fast and Slow Thinking</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction.html"><a href="introduction.html#randomness"><i class="fa fa-check"></i><b>1.2.4</b> Randomness</a></li>
<li class="chapter" data-level="1.2.5" data-path="introduction.html"><a href="introduction.html#the-anthropocentric-bias"><i class="fa fa-check"></i><b>1.2.5</b> The Anthropocentric Bias</a></li>
<li class="chapter" data-level="1.2.6" data-path="introduction.html"><a href="introduction.html#patterns-and-matters-of-habit"><i class="fa fa-check"></i><b>1.2.6</b> Patterns and Matters of Habit</a></li>
<li class="chapter" data-level="1.2.7" data-path="introduction.html"><a href="introduction.html#locical-fallacies-and-biases"><i class="fa fa-check"></i><b>1.2.7</b> Locical Fallacies and Biases</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#what-is-science"><i class="fa fa-check"></i><b>1.3</b> What is science?</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#clever-hans"><i class="fa fa-check"></i><b>1.3.1</b> Clever Hans</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#popper-falsification-and-scientific-progress"><i class="fa fa-check"></i><b>1.3.2</b> Popper, falsification, and scientific progress</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#what-is-empirical-linguistics"><i class="fa fa-check"></i><b>1.3.3</b> What is (empirical) Linguistics?</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#citation-session-info"><i class="fa fa-check"></i><b>1.4</b> Citation &amp; Session Info</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#references"><i class="fa fa-check"></i><b>1.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-concepts-in-quantitative-research.html"><a href="basic-concepts-in-quantitative-research.html"><i class="fa fa-check"></i><b>2</b> Basic Concepts in Quantitative Research</a></li>
<li class="chapter" data-level="3" data-path="primer-english-comparatives.html"><a href="primer-english-comparatives.html"><i class="fa fa-check"></i><b>3</b> Primer: English Comparatives</a>
<ul>
<li class="chapter" data-level="" data-path="primer-english-comparatives.html"><a href="primer-english-comparatives.html#length-of-the-adjective"><i class="fa fa-check"></i>Length of the adjective</a></li>
<li class="chapter" data-level="" data-path="primer-english-comparatives.html"><a href="primer-english-comparatives.html#syntactic-function"><i class="fa fa-check"></i>Syntactic Function</a></li>
<li class="chapter" data-level="" data-path="primer-english-comparatives.html"><a href="primer-english-comparatives.html#ending"><i class="fa fa-check"></i>Ending</a></li>
<li class="chapter" data-level="" data-path="primer-english-comparatives.html"><a href="primer-english-comparatives.html#subsequent-than"><i class="fa fa-check"></i>Subsequent <em>than</em></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>4</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="" data-path="hypotheses.html"><a href="hypotheses.html#types-of-hypotheses"><i class="fa fa-check"></i>Types of Hypotheses</a></li>
<li class="chapter" data-level="" data-path="hypotheses.html"><a href="hypotheses.html#why-test-the-h0"><i class="fa fa-check"></i>Why test the H0?!</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html"><i class="fa fa-check"></i><b>5</b> Data and Research Designs</a>
<ul>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#research-designs"><i class="fa fa-check"></i>Research Designs</a>
<ul>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#experimental-research"><i class="fa fa-check"></i>Experimental research</a></li>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#quasi-experimental-research"><i class="fa fa-check"></i>Quasi-experimental research</a></li>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#observational-designs"><i class="fa fa-check"></i>Observational designs</a></li>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#archival-research-and-reviews"><i class="fa fa-check"></i>Archival research and reviews</a></li>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#introspection"><i class="fa fa-check"></i>Introspection</a></li>
<li class="chapter" data-level="" data-path="data-and-research-designs.html"><a href="data-and-research-designs.html#questionnaire-designs"><i class="fa fa-check"></i>Questionnaire designs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variables-and-validity.html"><a href="variables-and-validity.html"><i class="fa fa-check"></i><b>6</b> Variables and Validity</a>
<ul>
<li class="chapter" data-level="" data-path="variables-and-validity.html"><a href="variables-and-validity.html#variable-types-scaling"><i class="fa fa-check"></i>Variable Types (Scaling)</a>
<ul>
<li class="chapter" data-level="" data-path="variables-and-validity.html"><a href="variables-and-validity.html#nominal-and-categorical-variables"><i class="fa fa-check"></i>Nominal and Categorical Variables</a></li>
<li class="chapter" data-level="" data-path="variables-and-validity.html"><a href="variables-and-validity.html#ordinal-variables"><i class="fa fa-check"></i>Ordinal Variables</a></li>
<li class="chapter" data-level="" data-path="variables-and-validity.html"><a href="variables-and-validity.html#true-numeric-variables"><i class="fa fa-check"></i>(True) Numeric Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="relationsships-between-variables.html"><a href="relationsships-between-variables.html"><i class="fa fa-check"></i><b>7</b> Relationsships between variables</a></li>
<li class="chapter" data-level="8" data-path="significance-and-probability.html"><a href="significance-and-probability.html"><i class="fa fa-check"></i><b>8</b> Significance and Probability</a>
<ul>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#significance-levels"><i class="fa fa-check"></i>Significance Levels</a></li>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#probability"><i class="fa fa-check"></i>Probability</a></li>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#non-normality-skewness-and-kurtosis"><i class="fa fa-check"></i>Non-normality: skewness and kurtosis</a>
<ul>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#skewness"><i class="fa fa-check"></i>Skewness</a></li>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#kurtosis"><i class="fa fa-check"></i>Kurtosis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="significance-and-probability.html"><a href="significance-and-probability.html#the-binomial-distribution"><i class="fa fa-check"></i>The Binomial Distribution</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="z-scores.html"><a href="z-scores.html"><i class="fa fa-check"></i><b>9</b> z-scores</a></li>
<li class="chapter" data-level="10" data-path="alpha-and-beta-errors.html"><a href="alpha-and-beta-errors.html"><i class="fa fa-check"></i><b>10</b> Alpha and Beta Errors</a></li>
<li class="chapter" data-level="11" data-path="independence.html"><a href="independence.html"><i class="fa fa-check"></i><b>11</b> Independence</a></li>
<li class="chapter" data-level="12" data-path="corrections.html"><a href="corrections.html"><i class="fa fa-check"></i><b>12</b> Corrections</a></li>
<li class="chapter" data-level="13" data-path="transformations.html"><a href="transformations.html"><i class="fa fa-check"></i><b>13</b> Transformations</a></li>
<li class="chapter" data-level="14" data-path="bayes-theorem.html"><a href="bayes-theorem.html"><i class="fa fa-check"></i><b>14</b> Bayes Theorem</a></li>
<li class="chapter" data-level="" data-path="citation-session-info-1.html"><a href="citation-session-info-1.html"><i class="fa fa-check"></i>Citation &amp; Session Info</a></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="15" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html"><i class="fa fa-check"></i><b>15</b> Getting Started with R and RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#goals-of-this-tutorial"><i class="fa fa-check"></i>Goals of this tutorial</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#audience"><i class="fa fa-check"></i>Audience</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#installing-r-and-rstudio"><i class="fa fa-check"></i>Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#how-to-use-the-workshop-materials"><i class="fa fa-check"></i>How to use the workshop materials</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#folder-structure-and-r-projects"><i class="fa fa-check"></i>Folder Structure and R projects</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#create-a-folder-for-your-project"><i class="fa fa-check"></i>1. Create a folder for your project</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#open-rstudio"><i class="fa fa-check"></i>3. Open RStudio</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-projects"><i class="fa fa-check"></i>4. R Projects</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-notebooks"><i class="fa fa-check"></i>5. R Notebooks</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#updating-r"><i class="fa fa-check"></i>6. Updating R</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#optimizing-r-project-options"><i class="fa fa-check"></i>7. Optimizing R project options</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-started-with-r-notebooks"><i class="fa fa-check"></i>8. Getting started with R Notebooks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-markdown"><i class="fa fa-check"></i>R Markdown</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#rstudio-panes"><i class="fa fa-check"></i>RStudio: Panes</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#r-console-bottom-left-pane"><i class="fa fa-check"></i>R Console (bottom left pane)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#running-commands-from-a-script"><i class="fa fa-check"></i>Running commands from a script</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#script-editor-top-left-pane"><i class="fa fa-check"></i>Script Editor (top left pane)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#setting-up-an-r-session"><i class="fa fa-check"></i>Setting up an R session</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#packages"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-help"><i class="fa fa-check"></i>Getting help</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#finding-help-within-r"><i class="fa fa-check"></i>Finding help within R</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#finding-help-online"><i class="fa fa-check"></i>Finding help online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-data-from-the-web"><i class="fa fa-check"></i>Loading data from the web</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#functions-and-objects"><i class="fa fa-check"></i>Functions and Objects</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#inspecting-data"><i class="fa fa-check"></i>Inspecting data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#accessing-individual-cells-in-a-table"><i class="fa fa-check"></i>Accessing individual cells in a table</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#tabulating-data"><i class="fa fa-check"></i>Tabulating data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#saving-data-to-your-computer"><i class="fa fa-check"></i>Saving data to your computer</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-data-from-your-computer"><i class="fa fa-check"></i>Loading data from your computer</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-excel-data"><i class="fa fa-check"></i>Loading Excel data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-text-data"><i class="fa fa-check"></i>Loading text data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#renaming-piping-and-filtering"><i class="fa fa-check"></i>Renaming, Piping, and Filtering</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#ordering-data"><i class="fa fa-check"></i>Ordering data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#creating-and-changing-variables"><i class="fa fa-check"></i>Creating and changing variables</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#if-statements"><i class="fa fa-check"></i>If-statements</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#summarizing-data"><i class="fa fa-check"></i>Summarizing data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#gathering-and-spreading-data"><i class="fa fa-check"></i>Gathering and spreading data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#loading-text-data-1"><i class="fa fa-check"></i>Loading text data</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#splitting-up-texts"><i class="fa fa-check"></i>Splitting-up texts</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#cleaning-texts"><i class="fa fa-check"></i>Cleaning texts</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#concordancing-and-kwics"><i class="fa fa-check"></i>Concordancing and KWICs</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#further-splitting-of-texts"><i class="fa fa-check"></i>Further splitting of texts</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#basics-of-regular-expressions"><i class="fa fa-check"></i>Basics of regular expressions</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#combining-tables"><i class="fa fa-check"></i>Combining tables</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#tokenization-and-counting-words"><i class="fa fa-check"></i>Tokenization and counting words</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#basics-of-ggplot2-syntax"><i class="fa fa-check"></i>Basics of ggplot2 syntax</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#practical-examples"><i class="fa fa-check"></i>Practical examples</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#extracting-session-information"><i class="fa fa-check"></i>Extracting session information</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SLAT7855 Quantitative Research Methods in Applied Linguistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="significance-and-probability" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Week 8</span> Significance and Probability<a href="significance-and-probability.html#significance-and-probability" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Hypothesis testing fundamentally builds on probabilities - or more precisely probabilities of error which is an estimation for the likelihood of the H<sub>0</sub> being true given the data. In other words, we are interested in how likely the null hypothesis (H<sub>0</sub>) is. If the null hypothesis (H<sub>0</sub>) is very unlikely, for instance lower than 5 percent, we can assume that the null hypothesis is not true and thus reject it and instead assume that our test hypothesis (H<sub>1</sub>) is correct.</p>
<p>This type of probability, the probability ( the probability that the null hypothesis is true) is typically provided in the form of p-values. In a more prosaic (and also coarse-grained, imprecise manner), p-values are an estimate of how likely an outcome is a result of chance. We will delve a little deeper into probabilities and how they relate to hypothesis testing below.</p>
<div id="significance-levels" class="section level2 unnumbered hasAnchor">
<h2>Significance Levels<a href="significance-and-probability.html#significance-levels" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before conducting a study, it is advisable to determine the so-called significance level or <span class="math inline">\(\alpha\)</span> level. This <span class="math inline">\(\alpha\)</span> level or level of significance indicates how high the p-value can be without having to assume that there is a significant relationship between the variables. It is customary to differentiate between three levels of significance (also called <span class="math inline">\(\alpha\)</span> levels):</p>
<ul>
<li><p>p &lt; .001: <em>highly significant</em> - indicated by three stars (***)</p></li>
<li><p>p &lt; .01: <em>very significant</em> - indicated by two stars (**)</p></li>
<li><p>p &lt; .05: <em>significant</em> - indicated by one star (*)</p></li>
</ul>
<p>Variables with a p value that is smaller than .1 but larger than .05 are sometimes referred to as being <em>marginally significant</em> (+).</p>
<p>Variables that are not significant are commonly referred to or labeled as <em>n.s.</em> (not significant). As we stated above, before we perform a test, we determine a value above which we reject the null hypothesis, the so-called significance level. It’s usually 5%. If the error probability is less than 5% (p &lt;. 05), we reject the null hypothesis. Conclusion: The relationship between the variables is statistically significant. It is important to note here that the H<sub>1</sub> (or Test Hypothesis) is correct only because the null hypothesis can be rejected! Statistics can NEVER prove hypotheses but only reject Null Hypotheses which leads us to accept the H<sub>1</sub> as preliminary accepted or not-yet-rejected. So all knowledge is preliminary in the empirical sciences.</p>
</div>
<div id="probability" class="section level2 unnumbered hasAnchor">
<h2>Probability<a href="significance-and-probability.html#probability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the following, we will turn to probability and try to understand why probability is relevant for testing hypotheses. This is important at this point because statistics, and thus hypothesis testing, fundamentally builds upon probabilities and probability distributions. In order to understand how probability works, we will investigate what happens when we flip a coin. The first question that we will be addressing is “<em>What is the probability of getting three Heads when flipping a coin three times?</em>”.</p>
<p>The probability of getting three heads when flipping a coin three times is .5 to the power of 3: .5<sup>3</sup> = .5 times .5 times .5 = .125. The probability of getting Heads twice when flipping the coin three times is .375. How do we know?</p>
<p>The probability of getting 3 heads in tree tosses is 12.5 percent:</p>
<p>.5<sup>3</sup> = .5 * .5 * .5 = .125</p>
<p>The probability of getting 2 heads in tree tosses is 37.5 percent:</p>
<p>.125 + .125 + .125 = 0.375</p>
<p>But how do we know this? Well, have look at the table below.</p>
<hr />
<template id="b579d91c-b92b-414d-bf37-3be29c21b6b0"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-39855e3c{table-layout:auto;width:75%;}.cl-397b50d6{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-397b50e0{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-397b7336{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-397bbce2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbcec{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbcf6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbcf7{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd00{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd01{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd02{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd0a{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd14{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd15{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd1e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-397bbd28{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-39855e3c'>
<caption class="Table Caption">
<p><span id="tab:unnamed-chunk-2">Table 8.1: </span>All possible results of 3 coin tosses.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-397bbd28"><p class="cl-397b7336"><span class="cl-397b50d6">Toss 1</span></p></td><td class="cl-397bbd15"><p class="cl-397b7336"><span class="cl-397b50d6">Toss 2</span></p></td><td class="cl-397bbd15"><p class="cl-397b7336"><span class="cl-397b50d6">Toss 3</span></p></td><td class="cl-397bbd15"><p class="cl-397b7336"><span class="cl-397b50d6">Heads</span></p></td><td class="cl-397bbd15"><p class="cl-397b7336"><span class="cl-397b50d6">Tails</span></p></td><td class="cl-397bbd1e"><p class="cl-397b7336"><span class="cl-397b50d6">Probabilty</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-397bbce2"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">3</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">0</span></p></td><td class="cl-397bbcf6"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbd01"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbd00"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbce2"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbcf6"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbd01"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbd00"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbce2"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbcf6"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbd01"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbcf7"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbd00"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbce2"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">Head</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">1</span></p></td><td class="cl-397bbcec"><p class="cl-397b7336"><span class="cl-397b50e0">2</span></p></td><td class="cl-397bbcf6"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-397bbd14"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbd02"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbd02"><p class="cl-397b7336"><span class="cl-397b50e0">Tails</span></p></td><td class="cl-397bbd02"><p class="cl-397b7336"><span class="cl-397b50e0">0</span></p></td><td class="cl-397bbd02"><p class="cl-397b7336"><span class="cl-397b50e0">3</span></p></td><td class="cl-397bbd0a"><p class="cl-397b7336"><span class="cl-397b50e0">0.125</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="1ec0618f-8649-49d6-89f6-122ec367f771"></div>
<script>
var dest = document.getElementById("1ec0618f-8649-49d6-89f6-122ec367f771");
var template = document.getElementById("b579d91c-b92b-414d-bf37-3be29c21b6b0");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<hr />
<p>Given this table, we are in fact, in a position to calculate the probability of getting 100 heads in 100 coin tosses because we can simply fill in the numbers in the formulas used above: .5<sup>100</sup> = 7.888609 * 10<sup>-31</sup></p>
<p>Okay, let us make a bet..</p>
<ul>
<li><p>If head shows, I win a dollar.</p></li>
<li><p>If tails shows, you win a dollar.</p></li>
</ul>
<p>But given that you know I am cheeky bastard, you do not trust me and claim that I will cheat. But how will you know that I cheat? At which point can you claim that the result is so unlikely that you are (scientifically backed) allowed to claim that I cheat and have manipulated the coin?</p>
<p><img src="bookdownproj_files/figure-html/normal2-1.png" width="672" /></p>
<p>So before we actually start with the coin tossing, you operationalize your hypothesis:</p>
<ul>
<li><p>H<sub>0</sub>: The author (Martin) is not cheating (heads shows just as often as tails).</p></li>
<li><p>H<sub>1</sub>: The author (Martin) is cheating (heads shows so often that the probability of the author not cheating is lower than 5 percent)</p></li>
</ul>
<p>We now toss the coin and head shows twice. The question now is whether head showing twice is lower than 5 percent.</p>
<p>We toss the coin 3 times. Head shows twice. How likely is it that I do not cheat and head falls more than twice anyway? (In other words, what is the probability p that I win twice or more and not cheat?) If you set the significance level at .05, could you then accuse me of being a cheater?</p>
<p>As you can see in the fourth column, there are three options that lead to heads showing twice (rows 2, 3, and 4). If we add these up (0.125 + 0.125 + 0.125 = 0.375). Also, we need to add the case where head shows 3 times which is another .125 (0.375 + 0.125 = .5), then we find out that the probability of heads showing at least twice in three coin tosses is 50 percent and thus 10 times more than the 5-percent threshold that we set initially. Therefore, you cannot claim that I cheated.</p>
<template id="e26fe9ac-8698-4014-a927-4500b7070d62"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-3b017b2e{table-layout:auto;width:75%;}.cl-3af76d5a{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3af76d64{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3af7895c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3af7bfda{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3af7bfee{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3af7bff8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3af7bff9{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3af7c002{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3af7c003{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-3b017b2e'>
<caption class="Table Caption">
<p><span id="tab:unnamed-chunk-3">Table 8.2: </span>Probability of successes in coin tosses.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-3af7bff9"><p class="cl-3af7895c"><span class="cl-3af76d5a">0 Heads</span></p></td><td class="cl-3af7c002"><p class="cl-3af7895c"><span class="cl-3af76d5a">1 Head</span></p></td><td class="cl-3af7c002"><p class="cl-3af7895c"><span class="cl-3af76d5a">2 Heads</span></p></td><td class="cl-3af7c003"><p class="cl-3af7895c"><span class="cl-3af76d5a">3 Heads</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-3af7bfda"><p class="cl-3af7895c"><span class="cl-3af76d64">0.125</span></p></td><td class="cl-3af7bfee"><p class="cl-3af7895c"><span class="cl-3af76d64">0.375</span></p></td><td class="cl-3af7bfee"><p class="cl-3af7895c"><span class="cl-3af76d64">0.375</span></p></td><td class="cl-3af7bff8"><p class="cl-3af7895c"><span class="cl-3af76d64">0.125</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="221b73e5-3e8b-434c-b842-acd38e67a4f4"></div>
<script>
var dest = document.getElementById("221b73e5-3e8b-434c-b842-acd38e67a4f4");
var template = document.getElementById("e26fe9ac-8698-4014-a927-4500b7070d62");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p><img src="bookdownproj_files/figure-html/probcoin01-1.png" width="672" /></p>
<p>We can do the same and check the probabilities of having heads in 10 coin tosses - if we plot the resulting probabilities, we get the bar plot shown below.</p>
<p><img src="bookdownproj_files/figure-html/probcoin02-1.png" width="672" /></p>
<p>The distribution looks more bell-shaped with very low probabilities of getting 0 or 1 as well as 9 or 10 times heads in the 10 coin tosses and a maximum at 5 times heads in 10 coin tosses. In fact, the probability of having 0 and 10 times head is .001 (or 1 in a 1000 attempts - one attempt is tossing a coin 10 times) - the probability of having heads once and 9 times is.01 or 1 in 100 attempts. In contrast, the probability of having 5 times head is .246 or about 25% (1 in 4 attempts will have 5 heads). Also, we can sum up probabilities: the probability of getting 8 or more heads in 10 coin tosses is the probability of getting 8, 9, and 10 times heads (.044 + .010 + 0.001 = .055 = 5.5 percent).</p>
<p>Calculating the probabilities for three or even 10 coin tosses is still manageable manually but is there an easier way to calculate probabilities? A handier way is have a computer calculate probabilities and the code below shows how to do that in R - a very powerful and flexible programming environment that has been designed for quantitative analysis (but R can, in fact, do much more - this website, for instance, is programmed in R).</p>
<p>The code chunk below calculates the probabilities of having 0, 1, 2, and 3 times head in 3 tosses.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="significance-and-probability.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilities of  0, 1, 2 and 3 times head in 3 coin tosses</span></span>
<span id="cb1-2"><a href="significance-and-probability.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.125 0.375 0.375 0.125</code></pre>
<p>The code chunk below calculates the probabilities of having 2 or 3 times head in 3 tosses.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="significance-and-probability.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilities of  2 or 3 times head in 3 coin tosses</span></span>
<span id="cb3-2"><a href="significance-and-probability.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<p>The code chunk below calculates the probabilities of having 100 head in 100 tosses.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="significance-and-probability.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of  100 times head in 100 coin tosses</span></span>
<span id="cb5-2"><a href="significance-and-probability.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">100</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## [1] 7.888609e-31</code></pre>
<p>The code chunk below calculates the probabilities of having 58 or more times head in 100 tosses.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="significance-and-probability.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of  58 to a 100 times head in 100 coin tosses</span></span>
<span id="cb7-2"><a href="significance-and-probability.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">58</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">100</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.06660531</code></pre>
<p>The code chunk below calculates the probabilities of having 59 or more times head in 100 tosses.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="significance-and-probability.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of  59 to a 100 times head in 100 coin tosses</span></span>
<span id="cb9-2"><a href="significance-and-probability.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">59</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">100</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.04431304</code></pre>
<p>The code chunk below calculates the number of heads in 100 tosses where the probability of getting that number of heads or more sums up to 5 percent (0.05).</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="significance-and-probability.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># at which point does the probability of getting head </span></span>
<span id="cb11-2"><a href="significance-and-probability.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dip below 5 percent in 100 coin tosses?</span></span>
<span id="cb11-3"><a href="significance-and-probability.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="fl">0.05</span>, <span class="dv">100</span>, <span class="fl">0.5</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 58</code></pre>
<p>Let’s go back to our example scenario. In our example scenario, we are dealing with a directed hypothesis and not with an un-directed/non-directed hypothesis because we claimed in our H<sub>1</sub> that I was cheating and would get <em>more</em> heads than would be expected by chance (<span class="math inline">\(\mu_{Martin}\)</span> <span class="math inline">\(&gt;\)</span> <span class="math inline">\(\mu_{NormalCoin}\)</span>). For this reason, the test we use is one-tailed. When dealing with un-directed hypotheses, you simply claim that the outcome is either higher or lower - in other words the test is two-tailed as you do not know in which direction the effect will manifest itself.</p>
<p>To understand this a more thoroughly, we will consider tossing a coin not merely 3 but 100 times. The Figure below shows the probabilities for the number of heads showing when we toss a coin 100 from 0 occurrences to 100 occurrences.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The next figure shows at which number of heads the cumulative probabilities dip below 5 percent for two-tailed hypotheses. According to the graph, if head shows up to 40 or more often than 60 times, the cumulative probability dips below 5 percent. Applied to our initial bet, you could thus claim that I cheated if head shows less than 41 times or more than 60 times (if out hypothesis were two-tailed - which it is not).</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The Figure below shows at which point the probability of heads showing dips below 5 percent for one-tailed hypotheses. Thus, according to the figure below, if we toss a coin 100 times and head shows 59 or more often, then you are justified in claiming that I cheated.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>When comparing the two figures above, it is notable that the number at which you can claim I cheated differs according to whether the H<sub>1</sub> as one- or two-tailed. When formulating a one-tailed hypothesis, then the number is lower compared with the the number at which you can reject the H<sub>0</sub> if your H<sub>1</sub> is two-tailed. This is actually the reason for why it is preferable to formulate more precise, one-tailed hypotheses (because then, it is easier for the data to be sufficient to reject the H<sub>0</sub>).</p>
</div>
<div id="the-normal-distribution" class="section level2 unnumbered hasAnchor">
<h2>The Normal Distribution<a href="significance-and-probability.html#the-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is important to note here that the above described calculation of probabilities does not work for numeric variables that are interval-scaled. The reason for this is that it is not possible to calculate the probabilities for all possible outcomes of a reaction time experiment (where time is a continuous variable). In such cases, we rely on <em>distributions</em> in order to determine how likely or probable a certain outcome is.</p>
<p>When relying on distributions, we determine whether a certain value falls within or outside of the area of a distribution that accounts for 5 percent of the entire area of the distribution - if it falls within the area that accounts for less than 5 percent of the total area, then the result is called <em>statistically significant</em> (see the normal distribution below) because the outcome is very unlikely.</p>
<p>The normal distribution (or Gaussian curve or Gaussian distribution) shown in the figure above has certain characteristics that can be derived mathematically. Some of these characteristics relate to the area of certain sections of that distribution. More generally, the normal distribution is a symmetric, bell-shaped probability distribution, used as the theoretical model for the distribution of physical and psychological variables. In fact, many variables in the real world are normally distributed: shoe sizes, IQs, sleep lengths, and many , many more.</p>
<p>The normal distribution is very important because it underlies many statistical procedures in one form or another. The normal distribution is a symmetrical, continuous distribution where</p>
<ul>
<li>the arithmetic mean, the median, and the mode are identical and have a value of 0 (and are thus identical);<br />
</li>
<li>50% of the area under the bell-shaped curve are smaller than the mean;<br />
</li>
<li>50% of the area under the bell-shaped curve are bigger than the mean;<br />
</li>
<li>50% of the area under the bell-shaped curve are within -0.675 and +0.675 standard deviations from the mean (0);<br />
</li>
<li>95% of the area under the bell-shaped curve are within -1.96 and +1.96 standard deviations from the mean (0);<br />
</li>
<li>99% of the area under the bell-shaped curve are within -2.576 and +2.576 standard deviations from the mean (0).</li>
</ul>
<p>There is also a very interesting aspect to the normal distribution that relates to the means (averages) of samples drawn from any type of distribution: no matter what type of distribution we draw samples from, the distribution of the means will approximate a normal distribution. In other words, if we draw samples form a very weird looking distribution, the means of these samples will approximate a normal distribution. This fact is called the <em>Central Limit Theorem</em>. What makes the central limit theorem so remarkable is that this result holds no matter what shape the original population distribution may have been.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As shown above, 50 percent of the total area under the curve are to left and 50 percent of the right of the mean value. Furthermore, 68 percent of the area are within -1 and +1 standard deviations from the mean; 95 percent of the area lie between -2 and +2 standard deviations from the mean; 99.7 percent of the area lie between -3 and +3 standard deviations from the mean. Also, 5 percent of the area lie outside -1.96 and +1.96 standard deviations from the mean (if these areas are combined) (see the Figure below). This is important. because we can reject null hypotheses if the probability of them being true is lower than 5 percent. This means that we can use the normal distribution to reject null hypotheses if our dependent variable is normally distributed.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Finally, 5 percent of the area lies beyond +1.68 standard deviations from the mean (see the Figure below).</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>These properties are extremely useful when determining the likelihood of values or outcomes that reflect certain interval-scaled variables.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Create a table with the possible outcomes and probabilities of 4 coin tosses (you can consider the table showing the outcomes of three coin tosses above as a guideline).</li>
</ol>
<details>
<summary>
Answer
</summary>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="significance-and-probability.html#cb13-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>  ## [1] 0.2734375</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>How likely is it for heads to show exactly 3 times when tossing a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="significance-and-probability.html#cb15-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="dv">7</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>  ## [1] 0.2734375</code></pre>
</details>
<ol start="3" style="list-style-type: decimal">
<li>How likely is it for heads to show exactly 2 or 5 times when tossing a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="significance-and-probability.html#cb17-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>), <span class="dv">7</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>  ## [1] 0.328125</code></pre>
</details>
<ol start="4" style="list-style-type: decimal">
<li>How likely is it for heads to show 5 or more times when tossing a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="significance-and-probability.html#cb19-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>, <span class="dv">7</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>  ## [1] 0.2265625</code></pre>
</details>
<ol start="5" style="list-style-type: decimal">
<li>How likely is it for heads to show between 3 and 6 times when tossing a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="significance-and-probability.html#cb21-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">7</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>  ## [1] 0.765625</code></pre>
</details>
</div>
<p>`</p>
<hr />
</div>
<div id="non-normality-skewness-and-kurtosis" class="section level2 unnumbered hasAnchor">
<h2>Non-normality: skewness and kurtosis<a href="significance-and-probability.html#non-normality-skewness-and-kurtosis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Depending on the phenomenon you are investigating, the distribution of that phenomenon can be distributed non-normally. Two factors causing distributions to differ from the normal distribution (that is two factors causing distributions to be non-normal) are <em>skewness</em> and <em>kurtosis</em>.</p>
<div id="skewness" class="section level3 unnumbered hasAnchor">
<h3>Skewness<a href="significance-and-probability.html#skewness" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Skewed distributions are asymmetrical and they can be positively or negatively skewed. The tail of a <em>negatively skewed distribution</em> points towards negative values (to the left) which means that the distribution leans towards the right (towards positive values) while the tail of a <em>positively skewed distribution</em> points towards positive values (to the right) which means that the distribution leans towards the left (towards negative values).</p>
<p>Another characteristic of skewed distributions is that the mean and median of a distribution differ. If the median is greater than the mean, the distribution is negatively skewed (the long tail points towards negative values). If the median is smaller than the mean, the distribution is positively skewed (the long tail points towards positive values).</p>
<p>Negatively skewed</p>
<ul>
<li>Tail points towards negative values (to the left)</li>
<li>Median is greater than the mean</li>
</ul>
<p>Positively skewed</p>
<ul>
<li>Tail points towards positive values (to the right)</li>
<li>Median is lower than the mean</li>
</ul>
<p><img src="bookdownproj_files/figure-html/skewness-1.png" width="672" /></p>
<p>To show how we can calculate skewness (or if a distribution is skewed), we generate a sample of values.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="significance-and-probability.html#cb23-1" aria-hidden="true" tabindex="-1"></a>SampleValues <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">50</span>)</span>
<span id="cb23-2"><a href="significance-and-probability.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect data</span></span>
<span id="cb23-3"><a href="significance-and-probability.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SampleValues)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.00   22.25   48.50   46.54   69.75  100.00</code></pre>
<p>We apply the <code>skewness</code> function from the <code>e1071</code> package to the sample scores to calculated skewness. The <code>skewness</code> function allows to calculate skewness in three different ways:</p>
<p>Type 1 (This is the typical definition used in many older textbooks):
<span class="math display">\[\begin{equation}
g_1 = m_3 / m_2^{(3/2)}.
\end{equation}\]</span></p>
<p>Type 2 (Used in SAS and SPSS):
<span class="math display">\[\begin{equation}
G_1 = g_1 * sqrt(n(n-1)) / (n-2)
\end{equation}\]</span></p>
<p>Type 3 (Used in MINITAB and BMDP):
<span class="math display">\[\begin{equation}
b_1 = m_3 / s^3 = g_1 ((n-1)/n)^{(3/2)}
\end{equation}\]</span></p>
<p>All three formulas have in common that the more negative values are, the more strongly positively skewed are the data (distribution leans to the left) and the more positive the values are, the more strongly negatively skewed are the data (distribution leans to the right). Here we use the second formula (by setting <code>type = 2</code>) that is also used in SPSS.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="significance-and-probability.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb25-2"><a href="significance-and-probability.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skewness</span>(SampleValues, <span class="at">type =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.0389159</code></pre>
<p>If the reported skewness value is negative, then the distribution is positively skewed. If the value is positive, then the distribution is negatively skewed. If the value is lower than -1 or greater than +1, then the distribution can be assumed to be substantively skewed <span class="citation">(<a href="#ref-hair2017dist" role="doc-biblioref">Hair et al. 2017</a>)</span>.</p>
</div>
<div id="kurtosis" class="section level3 unnumbered hasAnchor">
<h3>Kurtosis<a href="significance-and-probability.html#kurtosis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Another way in which distributions can differ from the normal distribution relates to the thickness of the tails and the spikiness of the distribution. If distributions are bell-shaped like the normal distribution, they are called <em>mesokurtic</em>. If distributions are symmetrical but they are more spiky than the normal distribution, they are called <em>leptokurtic</em>. If symmetrical distributions are flatter and have bigger tails than the normal distribution, the distributions are called <em>platykurtic</em>.</p>
<p><img src="bookdownproj_files/figure-html/kurtosis-1.png" width="672" /></p>
<p>To show how we can calculate kurtosis (or if a distribution suffers from kurtosis), we apply the <code>kurtosis</code> function from the <code>e1071</code> package to the sample scores we generated above /when we calculated skewness).</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="significance-and-probability.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(SampleValues)</span></code></pre></div>
<pre><code>## [1] -1.318594</code></pre>
<p>As the kurtosis value is positive, the distribution is leptokurtic (if it were negative, the distribution would be platykurtic). As a rule of thumb, values greater than +1 indicate that the distribution is too peaked while values lower than –1 indicate that the distribution is substantively platykurtic <span class="citation">(<a href="#ref-hair2017dist" role="doc-biblioref">Hair et al. 2017, pp61</a>)</span>.</p>
<p>The kurtosis score can thus be interpreted as follows:</p>
<ul>
<li><p>A values of 0 means that the distribution is perfectly <em>mesokurtic</em> with Values between -0.5 and 0.5 suggesting that the distribution is <em>approximately mesokurtic</em></p></li>
<li><p>Values between -0.5 and -1 mean that the distribution is <em>moderately platykurtic</em> with values smaller than -1 indicating that the distribution is <em>platykurtic</em>.</p></li>
<li><p>Values between 0.5 and 1 mean that the distribution is <em>moderately leptokurtic</em> with values greater than 1 indicating that the distribution is <em>leptokurtic</em></p></li>
</ul>
</div>
</div>
<div id="the-binomial-distribution" class="section level2 unnumbered hasAnchor">
<h2>The Binomial Distribution<a href="significance-and-probability.html#the-binomial-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A distribution which is very similar to the normal distribution is the “binomial distribution”. The binomial distribution displays the probability of binary outcomes. So, in fact, the distribution of the coin flips above represents a binomial distribution. However, the binomial distribution cane be (as above in case of the coin flips) but does not have to be symmetric (like the normal distribution).</p>
<p>To illustrate this, let us consider the following example: we are interested in how many people use discourse <em>like</em> in Australian English. We have analyzed a corpus, for instance the Australian component of the <a href="https://www.ice-corpora.uzh.ch/en.html">International Corpus of English</a> and found that 10 percent of all speakers have used discourse <em>like</em>. In this example, the corpus encompasses 100 speakers (actually the the spoken section of the Australian component of the ICE represents more than 100 speakers but it will make things easier for us in this example).</p>
<p>Now, given the result of our corpus analysis, we would like to know what percentage of speakers of Australian English use discourse <em>like</em> with a confidence of 95 percent. Given the corpus study results, we can plot the expected binomial distribution of discourse <em>like</em> users in Australian English.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The bar graph above shows the probability distribution of discourse <em>like</em> users in Australian English. The first thing we notice is that the binomial distribution is not symmetric as it is slightly left-skewed. If we would increase the number of draws or speakers in our example, the distribution would, however, approximate the normal distribution very quickly because the binomial distribution approximates the normal distribution for large N or if the probability is close to .5. Thus, it is common practice to use the normal distribution instead of the binomial distribution.</p>
<p>The bar graph below also shows the probability distribution of discourse <em>like</em> users in Australian English but, in addition, it is color-coded: bars within the 95 percent confidence interval are <em>lightgray</em>, the bars in red are outside the 95 percent confidence interval. In other words, if we repeated the corpus analysis, for instance 1000 times, on corpora which represent speakers from the same population, then 95 percent of samples would have between 1 and 8 discourse <em>like</em> users.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>In addition to the normal distribution and the binomial distribution, there are many other distributions which underlay common procedures in quantitative analyses. For instance, the t- and the F-distribution or the Chi-distribution. However, we will not deal with these distributions here.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-hair2017dist" class="csl-entry">
Hair, J. F., G. T. M. Hult, C. M. Ringle, and M. Sarstedt. 2017. <span>“A Primer on Partial Least Squares Structural Equation Modeling (PLS-SEM).”</span>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="relationsships-between-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="z-scores.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/edit/master/02-basic.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/MartinSchweinberger/SLAT7855/blob/master/02-basic.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
